### PR TITLE
fix: update deepseek logic to match deepseek v3.2

### LINKED ISSUE #11627: [Bug]:The official DeepSeek Reasoner is missing the reasoning_content field, making it unusable.
> [!NOTE]
> This issue/comment/review was translated by Claude.

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

1.7.1

### Bug Description

DeepSeek-V3.2 official version has been released, and the official thinking mode DeepSeek Reasoner now supports tool calling.
However, an error occurred.
It should require support for interleaved thinking:
https://api-docs.deepseek.com/zh-cn/guides/thinking_mode#%E5%B7%A5%E5%85%B7%E8%B0%83%E7%94%A8

> In the process of answering question 1 (requests 1.1 - 1.3), the model performed multiple thinking + tool calls before giving an answer. During this process, the user needs to send back the thinking chain content (reasoning_content) to the API to let the model continue thinking.

### Steps To Reproduce

Call deepseek-reasoner through the official DeepSeek API.

### Expected Behavior

Output results normally.

### Relevant Log Output

```shell
Missing `reasoning_content` field in the assistant message at message index 1. For more information, please refer to https://api-docs.deepseek.com/guides/thinking_with_tools
请求错误，请检查请求参数是否正确。如果修改了模型设置，请重置到默认设置
```

### Additional Context

_No response_

---
<details>
<summary>Original Content</summary>

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

1.7.1

### Bug Description

DeepSeek-V3.2 正式版已经发布，官方思考模式DeepSeek Reasoner 支持了工具调用。
但是出现错误。
应该是需要支持交错思考：
[](https://api-docs.deepseek.com/zh-cn/guides/thinking_mode#%E5%B7%A5%E5%85%B7%E8%B0%83%E7%94%A8)

> 在回答问题 1 过程中（请求 1.1 - 1.3），模型进行了多次思考 + 工具调用后给出答案。在这个过程中，用户需回传思维链内容（reasoning_content）给 API，以让模型继续思考。

### Steps To Reproduce

在深度求索官方接口调用deepseek-reasoner。

### Expected Behavior

正常输出结果。

### Relevant Log Output

```shell
Missing `reasoning_content` field in the assistant message at message index 1. For more information, please refer to https://api-docs.deepseek.com/guides/thinking_with_tools
请求错误，请检查请求参数是否正确。如果修改了模型设置，请重置到默认设置
```

### Additional Context

_No response_
</details>

### LINKED ISSUE #11643: [Bug]: I am unable to use internet search while using DeepSeek-reasoner
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

1.7.1

### Bug Description

Image

Image

Image

Image

### Steps To Reproduce

1. Use DeepSeek-reasoner
2. Enable online search, choose any engine, such as Baidu or Bing
3. Enter a prompt, for example, "English proposal for social contribution"
4. The deep thinking process will actively use online search, then report an error

Additionally, following the above steps in DeepSeek-chat did not encounter any issues.

### Expected Behavior

Expect online search not to report errors, normal use.

### Relevant Log Output

```shell
错误名称: AI_APICallError
错误信息: Missing `reasoning_content` field in the assistant message at message index 3. For more information, please refer to https://api-docs.deepseek.com/guides/thinking_with_tools
堆栈信息: AI_APICallError: Missing `reasoning_content` field in the assistant message at message index 3. For more information, please refer to https://api-docs.deepseek.com/guides/thinking_with_tools
    at file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/dist-mVY8hbYS.js:5132:11
    at async postToApi (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/dist-mVY8hbYS.js:5028:24)
    at async DeepSeekChatLanguageModel.doStream (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Z-tJeJfQ.js:236112:48)
    at async wrapStream (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Z-tJeJfQ.js:38808:31)
    at async fn (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Z-tJeJfQ.js:36993:17)
    at async file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Z-tJeJfQ.js:34371:19
    at async _retryWithExponentialBackoff (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Z-tJeJfQ.js:34473:10)
    at async streamStep (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Z-tJeJfQ.js:36961:108)
    at async Object.flush (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Z-tJeJfQ.js:37217:10)
错误原因: "[undefined]"
状态码: 400
请求路径: https://api.deepseek.com/v1/chat/completions
请求体: {
  "model": "deepseek-reasoner",
  "user": "[undefined]",
  "max_tokens": "[undefined]",
  "temperature": 1,
  "top_p": "[undefined]",
  "frequency_penalty": "[undefined]",
  "presence_penalty": "[undefined]",
  "response_format": "[undefined]",
  "stop": "[undefined]",
  "seed": "[undefined]",
  "serviceTier": "[undefined]",
  "reasoning_effort": "[undefined]",
  "verbosity": "[undefined]",
  "messages": [
    {
      "role": "user",
      "content": "致力于的英文表述"
    },
    {
      "role": "assistant",
      "content": "“致力于”在英文中有多种表达方式，可根据语境和强调的重点选择：\n\n**1. 最常用动词短语：**\n*   **Devote to** - 强调奉献时间、精力\n    *   *She **devotes herself to** scientific research.* (她致力于科学研究。)\n*   **Dedicate to** - 强调庄严的承诺和奉献（略正式）\n    *   *The organization is **dedicated to** helping the poor.* (该组织致力于帮助穷人。)\n*   **Commit to** - 强调做出承诺并坚守\n    *   *The company is **committed to** sustainable development.* (公司致力于可持续发展。)\n\n**2. 强调“努力、奋斗”方向：**\n*   **Work towards / Strive for** - 强调为达成目标而努力\n    *   *We are **working towards** a greener future.* (我们致力于创造一个更绿色的未来。)\n    *   *We **strive for** excellence in every project.* (我们致力于在每个项目中追求卓越。)\n*   **Work on** - 强调正在从事某项具体工作\n    *   *He is **working on** a new vaccine.* (他正致力于研发一种新疫苗。)\n\n**3. 正式书面语/名词形式：**\n*   **Be committed to** - (同上，名词形式 commitment)\n    *   *Show your **commitment to** the cause.* (展现你对该事业的投入。)\n*   **Dedication to** - 名词形式\n    *   *His **dedication to** his work is admirable.* (他对工作的投入令人钦佩。)\n*   **Focus on / Concentration on** - 强调关注的焦点\n    *   *Our **focus is on** innovation and quality.* (我们致力于创新和质量。)\n\n**4. 更正式或书面化的单个动词：**\n*   **Engage in** - 从事，参与\n    *   *The scholar **engages in** cross-cultural studies.* (这位学者致力于跨文化研究。)\n*   **Pursue** - 追求（事业、目标等）\n    *   *She came to China to **pursue** her acting career.* (她来到中国致力于演艺事业。)\n*   **Endeavor to** - 努力做（正式）\n    *   *We **endeavor to** provide the best service.* (我们致力于提供最佳服务。)\n\n**总结与选择建议：**\n*   **通用首选**：**devote to** (个人奉献) 和 **dedicate to** (组织/庄严目标)。\n*   **商业/目标语境**：**commit to** 及其名词形式 **commitment to** 非常常用。\n*   **强调过程努力**：**work towards/on** 或 **strive for**。\n*   **正式书面**：可选用 **dedication**, **focus on**, 或 **endeavor to**。\n\n根据您想强调的侧重点（奉献、承诺、努力过程或工作焦点），选择最贴切的表达即可。嗯，用户问的是“致力于”的英文表达。这是一个比较基础的翻译问题，但可能涉及不同语境下的用法差异。\n\n用户可能正在准备英文材料，需要准确且多样的表达方式。考虑到中文“致力于”的语义较广，英文对应表达会有侧重点差异。\n\n可以从几个层面回答：最常用动词短语、正式书面用语、强调过程的表达、名词化结构。需要给出清晰分类和例句，帮助用户理解使用场景。\n\n想到了mention最核心的devote to和dedicate to，但也要补充work towards/on这种强调过程的表达。commit to在商业语境很常见，名词commitment也很实用。最后可以提一下动词endeavor，虽然稍正式但很精准。",
      "tool_calls": "[undefined]"
    },
    {
      "role": "user",
      "content": "奉献社会的英文表达"
    },
    {
      "role": "assistant",
      "content": "",
      "tool_calls": [
        {
          "id": "call_00_7DlxTWyWg2B0eSjALe1GAimX",
          "type": "function",
          "function": {
            "name": "builtin_web_search",
            "arguments": "{\"additionalContext\":\"奉献社会的英文表达 \\\"奉献社会\\\" 英文翻译 \\\"contribute to society\\\" 英文说法\"}"
          }
        }
      ]
    },
    {
      "role": "tool",
      "tool_call_id": "call_00_7DlxTWyWg2B0eSjALe1GAimX",
      "content": "[{\"type\":\"text\",\"text\":\"This tool searches for relevant information and formats results for easy citation. The returned sources should be cited using [1], [2], etc. format in your response.\"},{\"type\":\"text\",\"text\":\"Found 5 relevant sources. Use [number] format to cite specific information.\"},{\"type\":\"text\",\"text\":\"Please answer the question based on the reference materials\\n\\n## Citation Rules:\\n- Please cite the context at the end of sentences when appropriate.\\n- Please use the format of citation number [number] to reference the context in corresponding parts of your answer.\\n- If a sentence comes from multiple contexts, please list all relevant citation numbers, e.g., [1][2]. Remember not to group citations at the end but list them in the corresponding parts of your answer.\\n- If all reference content is not relevant to the user's question, please answer based on your knowledge.\\n\\n## My question is:\\n\\nBased on the search results, please answer the user's question with proper citations.\\n\\n## Reference Materials:\\n\\n```json\\n[\\n  {\\n    \\\"number\\\": 1,\\n    \\\"title\\\": \\\"知了爱学\\\",\\n    \\\"content\\\": \\\"请扫描上方的二维码预览\\\",\\n    \\\"url\\\": \\\"http://www.baidu.com/link?url=Z3_NEUuqb6otRGyMFGsVfSrQRxWr9gxw4SfyJKlYWm5xXC-ikiwy8WhbjdQvTpb6RGRMy2vou4f1gGhgJ0Zt3ezffNqvpXbp2gyz_glzEHNZlqMsnFf2-G6pOUUA16YBH7Dd52i1ShZSenE91eP4F22Fddft4XEKAAiBI4T7tYa5z8vtoJBG2Zv0HXdMcpT2gOSPdTkUVak0Es6gD56mFNVoiVe4p2SDzt2R2fdA4zd-wAUUmvR5X6Ugaq2hrwPVvtfmkhW1pGy17_EPFHVEG9Y7q_kqM6cGlUY2kxcdpl4qhrJzne7m4jWZzaxvjfNpkfyqpJTP4DPJoLSPLl2gua\\\"\\n  },\\n  {\\n    \\\"number\\\": 2,\\n    \\\"title\\\": \\\"必应词典 - 中国领先的中英文在线词典\\\",\\n    \\\"content\\\": \\\"**Contribute-to-Society**\\\\n-------------------------\\\\n\\\\n*   Web对社会作出贡献\\\\n\\\\nWeb Definition\\\\n--------------\\\\n\\\\n1.\\\\n\\\\n对社会作出贡献\\\\n\\\\nWarm Christmas （圣诞暖流） ... are working on… 的意思是“致力于……”。 ● **contribute to society** = **对社会作出贡献** ...\\\\n\\\\n[www.for68.com](http://www.for68.com/new/2006/7/wu338102419276002237-0.htm)|[Based on 1 page](file:///C:/search?q=Contribute-to-Society+%e5%af%b9%e7%a4%be%e4%bc%9a%e4%bd%9c%e5%87%ba%e8%b4%a1%e7%8c%ae&FORM=BDVT01&cc=cn)\\\\n\\\\nSample Sentence\\\\n---------------\\\\n\\\\nDefinition:\\\\n\\\\nAllAll,对社会作出贡献对社会作出贡献\\\\n\\\\nCategory:AllAll,OralOral,WrittenWritten,TitleTitle,TechnicalTechnical\\\\n\\\\nSource:AllAll,DictionaryDictionary,WebWeb\\\\n\\\\nDifficulty:AllAll,EasyEasy,MiddleMiddle,HardHard\\\\n\\\\nMore sentence filters\\\\n\\\\nHide sentence filters\\\\n\\\\n![](file:///C:/s/a/video/vld.gif)\\\\n\\\\n1.\\\\n\\\\nAnd [even](file:///C:/dict/search?q=even&FORM=BDVSP6&cc=cn) [corporate](file:///C:/dict/search?q=corporate&FORM=BDVSP6&cc=cn) [aspirations](file:///C:/dict/search?q=aspirations&FORM=BDVSP6&cc=cn) [in](file:///C:/dict/search?q=in&FORM=BDVSP6&cc=cn) [the](file:///C:/dict/search?q=the&FORM=BDVSP6&cc=cn) [rich](file:///C:/dict/search?q=rich&FORM=BDVSP6&cc=cn) world [lag](file:///C:/dict/search?q=lag&FORM=BDVSP6&cc=cn) [far](file:///C:/dict/search?q=far&FORM=BDVSP6&cc=cn) [behind](file:///C:/dict/search?q=behind&FORM=BDVSP6&cc=cn) how much the [public](file:///C:/dict/search?q=public&FORM=BDVSP6&cc=cn) [expects](file:///C:/dict/search?q=expects&FORM=BDVSP6&cc=cn) [business](file:///C:/dict/search?q=business&FORM=BDVSP6&cc=cn) [to](file:///C:/dict/search?q=to&FORM=BDVSP6&cc=cn) [contribute](file:///C:/dict/search?q=contribute&FORM=BDVSP6&cc=cn) to [society](file:///C:/dict/search?q=society&FORM=BDVSP6&cc=cn)[.](file:///C:/dict/search?q=.&FORM=BDVSP6&cc=cn)\\\\n\\\\n[甚至](file:///C:/dict/search?q=%E7%94%9A%E8%87%B3&FORM=BDVSP6&cc=cn)[富裕](file:///C:/dict/search?q=%E5%AF%8C%E8%A3%95&FORM=BDVSP6&cc=cn)[国家](file:///C:/dict/search?q=%E5%9B%BD%E5%AE%B6&FORM=BDVSP6&cc=cn)[企业](file:///C:/dict/search?q=%E4%BC%81%E4%B8%9A&FORM=BDVSP6&cc=cn)[的](file:///C:/dict/search?q=%E7%9A%84&FORM=BDVSP6&cc=cn)[渴望](file:///C:/dict/search?q=%E6%B8%B4%E6%9C%9B&FORM=BDVSP6&cc=cn)[也](file:///C:/dict/search?q=%E4%B9%9F&FORM=BDVSP6&cc=cn)[远远](file:///C:/dict/search?q=%E8%BF%9C%E8%BF%9C&FORM=BDVSP6&cc=cn)[落后](file:///C:/dict/search?q=%E8%90%BD%E5%90%8E&FORM=BDVSP6&cc=cn)[于](file:///C:/dict/search?q=%E4%BA%8E&FORM=BDVSP6&cc=cn)[公众](file:///C:/dict/search?q=%E5%85%AC%E4%BC%97&FORM=BDVSP6&cc=cn)[对](file:///C:/dict/search?q=%E5%AF%B9&FORM=BDVSP6&cc=cn)[企业](file:///C:/dict/search?q=%E4%BC%81%E4%B8%9A&FORM=BDVSP6&cc=cn)[社会](file:///C:/dict/search?q=%E7%A4%BE%E4%BC%9A&FORM=BDVSP6&cc=cn)[贡献](file:///C:/dict/search?q=%E8%B4%A1%E7%8C%AE&FORM=BDVSP6&cc=cn)[的](file:///C:/dict/search?q=%E7%9A%84&FORM=BDVSP6&cc=cn)[期盼](file:///C:/dict/search?q=%E6%9C%9F%E7%9B%BC&FORM=BDVSP6&cc=cn)[。](file:///C:/dict/search?q=%E3%80%82&FORM=BDVSP6&cc=cn)\\\\n\\\\nshèn zhì fù yù guó jiā qǐ yè de kě wàng yě yuǎn yuǎn luò hòu yú gōng zhòng duì qǐ yè shè huì gòng xiàn de qī pàn 。\\\\n\\\\n[www.ecocn.org](http://www.ecocn.org/bbs.php?archiver=1&mod=viewthread&tid=8878)\\\\n\\\\n2.\\\\n\\\\n[He](file:///C:/dict/search?q=He&FORM=BDVSP6&cc=cn) [did](file:///C:/dict/search?q=did&FORM=BDVSP6&cc=cn) [not](file:///C:/dict/search?q=not&FORM=BDVSP6&cc=cn) [expect](file:///C:/dict/search?q=expect&FORM=BDVSP6&cc=cn) to [contribute](file:///C:/dict/search?q=contribute&FORM=BDVSP6&cc=cn) to [society](file:///C:/dict/search?q=society&FORM=BDVSP6&cc=cn)[,](file:///C:/dict/search?q=%2C&FORM=BDVSP6&cc=cn) [for](file:///C:/dict/search?q=for&FORM=BDVSP6&cc=cn) [society](file:///C:/dict/search?q=society&FORM=BDVSP6&cc=cn)[,](file:///C:/dict/search?q=%2C&FORM=BDVSP6&cc=cn) [not](file:///C:/dict/search?q=not&FORM=BDVSP6&cc=cn) a [bad thing](file:///C:/dict/search?q=bad%20thing&FORM=BDVSP6&cc=cn)[.](file:///C:/dict/search?q=.&FORM=BDVSP6&cc=cn)\\\\n\\\\n[他](file:///C:/dict/search?q=%E4%BB%96&FORM=BDVSP6&cc=cn)[没有](file:///C:/dict/search?q=%E6%B2%A1%E6%9C%89&FORM=BDVSP6&cc=cn)[想到](file:///C:/dict/search?q=%E6%83%B3%E5%88%B0&FORM=BDVSP6&cc=cn)[贡献](file:///C:/dict/search?q=%E8%B4%A1%E7%8C%AE&FORM=BDVSP6&cc=cn)[社会](file:///C:/dict/search?q=%E7%A4%BE%E4%BC%9A&FORM=BDVSP6&cc=cn)[，](file:///C:/dict/search?q=%EF%BC%8C&FORM=BDVSP6&cc=cn)[对](file:///C:/dict/search?q=%E5%AF%B9&FORM=BDVSP6&cc=cn)[社会](file:///C:/dict/search?q=%E7%A4%BE%E4%BC%9A&FORM=BDVSP6&cc=cn)[来说](file:///C:/dict/search?q=%E6%9D%A5%E8%AF%B4&FORM=BDVSP6&cc=cn)[，](file:///C:/dict/search?q=%EF%BC%8C&FORM=BDVSP6&cc=cn)[并](file:///C:/dict/search?q=%E5%B9%B6&FORM=BDVSP6&cc=cn)[不是](file:///C:/dict/search?q=%E4%B8%8D%E6%98%AF&FORM=BDVSP6&cc=cn)[坏事](file:///C:/dict/search?q=%E5%9D%8F%E4%BA%8B&FORM=BDVSP6&cc=cn)[。](file:///C:/dict/search?q=%E3%80%82&FORM=BDVSP6&cc=cn)\\\\n\\\\ntā méi yǒu xiǎng dào gòng xiàn shè huì , duì shè huì lái shuō , bìng bú shì huài shì 。\\\\n\\\\n[www.cutpic.cn](http://www.cutpic.cn/viewthread.php?tid=17858)\\\\n\\\\n3.\\\\n\\\\n[It](file:///C:/dict/search?q=It&FORM=BDVSP6&cc=cn) [will](file:///C:/dict/search?q=will&FORM=BDVSP6&cc=cn) not come [true](file:///C:/dict/search?q=true&FORM=BDVSP6&cc=cn) until [everyone](file:///C:/dict/search?q=everyone&FORM=BDVSP6&cc=cn) [fully](file:///C:/dict/search?q=fully&FORM=BDVSP6&cc=cn) [realizes](file:///C:/dict/search?q=realizes&FORM=BDVSP6&cc=cn) that [women](file:///C:/dict/search?q=women&FORM=BDVSP6&cc=cn) [can](file:///C:/dict/search?q=can&FORM=BDVSP6&cc=cn) [contribute](file:///C:/dict/search?q=contribute&FORM=BDVSP6&cc=cn) [to](file:///C:/dict/search?q=to&FORM=BDVSP6&cc=cn) [society](file:///C:/dict/search?q=society&FORM=BDVSP6&cc=cn) [and](file:///C:/dict/search?q=and&FORM=BDVSP6&cc=cn) [should](file:///C:/dict/search?q=should&FORM=BDVSP6&cc=cn) [be](file:///C:/dict/search?q=be&FORM=BDVSP6&cc=cn) [guaranteed](file:///C:/dict/search?q=guaranteed&FORM=BDVSP6&cc=cn) the [right](file:///C:/dict/search?q=right&FORM=BDVSP6&cc=cn) to [do](file:///C:/dict/search?q=do&FORM=BDVSP6&cc=cn) so[.](file:///C:/dict/search?q=.&FORM=BDVSP6&cc=cn)\\\\n\\\\n[妇女](file:///C:/dict/search?q=%E5%A6%87%E5%A5%B3&FORM=BDVSP6&cc=cn)[能够](file:///C:/dict/search?q=%E8%83%BD%E5%A4%9F&FORM=BDVSP6&cc=cn)[为](file:///C:/dict/search?q=%E4%B8%BA&FORM=BDVSP6&cc=cn)[社会](file:///C:/dict/search?q=%E7%A4%BE%E4%BC%9A&FORM=BDVSP6&cc=cn)[做出](file:///C:/dict/search?q=%E5%81%9A%E5%87%BA&FORM=BDVSP6&cc=cn)[贡献](file:///C:/dict/search?q=%E8%B4%A1%E7%8C%AE&FORM=BDVSP6&cc=cn)[。](file:///C:/dict/search?q=%E3%80%82&FORM=BDVSP6&cc=cn)[她们](file:///C:/dict/search?q=%E5%A5%B9%E4%BB%AC&FORM=BDVSP6&cc=cn)[的](file:///C:/dict/search?q=%E7%9A%84&FORM=BDVSP6&cc=cn)[这种](file:///C:/dict/search?q=%E8%BF%99%E7%A7%8D&FORM=BDVSP6&cc=cn)[权利](file:///C:/dict/search?q=%E6%9D%83%E5%88%A9&FORM=BDVSP6&cc=cn)[应该](file:///C:/dict/search?q=%E5%BA%94%E8%AF%A5&FORM=BDVSP6&cc=cn)[得到](file:///C:/dict/search?q=%E5%BE%97%E5%88%B0&FORM=BDVSP6&cc=cn)[保障](file:///C:/dict/search?q=%E4%BF%9D%E9%9A%9C&FORM=BDVSP6&cc=cn)[。](file:///C:/dict/search?q=%E3%80%82&FORM=BDVSP6&cc=cn)[当](file:///C:/dict/search?q=%E5%BD%93&FORM=BDVSP6&cc=cn)[每一](file:///C:/dict/search?q=%E6%AF%8F%E4%B8%80&FORM=BDVSP6&cc=cn)[个人](file:///C:/dict/search?q=%E4%B8%AA%E4%BA%BA&FORM=BDVSP6&cc=cn)[都](file:///C:/dict/search?q=%E9%83%BD&FORM=BDVSP6&cc=cn)[充分](file:///C:/dict/search?q=%E5%85%85%E5%88%86&FORM=BDVSP6&cc=cn)[认识](file:///C:/dict/search?q=%E8%AE%A4%E8%AF%86&FORM=BDVSP6&cc=cn)[到](file:///C:/dict/search?q=%E5%88%B0&FORM=BDVSP6&cc=cn)[这](file:///C:/dict/search?q=%E8%BF%99&FORM=BDVSP6&cc=cn)[一点](file:///C:/dict/search?q=%E4%B8%80%E7%82%B9&FORM=BDVSP6&cc=cn)[时](file:///C:/dict/search?q=%E6%97%B6&FORM=BDVSP6&cc=cn)[，](file:///C:/dict/search?q=%EF%BC%8C&FORM=BDVSP6&cc=cn)[我](file:///C:/dict/search?q=%E6%88%91&FORM=BDVSP6&cc=cn)[的](file:///C:/dict/search?q=%E7%9A%84&FORM=BDVSP6&cc=cn)[梦想](file:///C:/dict/search?q=%E6%A2%A6%E6%83%B3&FORM=BDVSP6&cc=cn)[就](file:///C:/dict/search?q=%E5%B0%B1&FORM=BDVSP6&cc=cn)[会](file:///C:/dict/search?q=%E4%BC%9A&FORM=BDVSP6&cc=cn)[实现](file:///C:/dict/search?q=%E5%AE%9E%E7%8E%B0&FORM=BDVSP6&cc=cn)[。](file:///C:/dict/search?q=%E3%80%82&FORM=BDVSP6&cc=cn)\\\\n\\\\nfù nǚ néng gòu wèi shè huì zuò chū gòng xiàn 。 tā men de zhè zhǒng quán lì yīng gāi dé dào bǎo zhàng 。 dāng měi yī gè rén dōu chōng fèn rèn shi dào zhè yì diǎn shí , wǒ de mèng xiǎng jiù huì shí xiàn 。\\\\n\\\\n[www.englishcn.com](http://www.englishcn.com/ext/view.php?aid=4753)\\\\n\\\\n4.\\\\n\\\\n[A](file:///C:/dict/search?q=A&FORM=BDVSP6&cc=cn) [school](file:///C:/dict/search?q=school&FORM=BDVSP6&cc=cn)'s [most](file:///C:/dict/search?q=most&FORM=BDVSP6&cc=cn) [sacred](file:///C:/dict/search?q=sacred&FORM=BDVSP6&cc=cn) [responsibility](file:///C:/dict/search?q=responsibility&FORM=BDVSP6&cc=cn) [is](file:///C:/dict/search?q=is&FORM=BDVSP6&cc=cn) [to](file:///C:/dict/search?q=to&FORM=BDVSP6&cc=cn) [produce](file:///C:/dict/search?q=produce&FORM=BDVSP6&cc=cn) successful and [responsible](file:///C:/dict/search?q=responsible&FORM=BDVSP6&cc=cn) [citizens](file:///C:/dict/search?q=citizens&FORM=BDVSP6&cc=cn) who [can](file:///C:/dict/search?q=can&FORM=BDVSP6&cc=cn) [contribute](file:///C:/dict/search?q=contribute&FORM=BDVSP6&cc=cn) to [society](file:///C:/dict/search?q=society&FORM=BDVSP6&cc=cn)[.](file:///C:/dict/search?q=.&FORM=BDVSP6&cc=cn)\\\\n\\\\n[学校](file:///C:/dict/search?q=%E5%AD%A6%E6%A0%A1&FORM=BDVSP6&cc=cn)[的](file:///C:/dict/search?q=%E7%9A%84&FORM=BDVSP6&cc=cn)[最](file:///C:/dict/search?q=%E6%9C%80&FORM=BDVSP6&cc=cn)[神圣](file:///C:/dict/search?q=%E7%A5%9E%E5%9C%A3&FORM=BDVSP6&cc=cn)[的](file:///C:/dict/search?q=%E7%9A%84&FORM=BDVSP6&cc=cn)[责任](file:///C:/dict/search?q=%E8%B4%A3%E4%BB%BB&FORM=BDVSP6&cc=cn)[是](file:///C:/dict/search?q=%E6%98%AF&FORM=BDVSP6&cc=cn)[培养](file:///C:/dict/search?q=%E5%9F%B9%E5%85%BB&FORM=BDVSP6&cc=cn)[教育](file:///C:/dict/search?q=%E6%95%99%E8%82%B2&FORM=BDVSP6&cc=cn)[出](file:///C:/dict/search?q=%E5%87%BA&FORM=BDVSP6&cc=cn)[能](file:///C:/dict/search?q=%E8%83%BD&FORM=BDVSP6&cc=cn)[对](file:///C:/dict/search?q=%E5%AF%B9&FORM=BDVSP6&cc=cn)[社会](file:///C:/dict/search?q=%E7%A4%BE%E4%BC%9A&FORM=BDVSP6&cc=cn)[作出](file:///C:/dict/search?q=%E4%BD%9C%E5%87%BA&FORM=BDVSP6&cc=cn)[贡献](file:///C:/dict/search?q=%E8%B4%A1%E7%8C%AE&FORM=BDVSP6&cc=cn)[的](file:///C:/dict/search?q=%E7%9A%84&FORM=BDVSP6&cc=cn)[负责任](file:///C:/dict/search?q=%E8%B4%9F%E8%B4%A3%E4%BB%BB&FORM=BDVSP6&cc=cn)[的](file:///C:/dict/search?q=%E7%9A%84&FORM=BDVSP6&cc=cn)[公民](file:///C:/dict/search?q=%E5%85%AC%E6%B0%91&FORM=BDVSP6&cc=cn)[。](file:///C:/dict/search?q=%E3%80%82&FORM=BDVSP6&cc=cn)\\\\n\\\\nxué xiào de zuì shén shèng de zé rèn shì péi yǎng jiào yù chū néng duì shè huì zuò chū gòng xiàn de fù zé rèn de gōng mín 。\\\\n\\\\n[iask.sina.com.cn](http://iask.sina.com.cn/b/10954903.html)\\\\n\\\\n5.\\\\n\\\\n[\\\\\\\"](file:///C:/dict/search?q=%22&FORM=BDVSP6&cc=cn)The [best](file:///C:/dict/search?q=best&FORM=BDVSP6&cc=cn) and [brightest](file:///C:/dict/search?q=brightest&FORM=BDVSP6&cc=cn) in the [education](file:///C:/dict/search?q=education&FORM=BDVSP6&cc=cn) [system](file:///C:/dict/search?q=system&FORM=BDVSP6&cc=cn) [are](file:///C:/dict/search?q=are&FORM=BDVSP6&cc=cn) educated in a way that doesn't [permit](file:///C:/dict/search?q=permit&FORM=BDVSP6&cc=cn) [them](file:///C:/dict/search?q=them&FORM=BDVSP6&cc=cn) [to](file:///C:/dict/search?q=to&FORM=BDVSP6&cc=cn) [contribute](file:///C:/dict/search?q=contribute&FORM=BDVSP6&cc=cn) to [society](file:///C:/dict/search?q=society&FORM=BDVSP6&cc=cn)[,](file:///C:/dict/search?q=%2C&FORM=BDVSP6&cc=cn) [\\\\\\\"](file:///C:/dict/search?q=%22&FORM=BDVSP6&cc=cn) [he](file:///C:/dict/search?q=he&FORM=BDVSP6&cc=cn) [says](file:///C:/dict/search?q=says&FORM=BDVSP6&cc=cn)[.](file:///C:/dict/search?q=.&FORM=BDVSP6&cc=cn)\\\\n\\\\n[“](file:///C:/dict/search?q=%E2%80%9C&FORM=BDVSP6&cc=cn)[最好](file:///C:/dict/search?q=%E6%9C%80%E5%A5%BD&FORM=BDVSP6&cc=cn)[最](file:///C:/dict/search?q=%E6%9C%80&FORM=BDVSP6&cc=cn)[聪明](file:///C:/dict/search?q=%E8%81%AA%E6%98%8E&FORM=BDVSP6&cc=cn)[的](file:///C:/dict/search?q=%E7%9A%84&FORM=BDVSP6&cc=cn)[教育](file:///C:/dict/search?q=%E6%95%99%E8%82%B2&FORM=BDVSP6&cc=cn)[体系](file:///C:/dict/search?q=%E4%BD%93%E7%B3%BB&FORM=BDVSP6&cc=cn)[，](file:///C:/dict/search?q=%EF%BC%8C&FORM=BDVSP6&cc=cn)[不会](file:///C:/dict/search?q=%E4%B8%8D%E4%BC%9A&FORM=BDVSP6&cc=cn)[让](file:///C:/dict/search?q=%E8%AE%A9&FORM=BDVSP6&cc=cn)[人](file:///C:/dict/search?q=%E4%BA%BA&FORM=BDVSP6&cc=cn)[把](file:///C:/dict/search?q=%E6%8A%8A&FORM=BDVSP6&cc=cn)[自己](file:///C:/dict/search?q=%E8%87%AA%E5%B7%B1&FORM=BDVSP6&cc=cn)[全都](file:///C:/dict/search?q=%E5%85%A8%E9%83%BD&FORM=BDVSP6&cc=cn)[奉献](file:///C:/dict/search?q=%E5%A5%89%E7%8C%AE&FORM=BDVSP6&cc=cn)[给](file:///C:/dict/search?q=%E7%BB%99&FORM=BDVSP6&cc=cn)[社会](file:///C:/dict/search?q=%E7%A4%BE%E4%BC%9A&FORM=BDVSP6&cc=cn)[。](file:///C:/dict/search?q=%E3%80%82&FORM=BDVSP6&cc=cn)[”](file:///C:/dict/search?q=%E2%80%9D&FORM=BDVSP6&cc=cn)[他](file:///C:/dict/search?q=%E4%BB%96&FORM=BDVSP6&cc=cn)[说](file:///C:/dict/search?q=%E8%AF%B4&FORM=BDVSP6&cc=cn)[。](file:///C:/dict/search?q=%E3%80%82&FORM=BDVSP6&cc=cn)\\\\n\\\\n\\\\\\\" zuì hǎo zuì cōng míng de jiào yù tǐ xì , bú huì ràng rén bǎ zì jǐ quán dōu fèng xiàn gěi shè huì 。 \\\\\\\" tā shuō 。\\\\n\\\\n[dongxi.net](http://dongxi.net/b106Z)\\\\n\\\\n6.\\\\n\\\\n[On](file:///C:/dict/search?q=On&FORM=BDVSP6&cc=cn) the [basis](file:///C:/dict/search?q=basis&FORM=BDVSP6&cc=cn) [of](file:///C:/dict/search?q=of&FORM=BDVSP6&cc=cn) [living](file:///C:/dict/search?q=living&FORM=BDVSP6&cc=cn) independently [,](file:///C:/dict/search?q=%2C&FORM=BDVSP6&cc=cn) I will [do](file:///C:/dict/search?q=do&FORM=BDVSP6&cc=cn) [my](file:///C:/dict/search?q=my&FORM=BDVSP6&cc=cn) [efforts](file:///C:/dict/search?q=efforts&FORM=BDVSP6&cc=cn) [to](file:///C:/dict/search?q=to&FORM=BDVSP6&cc=cn) [help](file:///C:/dict/search?q=help&FORM=BDVSP6&cc=cn) [people](file:///C:/dict/search?q=people&FORM=BDVSP6&cc=cn) who [need](file:///C:/dict/search?q=need&FORM=BDVSP6&cc=cn) [help](file:///C:/dict/search?q=help&FORM=BDVSP6&cc=cn) and do [more](file:///C:/dict/search?q=more&FORM=BDVSP6&cc=cn) [contribute](file:///C:/dict/search?q=contribute&FORM=BDVSP6&cc=cn) to [society](file:///C:/dict/search?q=society&FORM=BDVSP6&cc=cn).\\\\n\\\\n[先](file:///C:/dict/search?q=%E5%85%88&FORM=BDVSP6&cc=cn)[要](file:///C:/dict/search?q=%E8%A6%81&FORM=BDVSP6&cc=cn)[自己](file:///C:/dict/search?q=%E8%87%AA%E5%B7%B1&FORM=BDVSP6&cc=cn)[能](file:///C:/dict/search?q=%E8%83%BD&FORM=BDVSP6&cc=cn)[生存](file:///C:/dict/search?q=%E7%94%9F%E5%AD%98&FORM=BDVSP6&cc=cn)[靠](file:///C:/dict/search?q=%E9%9D%A0&FORM=BDVSP6&cc=cn)[自身](file:///C:/dict/search?q=%E8%87%AA%E8%BA%AB&FORM=BDVSP6&cc=cn)[的](file:///C:/dict/search?q=%E7%9A%84&FORM=BDVSP6&cc=cn)[努力](file:///C:/dict/search?q=%E5%8A%AA%E5%8A%9B&FORM=BDVSP6&cc=cn)[，](file:///C:/dict/search?q=%EF%BC%8C&FORM=BDVSP6&cc=cn)[如果](file:///C:/dict/search?q=%E5%A6%82%E6%9E%9C&FORM=BDVSP6&cc=cn)[有](file:///C:/dict/search?q=%E6%9C%89&FORM=BDVSP6&cc=cn)[能力](file:///C:/dict/search?q=%E8%83%BD%E5%8A%9B&FORM=BDVSP6&cc=cn)[要](file:///C:/dict/search?q=%E8%A6%81&FORM=BDVSP6&cc=cn)[帮助](file:///C:/dict/search?q=%E5%B8%AE%E5%8A%A9&FORM=BDVSP6&cc=cn)[需要](file:///C:/dict/search?q=%E9%9C%80%E8%A6%81&FORM=BDVSP6&cc=cn)[帮助](file:///C:/dict/search?q=%E5%B8%AE%E5%8A%A9&FORM=BDVSP6&cc=cn)[的](file:///C:/dict/search?q=%E7%9A%84&FORM=BDVSP6&cc=cn)[人](file:///C:/dict/search?q=%E4%BA%BA&FORM=BDVSP6&cc=cn)[，](file:///C:/dict/search?q=%EF%BC%8C&FORM=BDVSP6&cc=cn)[要](file:///C:/dict/search?q=%E8%A6%81&FORM=BDVSP6&cc=cn)[孝敬](file:///C:/dict/search?q=%E5%AD%9D%E6%95%AC&FORM=BDVSP6&cc=cn)[父母](file:///C:/dict/search?q=%E7%88%B6%E6%AF%8D&FORM=BDVSP6&cc=cn)[，](file:///C:/dict/search?q=%EF%BC%8C&FORM=BDVSP6&cc=cn)[多](file:///C:/dict/search?q=%E5%A4%9A&FORM=BDVSP6&cc=cn)[为](file:///C:/dict/search?q=%E4%B8%BA&FORM=BDVSP6&cc=cn)[社会](file:///C:/dict/search?q=%E7%A4%BE%E4%BC%9A&FORM=BDVSP6&cc=cn)[做](file:///C:/dict/search?q=%E5%81%9A&FORM=BDVSP6&cc=cn)[贡献](file:///C:/dict/search?q=%E8%B4%A1%E7%8C%AE&FORM=BDVSP6&cc=cn)[等等](file:///C:/dict/search?q=%E7%AD%89%E7%AD%89&FORM=BDVSP6&cc=cn)\\\\n\\\\nxiān yào zì jǐ néng shēng cún kào zì shēn de nǔ lì , rú guǒ yǒu néng lì yào bāng zhù xū yào bāng zhù de rén , yào xiào jìng fù mǔ , duō wèi shè huì zuò gòng xiàn děng děng\\\\n\\\\n[blog.sina.com.cn](http://blog.sina.com.cn/s/blog_4c8e53d30100algv.html)\\\\n\\\\n7.\\\\n\\\\n[So](file:///C:/dict/search?q=So&FORM=BDVSP6&cc=cn)[,](file:///C:/dict/search?q=%2C&FORM=BDVSP6&cc=cn) [I](file:///C:/dict/search?q=I&FORM=BDVSP6&cc=cn) [will](file:///C:/dict/search?q=will&FORM=BDVSP6&cc=cn) [devote](file:///C:/dict/search?q=devote&FORM=BDVSP6&cc=cn) [myself](file:///C:/dict/search?q=myself&FORM=BDVSP6&cc=cn) [to](file:///C:/dict/search?q=to&FORM=BDVSP6&cc=cn) [contribute](file:///C:/dict/search?q=contribute&FORM=BDVSP6&cc=cn) to [society](file:///C:/dict/search?q=society&FORM=BDVSP6&cc=cn) [and](file:///C:/dict/search?q=and&FORM=BDVSP6&cc=cn) [nature](file:///C:/dict/search?q=nature&FORM=BDVSP6&cc=cn) in [spirit](file:///C:/dict/search?q=spirit&FORM=BDVSP6&cc=cn) as well as [culture](file:///C:/dict/search?q=culture&FORM=BDVSP6&cc=cn) to [the](file:///C:/dict/search?q=the&FORM=BDVSP6&cc=cn) [greatest](file:///C:/dict/search?q=greatest&FORM=BDVSP6&cc=cn) degree[.](file:///C:/dict/search?q=.&FORM=BDVSP6&cc=cn)\\\\n\\\\n[所以](file:///C:/dict/search?q=%E6%89%80%E4%BB%A5&FORM=BDVSP6&cc=cn)[，](file:///C:/dict/search?q=%EF%BC%8C&FORM=BDVSP6&cc=cn)[我](file:///C:/dict/search?q=%E6%88%91&FORM=BDVSP6&cc=cn)[准备](file:///C:/dict/search?q=%E5%87%86%E5%A4%87&FORM=BDVSP6&cc=cn)[将](file:///C:/dict/search?q=%E5%B0%86&FORM=BDVSP6&cc=cn)[自己](file:///C:/dict/search?q=%E8%87%AA%E5%B7%B1&FORM=BDVSP6&cc=cn)[的](file:///C:/dict/search?q=%E7%9A%84&FORM=BDVSP6&cc=cn)[肉体](file:///C:/dict/search?q=%E8%82%89%E4%BD%93&FORM=BDVSP6&cc=cn)[奉献](file:///C:/dict/search?q=%E5%A5%89%E7%8C%AE&FORM=BDVSP6&cc=cn)[给](file:///C:/dict/search?q=%E7%BB%99&FORM=BDVSP6&cc=cn)[哲学](file:///C:/dict/search?q=%E5%93%B2%E5%AD%A6&FORM=BDVSP6&cc=cn)[以](file:///C:/dict/search?q=%E4%BB%A5&FORM=BDVSP6&cc=cn)[求得](file:///C:/dict/search?q=%E6%B1%82%E5%BE%97&FORM=BDVSP6&cc=cn)[对](file:///C:/dict/search?q=%E5%AF%B9&FORM=BDVSP6&cc=cn)[社会](file:///C:/dict/search?q=%E7%A4%BE%E4%BC%9A&FORM=BDVSP6&cc=cn)[和](file:///C:/dict/search?q=%E5%92%8C&FORM=BDVSP6&cc=cn)[文化](file:///C:/dict/search?q=%E6%96%87%E5%8C%96&FORM=BDVSP6&cc=cn)[的](file:///C:/dict/search?q=%E7%9A%84&FORM=BDVSP6&cc=cn)[最大](file:///C:/dict/search?q=%E6%9C%80%E5%A4%A7&FORM=BDVSP6&cc=cn)[精神](file:///C:/dict/search?q=%E7%B2%BE%E7%A5%9E&FORM=BDVSP6&cc=cn)[价值](file:///C:/dict/search?q=%E4%BB%B7%E5%80%BC&FORM=BDVSP6&cc=cn)[。](file:///C:/dict/search?q=%E3%80%82&FORM=BDVSP6&cc=cn)\\\\n\\\\nsuǒ yǐ , wǒ zhǔn bèi jiāng zì jǐ de ròu tǐ fèng xiàn gěi zhé xué yǐ qiú dé duì shè huì hé wén huà de zuì dà jīng shén jià zhí 。\\\\n\\\\n[blog.sina.com.cn](http://blog.sina.com.cn/s/blog_4e5581b20100ddag.html)\\\\n\\\\n8.\\\\n\\\\nIt['s](file:///C:/dict/search?q=%27s&FORM=BDVSP6&cc=cn) [amazing](file:///C:/dict/search?q=amazing&FORM=BDVSP6&cc=cn) [that](file:///C:/dict/search?q=that&FORM=BDVSP6&cc=cn) [somebody](file:///C:/dict/search?q=somebody&FORM=BDVSP6&cc=cn) [can](file:///C:/dict/search?q=can&FORM=BDVSP6&cc=cn) [still](file:///C:/dict/search?q=still&FORM=BDVSP6&cc=cn) [contribute](file:///C:/dict/search?q=contribute&FORM=BDVSP6&cc=cn) [to](file:///C:/dict/search?q=to&FORM=BDVSP6&cc=cn) [society](file:///C:/dict/search?q=society&FORM=BDVSP6&cc=cn) even [in](file:///C:/dict/search?q=in&FORM=BDVSP6&cc=cn) the autumn of his life[.](file:///C:/dict/search?q=.&FORM=BDVSP6&cc=cn)\\\\n\\\\n[令人](file:///C:/dict/search?q=%E4%BB%A4%E4%BA%BA&FORM=BDVSP6&cc=cn)[惊异](file:///C:/dict/search?q=%E6%83%8A%E5%BC%82&FORM=BDVSP6&cc=cn)[的](file:///C:/dict/search?q=%E7%9A%84&FORM=BDVSP6&cc=cn)[是](file:///C:/dict/search?q=%E6%98%AF&FORM=BDVSP6&cc=cn)[，](file:///C:/dict/search?q=%EF%BC%8C&FORM=BDVSP6&cc=cn)[有人](file:///C:/dict/search?q=%E6%9C%89%E4%BA%BA&FORM=BDVSP6&cc=cn)[在](file:///C:/dict/search?q=%E5%9C%A8&FORM=BDVSP6&cc=cn)[垂暮之年](file:///C:/dict/search?q=%E5%9E%82%E6%9A%AE%E4%B9%8B%E5%B9%B4&FORM=BDVSP6&cc=cn)[还](file:///C:/dict/search?q=%E8%BF%98&FORM=BDVSP6&cc=cn)[能够](file:///C:/dict/search?q=%E8%83%BD%E5%A4%9F&FORM=BDVSP6&cc=cn)[为](file:///C:/dict/search?q=%E4%B8%BA&FORM=BDVSP6&cc=cn)[社会](file:///C:/dict/search?q=%E7%A4%BE%E4%BC%9A&FORM=BDVSP6&cc=cn)[作](file:///C:/dict/search?q=%E4%BD%9C&FORM=BDVSP6&cc=cn)[贡献](file:///C:/dict/search?q=%E8%B4%A1%E7%8C%AE&FORM=BDVSP6&cc=cn)[。](file:///C:/dict/search?q=%E3%80%82&FORM=BDVSP6&cc=cn)\\\\n\\\\nlìng rén jīng yì de shì , yǒu rén zài chuí mù zhī nián hái néng gòu wèi shè huì zuò gòng xiàn 。\\\\n\\\\n[www.1stenglish.com](http://www.1stenglish.com/eng/89012.html)\\\\n\\\\n9.\\\\n\\\\nCurrently[,](file:///C:/dict/search?q=%2C&FORM=BDVSP6&cc=cn) [China](file:///C:/dict/search?q=China&FORM=BDVSP6&cc=cn) [needs](file:///C:/dict/search?q=needs&FORM=BDVSP6&cc=cn) many [human](file:///C:/dict/search?q=human&FORM=BDVSP6&cc=cn) resources in [accounting](file:///C:/dict/search?q=accounting&FORM=BDVSP6&cc=cn)[.](file:///C:/dict/search?q=.&FORM=BDVSP6&cc=cn) [By](file:///C:/dict/search?q=By&FORM=BDVSP6&cc=cn) [learning](file:///C:/dict/search?q=learning&FORM=BDVSP6&cc=cn) [it](file:///C:/dict/search?q=it&FORM=BDVSP6&cc=cn)[,](file:///C:/dict/search?q=%2C&FORM=BDVSP6&cc=cn) [I](file:///C:/dict/search?q=I&FORM=BDVSP6&cc=cn) [can](file:///C:/dict/search?q=can&FORM=BDVSP6&cc=cn) [contribute](file:///C:/dict/search?q=contribute&FORM=BDVSP6&cc=cn) [to](file:///C:/dict/search?q=to&FORM=BDVSP6&cc=cn) [society](file:///C:/dict/search?q=society&FORM=BDVSP6&cc=cn)[.](file:///C:/dict/search?q=.&FORM=BDVSP6&cc=cn)\\\\n\\\\n[当今](file:///C:/dict/search?q=%E5%BD%93%E4%BB%8A&FORM=BDVSP6&cc=cn)[，](file:///C:/dict/search?q=%EF%BC%8C&FORM=BDVSP6&cc=cn)[中国](file:///C:/dict/search?q=%E4%B8%AD%E5%9B%BD&FORM=BDVSP6&cc=cn)[很](file:///C:/dict/search?q=%E5%BE%88&FORM=BDVSP6&cc=cn)[需要](file:///C:/dict/search?q=%E9%9C%80%E8%A6%81&FORM=BDVSP6&cc=cn)[财会](file:///C:/dict/search?q=%E8%B4%A2%E4%BC%9A&FORM=BDVSP6&cc=cn)[方面](file:///C:/dict/search?q=%E6%96%B9%E9%9D%A2&FORM=BDVSP6&cc=cn)[的](file:///C:/dict/search?q=%E7%9A%84&FORM=BDVSP6&cc=cn)[人才](file:///C:/dict/search?q=%E4%BA%BA%E6%89%8D&FORM=BDVSP6&cc=cn)[，](file:///C:/dict/search?q=%EF%BC%8C&FORM=BDVSP6&cc=cn)[通过](file:///C:/dict/search?q=%E9%80%9A%E8%BF%87&FORM=BDVSP6&cc=cn)[学习](file:///C:/dict/search?q=%E5%AD%A6%E4%B9%A0&FORM=BDVSP6&cc=cn)[这个](file:///C:/dict/search?q=%E8%BF%99%E4%B8%AA&FORM=BDVSP6&cc=cn)[专业](file:///C:/dict/search?q=%E4%B8%93%E4%B8%9A&FORM=BDVSP6&cc=cn)[，](file:///C:/dict/search?q=%EF%BC%8C&FORM=BDVSP6&cc=cn)[我](file:///C:/dict/search?q=%E6%88%91&FORM=BDVSP6&cc=cn)[可以](file:///C:/dict/search?q=%E5%8F%AF%E4%BB%A5&FORM=BDVSP6&cc=cn)[为](file:///C:/dict/search?q=%E4%B8%BA&FORM=BDVSP6&cc=cn)[社会](file:///C:/dict/search?q=%E7%A4%BE%E4%BC%9A&FORM=BDVSP6&cc=cn)[作](file:///C:/dict/search?q=%E4%BD%9C&FORM=BDVSP6&cc=cn)[贡献](file:///C:/dict/search?q=%E8%B4%A1%E7%8C%AE&FORM=BDVSP6&cc=cn)[。](file:///C:/dict/search?q=%E3%80%82&FORM=BDVSP6&cc=cn)\\\\n\\\\ndāng jīn , zhōng guó hěn xū yào cái kuài fāng miàn de rén cái , tōng guò xué xí zhè ge zhuān yè , wǒ kě yǐ wèi shè huì zuò gòng xiàn 。\\\\n\\\\n[oral-english.com](http://oral-english.com/tag/%e8%8b%b1%e8%af%ad/page/8)\\\\n\\\\n10.\\\\n\\\\nIt [is](file:///C:/dict/search?q=is&FORM=BDVSP6&cc=cn) [driven](file:///C:/dict/search?q=driven&FORM=BDVSP6&cc=cn) [by](file:///C:/dict/search?q=by&FORM=BDVSP6&cc=cn) [man](file:///C:/dict/search?q=man&FORM=BDVSP6&cc=cn)['s](file:///C:/dict/search?q=%27s&FORM=BDVSP6&cc=cn) [desire](file:///C:/dict/search?q=desire&FORM=BDVSP6&cc=cn) [to](file:///C:/dict/search?q=to&FORM=BDVSP6&cc=cn) [win](file:///C:/dict/search?q=win&FORM=BDVSP6&cc=cn) [respect](file:///C:/dict/search?q=respect&FORM=BDVSP6&cc=cn) [and](file:///C:/dict/search?q=and&FORM=BDVSP6&cc=cn) to [contribute](file:///C:/dict/search?q=contribute&FORM=BDVSP6&cc=cn) to [society](file:///C:/dict/search?q=society&FORM=BDVSP6&cc=cn)[.](file:///C:/dict/search?q=.&FORM=BDVSP6&cc=cn)\\\\n\\\\n[学习](file:///C:/dict/search?q=%E5%AD%A6%E4%B9%A0&FORM=BDVSP6&cc=cn)[受](file:///C:/dict/search?q=%E5%8F%97&FORM=BDVSP6&cc=cn)[“](file:///C:/dict/search?q=%E2%80%9C&FORM=BDVSP6&cc=cn)[人](file:///C:/dict/search?q=%E4%BA%BA&FORM=BDVSP6&cc=cn)[要](file:///C:/dict/search?q=%E8%A6%81&FORM=BDVSP6&cc=cn)[赢得](file:///C:/dict/search?q=%E8%B5%A2%E5%BE%97&FORM=BDVSP6&cc=cn)[尊重](file:///C:/dict/search?q=%E5%B0%8A%E9%87%8D&FORM=BDVSP6&cc=cn)[，](file:///C:/dict/search?q=%EF%BC%8C&FORM=BDVSP6&cc=cn)[就](file:///C:/dict/search?q=%E5%B0%B1&FORM=BDVSP6&cc=cn)[得](file:///C:/dict/search?q=%E5%BE%97&FORM=BDVSP6&cc=cn)[对](file:///C:/dict/search?q=%E5%AF%B9&FORM=BDVSP6&cc=cn)[社会](file:///C:/dict/search?q=%E7%A4%BE%E4%BC%9A&FORM=BDVSP6&cc=cn)[做](file:///C:/dict/search?q=%E5%81%9A&FORM=BDVSP6&cc=cn)[贡献](file:///C:/dict/search?q=%E8%B4%A1%E7%8C%AE&FORM=BDVSP6&cc=cn)[”](file:///C:/dict/search?q=%E2%80%9D&FORM=BDVSP6&cc=cn)[的](file:///C:/dict/search?q=%E7%9A%84&FORM=BDVSP6&cc=cn)[欲望](file:///C:/dict/search?q=%E6%AC%B2%E6%9C%9B&FORM=BDVSP6&cc=cn)[所](file:///C:/dict/search?q=%E6%89%80&FORM=BDVSP6&cc=cn)[驱使](file:///C:/dict/search?q=%E9%A9%B1%E4%BD%BF&FORM=BDVSP6&cc=cn)[。](file:///C:/dict/search?q=%E3%80%82&FORM=BDVSP6&cc=cn)\\\\n\\\\nxué xí shòu \\\\\\\" rén yào yíng dé zūn zhòng , jiù de duì shè huì zuò gòng xiàn \\\\\\\" de yù wàng suǒ qū shǐ 。\\\\n\\\\n[www.englishtang.com](http://www.englishtang.com/view/48156.htm)\\\\n\\\\n*   1\\\\n*   2\\\\n*   3\\\",\\n    \\\"url\\\": \\\"http://www.baidu.com/link?url=4XIGDnTWUkpCzqgot0u5e_TJvpEOdKSGS4DsgZ5e8yZ9kHqD28dBodLfmTU91Io7H1aroV16ZY8vt6vCnKwXTq\\\"\\n  },\\n  {\\n    \\\"number\\\": 3,\\n    \\\"title\\\": \\\"汉英翻译为社会作贡献_____ - 百度文库\\\",\\n    \\\"content\\\": \\\"汉英翻译\\\\n\\\\n为社会作贡献\\\\n\\\\n\\\\\\\\_\\\\\\\\_\\\\\\\\_\\\\\\\\_\\\\\\\\_\\\\n\\\\n答案\\\\n\\\\n：\\\\n\\\\n答案：\\\\n\\\\nmake a contribution to society\\\\n\\\\n解析\\\\n\\\\n：\\\\n\\\\n本题考查\\\\n\\\\n\\\\\\\"\\\\n\\\\n为社会作贡献\\\\n\\\\n\\\\\\\"\\\\n\\\\n的英文固定表达。核心动词短语为\\\\n\\\\n\\\\\\\"make a \\\\n\\\\ncontribution to\\\\\\\"\\\\n\\\\n，其中需特别注意：\\\\n\\\\n1.\\\\n\\\\n\\\\\\\"contribution\\\\\\\"\\\\n\\\\n为可数名词，需添加不定冠词\\\\n\\\\n\\\\\\\"a\\\\\\\"\\\\n\\\\n2.\\\\n\\\\n介词必须使用\\\\n\\\\n\\\\\\\"to\\\\\\\"\\\\n\\\\n表示对象关系\\\\n\\\\n3.\\\\n\\\\n\\\\\\\"society\\\\\\\"\\\\n\\\\n作为集体名词使用时通常不带冠词\\\\n\\\\n易错点提示：\\\\n\\\\n\\\\n\\\\n误用介词（如错用\\\\n\\\\nfor\\\\n\\\\n代替\\\\n\\\\nto\\\\n\\\\n）\\\\n\\\\n\\\\n\\\\n遗漏不定冠词（直接使用\\\\n\\\\nmake contribution\\\\n\\\\n）\\\\n\\\\n\\\\n\\\\n错误添加冠词（如误用\\\\n\\\\nthe society\\\\n\\\\n）\\\\n\\\\n正确答案完整呈现了\\\\n\\\\n\\\\\\\"make a contribution to + \\\\n\\\\n对象\\\\n\\\\n\\\\\\\"\\\\n\\\\n的标准结构，符合\\\\n\\\\n英语惯用表达。该短语与\\\\n\\\\n\\\\\\\"contribute to society\\\\\\\"\\\\n\\\\n为同义表达，但本题更强调\\\\n\\\\n名词形式的使用。\\\",\\n    \\\"url\\\": \\\"http://www.baidu.com/link?url=f4BhIFD0ZyT211ILck-Xrl-xbM6cU33n5iZvDwMaQlo2bkS5CjWNaXhLam73J_b_dEG7E08pODiEeBh0PYA_97W3UVBfYwo96u0oixNjf---0b6cn-yYSBLLvUNvhvhp\\\"\\n  },\\n  {\\n    \\\"number\\\": 4,\\n    \\\"title\\\": \\\"contributing to society是什么意思_contributing to society的中文翻译\\\",\\n    \\\"content\\\": \\\"**相似词语短语**\\\\n\\\\ncontributing [to](file:///C:/_to)───贡献；有助于\\\\n\\\\n[contributing](file:///C:/_contributing)───v.捐献（contribute的ing形式）；adj.贡献的；起作用的\\\\n\\\\ncontributing to [science](file:///C:/_science)───对科学的贡献\\\\n\\\\nsociety───n.社会；交往；社团；社交界\\\\n\\\\nmenace to society───对社会的威胁\\\\n\\\\ncontributing [author](file:///C:/_author)───丛集著者\\\\n\\\\ncontributing [factors](file:///C:/_factors)───成因\\\\n\\\\ncontributing [editor](file:///C:/_editor)───特约编辑\\\\n\\\\ncontributing [cause](file:///C:/_cause)───促成原因\\\\n\\\\n**双语使用场景**\\\\n\\\\nWe give up on a lot of dreams because they don’t “have a point” or aren’t _contributing to society_.───我们对很多梦想失望，因为它们没有“意义”或者对社会没有贡献。\\\\n\\\\nYou want to renew and build your life in your way while _contributing to society_?───想不想以你自己的方式构建全新生活，服务贡献社会？\\\\n\\\\nEarly realization, _contributing to society_, commercial invention for human service.───提早实现发明商品化，贡献社会，为人类服务。\\\\n\\\\nNot starting excavations is the same as having nothing. Only by excavating will we find value capable of _contributing to society_.───不一样的是开始挖掘无聊。只有挖掘才能找到能够促成商品社会。\\\\n\\\\nThe company in good faith based, youth services, _contributing to society_.───公司以诚信为本，服务青年，奉献社会。\\\\n\\\\nVolunteer personally, volunteer activity has following positive significance: one is _contributing to society_.───对志愿者个人而言，志愿活动具有以下积极意义：一是奉献社会。\\\\n\\\\nTechnical volunteers are enthusiastic, skilled individuals who also care about _contributing to society_.───IT技术志愿者是热心的、拥有技术的，同时愿意为社会奉献的个人。\\\\n\\\\nour ancestor realized that people should accept setbacks to hone himself preceding _contributing to society_.───前人已经意识到了这人应该接受挫折，历练自己，才能有所作为。\\\\n\\\\nStaff Declaration: create employment for quality, with fine _contributing to society_.───员工宣言：用人品打造精品，用精品奉献社会。\\\\n\\\\n**英语使用场景**\\\\n\\\\nBut the goal of child-raising should be to produce an adult who is independent, self-directed (but able to connect with others), and capable of _contributing to society_.\\\\n\\\\nPart - time jobs give students a feeling of achievement through _contributing to society_.\\\",\\n    \\\"url\\\": \\\"http://www.baidu.com/link?url=Z3_NEUuqb6otRGyMFGsVfWyb_E-CBjLSQgnblIqVZsj9hFLBvf6m-Tow86nAMsqpQ_aMtptoVVXv1PbywVm_g_\\\"\\n  },\\n  {\\n    \\\"number\\\": 5,\\n    \\\"title\\\": \\\"make contribution to society - 英中  – Linguee词典\\\",\\n    \\\"content\\\": \\\"We hope that people with disabilities can be given a chance to bring their knowledge\\\\n\\\\n\\\\\\\\[...\\\\\\\\] and skills into full play **a****n****d** **make contribution** **to** **society**.\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr01-02/english/counmtg/hansard/cm0515ti-translate-e.pdf)\\\\n\\\\n我們希望社 會人士能給予殘疾 人士一 展 所 長的**機** **會，****令** 他 們 更 可以貢獻 其 學識和 技 能 。\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr01-02/chinese/counmtg/hansard/cm0515ti-translate-c.pdf)\\\\n\\\\nGrandpa WEN, I have a dream. My dream is to become a social worker when I grow up, so that I can help\\\\n\\\\n\\\\\\\\[...\\\\\\\\] people in need **a****n****d** **make contribution** **to** **society**.\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr09-10/english/counmtg/hansard/cm1118-translate-e.pdf)\\\\n\\\\n溫爺爺，我有一個夢想，我的夢想是長大後做一個social worker， 可以**幫****助有****需要**的**人****，****貢獻****社****會****。**\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr09-10/chinese/counmtg/hansard/cm1118-translate-c.pdf)\\\\n\\\\nIf only they have the opportunities, people with\\\\n\\\\n\\\\\\\\[...\\\\\\\\] disabilities are abl**e** **t****o** **make contribution** **to** **society** **i****n** **m**uch the same \\\\\\\\[...\\\\\\\\]\\\\n\\\\nway as anyone of us.\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr08-09/english/counmtg/hansard/cm1022-translate-e.pdf)\\\\n\\\\n實際經驗告訴我，殘疾人士最有需要的是平等機會，只要有機會， 殘疾人士可以跟你和我一**樣****貢****獻****社****會。**\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr08-09/chinese/counmtg/hansard/cm1022-translate-c.pdf)\\\\n\\\\nWe must holistically cater to the various needs of people with disabilities in their physical and mental development, so as\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nto make them self-reliant and\\\\n\\\\n\\\\\\\\[...\\\\\\\\] enable the**m** **t****o** **make contribution** **to** **society** **h****a****nd** in hand \\\\\\\\[...\\\\\\\\]\\\\n\\\\nwith other members of the public.\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr06-07/english/counmtg/hansard/cm1115-translate-e.pdf)\\\\n\\\\n我們必須整體 照顧殘疾人士身心發展的各方面需要，令他們能夠自力更生，讓他們與其他 市民**攜****手貢****獻****社會****。**\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr06-07/chinese/counmtg/hansard/cm1115-translate-c.pdf)\\\\n\\\\nDo you accept this point? If we accept the spirit of allowing both upward and downward adjustments of rents, and if we feel that we are members of this society, as mentioned by Mr Alan LEONG, hence it is necessary to\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nallow people to have\\\\n\\\\n\\\\\\\\[...\\\\\\\\] upward mobilit**y** **i****n** **society** **a****n****d** **make contribution** **to** **society****,** **s****ho**uld we also \\\\\\\\[...\\\\\\\\]\\\\n\\\\nallow the emergence of\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nthe spirit or the mechanism providing for both upward and downward adjustments of rents, thereby enabling the HA to use its rental income to help meet the expenditure of public housing estates?\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr06-07/english/counmtg/hansard/cm0613-translate-e.pdf)\\\\n\\\\n如果大家接受租金可加可減的精神，\\\\n\\\\n\\\\\\\\[...\\\\\\\\] 而大家又覺得作為社會一分子，正如梁家傑議員所說，有需 **要** **在** **社** **會向** **上流** 動**，****要向****社會****作出貢****獻的** 時候，我們是否也應容許租金可加可減的精神或機 制出現，令房委會在租金方面的收入，可幫助它支付屋邨的開支呢？\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr06-07/chinese/counmtg/hansard/cm0613-translate-c.pdf)\\\\n\\\\nMadam President, it is of course good\\\\n\\\\n\\\\\\\\[...\\\\\\\\] for wome**n** **t****o** **make contribution** **to** **society** **t****h****ro**ugh participation \\\\\\\\[...\\\\\\\\]\\\\n\\\\nin public services.\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr07-08/english/counmtg/hansard/cm1212-translate-e.pdf)\\\\n\\\\n主席女士，婦女通過參與公共服務 **而貢** **獻** **社會** **，** **當** **然是** 好事。\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr07-08/chinese/counmtg/hansard/cm1212-translate-c.pdf)\\\\n\\\\nI told him it was not like that and that if he could make it, he could go to university after completing, in sequence, primary school and secondary school, adding that there would be a lot to be learned at university\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nand that he could find employment\\\\n\\\\n\\\\\\\\[...\\\\\\\\] after graduat**io****n****,** **make contribution** **to** **society** **a****n****d** serve people, \\\\\\\\[...\\\\\\\\]\\\\n\\\\njust like his father.\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr00-01/english/counmtg/hansard/010207fe.pdf)\\\\n\\\\n我 告 訴他不是這樣的，唸 完 小學會 唸 中 學 ， 之後有機會 便 可上大 學 ， 在 大 學 裏\\\\n\\\\n\\\\\\\\[...\\\\\\\\] 會 學 到很多知 識 ， 畢 業 後 可 找 工 作 **，** **貢****獻** **社** **會****，****為** **人** 民服務，好 像 爸爸一 樣 。\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr00-01/chinese/counmtg/hansard/010207fc.pdf)\\\\n\\\\nI must point out that no one is born a talent and new arrivals to Hong Kong can be trained\\\\n\\\\n\\\\\\\\[...\\\\\\\\] and educate**d** **t****o** **make contribution** **to** **society**.\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr01-02/english/counmtg/hansard/cm0612ti-translate-e.pdf)\\\\n\\\\n我要指出，沒有人 一出世便是人才，新移民經過培訓亦 **可** **以貢** **獻** **社會****。**\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr01-02/chinese/counmtg/hansard/cm0612ti-translate-c.pdf)\\\\n\\\\nThis is my first point. Secondly, what is the viewpoint of the Government and society as a\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nwhole on this\\\\n\\\\n\\\\\\\\[...\\\\\\\\] motive force of the elderly who can s**ti****l****l** **make contribution** **to** **society** **f****o****r** 20 to 30 years after they have turned 60?\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr08-09/english/counmtg/hansard/cm0114-translate-e.pdf)\\\\n\\\\n我相信大家均覺得須有一項政策，以面對未 來數十年長者人口的增加，這是第一；第二，究竟整個政府、整 **個** **社會** **如** 何看我們的長者在60歲後，仍有二十多三十年 **可** **回** **饋** **社** **會** **的動** **力？**\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr08-09/chinese/counmtg/hansard/cm0114-translate-c.pdf)\\\\n\\\\nInstead, it should regard the elderly as an important human resource. Public and private organizations should be encouraged to make good use of the knowledge and experience of the elderly, encourage the elderly to\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nrejoin the employment market and even set up a business again, so that they\\\\n\\\\n\\\\\\\\[...\\\\\\\\] can continu**e** **t****o** **make contribution** **to** **society**.\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr08-09/english/counmtg/hansard/cm0114-translate-e.pdf)\\\\n\\\\n民建聯認為，面對人口高齡化，政府應積極倡導對長者的正確觀 念，拋棄“長者是社會的包袱”這類的思維模式，把長者視為重要的人力\\\\n\\\\n\\\\\\\\[...\\\\\\\\] 資源；要鼓勵公共和私營機構善用長者的知識和經驗，鼓勵長者再次 就業，甚至再次創業，使他們得**以****繼** **續** **為** **社** **會** **作** **出貢獻****。**\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr08-09/chinese/counmtg/hansard/cm0114-translate-c.pdf)\\\\n\\\\nECE is our foundation as it is the starting point of education. Hence, it is imperative for the Government to make commitment to pre-primary education by implementing 15-year free education expeditiously to benefit all school-age children by creating\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nconditions for each of them, so that they can realize their potential through\\\\n\\\\n\\\\\\\\[...\\\\\\\\] education **a****n****d** **make contribution** **to** **society**.\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr10-11/english/counmtg/hansard/cm0216-translate-e.pdf)\\\\n\\\\n因此，政府有必要對學前\\\\n\\\\n\\\\\\\\[...\\\\\\\\] 教育作出承擔，盡快落實15年免費教育，使所有適齡兒童受惠，為每 一名兒童創造條件，通過教育發**揮** **自身** **的潛能** **，** **貢** **獻** **社會****。**\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr10-11/chinese/counmtg/hansard/cm0216-translate-c.pdf)\\\\n\\\\nWe shall strive to explore and give depth to the room for young people's participation in public affairs. In the meantime, we will assist and equip the young people properly in response to the challenges and opportunities\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nbrought about by globalization and social changes, so that they can participate\\\\n\\\\n\\\\\\\\[...\\\\\\\\] actively in **a****n****d** **make contribution** **to** **society**.\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr03-04/english/counmtg/hansard/cm0218ti-translate-e.pdf)\\\\n\\\\n我們會致力 開 拓 和 深 化 青 少 年 參 與社會事務的空 間 ， 並 協 助 和 裝 備 青 少 年 回應全球 化\\\\n\\\\n\\\\\\\\[...\\\\\\\\] 及 社 會 改 變 帶 來 的 挑 戰 和機遇 ， 積 極 參 與 **及 貢****獻****社 會** **。**\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr03-04/chinese/counmtg/hansard/cm0218ti-translate-c.pdf)\\\\n\\\\nBy this I do not mean that all sectors are working for their own interests. In fact, initially, all of us firmly believed that the Member returned by each sector, particularly Members returned by the\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nprofessional FCs, would only play a transitional role and that we were\\\\n\\\\n\\\\\\\\[...\\\\\\\\] using our expertis**e** **t****o** **make contribution** **to** **society**.\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr09-10/english/counmtg/hansard/cm0428-translate-e.pdf)\\\\n\\\\n其實，在起初的時候，大家也很相信，每一個 界別，特別是專業的功能界別，我們相信從功能界別選出來，只是一個\\\\n\\\\n\\\\\\\\[...\\\\\\\\] 過渡角色，我們將自己的專長貢獻給整個社會，但時至今天，已不是這 樣了，人人也期望業界代表首要是為自己的 **利** **益發聲** **，所以** **業** **界利** **益必** **然**分散。\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr09-10/chinese/counmtg/hansard/cm0428-translate-c.pdf)\\\\n\\\\nIt should also encourage the elderly to actively participat**e** **i****n** **society** **a****n****d** **make contribution** **to** **society** **w****i****th** their valuable experience and knowledge, putting into effect the social philosophy of providing the elderly with \\\\\\\"a sense \\\\\\\\[...\\\\\\\\]\\\\n\\\\nof security, a sense\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nof belonging and a feeling of health and worthiness\\\\\\\".\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr02-03/english/counmtg/hansard/cm1113ti-translate-e.pdf)\\\\n\\\\n**面** **對** 這 種 人 口 老化帶 來 的 挑 戰 ，政府應致 力 改善長 者 的生活 條件，推 動 長 者 教育，於 **社** **會** 上建立 正面的長者 形 象 ， 亦要鼓勵長 者 積極**投****入** **社** **會，****利用**其 寶 貴 經 驗 及 知 識 繼續貢獻社 會，實 踐“老 有所養 ， 老 有所屬，老 有所為＂ 的 社 會理念 。\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr02-03/chinese/counmtg/hansard/cm1113ti-translate-c.pdf)\\\\n\\\\nI hope that in any future consultation or avenues of participation, the Government can allow all young people ― all young people irrespective of their family background ― to participate **a****n****d** **make contribution** **to** **society****,** **s****o** that all in society can have opportunities of upward social mobility.\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr09-10/english/counmtg/hansard/cm0318-translate-e.pdf)\\\\n\\\\n在這次議案辯論中，我們可以看到不論是馮檢基議員或張國柱議員 也是向着同樣的方向，希望政府可以在未來的諮詢或其他參與過程中， 讓一些年青人 ⎯⎯ 不論是否有“ 家底” 的年青人 ⎯⎯ 均可以真正參 與，一起貢獻社會，讓每一個人在社會上均有向上流動的機會。\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr09-10/chinese/counmtg/hansard/cm0318-translate-c.pdf)\\\\n\\\\nWhen there is a fiscal deficit, the Government thinks without hesitation about wielding its axe at the socially disadvantaged groups in the community who have the least power and influence, reasoning most\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nhigh-soundingly that\\\\n\\\\n\\\\\\\\[...\\\\\\\\] the socially disadvantaged groups should **al****s****o** **make contribution** **to** **society****.** **Y****et**, it has not considered their affordability \\\\\\\\[...\\\\\\\\]\\\\n\\\\nor evaluated all the\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nbad effects on society, in particular, it is very often seen grabbling rice from a beggar's bowl.\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr02-03/english/counmtg/hansard/cm0611ti-translate-e.pdf)\\\\n\\\\n當有財政赤 字 時，政府 第 一 時 間想到 的 便 是 向 社 會\\\\n\\\\n\\\\\\\\[...\\\\\\\\] 上 最 無 權 無 勢 的 弱勢社 開 刀 ， 美 其名是 弱勢社 也 要**為****社** **會** **付** **出** **，** **但** 卻 沒有考慮他 們 的 承 擔 能 力 ， 亦沒有評估**這****對****社** **會** **帶** 來 的 一 切 壞影響， 特別是 很 多 時 候還看到要在“乞 兒 \\\\\\\\[...\\\\\\\\]\\\\n\\\\n兜 內 飯 食 ＂。\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr02-03/chinese/counmtg/hansard/cm0611ti-translate-c.pdf)\\\\n\\\\nThis is to make sure that our old\\\\n\\\\n\\\\\\\\[...\\\\\\\\] folks who **ha****v****e** **made** **t****h****e****i****r** **contribution** **to** **society** **w****i****ll** be able \\\\\\\\[...\\\\\\\\]\\\\n\\\\nto have more joy and good fortune\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nin the remaining years of their lives.\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr92-93/english/lc_sitg/hansard/h921022.pdf)\\\\n\\\\n讓那**些****曾經****為****社會****作****出貢****獻的** 老㆟，能多㆒點笑容，多㆒點幸福，走過黃昏的歲 月。\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr92-93/chinese/lc_sitg/hansard/h921022.pdf)\\\\n\\\\nI do not think that people who are not proficient in either English or\\\\n\\\\n\\\\\\\\[...\\\\\\\\] Chinese ca**nn****o****t** **make contribution** **t****o** **o****u****r** **society**.\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr11-12/english/counmtg/hansard/cm0209-translate-e.pdf)\\\\n\\\\n我不認為說英語或對中文 認識不深的人無法對**我們****的****社會****作** **出貢** **獻。**\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr11-12/chinese/counmtg/hansard/cm0209-translate-c.pdf)\\\\n\\\\nFurthermore such measures coincide with\\\\n\\\\n\\\\\\\\[...\\\\\\\\] the SSE’s ai**m** **t****o** **make** **c****o****mp**anies demonstrate their ‘so**ci****a****l** **contribution****’** **t**o a harmon**io****u****s** **society**.\\\\n\\\\nsyntao.com\\\\n\\\\n[syntao.com](http://www.syntao.com/Uploads/%7BF8F4754C-383E-4019-A227-4F11E70D2D78%7D_transparency%20matters%20EN.pdf)\\\\n\\\\n同时， 这项措施也与上交所要求上市公司展示他们为 **和****谐** **社****会所****作出的****“社会贡****献”** 的宗旨相吻合。\\\\n\\\\nsyntao.com\\\\n\\\\n[syntao.com](http://www.syntao.com/Uploads/%7B483D395C-A8BA-4A36-B6FD-939414AEFB99%7D_%E4%BC%81%E4%B8%9A%E9%80%8F%E6%98%8E%E5%BA%A6%E6%8A%A5%E5%91%8A%EF%BC%9A%E4%B8%AD%E5%9B%BD%E9%87%87%E6%8E%98%E7%B1%BB%E4%B8%8A%E5%B8%82%E5%85%AC%E5%8F%B8%E5%90%91%E6%94%BF%E5%BA%9C%E6%94%AF%E4%BB%98%E8%B5%84%E9%87%91%E6%8A%AB%E9%9C%B2%E7%8E%B0%E7%8A%B6%E7%A0%94%E7%A9%B6.pdf)\\\\n\\\\nIn line with Panasonic business philosophy, we will faithfully conduct our\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nbusiness activities by servicing electronic and electrical\\\\n\\\\n\\\\\\\\[...\\\\\\\\] industries so a**s** **t****o** **make contribution** **t****o** **ea****c****h** **society** **i****n** **t**he world.\\\\n\\\\nindustrial.panasonic.com\\\\n\\\\n[industrial.panasonic.com](http://industrial.panasonic.com/ea/i_e/29085/psi_e/psi_e.html)\\\\n\\\\n我們將秉承松下集團 的經營理念,本著務實的態度進行經營 **活** **動** **,為** **社會** **的** **進** **步,** 文明的發展 **作** **出貢** **獻**.\\\\n\\\\nindustrial.panasonic.com\\\\n\\\\n[industrial.panasonic.com](http://industrial.panasonic.com/ea/i/29085/psi/psi.html)\\\\n\\\\nThis will ensure\\\\n\\\\n\\\\\\\\[...\\\\\\\\] international stud**en****t****s** **make** **a** **contribution** **t****o** **A**ustra**li****a****n** **society** **a****n****d** have an enriching \\\\\\\\[...\\\\\\\\]\\\\n\\\\nand positive educational experience.\\\\n\\\\naustraliachina.com.au\\\\n\\\\n[australiachina.com.au](http://www.australiachina.com.au/education/en/diverse-a-rich-experiences)\\\\n\\\\n这将确保留学生为澳**大利****亚****社会****做** **出贡** **献，** 并感受到丰富多彩、积极向上的教育体验。\\\\n\\\\naustraliachina.com.au\\\\n\\\\n[australiachina.com.au](http://www.australiachina.com.au/education/zh/diverse-a-rich-experiences)\\\\n\\\\nAny life lost means that we have lost a human being\\\\n\\\\n\\\\\\\\[...\\\\\\\\] who could **ha****v****e** **made** **a** **po**si**ti****v****e** **contribution** **t****o** **a** be**tt****e****r** **society**.\\\\n\\\\ndaccess-ods.un.org\\\\n\\\\n[daccess-ods.un.org](http://daccess-ods.un.org/access.nsf/Get?Open&DS=S/PV.6066\\\\\\\\(Resumption1\\\\\\\\)&Lang=E)\\\\n\\\\n任何生命损失都意味着我们失去了一个能够对 **更****美好****的****社会****作****出积极贡****献的**人。\\\\n\\\\ndaccess-ods.un.org\\\\n\\\\n[daccess-ods.un.org](http://daccess-ods.un.org/access.nsf/Get?Open&DS=S/PV.6066\\\\\\\\(Resumption1\\\\\\\\)&Lang=C)\\\\n\\\\nRelated examples are: y Control of metal corrosion has socio-economic importance and environmental relevance. y The use of catalysts has been very important to industry and in the medical\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nfield. y Research into\\\\n\\\\n\\\\\\\\[...\\\\\\\\] reaction rates **h****a****s** **made** **a** **po**si**ti****v****e** **contribution** **to** **society****,** **e****.g**. airbags in vehicles. \\\\\\\\[...\\\\\\\\]\\\\n\\\\ny Research into\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nreaction rates is closely linked with the development of lethal weapons.\\\\n\\\\n334.edb.hkedcity.net\\\\n\\\\n[334.edb.hkedcity.net](http://334.edb.hkedcity.net/doc/eng/chem_final_e_20091005.pdf)\\\\n\\\\ny 研究反應速率對社會有正面的**貢****獻，** 如汽車的安全氣囊。\\\\n\\\\n334.edb.hkedcity.net\\\\n\\\\n[334.edb.hkedcity.net](http://334.edb.hkedcity.net/doc/chi/chem_final_c_20091005.pdf)\\\\n\\\\nThere are two further honours bestowed by the Laureus founders and the Academy: the Laureus Lifetime Achievement Award, and\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nthe Laureus Sport for Good Award, which is presented to\\\\n\\\\n\\\\\\\\[...\\\\\\\\] individuals who **ha****v****e** **made** **a****n** **o**utstan**di****n****g** **contribution** **to** **society**.\\\\n\\\\nmercedes-benz.com.eg\\\\n\\\\n[mercedes-benz.com.eg](http://www.mercedes-benz.com.eg/content/egypt/mpc/mpc_egypt_website/enng/home_mpc/passengercars/home/world/sport_lifestyle/laureus/awards.html)\\\\n\\\\n另外勞倫斯創辦人與學院會頒發兩個特別獎項：勞倫斯終身成就獎與勞倫斯體育公益獎，此一獎項是個人獎項 **，** **頒** **給** **對** **社** **會** **有** **傑出貢獻** **的個** 人。\\\\n\\\\nmercedes-benz.com.tw\\\\n\\\\n[mercedes-benz.com.tw](http://www.mercedes-benz.com.tw/content/taiwan/mpc/mpc_taiwan_website/twng/home_mpc/passengercars/home/world/sport_lifestyle/laureus/awards.html)\\\\n\\\\nWe believe that, as the corporations are the main driving force in promoting social and economic development, the promotion of the concept of \\\\\\\"corporate citizens\\\\\\\"\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nwould have a positive effect on encouraging young people to\\\\n\\\\n\\\\\\\\[...\\\\\\\\] participat**e** **i****n** **society** **a****n****d** **make contribution** **t****o** **i**t as well.\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr03-04/english/counmtg/hansard/cm0218ti-translate-e.pdf)\\\\n\\\\n我們相信， 由於企 業是推 動 社 會及經濟\\\\n\\\\n\\\\\\\\[...\\\\\\\\] 發 展 的 重要動力， 推廣“企 業公民＂ 理 念 ， 對 促 進 青年人**參** **與****社** **會，貢獻****社** **會，****具** 正面作用。\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr03-04/chinese/counmtg/hansard/cm0218ti-translate-c.pdf)\\\\n\\\\nMany famous specialists and scholars including Morris Strong, the UN Under-Secretary-General and Eric, President of Royal Academy of Engineering, spoke highly of Hongyuan induction lamps and said that induction lamp had a\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nbroad development potential\\\\n\\\\n\\\\\\\\[...\\\\\\\\] space and w**ou****l****d** **make** **g****r****e****a****t** **contributions** **to** **society** **i****n** **t**erms of energy-saving \\\\\\\\[...\\\\\\\\]\\\\n\\\\nand intelligence lighting.\\\\n\\\\nen.lvd.cc\\\\n\\\\n[en.lvd.cc](http://en.lvd.cc/news_dtl349_5.html)\\\\n\\\\n包括联合国副秘书长莫里斯·斯特朗和英国皇家工程院院长艾里克等在内的国际知名人士，对宏源电磁感应无极灯 给予了高度评价，称赞电磁感应无极灯具有广阔的发展空间，将为人类节能和智能照明的发展 **作出卓** **越贡** **献。**\\\\n\\\\ncn.lvd.cc\\\\n\\\\n[cn.lvd.cc](http://cn.lvd.cc/news_dtl349_5.html)\\\\n\\\\nIt was sometimes forgotten\\\\n\\\\n\\\\\\\\[...\\\\\\\\] that migra**ti****o****n** **made** **a** **po**sitive, sometimes indispensable, socio-econ**om****i****c** **contribution** **to** **society** **a****n****d** increased \\\\\\\\[...\\\\\\\\]\\\\n\\\\nthe competitiveness\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nof host economies and that sealing borders was impossible in democratic States.\\\\n\\\\ndaccess-ods.un.org\\\\n\\\\n[daccess-ods.un.org](http://daccess-ods.un.org/access.nsf/Get?Open&DS=A/C.3/66/SR.27&Lang=E)\\\\n\\\\n有时，人们忘记， 移**徙****为****社****会做出了****积极** 的，甚至是不可缺少 **的社会****经** 济**贡****献，** 并且提高了东道国经济的竞争力，而封锁边 境在民主国家是不可能的。\\\\n\\\\ndaccess-ods.un.org\\\\n\\\\n[daccess-ods.un.org](http://daccess-ods.un.org/access.nsf/Get?Open&DS=A/C.3/66/SR.27&Lang=C)\\\\n\\\\nThe European Union has a 5 million euro (approx. 6.5 million dollars) programme of additional electoral assistance, which will support the legislative elections,\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nincluding the\\\\n\\\\n\\\\\\\\[...\\\\\\\\] Electoral Commiss**io****n****,** **make** **a** **contribution** **t****o** **U**NDP to ensure that the elections, including the audit of the electoral roll, are secure and support c**iv****i****l** **society** **(****i****n** coordination \\\\\\\\[...\\\\\\\\]\\\\n\\\\nwith other partners,\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nincluding France, Spain and the United States of America and the non-governmental organizations IFES, NDI, Guinea’s National Council of Civil Society Organizations (CNOSC-G) and Search for Common Ground).\\\\n\\\\ndaccess-ods.un.org\\\\n\\\\n[daccess-ods.un.org](http://daccess-ods.un.org/access.nsf/Get?Open&DS=PBC/6/GUI/3&Lang=E)\\\\n\\\\n欧洲联盟为立法选举制定了 500 万欧元(约合 650 万美元)的支持方案，包括 向全国独立选举**委****员会****提供**支**持****、****协** **助** **开** **发署** **保障** 选举安全(包括审计选举登记 册)并协同其他伙伴(包括法国、西班牙、美利坚合众国以及 IFES、NDI、几内亚 民间社会组织全国委员会和“寻求共同点”等非政府组织)对民间社会提供支持。\\\\n\\\\ndaccess-ods.un.org\\\\n\\\\n[daccess-ods.un.org](http://daccess-ods.un.org/access.nsf/Get?Open&DS=PBC/6/GUI/3&Lang=C)\\\\n\\\\nI very much hope that the Central Government can clearly understand that\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nHong Kong is a\\\\n\\\\n\\\\\\\\[...\\\\\\\\] sophisticated c**iv****i****l** **society****,** **a****nd** allow Hong Kong to expeditiously implement universal suffrage in accordance with the Basic Law, allow Hong Kong to implement \\\\\\\"one country, two systems\\\\\\\" with \\\\\\\"a high degree of autonomy\\\\\\\" full scale, and allow Hong Kon**g** **t****o** **make contribution** **t****o** **p**olitics and culture bes**id****e****s** **making contribution** **t****o** **t**he economy.\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr07-08/english/counmtg/hansard/cm0611-translate-e.pdf)\\\\n\\\\n我很希望中央政 府清楚明白香港是一個成**熟****的公****民****社** **會** **，** **就讓** **香港** 按照《基本法》盡早落實 普選，就讓香港人全面落實“一國兩制”和“高度自治”，就讓香港除了對 國家作出經濟方面的貢獻外，也作出政治和文化方面的貢獻。\\\\n\\\\nlegco.gov.hk\\\\n\\\\n[legco.gov.hk](http://www.legco.gov.hk/yr07-08/chinese/counmtg/hansard/cm0611-translate-c.pdf)\\\\n\\\\nConsideration was given to the advancement of information connections by linking Arab Internet networks; development in various fields in a number of Arab countries; the Great Arab Free Trade Area; movement towards the establishment of the Arab customs union; and the decisions that have been taken with a view to increasing inter-Arab investment\\\\n\\\\n\\\\\\\\[...\\\\\\\\]\\\\n\\\\nand enabling the\\\\n\\\\n\\\\\\\\[...\\\\\\\\] private sector and c**iv****i****l** **society** **to** **make** **a****n** **e**ffec**ti****v****e** **contribution** **t****o** **t**he overall development \\\\\\\\[...\\\\\\\\]\\\\n\\\\nprocess.\\\\n\\\\ndaccess-ods.un.org\\\\n\\\\n[daccess-ods.un.org](http://daccess-ods.un.org/access.nsf/Get?Open&DS=S/2011/215&Lang=E)\\\\n\\\\n我们审议了将阿拉伯互联网连接起来推\\\\n\\\\n\\\\\\\\[...\\\\\\\\] 动发展信息网络；在一些阿拉伯国家的各个领域推动发展；大阿拉伯自由贸易区； 建立阿拉伯关税同盟的行动；以及关于增加阿拉伯国家间投资和让私营部门 **和****民** **间****社会****能****够****对整**个发展进**程作****出有效** **贡献** **的** **决** **定。**\\\\n\\\\ndaccess-ods.un.org\\\\n\\\\n[daccess-ods.un.org](http://daccess-ods.un.org/access.nsf/Get?Open&DS=S/2011/215&Lang=C)\\\",\\n    \\\"url\\\": \\\"http://www.baidu.com/link?url=EmjraznGy0bp-tek8Ld_1rljuonKXoPAR_PUWC3GlLEpx1PHKiHeP7GKLXgob5BncPlI-VvcMlB_MvPJlSSAtMijl0shLEgEEbAEnGLTMg9wIvSg6vyq9_q2ifwJCndiqLulTvB9KKV-GP6lAqciiAEmTg173foxWceMT-25dRO\\\"\\n  }\\n]\\n```\\n\\nPlease respond in the same language as the user's question.\\n\"}]"
    }
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "builtin_web_search",
        "description": "Web search tool for finding current information, news, and real-time data from the internet.\n\nThis tool has been configured with search parameters based on the conversation context:\n- Prepared queries: \"奉献社会的英文表达\"\n\nYou can use this tool as-is to search with the prepared queries, or provide additionalContext to refine or replace the search terms.",
        "parameters": {
          "$schema": "http://json-schema.org/draft-07/schema#",
          "type": "object",
          "properties": {
            "additionalContext": {
              "description": "Optional additional context, keywords, or specific focus to enhance the search",
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      }
    }
  ],
  "tool_choice": "auto",
  "stream": true,
  "stream_options": "[undefined]"
}
响应首部: {
  "access-control-allow-credentials": "true",
  "connection": "keep-alive",
  "content-length": "272",
  "content-type": "application/json",
  "date": "Tue, 02 Dec 2025 12:17:49 GMT",
  "document-policy": "include-js-call-stacks-in-crash-reports",
  "server": "CW",
  "strict-transport-security": "max-age=31536000; includeSubDomains; preload",
  "vary": "origin, access-control-request-method, access-control-request-headers",
  "x-content-type-options": "nosniff",
  "x-ds-trace-id": "397f363ce58902b3fa6e6192f248d76b"
}
响应内容: {
  "error": {
    "message": "Missing `reasoning_content` field in the assistant message at message index 3. For more information, please refer to https://api-docs.deepseek.com/guides/thinking_with_tools",
    "type": "invalid_request_error",
    "param": null,
    "code": "invalid_request_error"
  }
}
数据: {
  "error": {
    "message": "Missing `reasoning_content` field in the assistant message at message index 3. For more information, please refer to https://api-docs.deepseek.com/guides/thinking_with_tools",
    "type": "invalid_request_error",
    "param": null,
    "code": "invalid_request_error"
  }
}
```

### Additional Context

_No response_

### LINKED ISSUE #11650: [Discussion]: How to control the thinking and non-thinking modes of DS models
> [!NOTE]
> This issue/comment/review was translated by Claude.

### Issue Checklist

- [x] I understand that issues are meant for feedback and problem-solving, not for venting, and I will provide as much detail as possible to help resolve the issue.
- [x] I have checked the pinned issues and searched through the existing [open issues](https://github.com/CherryHQ/cherry-studio/issues), [closed issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [discussions](https://github.com/CherryHQ/cherry-studio/discussions) and did not find a similar suggestion.
- [x] I confirm that I am here to ask questions and discuss issues, not to report bugs or request features.

### Platform

Windows

### Version

1.7.1

### Your Question

Image
In the settings, thinking mode has been enabled, but almost every conversation fails to think. The model generates answers directly each time.

Comparison:

Image

Image

I saw online API documentation saying it's possible to send an extra body or something, but I didn't see where the client can control this.

### Context

_No response_

### Additional Information

```shell

```

### Priority

Medium (Would like a response soon)

---
<details>
<summary>Original Content</summary>

### Issue Checklist

- [x] I understand that issues are meant for feedback and problem-solving, not for venting, and I will provide as much detail as possible to help resolve the issue.
- [x] I have checked the pinned issues and searched through the existing [open issues](https://github.com/CherryHQ/cherry-studio/issues), [closed issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [discussions](https://github.com/CherryHQ/cherry-studio/discussions) and did not find a similar suggestion.
- [x] I confirm that I am here to ask questions and discuss issues, not to report bugs or request features.

### Platform

Windows

### Version

1.7.1

### Your Question

Image
在设置中，已经点亮了思考模式，但是差不多每次对话都无法思考，模型每次都是直接就生成了答案。

对照：

Image

Image

我看到网上的API介绍说可以发送一个extra body啥的，不过我没看到客户端哪里能控制。

### Context

_No response_

### Additional Information

```shell

```

### Priority

Medium (Would like a response soon)</details>

### PR DESCRIPTION
**Pull request by DeJeune**
### What this PR does

升级 ai sdk 修复deepseek bug
特殊对待deepseek-v3.2-speciale
引入fixedReasoning 和相关测试

Fixes #11627  
Fixes #11643
Fixes #11650

### CheckList

- [x] DeepSeek Official
- [x] OpenRouter
- [x] ppio, silicon, sophnet, aihubmix, dmxapi ...

### CODE REVIEW

File: src/renderer/src/aiCore/utils/options.ts [hunk 1]
```diff
@@ -270,7 +270,9 @@ export function buildProviderOptions(
     }[rawProviderId] || rawProviderId
 
   if (rawProviderKey === 'cherryin') {
-    rawProviderKey = { gemini: 'google', ['openai-response']: 'openai' }[actualProvider.type] || actualProvider.type
+    rawProviderKey =
+      { gemini: 'google', ['openai-response']: 'openai', openai: 'cherryin' }[actualProvider.type] ||
```
Comment (EurFelux) [inline src/renderer/src/aiCore/utils/options.ts:279]: Can CherryIN provider extract and handle options from 'cherryin' correctly? That is why we do map from type to ai-sdk provider id.

And built-in CherryIN provider is still `openai` type. Actually why it must be `openai` type? By the way, we also take it as new-api type now. There's too much confusion.

Image

Comment (DeJeune) [reply src/renderer/src/aiCore/utils/options.ts:279]: > [!NOTE]
> This issue/comment/review was translated by Claude.

This providerOptions issue was resolved in this PR: https://github.com/CherryHQ/cherry-studio/pull/11605

However, this code doesn't mean that cherryin is of 'openai' type, but rather that the openai-compatible models in cherryin will be resolved to 'openai' type through getaisdkId, but after changing the ai-sdk from openai to openai-comatilbe in providerOptions, it's necessary to map providerOptions to request parameters through providerId.

---
<details>
<summary>Original Content</summary>
这个providerOptions问题，在这个PR中解决了: https://github.com/CherryHQ/cherry-studio/pull/11605
不过这段代码不是说cherryin是'openai' type，而是cherryin中的openai-compatible模型会通过getaisdkId解析到'openai'type，但是在
providerOptions中把ai-sdk从openai改成openai-comatilbe之后，必须要通过providerId才能将providerOptions映射到请求参数中
</details>

Comment (EurFelux) [reply src/renderer/src/aiCore/utils/options.ts:279]: > [!NOTE]
> This issue/comment/review was translated by Claude.

This is really going in circles, this part is getting more and more messy

---
<details>
<summary>Original Content</summary>

真是绕了好几圈啊，这一块越来越乱了

</details>

File: src/renderer/src/config/models/reasoning.ts [hunk 2]
```diff
@@ -596,3 +607,6 @@ export const findTokenLimit = (modelId: string): { min: number; max: number } |
   }
   return undefined
 }
+
+export const isFixedReasoningModel = (model: Model) =>
```
Comment (EurFelux) [inline src/renderer/src/config/models/reasoning.ts:622]: Add jsdoc plz

File: src/renderer/src/aiCore/utils/reasoning.ts [hunk 3]
```diff
@@ -274,6 +290,8 @@ export function getReasoningEffort(assistant: Assistant, model: Model): Reasonin
           logger.warn(
             `Skipping thinking options for provider ${provider.name} as DeepSeek v3.1 thinking control method is unknown`
           )
+        // Fall through to silicon case - silicon is already handled before this switch (lines 230-240)
+        // So this fall-through results in no action, which is correct for unknown providers
```
Comment (EurFelux) [inline src/renderer/src/aiCore/utils/reasoning.ts]: redundant with L296. Remove one

**Review by EurFelux — APPROVED** [review]

**Review by MyPrototypeWhat — APPROVED** [review]
