### PR TITLE
fix(code-tools): launch errors on Windows & Qwen Code auth issue

### LINKED ISSUE #12985: [Bug]: Some CLI commands in the code cli module fail to start
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.7.19

### Bug Description

opencode, Claude Code, GitHub Copilot CLI, and iFlow CLI all have similar error messages:
Image

"Installing @github/copilot..."
bun add v1.2.9 (9a329c04)
  🔍 Resolving [1/4] ============================================================
Bun v1.2.9 (9a329c04) Windows x64 (baseline)
Windows v.win11_dt
CPU: sse42 avx avx2
Args: "C:\Users\wmh21\.cherrystudio\bin\bun.exe" "install" "-g" "@github/copilot"
Features: text_lockfile
Elapsed: 88ms | User: 0ms | Sys: 31ms
RSS: 99.93MB | Peak: 99.93MB | Commit: 0.17GB | Faults: 24647

panic(thread 30364): Internal assertion failure at install/npm.zig:2412:66
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

---

qwen-code has this error:
"Checking qwen-code version..."
"Updating qwen-code from null to 0.10.5..."
"Update failed: Failed to update qwen-code: Command failed: set "BUN_INSTALL=C:\Users\wmh21\.cherrystudio" && set "NPM_CONFIG_REGISTRY=https://registry.npmmirror.com" && "C:\Users\wmh21\.cherrystudio\bin\bun.exe" install -g @qwen-code/qwen-code
'Resolving' is not recognized as an internal or external command,
operable program or batch file.
'Bun' is not recognized as an internal or external command,
operable program or batch file.
'Windows' is not recognized as an internal or external command,
operable program or batch file.
'CPU:' is not recognized as an internal or external command,
operable program or batch file.
'Args:' is not recognized as an internal or external command,
operable program or batch file.
'Features:' is not recognized as an internal or external command,
operable program or batch file.
'Elapsed:' is not recognized as an internal or external command,
operable program or batch file.

---

Gemini CLI and Kimi CLI work normally.

---

OpenAI CodeX has no corresponding model available to start.

### Steps To Reproduce

https://github.com/user-attachments/assets/7c47d214-6d67-4001-9fa7-3f9fd620ecd3

### Expected Behavior

Normal startup for the CLI tool

### Relevant Log Output

```shell

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by GeorgeDong32**
### What this PR does

Before this PR:
- CLI tools (qwen-code, Claude Code, GitHub Copilot CLI, etc.) fail to start on Windows
- bun install's multiline output (e.g., "Resolving [1/4]\nBun v1.2.9...") is misinterpreted by cmd.exe as separate commands
- Users see errors like "'Resolving' is not recognized as an internal or external command"
- Windows Terminal launch failed
- Qwen Code auth type incorrect, in [docs](https://qwenlm.github.io/qwen-code-docs/zh/users/configuration/model-providers/)

After this PR:
- Redirect bun install output to a log file on Windows
- Log file location: `userData/logs/cli-tools-install.log` (via `loggerService.getLogsDir()`)
- Windows Terminal launch normally
- Qwen Code auth type set to "openai" when package version >= 0.12.3

Fixes #12985 #13442 #13473

### Why we need it and why it was done in this way

The following tradeoffs were made:
- Using file redirection (`>> "logfile" 2>&1`) instead of `--silent` flag to preserve debug information for troubleshooting
- Windows-only fix since macOS/Linux terminals correctly handle multiline output

The following alternatives were considered:
- Using `bun install --silent`: Rejected because it would lose all debug information

Links to places where the discussion took place: #12985

### Breaking changes

None

### Special notes for your reviewer

- The fix uses `loggerService.getLogsDir()` to ensure logs are written to the same directory as other Cherry Studio logs
- Tested on Windows with qwen-code, GitHub Copilot CLI, and other affected tools

### Checklist

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. Check this only when the PR introduces or changes a user-facing feature or behavior.
- [x] Self-review: I have reviewed my own code (e.g., via [`/gh-pr-review`](/.claude/skills/gh-pr-review/SKILL.md), `gh pr diff`, or GitHub UI) before requesting review from others

### Release note

```release-note
Fix CLI tools failing to start on Windows by redirecting bun install output to log file
```

### CODE REVIEW

**Comment by GeorgeDong32** [comment]
> [!NOTE]
> This comment was translated by Claude.

The last two issues are reproducible, and I have verified that they are resolved. However, I cannot reproduce #12985 on my side, so I tentatively believe it can be solved with output redirection. @DeJeune @beyondkmp feel free to try it when you have time.

---
<details>
<summary>Original Content</summary>

后两个issue可复现，我这边验证解决了。但是 #12985 我这边复现不出来，暂时判断是输出重定向可以解决的。 @DeJeune @beyondkmp 有空可以试试

</details>

File: src/main/services/CodeToolsService.ts [hunk 1]
```diff
@@ -80,6 +80,26 @@ class CodeToolsService {
     return bunPath
   }
 
+  /**
+   * Compare two semantic versions
+   * @param version1 - First version string (e.g., "1.2.3")
+   * @param version2 - Second version string (e.g., "1.2.4")
+   * @returns -1 if version1 < version2, 0 if equal, 1 if version1 > version2
+   */
+  private compareVersions(version1: string, version2: string): number {
```
Comment (beyondkmp) [inline src/main/services/CodeToolsService.ts]: > [!NOTE]
> This comment was translated by Claude.

It would be better to use the semver library.

---
<details>
<summary>Original Content</summary>
用 semver lib库应该更好。
</details>

File: src/main/services/CodeToolsService.ts [hunk 2]
```diff
@@ -913,6 +922,18 @@ class CodeToolsService {
       baseCommand = `${uvPath} tool run ${packageName}`
     }
 
+    // Special handling for qwen-code: add --auth-type openai for version >= 0.12.3
+    if (cliTool === codeTools.qwenCode) {
+      // Use semver for proper version comparison (handles v-prefix, prereleases, etc.)
+      const needsAuthType = installedVersion && semver.gte(semver.coerce(installedVersion) || '0.0.0', '0.12.3')
```
Comment (DeJeune) [inline src/main/services/CodeToolsService.ts]: **[A2]** `semver.coerce()` can return `null` when `installedVersion` is a non-semver string. The fallback `|| '0.0.0'` passes a **string** to `semver.gte()`, which expects a `SemVer` object — this will throw at runtime.

Suggested fix:
```ts
const coerced = semver.coerce(installedVersion)
const needsAuthType = installedVersion && coerced && semver.gte(coerced, '0.12.3')
```
