### PR TITLE
fix(providers): update poe url

### LINKED ISSUE #9259: [错误]: poe的GPT5适配问题
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我的问题不是 [常见问题](https://github.com/CherryHQ/cherry-studio/issues/3881) 中的内容。
- [x] 我已经查看了 **置顶 Issue** 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。
- [x] 我确认我正在使用最新版本的 Cherry Studio。

### 平台

Windows

### 版本

1.5.6

### 错误描述

1.poe的默认地址为https://api.poe.com/v1，缺少了一个/
2.poe的GPT5设置思考强度的方式是在prompt最后加入 --reasoning_effort minimal/low/medium/high，即：解决这个问题 --reasoning_effort high，目前cherry的推理强度设置貌似对poe是不生效的

### 重现步骤

正常使用poe服务商的GPT5模型即可

### 预期行为

正确处理如上两个问题

### 相关日志输出

```shell

```

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by EurFelux**
### What this PR does

- 修复了poe的base url
- 支持poe特别的 GPT-5, Gemini, Claude 的命令式思考参数设置

Fixes #9259

### Why we need it and why it was done in this way

The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Breaking changes

If this PR introduces breaking changes, please describe the changes and the impact on users.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### Release note

```release-note

```

### CODE REVIEW

File: src/renderer/src/types/sdk.ts [hunk 1]
```diff
@@ -81,7 +81,14 @@ export type ReasoningEffortOptionalParams = {
   thinking_budget?: number
   incremental_output?: boolean
   enable_reasoning?: boolean
-  extra_body?: Record<string, any>
+  extra_body?: {
+    google?: {
```
Comment (DeJeune) [inline src/renderer/src/types/sdk.ts:85]: 不一定只有google{}

Comment (EurFelux) [reply src/renderer/src/types/sdk.ts:85]: 目前只有google，后面需要的时候再修改类型吧
