### PR TITLE
fix(knowledge): support Ollama knowledge embeddings

### LINKED ISSUE #14168: [Bug]: Error when adding knowledge base using ollama nomic-embed-text model
> [\!NOTE]
> This issue was translated by Claude.

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

macOS

### Version

v1.8.4

### Bug Description

Image
Using local ollama nomic-embed-text model prompted: Embedding failed: Cannot read properties of undefined (reading '0')

I tried using the local CLI after encountering this problem, and it worked without issues
Image

Using local ollama inference model deepseek-r1:8b in Cherry Studio runs normally
Image

I also tried using OpenRouter's embedding model and it had no issues
Image

### Steps To Reproduce

Steps have been included in the details above

### Expected Behavior

Expect to be able to use ollama embedding model normally, web search found no answer to this problem

### Relevant Log Output

```shell

```

### Additional Context

_No response_

---
<details>
<summary>Original Content</summary>

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

macOS

### Version

v1.8.4

### Bug Description

Image
使用本地ollama  nomic-embed-text模型提示  嵌入失败:Cannot read properties ofundefined (reading '0')

遇到这个问题我尝试使用了本地cli执行没有问题
Image

在cherry studio使用本地ollama推理模型deepseek-r1:8b正常运行
Image

也尝试了使用Openrouter的嵌入模型也是没问题的
Image

### Steps To Reproduce

步骤已经附在详情中

### Expected Behavior

能正常使用ollama嵌入模型，网络搜索没有该问题的答案

### Relevant Log Output

```shell

```

### Additional Context

_No response_
</details>

### PR DESCRIPTION
**Pull request by 404-Page-Found**
### What this PR does

Before this PR:
- Creating a knowledge base with an Ollama embedding model such as `nomic-embed-text` could fail during initialization with `Cannot read properties of undefined (reading '0')`.

After this PR:
- Knowledge base initialization keeps using `@cherrystudio/embedjs-ollama` instead of a Cherry Studio-only Ollama adapter.
- The PR applies the Ollama response-handling hotfix in a scoped `pnpm` patch for `@cherrystudio/embedjs-ollama`.
- The patched library handles the current `/api/embed` response shape and falls back to the legacy `/api/embeddings` response during dimension detection.
- A focused regression test covers configured dimensions, current Ollama responses, and legacy fallback behavior.

Fixes #14168

### Why we need it and why it was done in this way

The following tradeoffs were made:
- Moved the fix from app-local code into a patched `@cherrystudio/embedjs-ollama` dependency so Cherry Studio can keep using the library abstraction on the frozen `main` branch.
- Kept support for both current and legacy Ollama embedding APIs because the failure happens during dimension probing before any documents are added.

The following alternatives were considered:
- Keeping the Cherry Studio-only `OllamaEmbeddings` adapter introduced in the first revision of this PR.
- Opening an upstream `CherryHQ/embed-js` PR first and waiting for a released package version before fixing Cherry Studio.
- Patching `@langchain/ollama` or widening shared dependency changes on `main`.

Links to places where the discussion took place: https://github.com/CherryHQ/cherry-studio/pull/14172#issuecomment-4229167072

### Breaking changes

If this PR introduces breaking changes, please describe the changes and the impact on users.

None.

### Special notes for your reviewer

- Per review, this PR no longer keeps a Cherry Studio-only Ollama adapter; the fix now lives in the patched `@cherrystudio/embedjs-ollama` dependency.
- `pnpm exec vitest run src/main/knowledge/embedjs/embeddings/__tests__/OllamaEmbeddings.test.ts` passed.
- `pnpm lint` completed successfully.
- `pnpm test` still fails in pre-existing CherryClaw prompt tests under `src/main/services/agents/services/cherryclaw/__tests__/prompt.test.ts`; these failures are unrelated to this hotfix.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. Check this only when the PR introduces or changes a user-facing feature or behavior.
- [x] Self-review: I have reviewed my own code (e.g., via [`/gh-pr-review`](/.claude/skills/gh-pr-review/SKILL.md), `gh pr diff`, or GitHub UI) before requesting review from others

### Release note

```release-note
Fix knowledge base creation for Ollama embedding models such as `nomic-embed-text` by handling current and legacy Ollama embedding API responses through `@cherrystudio/embedjs-ollama` during dimension detection.
```

### CODE REVIEW

File: src/main/knowledge/embedjs/embeddings/OllamaEmbeddings.ts [hunk 1]
```diff
@@ -0,0 +1,145 @@
...
+  private readonly headers?: Record<string, string>
+
+  constructor(configuration: OllamaEmbeddingsConfig) {
+    super()
+
+    this.model = configuration.model
+    this.baseUrl = configuration.baseUrl
+    this.dimensions = configuration.dimensions
+    this.keepAlive = configuration.keepAlive
+    this.truncate = configuration.truncate ?? false
```
Comment (eeee0717) [inline src/main/knowledge/embedjs/embeddings/OllamaEmbeddings.ts]: **Bug:** Ollama's /api/embed endpoint already defaults `truncate` to `true`, but this adapter now forces it to `false` for every request because `EmbeddingsFactory` never passes an explicit override. That changes the previous behavior from "truncate long inputs" to "fail when a chunk exceeds the model context window", which can break knowledge indexing for long documents. Please leave `truncate` undefined unless the caller explicitly sets it, or default it to `true`.

File: src/main/knowledge/embedjs/embeddings/OllamaEmbeddings.ts [hunk 2]
```diff
@@ -0,0 +1,145 @@
...
+        keep_alive: this.keepAlive,
+        truncate: this.truncate,
+        dimensions: this.dimensions,
+        options: this.requestOptions
+      })
+
+      return this.normalizeEmbeddings(response)
+    } catch (currentApiError) {
+      try {
+        return await Promise.all(texts.map((text) => this.embedWithLegacyApi(text)))
```
Comment (eeee0717) [inline src/main/knowledge/embedjs/embeddings/OllamaEmbeddings.ts]: **Bug:** The legacy fallback cannot preserve a caller-supplied `dimensions` value. If a knowledge base is configured with custom dimensions, `getDimensions()` returns that configured size without probing, but `embedDocuments()` will still fall back to /api/embeddings, which has no `dimensions` parameter and can return the model's default length instead. The failure then moves downstream to vector-store insertion with a dimension mismatch. Please fail fast when `dimensions` is set and only the legacy endpoint is available, and add a regression test for that path.

**Comment by kangfenmao** [comment]
> [\!NOTE]
> This issue/comment/review was translated by Claude.

It would be better to PR this library first: https://github.com/CherryHQ/embed-js

https://github.com/CherryHQ/embed-js/blob/main/models/embedjs-ollama/src/ollama-embeddings.ts

---
<details>
<summary>Original Content</summary>

直接先 pr 这个库会比较好一些：https://github.com/CherryHQ/embed-js

https://github.com/CherryHQ/embed-js/blob/main/models/embedjs-ollama/src/ollama-embeddings.ts

</details>

**Comment by eeee0717** [comment]
> [\!NOTE]
> This issue/comment/review was translated by Claude.

@404-Page-Found It should not be a patch, but submit a PR in the https://github.com/CherryHQ/embed-js repository

---
<details>
<summary>Original Content</summary>

@404-Page-Found 应该不是打patch，而是在 https://github.com/CherryHQ/embed-js 这个仓库提交pr
</details>

**Comment by 404-Page-Found** [comment]
> [\!NOTE]
> This issue/comment/review was translated by Claude.

Submitted upstream PR as suggested: CherryHQ/embed-js#8

This fix has been migrated to embed-js, handling current /api/embed responses and compatible with legacy /api/embeddings fallback.

---
<details>
<summary>Original Content</summary>

已按建议先提交上游 PR：CherryHQ/embed-js#8

这个修复已迁移到 embed-js 中，处理当前 /api/embed 响应并兼容旧版 /api/embeddings 回退。

</details>

**Comment by kangfenmao** [comment]
> [\!NOTE]
> This issue/comment/review was translated by Claude.

Shouldn't we update the @cherrystudio/embedjs-ollama version instead of solving it by patching?

---
<details>
<summary>Original Content</summary>

是不是要更新一下 @cherrystudio/embedjs-ollama 版本，而不是通过打 patch 来解决
</details>

**Comment by eeee0717** [comment]
> [\!NOTE]
> This issue/comment/review was translated by Claude.

@kangfenmao Has the embedjs version been released?

---
<details>
<summary>Original Content</summary>

@kangfenmao embedjs版本发了吗？

</details>

**Comment by kangfenmao** [comment]
> [\!NOTE]
> This issue/comment/review was translated by Claude.

It has been released.

---
<details>
<summary>Original Content</summary>

已经发了
</details>

**Comment by 404-Page-Found** [comment]
> [\!NOTE]
> This issue/comment/review was translated by Claude.

@kangfenmao @eeee0717 Changed to use the published @cherrystudio/embedjs-ollama 0.1.35 directly, removed local patch, and confirmed Ollama regression tests pass.

---
<details>
<summary>Original Content</summary>

@kangfenmao @eeee0717 已改为直接使用已发布的 @cherrystudio/embedjs-ollama 0.1.35，去掉本地 patch，并确认 Ollama 回归测试通过。

</details>

**Review by eeee0717 — APPROVED** [review]

File: src/main/knowledge/embedjs/embeddings/EmbeddingsFactory.ts [hunk 3]
```diff
@@ -20,12 +20,9 @@ export default class EmbeddingsFactory {
...
+        model,
         baseUrl: baseURL.replace(/\/api$/, ''),
-        requestOptions: {
-          // @ts-ignore expected
-          'encoding-format': 'float'
-        }
+        dimensions
       })
     }
     // NOTE: Azure OpenAI 也走 OpenAIEmbeddings, baseURL是https://xxxx.openai.azure.com/openai/v1
```
Comment (GeorgeDong32) [inline src/main/knowledge/embedjs/embeddings/EmbeddingsFactory.ts:28]: ✅ **代码简化做得很好**

移除了冗余的 `requestOptions` 和 `ts-ignore`，代码更简洁清晰。新增 `dimensions` 参数传递也符合预期，避免了每次都需要探测维度。

这个改动让代码质量明显提升：
- 移除 `model: model` → `model` (ES6 shorthand)
- 移除不必要的 `encoding-format` 配置
- 移除 `ts-ignore` hack

File: src/main/knowledge/embedjs/embeddings/__tests__/OllamaEmbeddings.test.ts [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+        body: JSON.stringify({
+          model: 'nomic-embed-text',
+          prompt: 'second',
+          keep_alive: undefined,
+          options: undefined
+        })
+      })
+    )
+  })
+})
```
Comment (GeorgeDong32) [inline src/main/knowledge/embedjs/embeddings/__tests__/OllamaEmbeddings.test.ts:100]: ✅ **测试覆盖充分**

三个测试场景覆盖了关键路径：
1. 配置 dimensions 时无需探测（避免不必要的 API 调用）
2. 当前 `/api/embed` 响应格式处理
3. `/api/embed` 失败时回退到 `/api/embeddings`

Mock 模式正确隔离了外部依赖，边界清晰。

**Review by GeorgeDong32 — APPROVED** [review]
## 审查总结

✅ **批准此 PR**

### 变更质量

| 维度 | 评价 |
|------|------|
| **安全性** | ✅ 无安全风险 |
| **代码质量** | ✅ 简洁有效，移除 ts-ignore |
| **测试覆盖** | ✅ 三关键场景已覆盖 |
| **向后兼容** | ✅ 新旧 API 均支持 |

###亮点

1. **正确的开源协作流程** - 先向上游 `embed-js` 提交 PR，再升级依赖版本
2. **代码简化** - 移除冗余配置和 `ts-ignore`，代码更整洁
3. **测试设计** - Mock 模式正确隔离依赖，边界清晰

### 依赖升级

`@cherrystudio/embedjs-ollama` 0.1.31 → 0.1.35 (patch 版本，低风险)

感谢贡献！
