### PR TITLE
fix: improve Qwen 3.5 reasoning model detection and thinking param handling

### LINKED ISSUE #13182: [Bug]: cannot switch the model thinking mode of qwen3.5-397b at nvidia api
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.7.22

### Bug Description

cannot switch the model thinking mode of qwen3.5-397b

### Steps To Reproduce

1. go to nvidia api 
2. use qwen3.5
3. choose thinking mode
4. you can find the model not thinking

### Expected Behavior

the model can thinking in the thinking mode

### Relevant Log Output

```shell

```

### Additional Context

i find that the different models in the nvidia api have different methods to choose thinking mode 
eg: Qwen3.5

you can find that https://docs.api.nvidia.com/nim/reference/qwen-qwen3-5-397b-a17b-infer  qwen3.5 in the nvidia must use this method to choose thinking mode although you use the thinking budgest

```
chat_template_kwargs
Optional kwargs forwarded to the model chat template. Use {"enable_thinking": true} to enable thinking mode or {"enable_thinking": false} to disable it.
```

```
curl --request POST \
     --url https://integrate.api.nvidia.com/v1/chat/completions \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "messages": [
    {
      "role": "system"
    },
    {
      "role": "system"
    },
    {
      "role": "system"
    }
  ],
  "model": "qwen/qwen3.5-397b-a17b",
  "chat_template_kwargs": {
    "enable_thinking": "true"
  },  // the important
  "max_tokens": 16384,
  "stream": false, 
  "temperature": 0.6,
  "top_p": 0.95,
  "top_k": 20,
  "presence_penalty": 0
}

```

### LINKED ISSUE #13220: [Bug]: Qwen3.5: /think appended to prompts and thinking toggle not working
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

1.7.23

### Bug Description

Model: qwen3.5-27b

API Type: Cloud API

Description

When using Qwen3.5 models, the client always appends /think to the end of the user prompt.

Two issues are observed:

Thinking mode toggle in the UI cannot be switched properly.

/think is appended to the request content regardless of whether the reasoning option is enabled or disabled.

This behavior appears to reuse the Qwen3 reasoning control logic, but Qwen3.5 does not use /think as a soft switch for thinking mode, so the injected suffix is unnecessary and may affect model responses.

Steps to Reproduce

Select Qwen3.5 model (e.g. qwen3.5-27b)

Toggle the reasoning / thinking option

Send a message

Inspect the outgoing API request

Actual Request Payload

Example captured request:

POST /v1/chat/completions

{
  "model": "qwen3.5-27b",
  "temperature": 0.8,
  "top_p": 0.9,
  "messages": [
    {
      "role": "system",
      "content": " 我是默认助手"
    },
    {
      "role": "user",
      "content": "你好 /think"
    }
  ],
  "stream": true,
  "stream_options": {
    "include_usage": true
  }
}

Note that the user message becomes:

你好 /think

even though /think was not included in the original input.

Expected Behavior

Additional Notes

/think is used by Qwen3 models for soft reasoning mode switching.

Qwen3.5 models do not rely on this mechanism, so the current behavior appears to be model-specific logic incorrectly applied to Qwen3.5.

### Steps To Reproduce

Select Qwen3.5 model (e.g. qwen3.5-27b)

Toggle the reasoning / thinking option

Send a message

Inspect the outgoing API request

Actual Request Payload

Example captured request:

POST /v1/chat/completions

{
  "model": "qwen3.5-27b",
  "temperature": 0.8,
  "top_p": 0.9,
  "messages": [
    {
      "role": "system",
      "content": " 我是默认助手"
    },
    {
      "role": "user",
      "content": "你好 /think"
    }
  ],
  "stream": true,
  "stream_options": {
    "include_usage": true
  }
}

Note that the user message becomes:

你好 /think

even though /think was not included in the original input.

### Expected Behavior

The client should not automatically append /think when using Qwen3.5 models.

The thinking mode toggle should behave correctly.

Requests should send the original user prompt unchanged, unless explicitly required by the model.

### Relevant Log Output

```shell
[DEBUG]
 Received request: POST to /v1/chat/completions with body  {
  "model": "qwen3.5-27b",
  "temperature": 0.8,
  "top_p": 0.9,
  "messages": [
    {
      "role": "system",
      "content": " 我是默认助手"
    },
    {
      "role": "user",
      "content": "你好 /think"
    }
  ],
  "stream": true,
  "stream_options": {
    "include_usage": true
  }
}
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by EurFelux**
### What this PR does

Before this PR:
- `isSupportedThinkingTokenQwenModel` used a hardcoded model ID list, missing some Qwen variants (e.g. `qwen-max-latest`)
- Qwen 3.5 models incorrectly went through QwenThinkingPlugin (not supported since Qwen 3.5)
- Qwen 3.5 non-thinking mode did not send `chat_template_kwargs.enable_thinking: false`
- `chat_template_kwargs` type was missing `enable_thinking` field

After this PR:
- Replaced hardcoded list with regex patterns (MAX, PLUS, FLASH, TURBO, QWEN3_OPEN) for better coverage of current and future model variants
- Added `isQwen35Model` helper to distinguish Qwen 3.5 from Qwen 3 series
- Excluded Qwen 3.5 from QwenThinkingPlugin since it uses a different thinking param format
- Added `chat_template_kwargs.enable_thinking: false` for Qwen 3.5 non-thinking mode
- Consolidated Qwen 3.5 thinking token map entries into a single regex
- Updated `chat_template_kwargs` type to include `enable_thinking`

Fixes #13220
Fixes #13182

### Why we need it and why it was done in this way

The following tradeoffs were made:
- Qwen 3.5 doesn't support soft thinking control like `/think` and `/no_think`. Instead, we should use `chat_template_kwargs` to send thinking parameter for providers which don't directly support `enable_thinking`.
- Regex patterns are more maintainable than hardcoded lists and automatically cover dated snapshot variants (e.g. `qwen-plus-2025-07-28`)
- `isQwen35Model` is placed in a separate `qwen.ts` utility file for reuse across reasoning and plugin logic

The following alternatives were considered:
- Keeping the hardcoded list approach, but it requires manual updates for every new model snapshot

### Breaking changes

None

### Special notes for your reviewer

- The `QWEN3_OPEN_REGEX` (`/^qwen3-\d/i`) matches open-weight Qwen3 models by numeric size prefix (e.g. `qwen3-8b`), after `instruct`/`thinking`/`coder` variants are already filtered out
- `qwen3-max-2025-09-23` is explicitly excluded via negative lookahead as only this qwen3-max variant doesn't support reasoning control

### Checklist

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: Write code that humans can understand and Keep it simple
- [x] Refactor: You have left the code cleaner than you found it (Boy Scout Rule)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A user-guide update was considered and is present (link) or not required.
- [x] Self-review: I have reviewed my own code before requesting review from others

### Release note

```release-note
NONE
```

### CODE REVIEW

File: src/renderer/src/aiCore/utils/reasoning.ts [hunk 1]
```diff
@@ -143,6 +144,16 @@ export function getReasoningEffort(assistant: Assistant, model: Model): Reasonin
       }
     }
 
+    // Qwen 3.5 without enable_thinking
```
Comment (EurFelux) [inline src/renderer/src/aiCore/utils/reasoning.ts]:
```suggestion
    // Qwen 3.5 without direct enable_thinking
```

File: src/renderer/src/aiCore/utils/reasoning.ts [hunk 2]
```diff
@@ -371,11 +382,21 @@ export function getReasoningEffort(assistant: Assistant, model: Model): Reasonin
...
+    if (supportEnableThinking) {
+      return {
+        ...enableThinkingConfig,
+        thinking_budget: budgetTokens
+      }
+    } else {
+      return {
+        thinking_budget: budgetTokens,
+        chat_template_kwargs: {
+          ...enableThinkingConfig
```
Comment (EurFelux) [inline src/renderer/src/aiCore/utils/reasoning.ts:396]: This parameter is also sent to qwen3 model. Please check it.

File: src/renderer/src/config/models/__tests__/models.test.ts [hunk 3]
```diff
@@ -65,17 +66,35 @@ describe('Qwen Model Detection', () => {
...
+    expect(isSupportedThinkingTokenQwenModel({ id: 'qwen3.5-plus' } as Model)).toBe(true)
+    expect(isSupportedThinkingTokenQwenModel({ id: 'qwen-plus' } as Model)).toBe(true)
+    expect(isSupportedThinkingTokenQwenModel({ id: 'qwen-plus-latest' } as Model)).toBe(true)
+    expect(isSupportedThinkingTokenQwenModel({ id: 'qwen3.5-plus-2026-02-15' } as Model)).toBe(true)
+    // flash
+    expect(isSupportedThinkingTokenQwenModel({ id: 'qwen3.5-flash' } as Model)).toBe(true)
+    expect(isSupportedThinkingTokenQwenModel({ id: 'qwen3.5-flash-2026-02-23' } as Model)).toBe(true)
+    expect(isSupportedThinkingTokenQwenModel({ id: 'qwen-flash' } as Model)).toBe(true)
+    expect(isSupportedThinkingTokenQwenModel({ id: 'qwen-flash-2025-07-28' } as Model)).toBe(true)
+    // turbo (deprecated)
```
Comment (EurFelux) [inline src/renderer/src/config/models/__tests__/models.test.ts]:
```suggestion
    // turbo (deprecated variant in dashscope)
```

File: src/renderer/src/aiCore/utils/reasoning.ts (hunk 2 above)
Comment (EurFelux) [reply src/renderer/src/aiCore/utils/reasoning.ts:396]: seems ok

File: src/renderer/src/config/models/qwen.ts [hunk 4]
```diff
@@ -5,3 +5,20 @@ export const isQwenMTModel = (model: Model): boolean => {
...
+ *
+ * This function determines whether the given model belongs to the Qwen 3.5 series
+ * by checking if its ID starts with 'qwen3.5'. The check is case-insensitive.
+ *
+ * @param model - The model to check, can be undefined.
+ * @returns `true` if the model is a Qwen 3.5 series model, `false` otherwise.
+ */
+export function isQwen35Model(model?: Model): boolean {
+  if (!model) {
+    return false
```
Comment (DeJeune) [inline src/renderer/src/config/models/qwen.ts:20]: Nit: startsWith('qwen3.5') may also match qwen3.50* style IDs. Consider a stricter pattern like qwen3.5 followed by '-' or end of string to avoid accidental over-match.

**Review by DeJeune — COMMENTED** [review]
Overall looks good. Nice cleanup around Qwen 3.5 handling and provider-specific thinking param routing. Findings: one non-blocking inline nit about tightening isQwen35Model matching boundary to avoid potential future over-match. No blocking issues from my side.

File: src/renderer/src/config/models/qwen.ts (hunk 4 above)
Comment (EurFelux) [reply src/renderer/src/config/models/qwen.ts:20]: > [!NOTE]
> This comment was translated by Claude.

By convention, model versions are unlikely to reach x.10 or above.

---
<details>
<summary>Original Content</summary>

按照惯例，模型版本不太可能到x.10以上

</details>

File: src/renderer/src/aiCore/utils/reasoning.ts
Comment (aosan002) [inline src/renderer/src/aiCore/utils/reasoning.ts:89]: In this case, Qwen 3.5 also passes the check, causing it to return incorrect request parameters.

Comment (EurFelux) [reply src/renderer/src/aiCore/utils/reasoning.ts:89]: > [!NOTE]
> This comment was translated by Claude.

By default, `enable_thinking` is used, and the fallback branch is only entered when `isSupportEnableThinkingProvider` returns `false`. If your provider does not support this parameter, you need to configure it manually in the provider settings page.

---
<details>
<summary>Original Content</summary>

默认使用`enable_thinking`，仅在`isSupportEnableThinkingProvider`得到`false`时进入后面的回退分支。如果你使用的provider不支持该参数，需要在provider设置页面自行配置。

</details>

Comment (aosan002) [reply src/renderer/src/aiCore/utils/reasoning.ts:89]: > [!NOTE]
> This comment was translated by Claude.

We are currently using VLLM to deploy Qwen 3.5. Both `isSupportEnableThinkingProvider` and `isSupportedThinkingTokenQwenModel` return True, so the program returns directly here and won't reach the Qwen 3.5 branch below. So this place might need to handle Qwen 3.5 separately?

---
<details>
<summary>Original Content</summary>

现在我们使用的是VLLM来部署的Qwen 3.5,  `isSupportEnableThinkingProvider` 和`isSupportedThinkingTokenQwenModel`返回为True，所以程序直接在此处返回了，不会走到下面的Qwen 3.5的分支，所以这个地方可能要另外处理Qwen 3.5的情况？

</details>

Comment (EurFelux) [reply src/renderer/src/aiCore/utils/reasoning.ts:89]: > [!NOTE]
> This comment was translated by Claude.

No need, if you use vllm you should be using a custom provider, just need to change the API settings:

image

---
<details>
<summary>Original Content</summary>

不用，你用vllm的话应该就是自定义供应商了，改下api设置就行：

image

</details>

Comment (EurFelux) [reply src/renderer/src/aiCore/utils/reasoning.ts:89]: > [!NOTE]
> This comment was translated by Claude.

btw, the commits in this PR haven't been released to the stable version yet, so if you want to use this feature, you'll need to use the nightly build version.

---
<details>
<summary>Original Content</summary>

btw, 这个pr的commit还没发布到正式版，所以你想用上这个feature的话得用nightly build版本

</details>

Comment (aosan002) [reply src/renderer/src/aiCore/utils/reasoning.ts:89]: > [!NOTE]
> This issue/comment/review was translated by Claude.

Thanks for the reply. I saw this PR and built it myself to try it out. The problem persisted, so I looked at the code and found that for my case, the issue was here. Later, when the Release version is released, I'll follow your reply settings. Thanks again~

---
<details>
<summary>Original Content</summary>

感谢回复，我是看有这个PR之后就自己Build试了一下，问题还在就看了下代码，发现对于我的情况是这里出了问题，后面等Release版本上线之后就按照您刚刚的回复设置了，再次感谢~

</details>
