### PR TITLE
fix(openai): apply verbosity setting with type safety improvements

### LINKED ISSUE #10963: [Bug]: GPT-5 series models'  parameter settings are not working in version 1.6.x, custom parameter settings are also not working
> [!NOTE]
> This issue/comment/review was translated by Claude.

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

1.6.5

### Bug Description

The `verbosity` setting for GPT-5 series models is not working. After testing, version 1.5.11 works normally, but all 1.6.x versions are not working.
Additionally, the "Custom Parameters" setting is also completely ineffective.

Image

### Steps To Reproduce

1. Select GPT-5 model
2. Set the "Verbosity" option in "OpenAI Settings" in the left sidebar settings
3. Start a conversation

### Expected Behavior

The `verbosity` setting and custom parameters should take effect

### Relevant Log Output

```shell

```

### Additional Context

_No response_

---
<details>
<summary>Original Content</summary>

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

1.6.5

### Bug Description

GPT-5系列模型的`verbosity`设置选项无效。经过测试1.5.11版本是正常的，1.6.x版本均无效。
而且"自定义参数"设置也完全无效。

Image

### Steps To Reproduce

1. 模型选择GPT-5
2. 左侧栏设置中的"OpenAI设置"中设置"详细程度"选项
3. 进行对话

### Expected Behavior

`verbosity`设置及自定义参数生效

### Relevant Log Output

```shell

```

### Additional Context

_No response_
</details>

### PR DESCRIPTION
**Pull request by EurFelux**
### What this PR does

**Before this PR:**
- The verbosity setting for OpenAI GPT-5 models was not being applied during API requests
- Type definitions for OpenAI-specific parameters were scattered across different files
- Service tier type handling lacked proper type safety
- Summary text default value was set to 'off' instead of 'auto'

**After this PR:**
- Verbosity setting is now properly retrieved and applied to OpenAI provider options
- Consolidated OpenAI-specific types (`OpenAIVerbosity`, `OpenAISummaryText`) into `aiCoreTypes.ts`
- Enhanced `getServiceTier` with function overloads for better type safety
- Improved `Selector` component to support `undefined` and `null` values
- Updated summary text default to 'auto' with migration for existing users
- Added utility functions (`toNullIfUndefined`, `toUndefinedIfNull`) for null/undefined handling
- Renamed `options` parameter to `requestOptions` for better clarity

Fixes #10963

### Why we need it and why it was done in this way

**Problem:**
The verbosity setting was being stored in Redux but never actually passed to the AI provider, causing the setting to have no effect on API requests.

**Solution approach:**
1. Added `getVerbosity()` function to retrieve the setting from Redux store
2. Applied `textVerbosity` parameter when building provider options for OpenAI and compatible providers
3. Refactored types to be more explicit and type-safe, preventing similar issues in the future

**Tradeoffs made:**
- Changed the meaning of `undefined` vs `null` for service tier settings (undefined = default, null = explicitly off)
- This provides clearer semantics and better type safety, though it requires a data migration

**Alternatives considered:**
- Could have left types as-is, but the refactoring improves maintainability and catches potential bugs at compile time

### Breaking changes

None. The data migration (version 177) handles converting legacy 'off' values to 'auto' automatically.

### Special notes for your reviewer

1. The function overloads in `getServiceTier` ensure that Groq providers return `GroqServiceTier` while other providers return `OpenAIServiceTier`, eliminating runtime type mismatches
2. The `Selector` component changes enable it to properly handle "Off" (null) and "Default" (undefined) options in the UI
3. The verbosity setting is now consistently applied across all OpenAI-compatible providers (OpenAI, Azure, custom providers using OpenAI API)

### Checklist

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: Write code that humans can understand and Keep it simple
- [x] Refactor: Left the code cleaner than before (Boy Scout Rule)
- [x] Upgrade: Data migration (version 177) handles the summary text setting change
- [ ] Documentation: No user-guide update required (internal fix)

### Release note

```release-note
fix(openai): verbosity setting now properly applies to GPT-5 model requests
refactor(types): improved type safety for OpenAI provider options and service tiers
```

### CODE REVIEW

File: src/renderer/src/types/provider.ts [hunk 1]
```diff
@@ -39,36 +42,36 @@ export type ProviderApiOptions = {
   isNotSupportEnableThinking?: boolean
 }
 
+// scale is not well supported now. It event lacks of docs
```
Comment (EurFelux) [inline src/renderer/src/types/provider.ts]:
```suggestion
// scale is not well supported now. It even lacks of docs
```

**Comment by DeJeune** [comment]
> [!NOTE]
> This issue/comment/review was translated by Claude.

You can install the @ai-sdk/groq dependency, the officially maintained one should have some input parameter validation

---
<details>
<summary>Original Content</summary>

可以安装一下 @ai-sdk/groq依赖，官方维护的应该有一些入参校验

</details>

**Comment by EurFelux** [comment]
> [!NOTE]
> This issue/comment/review was translated by Claude.

I took a look, and the type definitions are not great. reasoningEffort is even a pure string type.

---
<details>
<summary>Original Content</summary>

看了一下，类型定义不太行，reasoningEffort甚至是纯string类型

</details>

File: src/renderer/src/store/migrate.ts [hunk 2]
```diff
@@ -2797,14 +2799,38 @@ const migrateConfig = {
...
+        state.llm.settings.awsBedrock = llmInitialState.settings.awsBedrock
+      } else {
+        // For users who have awsBedrock but missing new fields (authType and apiKey)
+        if (!state.llm.settings.awsBedrock.authType) {
+          state.llm.settings.awsBedrock.authType = 'iam'
+        }
+        if (state.llm.settings.awsBedrock.apiKey === undefined) {
+          state.llm.settings.awsBedrock.apiKey = ''
+        }
+      }
```
Comment (EurFelux) [inline src/renderer/src/store/migrate.ts]: It's a mistake in #10727

**Comment by Nerooo-g** [comment]
The custom parameters still do not work in version 1.7.0-rc1. When can we expect this issue to be fixed?

File: packages/shared/utils.ts [hunk 3]
```diff
@@ -4,3 +4,28 @@ export const defaultAppHeaders = () => {
     'X-Title': 'Cherry Studio'
   }
 }
+/**
```
Comment (defi-failure) [inline packages/shared/utils.ts:11]: Defined and not used, should we remove it?

Comment (EurFelux) [reply packages/shared/utils.ts:11]: True. Maybe I'll need it later, so I'll just comment it out for now.

**Comment by EurFelux** [comment]
@0xfullex It's ready for merge
