### PR TITLE
fix: fall back to first message text when topic naming fails

### LINKED ISSUE #12842: Continuously popping up: Topic naming failed
> [!NOTE]
> This issue was translated by Claude.

Image

Why is this happening? I'm already on the latest version 1.7.17
Image

---
<details>
<summary>Original Content</summary>

Image

这是为什么？已经是最新版本1.7.17了
Image

</details>

### PR DESCRIPTION
**Pull request by DeJeune**
### What this PR does

Before this PR:
When LLM-based topic auto-rename fails (e.g. the quick model's provider has no API key configured, or the API call errors), an error toast "Topic naming failed" is displayed. Because the topic name remains as the default, `autoRenameTopic` retries on every subsequent message completion, causing repeated error toasts to pop up continuously.

After this PR:
When LLM-based topic naming fails, the system silently falls back to extracting the first 50 characters from the first user message as the topic name (the same behavior used when "Topic Auto Rename" is disabled). This gives the topic a meaningful name and prevents the retry loop.

Fixes #12842

### Why we need it and why it was done in this way

The root cause is a feedback loop: failed naming → default name persists → next message triggers another rename attempt → fails again → repeated error toasts. The fix breaks this loop by providing a fallback name.

The following tradeoffs were made:
- Error toasts are removed from the auto-rename path. Users who want LLM-based naming but have misconfigured their quick model will silently get text-extracted names instead of being alerted. However, the manual "Auto Rename" context menu option still shows errors since it's user-initiated.

The following alternatives were considered:
- Only suppressing the toast without setting a fallback name — rejected because it would still retry on every message (wasting API calls when the key exists but calls fail)
- Showing the error only once per topic — more complex and still leaves the topic unnamed
- Adding a retry limit — adds complexity without addressing the UX issue

### Breaking changes

None. The manual "Auto Rename" context menu action still shows error toasts as before. Only the automatic rename path is changed.

### Special notes for your reviewer

The duplicated topic-update logic (`applyTopicName`) and first-message extraction (`getFirstMessageName`) were extracted into local helpers to reduce repetition across the `!enableTopicNaming` and fallback paths.

### Checklist

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: Write code that humans can understand and Keep it simple
- [x] Refactor: You have left the code cleaner than you found it (Boy Scout Rule)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: N/A - no user-facing documentation change needed

### Release note

```release-note
Fixed "Topic naming failed" error toast repeatedly popping up by falling back to first message text when LLM-based topic naming fails.
```

### CODE REVIEW

File: src/renderer/src/store/thunk/messageThunk.ts [hunk 1]
```diff
@@ -161,7 +161,7 @@ export const renameAgentSessionIfNeeded = async (
       return
     }
 
-    const summary = await fetchMessagesSummary({ messages, assistant })
+    const { text: summary } = await fetchMessagesSummary({ messages, assistant })
```
Comment (GeorgeDong32) [inline src/renderer/src/store/thunk/messageThunk.ts:164]: > [!NOTE]
> This issue/comment/review was translated by Claude.

## Suggestion: Add comment explaining why error is ignored

**Priority**: P2

In the `renameAgentSessionIfNeeded` function, the `error` field is ignored, but this is acceptable behavior for background processing. It is recommended to add a comment to explain this.

```typescript
const { text: summary, error } = await fetchMessagesSummary({ messages, assistant })
// Note: We intentionally ignore the error here as this is background processing
// for agent session syncing, not user-facing operations
const summaryText = summary?.trim()
if (!summaryText) {
  return
}
```

---

<details>
<summary>Original Content</summary>

## 建议：添加注释说明 error 被忽略的原因

**优先级**: P2

在 `renameAgentSessionIfNeeded` 函数中，`error` 字段被忽略，但这对于后台处理是可接受的行为。建议添加注释说明这一点。

```typescript
const { text: summary, error } = await fetchMessagesSummary({ messages, assistant })
// Note: We intentionally ignore the error here as this is background processing
// for agent session syncing, not user-facing operations
const summaryText = summary?.trim()
if (!summaryText) {
  return
}
```

</details>

File: src/renderer/src/services/MessagesService.ts [hunk 2]
```diff
@@ -211,7 +211,7 @@ export async function getMessageTitle(message: Message, length = 30): Promise<st
 
       const titlePromise = fetchMessagesSummary({ messages: [tempMessage], assistant: {} as Assistant })
       window.toast.loading({ title: t('chat.topics.export.wait_for_title_naming'), promise: titlePromise })
-      const title = await titlePromise
+      const { text: title } = await titlePromise
```
Comment (GeorgeDong32) [inline src/renderer/src/services/MessagesService.ts:214]: > [!NOTE]
> This comment was translated by Claude.

## Suggestion: Add Logging

**Priority**: P3

In the `getMessageTitle` function, when `fetchMessagesSummary` fails, it is recommended to log the `error` for debugging purposes.

```typescript
const { text: title, error } = await titlePromise
if (!title && error) {
  logger.warn('Failed to fetch message title using topic naming, downgraded to default logic', error)
}
```

---
<details>
<summary>Original Content</summary>

## 建议：添加日志记录

**优先级**: P3

在 `getMessageTitle` 函数中，当 `fetchMessagesSummary` 失败时，建议记录 `error` 日志以便调试。

```typescript
const { text: title, error } = await titlePromise
if (!title && error) {
  logger.warn('Failed to fetch message title using topic naming, downgraded to default logic', error)
}
```

</details>
