### PR TITLE
fix: support gpt-5-codex for github copilot

### LINKED ISSUE #10560: [Bug]: Unable to use GPT-5 Codex from GitHub Copilot
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

macOS

### Version

v1.6.2

### Bug Description

GPT-5 Codex from GitHub Copilot is currently unsupported. The error message says "model gpt-5-codex is not supported in this VS Code version. Please update it to version 1.104.1 or newer".

According to the discussion at https://github.com/zed-industries/zed/issues/38858, `/responses` endpoint should be used for GPT-5 Codex from GitHub Copilot instead of `/chat/completion` endpoint.

### Steps To Reproduce

1. Set up GitHub Copilot Provider
2. Add the model with ID `gpt-5-codex`
3. Send a random message to it
4. Encounter error

### Expected Behavior

The model should respond normally like other models.

### Relevant Log Output

```shell
Error name: AI_APICallError
Error Message: model gpt-5-codex is not supported in this VS Code version. Please update it to version 1.104.1 or newer
Stack Trace: AI_APICallError: model gpt-5-codex is not supported in this VS Code version. Please update it to version 1.104.1 or newer
    at file:///Applications/Cherry%20Studio.app/Contents/Resources/app.asar/out/renderer/assets/dist-DljPbAPG.js:4456:11
    at async postToApi (file:///Applications/Cherry%20Studio.app/Contents/Resources/app.asar/out/renderer/assets/dist-DljPbAPG.js:4352:24)
    at async OpenAICompatibleChatLanguageModel.doStream (file:///Applications/Cherry%20Studio.app/Contents/Resources/app.asar/out/renderer/assets/store-D-H00nsq.js:48200:48)
    at async wrapStream (file:///Applications/Cherry%20Studio.app/Contents/Resources/app.asar/out/renderer/assets/store-D-H00nsq.js:41532:31)
    at async fn (file:///Applications/Cherry%20Studio.app/Contents/Resources/app.asar/out/renderer/assets/store-D-H00nsq.js:39723:17)
    at async file:///Applications/Cherry%20Studio.app/Contents/Resources/app.asar/out/renderer/assets/store-D-H00nsq.js:37132:19
    at async _retryWithExponentialBackoff (file:///Applications/Cherry%20Studio.app/Contents/Resources/app.asar/out/renderer/assets/store-D-H00nsq.js:37234:10)
    at async streamStep (file:///Applications/Cherry%20Studio.app/Contents/Resources/app.asar/out/renderer/assets/store-D-H00nsq.js:39691:108)
    at async fn (file:///Applications/Cherry%20Studio.app/Contents/Resources/app.asar/out/renderer/assets/store-D-H00nsq.js:39970:5)
    at async file:///Applications/Cherry%20Studio.app/Contents/Resources/app.asar/out/renderer/assets/store-D-H00nsq.js:37132:19
Error cause: "[undefined]"
Status Code: 400
Request URL: https://api.githubcopilot.com/chat/completions
Request Body Values: {
  "model": "gpt-5-codex",
  "user": "[undefined]",
  "max_tokens": "[undefined]",
  "temperature": "[undefined]",
  "top_p": "[undefined]",
  "frequency_penalty": "[undefined]",
  "presence_penalty": "[undefined]",
  "response_format": "[undefined]",
  "stop": "[undefined]",
  "seed": "[undefined]",
  "reasoning_effort": "[undefined]",
  "serviceTier": "[undefined]",
  "messages": [
    {
      "role": "user",
      "content": "hi"
    }
  ],
  "tools": "[undefined]",
  "tool_choice": "[undefined]",
  "stream": true,
  "stream_options": {
    "include_usage": true
  }
}
Response Header: {
  "content-length": "169",
  "content-type": "text/plain; charset=utf-8",
  "date": "Tue, 07 Oct 2025 12:55:16 GMT",
  "strict-transport-security": "max-age=31536000",
  "x-content-type-options": "nosniff",
  "x-github-backend": "Kubernetes",
  "x-github-request-id": "E257:2E82E8:331F5CD:3D4DD15:68E50DB4",
  "x-request-id": "00000-9449d4ca-d4b6-4465-967c-6eb45d2dff45"
}
Response Body: {
  "error": {
    "message": "model gpt-5-codex is not supported in this VS Code version. Please update it to version 1.104.1 or newer",
    "code": "model_not_supported_in_version"
  }
}
Data: {
  "error": {
    "message": "model gpt-5-codex is not supported in this VS Code version. Please update it to version 1.104.1 or newer",
    "code": "model_not_supported_in_version"
  }
}
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by beyondkmp**
Fixes #10560

### CODE REVIEW

File: src/renderer/src/aiCore/provider/providerConfig.ts [hunk 1]
```diff
@@ -238,6 +238,17 @@ export function providerToAiSdkConfig(
     }
   }
 
+  if (actualProvider.id === 'copilot' && model.name.toLowerCase().includes('gpt-5-codex')) {
+    const options = ProviderConfigFactory.fromProvider('openai', baseConfig, {
```
Comment (MyPrototypeWhat) [inline src/renderer/src/aiCore/provider/providerConfig.ts]: > [!NOTE]
> This comment was translated by Claude.

Would there be any issues with using openai-compatible?

---
<details>
<summary>Original Content</summary>

用openai-compatible会有什么问题吗

</details>

Comment (beyondkmp) [reply src/renderer/src/aiCore/provider/providerConfig.ts]: > [!NOTE]
> This comment was translated by Claude.

There's an issue with it, that's why we don't use it.

gpt-5-codex cannot use /chat/completions, it can only use /responses. Can openai-compatible use responses? I haven't found the corresponding parameter.

---
<details>
<summary>Original Content</summary>

有问题啊,所以才不用。 

gpt-5-codex不能用/chat/completions, 只能用/responses。 openai-compatible能用responses吗?没有找到对应的参数。
</details>

Comment (MyPrototypeWhat) [reply src/renderer/src/aiCore/provider/providerConfig.ts]: > [!NOTE]
> This comment was translated by Claude.

Got it, indeed we can't use openai-compatible.

---
<details>
<summary>Original Content</summary>

懂了,那确实不能用openai-compatible

</details>

**Comment by beyondkmp** [comment]
@claude review it again.

File: docs/patches/ai-sdk-openai.md [hunk 2]
```diff
@@ -0,0 +1,18 @@
+# @ai-sdk/openai Patch Notes
+
+Cherry Studio applies a Yarn patch to `@ai-sdk/openai@2.0.42` (see `.yarn/patches/@ai-sdk-openai-npm-2.0.42-63cda2d10f.patch`).
```
Comment (EurFelux) [inline docs/patches/ai-sdk-openai.md]: > [!NOTE]
> This comment was translated by Claude.

Considering that the AI SDK is still iterating rapidly, I think it would be better not to apply patches, as it will make future updates more difficult. We could either fork our own version to maintain, or submit a PR directly to the upstream project.

---
<details>
<summary>Original Content</summary>

考虑到aisdk仍在高速迭代,我觉得不要打补丁比较好,否则以后更新也会很麻烦。我们可以fork一个自己的版本来维护,或者直接给上游提pr

</details>

**Comment by beyondkmp** [comment]
@claude  review it again.

File: docs/patches/ai-sdk-openai.md (hunk 2 above)
Comment (beyondkmp) [reply docs/patches/ai-sdk-openai.md]: > [!NOTE]
> This comment was translated by Claude.

Yes, I directly changed to a different implementation approach. Using the plugin library, this way it can be fully compatible with the AI SDK.

---
<details>
<summary>Original Content</summary>
是的,直接换了一种实现方式的。使用plugin库,这样可以完全兼容ai sdk.
</details>

**Comment by MyPrototypeWhat** [comment]
> [!NOTE]
> This comment was translated by Claude.

Having a ready-made library makes things much more convenient.

---
<details>
<summary>Original Content</summary>

有现成的库就方便很多了

</details>

**Comment by beyondkmp** [comment]
> [!NOTE]
> This comment was translated by Claude.

> Having a ready-made library makes things much more convenient.

Yes, if there are any issues later, we can just go there to submit issues or PRs to solve them.

---
<details>
<summary>Original Content</summary>

> 有现成的库就方便很多了

是的,后面有问题就直接去那边提issue或者pr解决了。

</details>
