### PR TITLE
fix(paintings): fix base64 image handling across providers

### LINKED ISSUE #12602: [Bug]: HTTP 413 "Payload Too Large" when sending follow-up messages after a Base64 image generation
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

1.7.15

### Bug Description

I encountered an `AI_APICallError: Payload Too Large (Status 413)` error when attempting to continue a conversation.

The issue occurs when previous Assistant response contains a raw Base64 image string `(e.g., image)`. 
When I send a follow-up message, Cherry Studio attempts to send the entire conversation history including the massive Base64 string back to the API provider. This causes the request body to exceed the server's payload capacity.

### Steps To Reproduce

1. Send a prompt that triggers an image generation where the model returns the image.
2. Wait for the response (the image displays in the chat).
3. Send a text follow-up message.

Result: The application throws an `AI_APICallError`.

Image

--- 
Error Detail <br>
Image

### Expected Behavior

Cherry Studio should handle Base64 images in the chat history by either:
- Truncating the Base64 string from the messages array payload sent to the API for subsequent requests.
 _(Trade-off: This will avoid the HTTP 413 error but will result in a loss of visual context for the model. The user would need to manually re-upload the generated image if they wish to make further edits)_
- Converting the Base64 image to a temporary file reference or a placeholder text in the context window.

### Actual Behavior
The application sends the full raw Base64 string in the messages history. The backend rejects the request because the body size exceeds the allowed limit (HTTP 413).

### Relevant Log Output

```shell
Error name: AI_APICallError
Error Message: Payload Too Large
Status Code: 413
Request URL: http://localhost:8045/v1/chat/completions

Response Body: Failed to buffer the request body: length limit exceeded

Request Body causing error (truncated):
{
  "messages": [
    { "role": "user", "content": "..." },
    {
      "role": "assistant",
      "content": "![image](data:image/jpeg;base64,//very long text..." 
      // ^ This Base64 string is likely causing the payload overflow
    },
    { "role": "user", "content": "Change the color of the logo to a shade of red with gradient stripes at the back" }
  ]
}
```

### Stack Trace
```
AI_APICallError: Payload Too Large
    at file:///C:/Users/.../resources/app.asar/out/renderer/assets/dist-CtZQEYA8.js:360:11
    at async postToApi (file:///C:/Users/.../resources/app.asar/out/renderer/assets/dist-CtZQEYA8.js:279:24)
    at async OpenAICompatibleChatLanguageModel.doStream (...)
```

### Temporary Fix
Clearing the context after every generation or starting a new topic fixes the issue however, this is highly impractical as it requires the user to clear the context after every single generation just to continue using the same chat session.

### PR DESCRIPTION
**Pull request by Pleasurecruise**
### What this PR does

Before this PR:
- NewApi image generation hardcoded `response_format: 'b64_json'`, forcing all responses to base64 regardless of model capability
- All providers that handle base64 responses stored `urls: validFiles.map(f => f.name)` — just filenames — causing `handleRetry` to fail with invalid URLs
- Chat-generated base64 images were stored as full `data:image/...;base64,...` URIs inside `ImageMessageBlock.url`, which got included in subsequent message history and caused HTTP 413 errors (#12602)

After this PR:
- NewApi no longer forces `response_format: 'b64_json'`; the API defaults to returning URLs, with base64 as a transparent fallback
- Base64 responses in NewApi, Aihubmix, and Ovms now correctly store `urls: []` (no retry URL exists for inline base64 data)
- Chat-generated base64 images are persisted to disk immediately; the block stores a `file` reference and a local `file://` URL instead of the raw data URI
- `ImageGenerationMiddleware` now prefers `block.file` over `block.url` when collecting images from previous assistant messages

https://linux.do/t/topic/1681973/18
Fixes #12602

### Why we need it and why it was done in this way

The following tradeoffs were made:
- Removing `response_format: 'b64_json'` from NewApi follows the same pattern as Aihubmix's `gpt-image-1` handling — no explicit format is set, and the response handler already supports both URL and base64 paths.
- Storing `urls: []` for base64 responses is semantically correct: there is no remote URL to retry from once the base64 payload is gone.
- Persisting base64 chat images to disk is the minimal fix for #12602; it reuses the existing `saveBase64Image` IPC path without changing any message schema or Redux state shape.

The following alternatives were considered:
- Keeping `response_format: 'b64_json'` and fixing only the `urls` field — rejected because NewApi supports URL responses natively, and URL mode is more efficient.

### Breaking changes

None.

### Special notes for your reviewer

The `imageCallbacks.ts` change means that after a base64 image is generated in chat, the `ImageMessageBlock` will have `file` set and `url` as a local `file://` path. Existing messages already stored with raw base64 URLs are unaffected (they will continue to display correctly via the existing `parseDataUrl` path in `messageConverter.ts`).

### Checklist

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: Write code that humans can understand and Keep it simple
- [x] Refactor: You have left the code cleaner than you found it (Boy Scout Rule)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Documentation: Not required — no user-facing feature added, only bug fixes
- [x] Self-review: I have reviewed my own code before requesting review from others

### Release note

```release-note
Fix base64 image handling in paintings (NewApi, Aihubmix, Ovms): images now return as URLs by default, preventing invalid retry URLs. Fix chat image generation storing large base64 data URIs in message history, which caused HTTP 413 errors on follow-up messages.
```

### CODE REVIEW

File: src/renderer/src/services/messageStreaming/callbacks/imageCallbacks.ts [hunk 1]
```diff
@@ -49,29 +50,41 @@ export const createImageCallbacks = (deps: ImageCallbacksDependencies) => {
...
+            status: MessageBlockStatus.SUCCESS
+          }
+        }
+        return {
+          url: imageUrl,
+          metadata: { generateImageResponse: imageData },
+          status: MessageBlockStatus.SUCCESS
+        }
+      }
+
```
Comment (GeorgeDong32) [inline src/renderer/src/services/messageStreaming/callbacks/imageCallbacks.ts]: **💡 Suggestion: Consider hoisting this function**

The `buildImageBlockFields` function is defined inside `onImageGenerated`, which means a new function instance is created on every call. Consider moving it outside to the module level or within `createImageCallbacks` (but outside the returned object) for better memory efficiency.

```typescript
// Option 1: Module level (if it doesn't need deps)
const buildImageBlockFields = async (imageData: any): Promise<Partial<ImageMessageBlock>> => {
  // ...
}

// Option 2: Inside createImageCallbacks but outside returned object
export const createImageCallbacks = (deps: ImageCallbacksDependencies) => {
  const buildImageBlockFields = async (imageData: any) => {
    // can access deps here if needed
  }
  return { ... }
}
```

This is a minor optimization but improves code organization.

**Review by DeJeune — APPROVED** [review]
