### PR TITLE
test: add integration test for message thunk and fix some bugs

### LINKED ISSUE #8106: [错误]: v1.4.11 claude回复一部分就中止了
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我的问题不是 [常见问题](https://github.com/CherryHQ/cherry-studio/issues/3881) 中的内容。
- [x] 我已经查看了 **置顶 Issue** 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。

### 平台

Windows

### 版本

 v1.4.11

### 错误描述

[错误]: v1.4.11 claude回复一部分就中止了，试了很多次都这样

### 重现步骤

[错误]: v1.4.11 claude回复一部分就中止了，试了很多次都这样

### 预期行为

[错误]: v1.4.11 claude回复一部分就中止了，试了很多次都这样

### 相关日志输出

```shell

```

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by DeJeune**
### What this PR does

为messagethunk和apiservice新增了测试文件，未来继续添加更多测试用例

Fixes #8106 #8085 #8089

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### CODE REVIEW

**Comment by alephpiece** [comment]
回复内容截断是因为之前没有正确传递累积的文本吗？

**Comment by DeJeune** [comment]
> 回复内容截断是因为之前没有正确传递累积的文本吗？

blocktype的问题

**Comment by alephpiece** [comment]
有没有能比较容易复现问题的方法？我试了好几个模型都没有复现

**Comment by DeJeune** [comment]
我也复现不出来，你可以在主分支跑一下这个分支的测试，应该跑不过

File: src/renderer/src/store/thunk/messageThunk.ts [hunk 1]
```diff
@@ -311,469 +311,469 @@ const dispatchMultiModelResponses = async (
 
 // --- End Helper Function ---
 
-// Internal function extracted from sendMessage to handle fetching and processing assistant response
-const fetchAndProcessAssistantResponseImpl = async (
+export const streamCallback = (
```
Comment (DeJeune) [inline src/renderer/src/store/thunk/messageThunk.ts:314]: 主要是为了导出回调函数

**Review by MyPrototypeWhat — APPROVED** [review]

**Review by GeorgeDong32 — APPROVED** [review]
