### PR TITLE
fix(skills): support agent-authored skills via skills tool init/register

### LINKED ISSUE #14191: [Bug]: Remove confusing SOUL badge from Agent list in autonomous mode
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

macOS

### Version

v1.9.1

### Bug Description

In the Agent list, Agents using autonomous mode display a "SOUL" badge/tag. This label is confusing to users — they don't understand what "SOUL" means. Additionally, the badge overlaps and obscures the Agent name text.

### Steps To Reproduce

1. Create or select an Agent with autonomous mode enabled
2. Go to the Agent list view
3. Observe the "SOUL" badge next to the Agent name
4. Notice it obscures part of the Agent name

### Expected Behavior

The "SOUL" badge should be removed entirely from the Agent list to avoid user confusion and name truncation.

### Additional Context

**Priority: P0**

Found during v1.9.1 system testing.

**Suggestion**: Remove the SOUL badge.

---

**原文（Chinese）**：

Agent 列表中自主模式的 SOUL 标签用户看不懂含义，且遮挡 Agent 名称显示。

优化建议：去掉 SOUL 标签。

### LINKED ISSUE #14192: [Bug]: Agent-created Skills not visible in Skill list when no working directory is selected
> [\!NOTE]
> This issue was translated by Claude.

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

macOS

### Version

v1.9.1

### Bug Description

When the user has not explicitly selected a working directory, Skills created by an Agent are installed to an incorrect path. As a result, the newly created Skill does not appear in either the global Skill list or the current Agent's Skill list. This is a **blocking issue** — external users have already reported it.

### Steps To Reproduce

1. Do not select a working directory for the Agent
2. Ask the Agent to create a new Skill
3. The Agent reports the Skill was created successfully
4. Check the global Skill list — the new Skill is not there
5. Check the current Agent's Skill list — the new Skill is not there either

### Expected Behavior

1. The Skill should appear in the global Skill list
2. The Skill should appear in the current Agent's Skill list and be enabled by default
3. The working directory should contain a CLAUDE.md file

### Additional Context

**Priority: P0** (blocking)

Found during v1.9.1 system testing. External users have also reported this issue.

**Optimization Suggestions**: The Skill should appear in the global Skill list; should appear in the current Agent's Skill list and be enabled by default; the working directory should contain a CLAUDE.md file.

---
<details>
<summary>Original Content</summary>

**原文（Chinese）**：

用户未主动选择工作目录时，Agent 创建的 Skill 安装路径有问题，全局和当前 Agent 的 Skill 列表都找不到。已有外部用户反馈。

优化建议：Skill 应出现在全局 Skill 列表；应出现在当前 Agent 的 Skill 列表且默认开启；工作目录下应有 CLAUDE.md。

</details>

### PR DESCRIPTION
**Pull request by DeJeune**
### What this PR does

Before this PR:
- Inside agent chat, the `skill-creator` skill could not actually persist a new skill. The agent would write `SKILL.md` files to disk, but the global skill DB row and `.claude/skills/` symlink were never created, so authored skills silently failed to take effect.
- `SkillInstaller.install` was destructive when source and destination resolved to the same path: the backup-and-rename step moved the source out from under the subsequent copy, leaving no way to install from an in-place source.
- Agents in the sidebar showed an unexplained purple `SOUL` badge next to their name when Soul Mode was on, crowding out the agent name and using internal jargon users could not understand.

After this PR:
- The claw MCP `skills` tool gains two new actions:
  - `init name=<name>` — creates / resolves the absolute target directory under the global Skills storage root and returns it to the agent.
  - `register name=<name>` — registers the in-place directory through the existing `installFromDirectory` pipeline and toggles the skill on for the current session.
- `installSkill` (marketplace install) now also auto-toggles the skill on, so an agent-driven install from chat is immediately usable without a UI roundtrip.
- `SkillInstaller.install` short-circuits when src and dest resolve to the same path.
- `SkillService.installSkillDir` detects in-place input under the Skills root and preserves the existing basename as the folder name, avoiding sanitize drift between caller-chosen names and `parseSkillMetadata`'s derived filename.
- New public `SkillService.getSkillDirectory(name)` helper exposes the resolved path so callers don't duplicate sanitize logic.
- `resources/skills/skill-creator/SKILL.md` gains a "Cherry Studio workflow" preamble that overrides the Claude Code / Claude.ai packaging steps and instructs the agent to use init/register. The original sections are kept as-is.
- The `SOUL` badge is removed from the agent sidebar item along with the now-dead `SoulTag` styled component and unused `isSoulModeEnabled` import in `AgentItem.tsx`. The Soul Mode toggle and underlying feature are unchanged — the toggle still lives in agent settings.
- `claw.test.ts`'s `skillService` mock is extended with `toggle` / `installFromDirectory` / `getSkillDirectory` so the new install / init / register actions have a working stub (fixes the CI failure on the first push of this branch).

Fixes #

### Why we need it and why it was done in this way

The skill-creator skill is meant to let users author custom skills directly from agent chat, but with no integration into `SkillService` the result was always a silent failure — a `SKILL.md` sitting in some directory that no part of the system knew about. Users saw the agent confidently report "skill created" while the global skill list remained empty. This is the fix for that broken end-to-end flow.

The SOUL badge removal is bundled into this hotfix because it landed on the same review cycle and is a strict UI cleanup — reported as P0 by Kenny / 郑克 with the same root cause as the rest of this PR's framing: Soul Mode internals leaking into the user-facing surface.

The following tradeoffs were made:
- Extended the existing `skills` MCP tool with two additive actions instead of introducing a new tool, keeping the agent's tool surface small.
- Reused `installFromDirectory` rather than adding a parallel "register in place" code path. This required two small robustness fixes (src===dest no-op + in-place folder name detection) but keeps a single install entry point.
- The skill is auto-enabled on register (and on marketplace install); an agent-authored or agent-installed skill that requires a manual UI toggle would surprise users who just told the agent "create / install a skill for X".
- Just delete the SOUL badge instead of trying to make it discoverable (tooltip / icon-only / rename). The badge was not pulling its weight in the list item, and the settings panel is the right place for users to learn about Soul Mode.

The following alternatives were considered:
- A new `registerInPlace` method on `SkillService` bypassing `installer.install` entirely. Rejected to avoid duplicating insert/link logic.
- A staging directory under `app.getPath('temp')` copied into the Skills root on register. Rejected because it forces an extra copy and breaks live iteration: with in-place files, the `.claude/skills/<name>/` symlink reflects edits immediately, so no second `register` is needed for runtime effect.
- A file watcher / per-turn reconciliation that auto-discovers `SKILL.md` files in the agent workspace. Rejected as too magical for a first cut; can revisit later.
- For the badge: keep but rename / translate. Rejected — the underlying problem is that "Soul Mode" itself is internal-facing terminology, so renaming the badge would only move the comprehension issue.

Links to places where the discussion took place: N/A

### Breaking changes

None. The new tool actions are additive and existing `search` / `install` / `remove` / `list` behavior is unchanged. The `SkillInstaller.install` short-circuit only fires when src and dest resolve to the exact same path, which previously raised — strictly more permissive than before. The badge removal is UI-only and the Soul Mode feature is untouched.

### Special notes for your reviewer

- Functionally most of this PR fixes a silent failure ("agent-authored skills don't take effect"), but it also introduces new MCP tool actions, so the underlying commits have a mix of `feat:` and `fix:` prefixes. The PR title uses `fix:` since it lands on a hotfix branch.
- The skill-creator SKILL.md change only **adds** a "Cherry Studio workflow" preamble at the top; nothing else is removed, so upstream changes to the rest of the file still merge cleanly.
- The SOUL badge removal commit was originally on a separate branch / PR (#14185, now closed) and is cherry-picked into this branch so it can ship in the same review cycle.
- The CI fix commit (`test(skills): add toggle mock to claw test ...`) is here because the first push hit `skillService.toggle is not a function` — the `installSkill` change calls toggle but the existing mock didn't expose it.
- Manual testing: end-to-end verified by the author — agent runs `skills init` → writes SKILL.md and supporting files → calls `skills register` → the new skill appears in the global skill list and is enabled for the session. Sidebar verified to no longer show the SOUL badge after the cherry-pick.

### Checklist

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: Write code that humans can understand and Keep it simple
- [x] Refactor: Boy Scout Rule applied — `SkillInstaller.install` is now safer for any in-place caller, and AgentItem dropped the now-dead `SoulTag` component along with the unused import
- [x] Upgrade: No upgrade impact (additive, no schema migration)
- [x] Documentation: skill-creator SKILL.md preamble updated; no external docs change required
- [x] Self-review: Reviewed via local diff before pushing

### Release note

```release-note
fix(skills): agents in Soul Mode can now author new skills end-to-end from agent chat. The `skills` tool gains `init` / `register` actions, marketplace install auto-enables, and the skill-creator skill persists to the global skill list. UI cleanup: the unexplained SOUL badge next to agent names in the sidebar is removed; Soul Mode itself is unchanged and still toggleable from agent settings.
fix(agents): the skills and memory MCP tools are now available to every agent (not just Soul-Mode agents), with cross-session FACT.md recall, auto-approved permissions, and `skills list` exposing on-disk paths so the agent can patch installed skills in place via Read/Edit. Skill management (search/install/list/remove/init/register) and persistent workspace memory work in regular chat agents the same way they did in Soul Mode.
```

### CODE REVIEW

File: src/main/mcpServers/skills.ts [hunk 1]
```diff
@@ -0,0 +1,305 @@
...
+      content: [{ type: 'text' as const, text: JSON.stringify(results, null, 2) }]
+    }
+  }
+
+  private async initSkill(args: Record<string, string | undefined>) {
+    const name = args.name
+    if (!name) throw new McpError(ErrorCode.InvalidParams, "'name' is required for init")
+
+    const skillDir = skillService.getSkillDirectory(name)
+    await mkdir(skillDir, { recursive: true })
```
Comment (EurFelux) [inline src/main/mcpServers/skills.ts:290]: > [\!NOTE]
> This comment was translated by Claude.

`init` lacks conflict detection: if the agent passes in a `name` that conflicts with an already installed skill, `mkdir(skillDir, { recursive: true })` will silently land in that existing directory, and the agent's subsequent writes to `SKILL.md` / `scripts/` will directly overwrite the original files. Then when `register` comes in:

1. `SkillInstaller.install` short-circuits because `src === dest`, doing nothing (the original files have already been overwritten by the agent by this point)
2. `installSkillDir` finds `existing`, executes `this.repository.delete(existing.id)`, then inserts a new row with the agent's metadata

**The result is: the user's original skill with the same name is silently replaced, and the agent has no way of knowing a collision occurred.** A near-name collision could wipe out a skill the user previously installed from the marketplace.

I suggest adding a pre-install check in `init` to verify if the target directory already exists and is non-empty (or directly query the database with `getByFolderName`). If it exists, either return a clear error or inform the agent in the response text that "this name is already taken, please choose another or explicitly confirm overwriting." At minimum, the agent and user should be aware of and consent to the overwrite.

---
<details>
<summary>Original Content</summary>

`init` 缺少冲突检测喵：如果 agent 传进来的 `name` 和已安装的 skill 撞名，`mkdir(skillDir, { recursive: true })` 会静默落到那个已有目录，agent 后续写入的 `SKILL.md` / `scripts/` 直接覆盖原文件。随后 `register` 走进来：

1. `SkillInstaller.install` 因为 `src === dest` 短路，什么都不做（原文件此刻已被 agent 覆盖完了）
2. `installSkillDir` 发现 `existing`，走 `this.repository.delete(existing.id)` 再以 agent 的 metadata 插一行新的

**结果是：用户原来装的同名 skill 被静默替换，agent 也无从感知碰撞发生。** 一个近名冲突就可能擦掉用户之前从 marketplace 装的 skill。

建议 `init` 先检查一下目标目录是否已存在非空（或者直接查 DB `getByFolderName`）；若存在，要么返回明确错误，要么在返回文本里告诉 agent「该名字已被占用，请换一个或显式确认要覆盖」。至少要让 agent 和用户对 overwrite 是知情的喵。

</details>

File: src/main/services/agents/services/claudecode/index.ts [hunk 2]
```diff
@@ -552,13 +565,53 @@ class ClaudeCodeService implements AgentServiceInterface {
...
+    // / list / remove / init / register) is a generally useful capability and is
+    // not coupled to Soul Mode's autonomous-agent semantics.
+    const skillsServer = new SkillsServer(session.agent_id)
+    options.mcpServers.skills = { type: 'sdk', name: 'skills', instance: skillsServer.mcpServer }
+    // Auto-approve via Cherry Studio's own permission gate. The SDK whitelist
+    // (`options.allowedTools`) takes glob patterns, but `canUseTool` checks
+    // `autoAllowTools` with exact string matching, so we have to add the full
+    // tool names there too — otherwise non-Soul agents (which do not run in
+    // bypassPermissions mode) get an approval prompt for every call.
+    autoAllowTools.add('mcp__skills__skills')
```
Comment (EurFelux) [inline src/main/services/agents/services/claudecode/index.ts:578]: > [\!NOTE]
> This comment was translated by Claude.

The code adds `mcp__skills__skills` to `autoAllowTools` for **all agents** (including regular chat agents), while `action="install"` fetches remote repositories from `claude-plugins.dev`, extracts them to the global Skills root directory, and registers them. This means any agent with the skills MCP injected can write remote code to `~/Library/Application Support/.../Skills/` **without user confirmation**, and this code will be loaded by other sessions.

Several potential mitigations to consider:
1. Separate the `install` action from auto-approval (keep search/list/init/register), requiring approval for each install — still satisfies the skill-creator's init/register scenario without sacrificing UX
2. Or only auto-approve `install` for Soul / Assistant agents, while regular chat agents still require approval
3. At minimum, explicitly disclose this trust surface expansion in release notes (current release notes focus more on "capability restoration")

Also, regarding scope: according to `main`'s branch strategy, hotfix PRs should be minimal scope and not include refactor. "Extracting skills/memory MCP from Soul-Mode-only claw + injecting all agents by default + full auto-approval" seems more like a feature-level decision rather than a bug fix, with risks and impact not on the same scale as the skill-creator init/register fix. Should this be split into v2? Would love to hear your thoughts~

---
<details>
<summary>Original Content</summary>

这里把 `mcp__skills__skills` 对**所有 agent**（含普通 chat agent）都加进了 `autoAllowTools`，而 `action="install"` 会从 `claude-plugins.dev` 拉取远程仓库解压到全局 Skills 根目录并注册。等于任何注入了 skills MCP 的 agent 只要说服模型就能在**无用户确认**的前提下往 `~/Library/Application Support/.../Skills/` 落远程代码，且这份代码之后会被其它会话也加载。

几点可考虑的 mitigation：
1. 把 `install` 动作单独从 auto-approve 里摘出（保留 search/list/init/register），让 install 每次弹 approval —— 仍满足 skill-creator 的 init/register 场景，不牺牲 UX
2. 或者只对 Soul / Assistant agent auto-approve `install`，普通 chat agent 仍需 approval
3. 至少在 release note 里对此信任面扩张显式披露（目前的 release note 更多是在讲「能力回归」）

顺带一个 scope 问题：按 `main` 的 branch strategy，hotfix PR 应当是最小 scope 且不含 refactor。「把 skills/memory MCP 从 Soul-Mode-only 的 claw 里拆出来 + 给所有 agent 默认注入 + 全员 auto-approve」这一半看起来更像 feature-level 决策而非 bug fix，风险和影响面与 skill-creator init/register 的 fix 并不在同一个量级。是否考虑把这部分拆到 v2 单独走？听听你的想法喵～

</details>

File: src/main/mcpServers/skills.ts [hunk 3]
```diff
@@ -0,0 +1,305 @@
...
+}
+
+/**
+ * MCP server exposing skill management to any agent (not gated on Soul Mode).
+ *
+ * Skills are a generally useful capability — searching the marketplace,
+ * installing, listing, and authoring skills via init/register applies to
+ * regular chat agents and autonomous agents alike.
+ */
+class SkillsServer {
```
Comment (EurFelux) [inline src/main/mcpServers/skills.ts:85]: > [\!NOTE]
> This comment was translated by Claude.

**Thoughts on Root Cause and Long-term Direction:**

The problem this PR fixes (agent writes `SKILL.md` but app doesn't know) is essentially a **lack of sync mechanism between the app's skill registry and disk files**. `init`/`register` as a workaround can solve the current skill-creator scenario, but from an architectural perspective, this is using additional agent-side protocols to compensate for missing app-side reconciliation—every place that needs sync requires developers to manually add a pair of init/register-style tools, which is easily overlooked. SKILL is just one example that happened to be exposed.

For the future (in v2), consider using a **file watcher** mechanism to solve it from the root cause: monitor changes to the Skills root directory, automatically trigger DB reconcile + symlink creation when new/modified `SKILL.md` files are detected. This would be transparent to agents—just write files, the app automatically perceives them, no need to learn a special registration protocol.

The current PR's init/register approach as a first-cut workaround is acceptable, but it's recommended to mark this as a temporary solution in the PR description or code comments, indicating it will be replaced by a watcher mechanism in the future, to avoid this explicit protocol proliferating in more places meow.

---
<details>
<summary>Original Content</summary>

**关于根因和长期方向的想法：**

这个 PR 修复的问题（agent 写了 `SKILL.md` 但 app 不知道）本质上是 **app 的 skill registry 和磁盘文件之间缺少同步机制**。`init`/`register` 作为 workaround 能解决当前 skill-creator 的场景，但从架构角度看，这是在用 agent 侧的额外协议弥补 app 侧缺失的 reconciliation——每个需要同步的地方都要开发者手动加一对 init/register 式的 tool，很容易遗漏。SKILL 只是碰巧暴露出来的一个例子。

建议后续（v2 里）考虑用 **file watcher** 机制从根因解决：监听 Skills 根目录的变更，发现新增/修改的 `SKILL.md` 时自动触发 DB reconcile + symlink 创建。这样对 agent 来说是透明的——只管写文件，app 自动感知，不需要学一套特殊的注册协议。

当前 PR 的 init/register 方案作为 first-cut workaround 是可以接受的，但建议在 PR 描述或代码注释里标注这是临时方案，后续要被 watcher 替代，避免这套显式协议在更多地方扩散喵。
</details>

File: src/renderer/src/components/InputEmbeddingDimension.tsx [hunk 4]
```diff
@@ -48,7 +49,11 @@ const InputEmbeddingDimension = ({
 
     setLoading(true)
     try {
-      const aiProvider = new AiProvider(provider)
+      const providerWithRotatedKey = {
```
Comment (EurFelux) [inline src/renderer/src/components/InputEmbeddingDimension.tsx:52]: > [\!NOTE]
> This comment was translated by Claude.

This embedding dimension rotated API key fix is completely unrelated to this PR's skill-creator theme and should be an independent hotfix.

Currently, this PR has bundled at least 4 different concerns:
1. skill-creator init/register end-to-end flow fix (the PR's original intent)
2. skills/memory MCP extraction from Soul-Mode-only + injection into all agents (#14186, capability expansion)
3. SOUL badge removal (#14185, UI cleanup)
4. embedding dimension rotated API key (completely unrelated renderer bug fix)

Additionally, with the two prompt tuning commits in between (self-improve rules), the entire PR's scope can no longer be easily summarized by a single theme. Per the branch strategy's hotfix requirement of "must be minimal in scope", I recommend splitting this embedding fix into a separate PR, so each hotfix's changeset can be independently reviewed and reverted, meow.

---
<details>
<summary>Original Content</summary>

这个 embedding dimension 的 rotated API key fix 和本 PR 的 skill-creator 主题完全无关，应该是个独立的 hotfix。

目前这个 PR 已经捆绑了至少 4 个不同的关注点：
1. skill-creator init/register 端到端流程修复（PR 的本意）
2. skills/memory MCP 从 Soul-Mode-only 拆出 + 给所有 agent 注入（#14186，能力面扩展）
3. SOUL badge 移除（#14185，UI 清理）
4. embedding dimension rotated API key（完全无关的 renderer bug fix）

加上中间两个 prompt 微调 commit（self-improve rules），整个 PR 的 scope 已经很难用一个主题概括了。按 branch strategy 里 hotfix 「must be minimal in scope」的要求，建议至少把这个 embedding fix 拆成独立 PR，让每个 hotfix 的变更集保持可独立 review、可独立 revert 喵。

</details>

**Review by EurFelux — CHANGES_REQUESTED** [review]
> [\!NOTE]
> This review was translated by Claude.

Thanks for fixing the skill-creator end-to-end silent failure in this PR - the init/register approach works. There are a few points that need to be addressed:

1. **`init` name collision**: Calling init on an existing skill name silently overwrites the original files + DB row without user awareness. Collision detection is needed.
2. **auto-approve scope**: The `install` action auto-approves all agents, meaning any agent can pull code from remote to the global Skills directory without user confirmation. Recommend narrowing the trust boundary.
3. **PR scope**: Currently bundles 4+ different concerns (init/register fix, skills/memory global injection, SOUL badge removal, embedding rotated key fix, prompt tuning). Per hotfix minimal scope constraints, suggest splitting.
4. **Long-term direction**: init/register as a workaround is OK, but the root cause is the lack of sync mechanism between app and filesystem. Recommend v2 use file watcher to address from the root cause.

---
<details>
<summary>Original Content</summary>

感谢这个 PR 修复了 skill-creator 端到端的静默失败，init/register 的思路能跑通。主要有几个需要回应的点：

1. **`init` 同名冲突**：对已存在的 skill name 调 init 会静默覆盖原有文件 + DB row，用户无感知。需要加碰撞检查。
2. **auto-approve scope**：`install` action 对所有 agent auto-approve 意味着任何 agent 都能在无用户确认的情况下从远程拉代码到全局 Skills 目录，建议收窄信任面。
3. **PR scope**：目前捆绑了 4+ 个不同关注点（init/register fix、skills/memory 全员注入、SOUL badge 移除、embedding rotated key fix、prompt 微调），按 hotfix 的最小 scope 约束建议拆分。
4. **长期方向**：init/register 作为 workaround OK，但根因是 app 与文件系统缺少同步机制，建议 v2 用 file watcher 从根因解决。

</details>

**Comment by DeJeune** [comment]
> [\!NOTE]
> This comment was translated by Claude.

@EurFelux To facilitate testing by @kennyzheng-builds, intentionally placed on one branch for easy packaging

---
<details>
<summary>Original Content</summary>

@EurFelux 为了方便 @kennyzheng-builds 测试，故意放到一个分支方便打包
</details>

File: src/main/mcpServers/skills.ts (hunk 3 above)
Comment (DeJeune) [reply src/main/mcpServers/skills.ts:85]: will be updated in v2

File: src/main/mcpServers/skills.ts (hunk 1 above)
Comment (DeJeune) [reply src/main/mcpServers/skills.ts:290]: fixed

File: src/main/services/agents/services/claudecode/index.ts (hunk 2 above)
Comment (DeJeune) [reply src/main/services/agents/services/claudecode/index.ts:578]: Need a skill_audit skill, consider adding it later version

**Comment by EurFelux** [comment]
Two items were deferred with verbal acknowledgment in review comments — please open tracking issues so they don't get lost:

1. **auto-approve scope for `install` action** (re: [this comment](https://github.com/CherryHQ/cherry-studio/pull/14184#discussion_r3068364065))
   You replied "Need a skill_audit skill, consider adding it later version" — please open a feature request issue to track narrowing the trust boundary (e.g. exclude `install` from auto-approve for non-Soul agents, or add a skill_audit mechanism).

2. **File watcher to replace init/register** (re: [this comment](https://github.com/CherryHQ/cherry-studio/pull/14184#discussion_r3069407695))
   You replied "will be updated in v2" — please open an issue to track adding a file watcher on the Skills root directory for automatic DB reconciliation in v2, so this workaround doesn't proliferate.

Verbal "later" is fine, but an issue makes it trackable. Thanks!

**Comment by DeJeune** [comment]
> [\!NOTE]
> This comment was translated by Claude.

thanks, i have created two issues to track

---
<details>
<summary>Original Content</summary>

thanks, i have created two issues to track

> 2026年4月13日 20:49，Phantom ***@***.***> 写道：
> 
> Two
</details>

File: src/main/mcpServers/skills.ts [hunk 5]
```diff
@@ -0,0 +1,332 @@
...
+    })
+    return {
+      content: [
+        {
+          type: 'text' as const,
+          text: [
+            `Skill "${installed.name}" registered and enabled.`,
+            `  Folder: ${installed.folderName}`,
+            `  Description: ${installed.description ?? 'N/A'}`,
+            `  Enabled: ${enabled?.isEnabled ?? true}`
```
Comment (EurFelux) [inline src/main/mcpServers/skills.ts]: > [\!NOTE]
> This comment was translated by Claude.

**[Critical] `linkSkill` swallows symlink errors, causing install/register to falsely report success**

The catch block in `SkillService.linkSkill` only logs without re-throwing (`SkillService.ts:237-263`). The call chain is:

1. `registerSkill` → `skillService.toggle()` → internally calls `linkSkill`
2. `linkSkill` fails (EPERM / ENOSPC / EACCES, etc.) → catch swallows the error, toggle updates DB to `isEnabled: true` as usual
3. Here `enabled?.isEnabled ?? true` further uses `?? true` as a fallback, reporting success even when toggle returns null

**Result: The agent receives "Skill registered and enabled", but the symlink wasn't created, so the skill is actually unusable.** When the agent subsequently tries to use the skill, it will fail, with no indication that the installation failed.

Suggestions:
1. `linkSkill` should throw rather than swallow errors (or return a boolean)
2. Remove `?? true` here, check if `enabled` is null and return an error

---
<details>
<summary>Original Content</summary>

**[Critical] `linkSkill` swallows symlink 错误，导致 install/register 假报成功**

`SkillService.linkSkill` 的 catch 只 log 不 re-throw（`SkillService.ts:237-263`）。这里调用链是：

1. `registerSkill` → `skillService.toggle()` → 内部调 `linkSkill`
2. `linkSkill` 失败（EPERM / ENOSPC / EACCES 等）→ catch 吞掉错误，toggle 照常把 DB 更新为 `isEnabled: true`
3. 这里 `enabled?.isEnabled ?? true` 还进一步用 `?? true` 兜底，当 toggle 返回 null 时也报成功

**结果：agent 收到 "Skill registered and enabled"，但 symlink 没创建，skill 实际不可用。** agent 后续尝试使用该 skill 会失败，且完全没有提示是安装出了问题。

建议：
1. `linkSkill` 应该 throw 而非吞掉错误（或返回 boolean）
2. 这里去掉 `?? true`，检查 `enabled` 为 null 时返回 error

</details>

File: src/main/mcpServers/skills.ts [hunk 6]
```diff
@@ -0,0 +1,332 @@
...
+          `Choose a different name, or use action="remove" with name="${name}" first if you intend to replace it.`
+      )
+    }
+
+    // Guard against an orphaned non-empty directory that isn't tracked in the DB.
+    let dirHasContent = false
+    try {
+      const entries = await readdir(skillDir)
+      dirHasContent = entries.length > 0
+    } catch {
```
Comment (EurFelux) [inline src/main/mcpServers/skills.ts]: > [\!NOTE]
> This comment was translated by Claude.

**[Important] Catch block too wide — intended to handle ENOENT only, actually swallows all readdir errors**

The comment for this catch block says "Directory doesn't exist yet", but it actually swallows EACCES (permission denied), ENOTDIR (path is a file not a directory), ELOOP, and more.

If the directory exists but lacks read permissions, the code will skip the check and proceed directly to `mkdir`, producing confusing subsequent errors.

Suggested fix: check the error code:

```typescript
} catch (err) {
  const code = (err as NodeJS.ErrnoException).code
  if (code \!== 'ENOENT') {
    throw new McpError(
      ErrorCode.InternalError,
      `Cannot read skill directory "${skillDir}": ${(err as Error).message}`
    )
  }
}
```

---
<details>
<summary>Original Content</summary>

**[Important] catch 过宽 — 只想处理 ENOENT，实际吞掉所有 readdir 错误**

这里 catch 的注释写的是 "Directory doesn't exist yet"，但实际会吞掉 EACCES（权限拒绝）、ENOTDIR（路径是文件不是目录）、ELOOP 等。

如果目录存在但没有读取权限，代码会跳过检查直接 `mkdir`，产生令人困惑的后续错误。

建议检查 error code：

```typescript
} catch (err) {
  const code = (err as NodeJS.ErrnoException).code
  if (code \!== 'ENOENT') {
    throw new McpError(
      ErrorCode.InternalError,
      `Cannot read skill directory "${skillDir}": ${(err as Error).message}`
    )
  }
}
```

</details>

File: src/main/mcpServers/workspaceMemory.ts [hunk 7]
```diff
@@ -0,0 +1,260 @@
...
+  }
+
+  try {
+    const entries = await readdir(dir)
+    const target = name.toLowerCase()
+    const match = entries.find((e) => e.toLowerCase() === target)
+    return match ? path.join(dir, match) : exact
+  } catch {
+    return exact
+  }
```
Comment (EurFelux) [inline src/main/mcpServers/workspaceMemory.ts:38]: > [\!NOTE]
> This comment was translated by Claude.

**[Important] `resolveFileCI` both catch blocks have no type filtering, swallowing permission errors etc.**

Both catch blocks are empty. The intention was to handle ENOENT, but EACCES (permission), ELOOP (symlink loop), etc. are also silently swallowed.

First catch: If stat fails due to permission issues, it will reach readdir which is also likely to fail, ultimately returning the `exact` path. Subsequent writeFile/readFile operations with this path will report an error unrelated to the real cause.

Second catch: When `readdir` fails, it directly returns `exact`. If there are permission issues with the memory directory, all subsequent operations are based on wrong assumptions.

It is recommended to at least log a warning for non-ENOENT errors to facilitate troubleshooting.

---
<details>
<summary>Original Content</summary>

**[Important] `resolveFileCI` 两个 catch 都无类型过滤，吞掉权限错误等**

两个 catch 块都是空的，本意是处理 ENOENT，但 EACCES（权限）、ELOOP（symlink 循环）等也会被静默吞掉。

第一个 catch：stat 失败如果是权限问题，会走到 readdir 也大概率失败，最终返回 `exact` 路径。后续 writeFile/readFile 拿到这个路径时会报一个与真正原因无关的错误。

第二个 catch：`readdir` 失败时直接返回 `exact`，如果内存目录有权限问题，后续操作全部基于错误的假设。

建议至少对非 ENOENT 错误打 warn log，便于排查。

</details>

File: src/main/mcpServers/workspaceMemory.ts [hunk 8]
```diff
@@ -0,0 +1,260 @@
...
+    const workspace = await this.getWorkspacePath()
+    const memoryDir = path.join(workspace, 'memory')
+    const journalPath = await resolveFileCI(memoryDir, 'JOURNAL.jsonl')
+
+    let fileContent: string
+    try {
+      fileContent = await readFile(journalPath, 'utf-8')
+    } catch {
+      return { content: [{ type: 'text' as const, text: 'No journal entries found.' }] }
+    }
```
Comment (EurFelux) [inline src/main/mcpServers/workspaceMemory.ts:236]: > [\!NOTE]
> This comment was translated by Claude.

**[Important] readFile catch treats all errors as "no log"; EACCES also returns "No journal entries found"**

This code only handles file not existing, but EACCES / EISDIR / EMFILE and other errors would all be returned to the agent as "No journal entries found".

The agent will think the log is empty and continue appending new entries, losing previous context.

```typescript
} catch (err) {
  const code = (err as NodeJS.ErrnoException).code
  if (code === 'ENOENT') {
    return { content: [{ type: 'text' as const, text: 'No journal entries found.' }] }
  }
  throw new Error(`Failed to read journal at ${journalPath}: ${(err as Error).message}`)
}
```

Similarly, the `JSON.parse` catch below (L238) is also suggested to add a warn log, so that when skipping corrupted lines there's at least some trace.

---
<details>
<summary>Original Content</summary>

**[Important] readFile catch 把所有错误当作「无日志」,EACCES 也返回 "No journal entries found"**

这里只想处理文件不存在，但 EACCES / EISDIR / EMFILE 等都会被当作 "No journal entries found" 返回给 agent。

agent 会认为日志为空，继续追加新条目，丢失之前的上下文。

```typescript
} catch (err) {
  const code = (err as NodeJS.ErrnoException).code
  if (code === 'ENOENT') {
    return { content: [{ type: 'text' as const, text: 'No journal entries found.' }] }
  }
  throw new Error(`Failed to read journal at ${journalPath}: ${(err as Error).message}`)
}
```

同理下面 `JSON.parse` 的 catch（L238）也建议加 warn 日志，跳过损坏行时至少有迹可循。

</details>

File: src/main/services/agents/skills/SkillInstaller.ts [hunk 9]
```diff
@@ -17,8 +18,16 @@ const logger = loggerService.withContext('SkillInstaller')
...
    * Install a skill folder to the destination path with backup-restore safety.
+   *
+   * If sourceDir and destPath resolve to the same location, the files are
+   * already in place (in-place registration flow) and no copy is performed.
    */
   async install(sourceDir: string, destPath: string): Promise<void> {
+    if (path.resolve(sourceDir) === path.resolve(destPath)) {
+      logger.debug('Source equals destination, skipping copy', { destPath })
+      return
+    }
```
Comment (EurFelux) [inline src/main/services/agents/skills/SkillInstaller.ts:29]: > [\!NOTE]
> This comment was translated by Claude.

**[Important] `SkillInstaller` src===dest short-circuit and `SkillService.installSkillDir` isInPlace branch both lack tests**

These two sections are the core logic of in-place registration:

1. `SkillInstaller.install` (L26-29): The `path.resolve(sourceDir) === path.resolve(destPath)` short-circuit is the key to preventing backup-and-rename-from-self from corrupting files. If mistakenly deleted/corrupted, the installer will attempt to rename the directory to itself.
2. `SkillService.installSkillDir` (L392): The `isInPlace` check determines whether to skip `sanitizeFolderName`. If this condition fails (e.g., trailing slash or platform differences), folderName doesn't match, and the installer won't short-circuit, going full copy and corrupting files.

Neither has unit tests. Suggested minimum coverage:
- When src === dest, `install()` should immediately return without calling any fs operations
- When skillDir is under Skills root, `folderName` equals `path.basename(skillDir)`

---
<details>
<summary>Original Content</summary>

**[Important] `SkillInstaller` src===dest 短路 和 `SkillService.installSkillDir` 的 isInPlace 分支都没有测试**

这两段是 in-place 注册的核心逻辑：

1. `SkillInstaller.install`（L26-29）：`path.resolve(sourceDir) === path.resolve(destPath)` 的短路是防止 backup-and-rename-from-self 破坏文件的关键。如果被误删/改坏，installer 会尝试把目录 rename 到自己身上。
2. `SkillService.installSkillDir`（L392）：`isInPlace` 判断决定是否跳过 `sanitizeFolderName`。如果这个条件出错（比如 trailing slash 或平台差异），folderName 不匹配，installer 就不会短路，走全量 copy 破坏文件。

两者都没有单元测试。建议至少覆盖：
- src === dest 时 `install()` 立即 return，不调用任何 fs 操作
- skillDir 在 Skills root 下时，`folderName` 等于 `path.basename(skillDir)`

</details>

File: resources/skills/skill-creator/SKILL.md [hunk 10]
```diff
@@ -3,6 +3,36 @@ name: skill-creator
...
+   It returns an absolute directory path. Write `SKILL.md` and any supporting
+   files (`scripts/`, `references/`, `assets/`) **directly into that directory**.
+2. When the skill is ready, call `skills` with `action="register"` and the same
+   `name`. The skill is registered into the global skill list and enabled for
+   the current session automatically. You can re-edit files in place and call
+   `register` again at any time to refresh — the live symlink picks up file
+   content changes immediately, so mid-iteration edits work without ceremony.
+
+Use the same `<skill-folder-name>` for both calls, and make sure the `name:`
+field inside your `SKILL.md` frontmatter matches it too.
```
Comment (EurFelux) [inline resources/skills/skill-creator/SKILL.md]: > [\!NOTE]
> This comment was translated by Claude.

**[Important]** The instruction states that the `name:` field must match the folder name, but there is no such validation in the code.

> make sure the `name:` field inside your `SKILL.md` frontmatter matches it too.

Actually, in `installSkillDir`, the frontmatter `name` is only used as the display name (`metadata.name`), and the folder name is directly taken from `path.basename(skillDir)` in in-place mode. The two can be different and registration will still work normally.

This instruction could lead agents to mistakenly believe that registration will fail when the names don't match, or waste time trying to align the naming.

Suggested change:
> Use the same `<skill-folder-name>` for both `init` and `register` calls. The `name:` field inside your `SKILL.md` frontmatter becomes the display name and may differ from the folder name (e.g. `name: My Cool Skill` with folder `my-cool-skill`).

---
<details>
<summary>Original Content</summary>

**[Important] 这里说 `name:` 字段必须匹配文件夹名，但代码中无此校验**

> make sure the `name:` field inside your `SKILL.md` frontmatter matches it too.

实际上 `installSkillDir` 中 frontmatter 的 `name` 只用作 display name（`metadata.name`），文件夹名在 in-place 模式下直接取 `path.basename(skillDir)`。两者不匹配也能正常注册和使用。

这条指令可能导致 agent 在两者不同时误以为注册会失败，或浪费时间去对齐命名。

建议改为：
> Use the same `<skill-folder-name>` for both `init` and `register` calls. The `name:` field inside your `SKILL.md` frontmatter becomes the display name and may differ from the folder name (e.g. `name: My Cool Skill` with folder `my-cool-skill`).

</details>

File: src/main/mcpServers/skills.ts [hunk 11]
```diff
@@ -0,0 +1,332 @@
...
+      ]
+    }
+  }
+
+  private async registerSkill(args: Record<string, string | undefined>) {
+    const name = args.name
+    if (!name) throw new McpError(ErrorCode.InvalidParams, "'name' is required for register")
+
+    const skillDir = skillService.getSkillDirectory(name)
+    const installed = await skillService.installFromDirectory({ directoryPath: skillDir })
```
Comment (EurFelux) [inline src/main/mcpServers/skills.ts:340]: > [\!NOTE]
> This comment was translated by Claude.

**[Medium] `registerSkill` does not validate if directory/SKILL.md exists**

If an agent calls `register` after `init` without writing `SKILL.md`, it will get an internal error thrown by `parseSkillMetadata` instead of a clear prompt like "Did you call init first and write SKILL.md?"

I suggest doing a pre-flight check before `installFromDirectory`:

```typescript
const entries = await readdir(skillDir)
if (\!entries.some(e => e.toLowerCase() === 'skill.md')) {
  throw new McpError(
    ErrorCode.InvalidParams,
    `No SKILL.md found in "${skillDir}". Call action="init" first and write a SKILL.md file.`
  )
}
```

Also, the init success message (L296) mentions "the live symlink picks up file changes immediately", but there is no symlink at the init stage (the symlink is created during register/toggle). I suggest removing this sentence from the init response and adding it to the register response.

---
<details>
<summary>Original Content</summary>

**[Medium] `registerSkill` 不校验目录/SKILL.md 是否存在**

agent 在 `init` 后如果还没写 `SKILL.md` 就调 `register`，会得到 `parseSkillMetadata` 抛出的内部错误，而不是一个清晰的提示 "Did you call init first and write SKILL.md?"

建议在 `installFromDirectory` 之前做 pre-flight check：

```typescript
const entries = await readdir(skillDir)
if (\!entries.some(e => e.toLowerCase() === 'skill.md')) {
  throw new McpError(
    ErrorCode.InvalidParams,
    `No SKILL.md found in "${skillDir}". Call action="init" first and write a SKILL.md file.`
  )
}
```

另外，init 成功消息（L296）提到 "the live symlink picks up file changes immediately"，但 init 阶段还没有 symlink（symlink 在 register/toggle 时才创建）。建议从 init response 中移除这句，放到 register response 中。

</details>

File: src/main/services/agents/skills/SkillService.ts [hunk 12]
```diff
@@ -368,7 +383,14 @@ export class SkillService {
...
     const metadata = await parseSkillMetadata(skillDir, path.basename(skillDir), 'skills')
-    const folderName = this.sanitizeFolderName(metadata.filename)
+
+    // In-place registration: when skillDir already lives directly under the global
+    // Skills storage root, preserve its existing basename as folderName so the
+    // destination resolves to the same path and SkillInstaller short-circuits the
+    // copy. This avoids sanitize drift between caller-chosen names and metadata.
+    const skillsRoot = path.resolve(getDataPath('Skills'))
+    const isInPlace = path.resolve(path.dirname(skillDir)) === skillsRoot
+    const folderName = isInPlace ? path.basename(skillDir) : this.sanitizeFolderName(metadata.filename)
```
Comment (EurFelux) [inline src/main/services/agents/skills/SkillService.ts:402]: > [\!NOTE]
> This comment was translated by Claude.

**[Medium] In-place mode skips `sanitizeFolderName`, missing precondition documentation**

When `isInPlace` is true, `folderName` directly uses `path.basename(skillDir)` without going through `sanitizeFolderName`. The current call chain is safe (since `getSkillDirectory` already sanitizes), but `installSkillDir` itself is a private API with no documentation stating "callers must guarantee basename has been sanitized."

If there's a new call path in the future that directly passes an unsanitized in-place path, it will bypass validation.

Suggestion: Add a defensive assertion or comment:
```typescript
const folderName = isInPlace ? path.basename(skillDir) : this.sanitizeFolderName(metadata.filename)
// INVARIANT: isInPlace assumes basename was already sanitized by getSkillDirectory()
```

---
<details>
<summary>Original Content</summary>

**[Medium] in-place 模式跳过 `sanitizeFolderName`，缺少前置条件文档**

当 `isInPlace` 为 true 时，`folderName` 直接用 `path.basename(skillDir)` 而不经过 `sanitizeFolderName`。当前调用链安全（`getSkillDirectory` 已 sanitize），但 `installSkillDir` 本身是 private API，没有文档说明 "调用者必须保证 basename 已经过 sanitize"。

如果将来有新调用路径直接传一个未 sanitize 的 in-place 路径，就会绕过校验。

建议加个防御性断言或注释：
```typescript
const folderName = isInPlace ? path.basename(skillDir) : this.sanitizeFolderName(metadata.filename)
// INVARIANT: isInPlace assumes basename was already sanitized by getSkillDirectory()
```

</details>

**Review by EurFelux — CHANGES_REQUESTED** [review]
## Comprehensive Review (Round 2)

> [!NOTE]
> This review was generated with the help of automated review agents (code-reviewer, silent-failure-hunter, pr-test-analyzer, comment-analyzer). Findings that overlap with the previous review round have been excluded.

Overall the init/register core logic is sound and the collision detection is well done. The main new concerns are around **error handling** — several catch blocks are too broad (intended for ENOENT but swallowing EACCES/ENOTDIR/etc.), which can cause silent data loss or misleading error messages. The most critical issue is `linkSkill` swallowing symlink failures, causing install/register to falsely report success.

### Summary

| Severity | Count | Theme |
|---|---|---|
| Critical | 1 | `linkSkill` swallows errors → false "enabled" reports |
| Important | 5 | Broad catch blocks, missing tests for core in-place logic, SKILL.md mismatch claim |
| Medium | 2 | Missing pre-flight check in register, sanitize bypass undocumented |

### Strengths

- Init collision detection with DB + directory check is thorough and well-tested (3 scenarios)
- `SkillInstaller` src===dest short-circuit design is correct (`path.resolve` handles edge cases)
- `WorkspaceMemoryServer` JSDoc clearly differentiates from the knowledge-graph `memory.ts`
- Test migration from claw preserved all original scenarios without coverage loss
- Prompt builder tests cover key behavioral contracts comprehensively

File: src/main/mcpServers/skills.ts (hunk 5 above)
Comment (DeJeune) [reply src/main/mcpServers/skills.ts]: Fixed in `3d4ebfe`. `linkSkill` now re-throws after logging. Also replaced `?? true` with `?? false` and added a warning message in the response text when toggle fails, so the agent gets an honest status.

File: src/main/mcpServers/skills.ts (hunk 6 above)
Comment (DeJeune) [reply src/main/mcpServers/skills.ts]: Fixed in `3d4ebfe`. Narrowed to ENOENT-only; EACCES / ENOTDIR etc. now throw `McpError(InternalError)`. Added test for the EACCES case.

File: src/main/mcpServers/workspaceMemory.ts (hunk 7 above)
Comment (DeJeune) [reply src/main/mcpServers/workspaceMemory.ts:38]: Fixed in `3d4ebfe`. Both catch blocks now log a warning for non-ENOENT errors.

File: src/main/mcpServers/workspaceMemory.ts (hunk 8 above)
Comment (DeJeune) [reply src/main/mcpServers/workspaceMemory.ts:236]: Fixed in `3d4ebfe`. readFile catch now only returns "No journal entries found" for ENOENT; other errors throw. Also added `logger.warn` for corrupted JSON lines during parse.

File: src/main/services/agents/skills/SkillInstaller.ts (hunk 9 above)
Comment (DeJeune) [reply src/main/services/agents/skills/SkillInstaller.ts:29]: Added in `3d4ebfe`. New `SkillInstaller.test.ts` covers src===dest short-circuit (no fs ops called). Also added tests for register pre-flight (missing SKILL.md, missing directory).

File: resources/skills/skill-creator/SKILL.md (hunk 10 above)
Comment (DeJeune) [reply resources/skills/skill-creator/SKILL.md]: Fixed in `3d4ebfe`. Updated to clarify that `name:` is the display name and may differ from the folder name.

File: src/main/mcpServers/skills.ts (hunk 11 above)
Comment (DeJeune) [reply src/main/mcpServers/skills.ts:340]: Fixed in `3d4ebfe`. Added readdir + SKILL.md existence pre-flight check before `installFromDirectory`. If missing, returns a clear error pointing to `action="init"`. Also moved the "live symlink" text from init response to register response (symlink is created at register time, not init).

File: src/main/services/agents/skills/SkillService.ts (hunk 12 above)
Comment (DeJeune) [reply src/main/services/agents/skills/SkillService.ts:402]: Added `// INVARIANT: isInPlace assumes basename was already sanitized by getSkillDirectory()` comment in `3d4ebfe`.

File: src/renderer/src/components/InputEmbeddingDimension.tsx (hunk 4 above)
Comment (DeJeune) [reply src/renderer/src/components/InputEmbeddingDimension.tsx:52]: Agree — will split the embedding rotated key fix into a separate hotfix PR.

File: src/main/mcpServers/skills.ts [hunk 13]
```diff
@@ -0,0 +1,357 @@
...
+        throw new McpError(
+          ErrorCode.InvalidParams,
+          `No SKILL.md found in "${skillDir}". Call action="init" first and write a SKILL.md file before registering.`
+        )
+      }
+    } catch (err) {
+      if (err instanceof McpError) throw err
+      throw new McpError(
+        ErrorCode.InvalidParams,
+        `Cannot read skill directory "${skillDir}": ${(err as Error).message}. Did you call action="init" first?`
```
Comment (EurFelux) [inline src/main/mcpServers/skills.ts]: > [\!NOTE]
> This comment was translated by Claude.

**[Important] register pre-flight catch uniformly uses `InvalidParams` + "Did you call init first?" — Misleads agent on EACCES**

The pre-flight check added in `3d4ebfe` is good, but the catch block does not distinguish between ENOENT and EACCES:

```typescript
} catch (err) {
  if (err instanceof McpError) throw err
  throw new McpError(
    ErrorCode.InvalidParams,
    `Cannot read skill directory "${skillDir}": ${...}. Did you call action="init" first?`
  )
}
```

If the directory exists but has insufficient permissions (EACCES), the agent sees "Did you call init first?" and will repeatedly retry init, when the actual problem is permissions.

The `initSkill`'s readdir catch (fixed in the same commit) correctly distinguishes: ENOENT gets pass-through with `InvalidParams`, non-ENOENT uses `InternalError`. This should be consistent:

```typescript
} catch (err) {
  if (err instanceof McpError) throw err
  const code = (err as NodeJS.ErrnoException).code
  if (code === 'ENOENT') {
    throw new McpError(ErrorCode.InvalidParams,
      `Skill directory "${skillDir}" does not exist. Did you call action="init" first?`)
  }
  throw new McpError(ErrorCode.InternalError,
    `Cannot read skill directory "${skillDir}`: ${(err as Error).message}`)
}
```

---
<details>
<summary>Original Content</summary>

**[Important] register pre-flight catch 对所有错误统一用 `InvalidParams` + "Did you call init first?" — EACCES 时误导 agent**

`3d4ebfe` 新增的 pre-flight check 很好，但 catch 对 ENOENT 和 EACCES 不加区分：

```typescript
} catch (err) {
  if (err instanceof McpError) throw err
  throw new McpError(
    ErrorCode.InvalidParams,
    `Cannot read skill directory "${skillDir}`: ${...}. Did you call action="init" first?`
  )
}
```

如果目录存在但权限不足（EACCES），agent 看到 "Did you call init first?" 会反复重试 init，而问题其实是权限。

`initSkill` 的 readdir catch（同一个 commit 修的）已正确区分：ENOENT pass-through，non-ENOENT 用 `InternalError`。这里应保持一致：

```typescript
} catch (err) {
  if (err instanceof McpError) throw err
  const code = (err as NodeJS.ErrnoException).code
  if (code === 'ENOENT') {
    throw new McpError(ErrorCode.InvalidParams,
      `Skill directory "${skillDir}" does not exist. Did you call action="init" first?`)
  }
  throw new McpError(ErrorCode.InternalError,
    `Cannot read skill directory "${skillDir}`: ${(err as Error).message}`)
}
```

</details>

File: src/main/mcpServers/__tests__/skills.test.ts [hunk 14]
```diff
@@ -0,0 +1,359 @@
...
+        isEnabled: false
+      })
+
+      const server = createServer('agent_1')
+      const result = await callTool(server, { action: 'register', name: 'my-skill' })
+
+      expect(mockSkillInstallFromDirectory).toHaveBeenCalledWith({ directoryPath: '/global-skills/my-skill' })
+      expect(mockSkillToggle).toHaveBeenCalledWith({ skillId: 'skill-2', isEnabled: true })
+      expect(result.content[0].text).toContain('My Skill')
+      expect(result.content[0].text).toContain('registered and enabled')
```
Comment (EurFelux) [inline src/main/mcpServers/__tests__/skills.test.ts:333]: > [\!NOTE]
> This comment was translated by Claude.

**[Important] The `?? false` + "(warning: failed to enable)" branch is not covered by any tests**

Commit `3d4ebfe` changed `?? true` to `?? false` and added the `(warning: failed to enable)` conditional message. This is the core behavior change of this fix, but in the tests `mockSkillToggle` always returns `{ isEnabled: true }`, so the `false`/`null` branches are never reached.

Suggestion: add a test for toggle failure:

```typescript
it('should warn when toggle fails after register', async () => {
  mockSkillGetSkillDirectory.mockReturnValue('/global-skills/my-skill')
  mockReaddir.mockResolvedValue(['SKILL.md'])
  mockSkillInstallFromDirectory.mockResolvedValue({ id: 'skill-2', name: 'My Skill', ... })
  mockSkillToggle.mockResolvedValue(null) // toggle returns null

  const server = createServer()
  const result = await callTool(server, { action: 'register', name: 'my-skill' })

  expect(result.content[0].text).toContain('warning: failed to enable')
  expect(result.content[0].text).toContain('Enabled: false')
})
```

Similarly, `installSkill`'s "(warning: failed to enable)" also needs corresponding tests.

---
<details>
<summary>Original Content</summary>

**[Important] `?? false` + "(warning: failed to enable)" 分支未被任何测试覆盖**

`3d4ebfe` 把 `?? true` 改为 `?? false`，并加了 `(warning: failed to enable)` 条件文案。这是本次修复的核心行为变更，但测试中 `mockSkillToggle` 始终返回 `{ isEnabled: true }`，`false`/`null` 分支从未走到。

建议加一个 toggle 失败的测试：

```typescript
it('should warn when toggle fails after register', async () => {
  mockSkillGetSkillDirectory.mockReturnValue('/global-skills/my-skill')
  mockReaddir.mockResolvedValue(['SKILL.md'])
  mockSkillInstallFromDirectory.mockResolvedValue({ id: 'skill-2', name: 'My Skill', ... })
  mockSkillToggle.mockResolvedValue(null) // toggle returns null

  const server = createServer()
  const result = await callTool(server, { action: 'register', name: 'my-skill' })

  expect(result.content[0].text).toContain('warning: failed to enable')
  expect(result.content[0].text).toContain('Enabled: false')
})
```

同理 `installSkill` 的 "(warning: failed to enable)" 也需要对应测试。

</details>

File: src/main/services/agents/skills/SkillService.ts [hunk 15]
```diff
@@ -244,6 +259,7 @@ export class SkillService {
         folderName,
         error: error instanceof Error ? error.message : String(error)
       })
+      throw error
```
Comment (EurFelux) [inline src/main/services/agents/skills/SkillService.ts:262]: [\!NOTE]
> This comment was translated by Claude.

**[Medium] `unlinkSkill`'s bare catch was missed in this round of catch narrowing**

It's good that `linkSkill` now throws an error here. But `unlinkSkill` in the same file (line 277) has a completely symmetric bare catch:

```typescript
// unlinkSkill, line 277
} catch {
  // Does not exist, fine
}
```

EACCES / EPERM errors are also silently skipped as "does not exist". The effect is: user disables skill → DB changes to disabled → `unlinkSkill` permission failure is swallowed → symlink still exists → skill is still actually active.

Since this commit's theme is narrowing catch blocks, it's recommended to handle this together.

---
<details>
<summary>Original Content</summary>

**[Medium] `unlinkSkill` 的 bare catch 在本轮 catch 收窄中被遗漏**

`linkSkill` 这里加了 `throw error` 很好。但同文件的 `unlinkSkill`（line 277）有一个完全对称的 bare catch：

```typescript
// unlinkSkill, line 277
} catch {
  // Does not exist, fine
}
```

EACCES / EPERM 也被当作 "does not exist" 静默跳过。效果是：用户禁用 skill → DB 改 disabled → `unlinkSkill` 权限失败被吞 → symlink 仍在 → skill 实际仍活跃。

既然本轮 commit 主题就是收窄 catch，建议顺手一起处理。

</details>

**Review by EurFelux — COMMENTED** [review]
## Round 3 Review (post-fix `3d4ebfe` audit)

> [!NOTE]
> Verified `3d4ebfe` with 3 specialized agents: error handling audit, test coverage analysis, and linkSkill re-throw impact assessment.

The fix commit addresses all Round 2 issues correctly. Three new findings surfaced from the fix itself:

| Severity | Count | Theme |
|---|---|---|
| Important | 2 | Register pre-flight catch doesn't distinguish ENOENT vs EACCES; toggle-failure warning text path untested |
| Medium | 1 | `unlinkSkill` bare catch missed in the narrowing pass |

### linkSkill re-throw impact: verified safe

All `toggle()` callers handle the now-propagating error:
- `ipc.ts:1085` — try-catch returns `{ success: false, error }` ✓
- `skills.ts:201,309` — outer MCP handler (line 138) catches and returns `isError: true` ✓
- `useSkills.ts:37` — try-catch ✓

File: src/main/mcpServers/skills.ts (hunk 13 above)
Comment (DeJeune) [reply src/main/mcpServers/skills.ts]: Fixed in `50d3180`. Register catch now splits ENOENT → `InvalidParams` + "does not exist … Did you call init first?" vs non-ENOENT → `InternalError` + raw error message (no misleading init hint). Consistent with initSkill pattern.

File: src/main/mcpServers/__tests__/skills.test.ts (hunk 14 above)
Comment (DeJeune) [reply src/main/mcpServers/__tests__/skills.test.ts:333]: Fixed in `50d3180`. Added toggle-failure tests for both `installSkill` and `registerSkill` — `mockSkillToggle.mockResolvedValue(null)` → asserts `"warning: failed to enable"` and `"Enabled: false"`.

File: src/main/services/agents/skills/SkillService.ts (hunk 15 above)
Comment (DeJeune) [reply src/main/services/agents/skills/SkillService.ts:262]: Fixed in `50d3180`. `unlinkSkill` catch narrowed to ENOENT only; EACCES/EPERM now log and re-throw so a failed unlink does not leave a stale symlink while the DB shows disabled.

**Review by EurFelux — APPROVED** [review]
## Approved after 4 rounds of review

All inline review issues have been addressed and verified:

- **Round 1**: init collision detection added; auto-approve scope and file watcher deferred to issue tracker
- **Round 2** (8 threads): `linkSkill` error swallowing, broad catch blocks, missing tests, SKILL.md accuracy, register pre-flight — all fixed in `3d4ebfe`
- **Round 3** (3 threads): register catch ENOENT split, toggle-failure warning tests, `unlinkSkill` catch narrowing — all fixed in `50d3180`
- **Round 4**: Final pass — no new issues found

Remaining deferred items (not blocking merge):
- [ ] Create tracking issue: narrow auto-approve scope for `install` action
- [ ] Create tracking issue: v2 file watcher to replace init/register workaround
