### PR TITLE
fix: suppress DeepSeek DSML tags in web search results

### LINKED ISSUE #14714: [Bug]: DeepSeek V4-pro web search outputs raw DSML tool_calls tokens instead of invoking the tool
> [\!NOTE]
> This issue was translated by Claude.

### Platform

macOS

### Version

v1.9.4 (draft)

### Bug Description

When using `agent/deepseek-v4-pro` (CherryIN provider) with built-in web search enabled, the model emits the raw DSML tool-call protocol syntax as plain message text instead of having the client parse it as a tool invocation. The web search itself does fire (the citations card with "5 search results / 5 cited sources" appears earlier in the message), but the final assistant turn ends up showing protocol tokens to the user with no actual answer content.

Concretely the message body contains, verbatim:

```
< | DSML | tool_calls>
< | DSML | invoke name="builtin_web_search">
< | DSML | parameter name="additionalContext" string="true">DeepSeek V4 发布 特性 性能 评测 2025</ | DSML | parameter>
</ | DSML | invoke>
</ | DSML | tool_calls>
```

This looks like a tool-use parser miss for DeepSeek V4-pro: the DSML wrapper tokens that should be intercepted and turned into a tool-call UI block are leaking into the rendered text. Same provider + similar request on `deepseek-v3.2` does not exhibit this — the issue appears tied to V4-pro's tool-use formatting.

deepseek-v4-pro emitting raw DSML tool_calls in chat

### Steps to Reproduce

1. Provider: CherryIN
2. Model: `agent/deepseek-v4-pro`
3. Enable built-in web search (globe toggle in the composer)
4. Send: 搜一下 DeepSeek V4 的资料 (or any query that triggers a follow-up web search)
5. Observe the assistant turn

### Expected Behavior

After the web search runs, the assistant should produce a normal natural-language summary citing the 5 sources. The DSML protocol tokens (`< | DSML | tool_calls>`, `< | DSML | invoke …>`, etc.) should never be visible in the rendered message.

### Actual Behavior

- ✅ Thinking blocks render (1.5s, 1.3s)
- ✅ "5 个搜索结果" / "5 个引用内容" cards appear
- ❌ Final answer is replaced by raw DSML tool_calls XML — user sees protocol syntax, not an answer
- ❌ The conversation turn is effectively wasted; the user has to retry

### Severity

P0 — main path is blocked. The user asks a question, web search succeeds, but no answer text is produced. The visible output is internal protocol noise. Single-turn conversations using V4-pro + web search are unusable.

### Possibly Related

- #14671 (DeepSeek search-result annotations not displayed) — different (annotations vs tool-call token leak), but both touch DeepSeek + web search rendering.

### Environment

- App: Cherry Studio 社区版 v1.9.4 (draft)
- OS: macOS
- Provider: CherryIN (gateway-class)
- Model: `agent/deepseek-v4-pro`

---
<details>
<summary>Original Content</summary>

### 现象

v1.9.4 (draft)、CherryIN provider、模型 `agent/deepseek-v4-pro`，开启内置网络搜索后，模型把 DSML 工具调用协议的 raw token 当作正文输出到聊天区，没有触发客户端的工具调用 UI。web search 实际跑成了（消息中段已经出现"5 个搜索结果 / 5 个引用内容"卡片），但最终回答位置展示的是：

```
< | DSML | tool_calls>
< | DSML | invoke name="builtin_web_search">
< | DSML | parameter name="additionalContext" string="true">DeepSeek V4 发布 特性 性能 评测 2025</ | DSML | parameter>
</ | DSML | invoke>
</ | DSML | tool_calls>
```

应该被前端拦截、转成工具调用 UI 的 DSML 包裹 token 直接泄露到了渲染文本里。同 provider 下 deepseek-v3.2 不复现这个问题，看起来是 V4-pro 工具调用语法的解析适配缺失。

### 复现步骤

1. provider 选 CherryIN
2. 模型选 `agent/deepseek-v4-pro`
3. 开启内置网络搜索
4. 发送：搜一下 DeepSeek V4 的资料
5. 观察助手回复

### 期望

搜索完成后，助手应该输出引用了 5 个搜索结果的自然语言总结。DSML 协议 token 不应该出现在最终消息中。

### 优先级

P0：主路径阻塞。用户问完问题、search 成功，但看不到答案，只有协议语法。V4-pro + web search 单轮基本不可用。

### 相关 issue

- #14671（DeepSeek 搜索结果 annotations 不展示）— 现象不同（annotations 缺失 vs DSML token 泄露），但同样在 DeepSeek + web search 渲染链上。
</details>

### PR DESCRIPTION
**Pull request by kangfenmao**
### What this PR does

Before this PR:
DeepSeek models could include DSML tool-call tags in responses after built-in web search returned reference instructions.

After this PR:
Built-in web search appends a DeepSeek-only instruction to avoid outputting DSML tags, while other models keep the shared reference prompt unchanged.

Fixes #14714

### Why we need it and why it was done in this way

The following tradeoffs were made:
The fix keeps the change scoped to built-in web search output and model classification, avoiding broader prompt or tool-call changes.

The following alternatives were considered:
Adding the instruction to the shared reference prompt was rejected because it would affect non-DeepSeek models unnecessarily.

Links to places where the discussion took place: https://github.com/CherryHQ/cherry-studio/issues/14714

### Breaking changes

None.

If this PR introduces breaking changes, please describe the changes and the impact on users.

### Special notes for your reviewer

This PR targets `main` as a minimal hotfix branch because it fixes a user-visible DeepSeek web-search response issue.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. Check this only when the PR introduces or changes a user-facing feature or behavior.
- [x] Self-review: I have reviewed my own code (e.g., via [`/gh-pr-review`](/.claude/skills/gh-pr-review/SKILL.md), `gh pr diff`, or GitHub UI) before requesting review from others

### Release note

```release-note
Fix DeepSeek web-search responses leaking DSML tool-call tags.
```

### CODE REVIEW

**Review by DeJeune — APPROVED** [review]

File: src/renderer/src/config/models/utils.ts [hunk 1]
```diff
@@ -208,6 +208,16 @@ export const isAnthropicModel = (model?: Model): boolean => {
   return modelId.startsWith('claude')
 }
 
+export const isDeepSeekModel = (model?: Model | null): boolean => {
```
Comment (GeorgeDong32) [inline src/renderer/src/config/models/utils.ts]: > [\!NOTE]
> This comment was translated by Claude.

**Missing unit tests for `isDeepSeekModel`**

`isGemmaModel`, `isGeminiModel` and similar functions all have test coverage in `utils.test.ts`, but the newly added `isDeepSeekModel` is missing corresponding tests. Suggest adding the following test cases:

- Match via `model.id` (e.g., `deepseek-chat`)
- Match via `model.name` (e.g., `DeepSeek V3`)
- `null` / `undefined` inputs return `false`
- Non-DeepSeek models return `false`

---
<details>
<summary>Original Content</summary>

**Missing unit tests for `isDeepSeekModel`**

`isGemmaModel`, `isGeminiModel` 等同类函数在 `utils.test.ts` 中均有测试覆盖，但新增的 `isDeepSeekModel` 缺少对应测试。建议补充以下用例：

- 通过 `model.id` 匹配（如 `deepseek-chat`）
- 通过 `model.name` 匹配（如 `DeepSeek V3`）
- `null` / `undefined` 输入返回 `false`
- 非 DeepSeek 模型返回 `false`
</details>

File: src/renderer/src/aiCore/tools/WebSearchTool.ts [hunk 2]
```diff
@@ -119,6 +120,7 @@ You can use this tool as-is to search with the prepared queries, or provide addi
         '{question}',
         "Based on the search results, please answer the user's question with proper citations."
       ).replace('{references}', referenceContent)
+      const instructions = isDeepSeekModel ? `${fullInstructions}\n- Do not output DSML tags` : fullInstructions
```
Comment (GeorgeDong32) [inline src/renderer/src/aiCore/tools/WebSearchTool.ts]: **Hardcoded magic string — extract to constant or i18n key**

`- Do not output DSML tags` is a model instruction visible to the LLM. Hardcoding it inline makes it harder to maintain and reuse. Consider:

```typescript
const DEEPSEEK_DSML_SUPPRESSION = '\n- Do not output DSML tags'

const instructions = isDeepSeekModel
  ? `${fullInstructions}${DEEPSEEK_DSML_SUPPRESSION}`
  : fullInstructions
```

This also makes it searchable when auditing model-specific prompt overrides.

File: src/renderer/src/config/models/utils.ts (hunk 1 above)
Comment (GeorgeDong32) [inline src/renderer/src/config/models/utils.ts]: > [\!NOTE]
> This comment was translated by Claude.

**Minor: parameter type inconsistency with similar functions**

Similar functions like `isGemmaModel` and `isZhipuModel` use `(model?: Model)` (i.e., `Model | undefined`), while here it explicitly declares `Model | null`. `\!model` handles both, so functionally there's no difference, but I recommend unifying to `(model?: Model)` for consistency.

---
<details>
<summary>Original Content</summary>

**Minor: parameter type inconsistency with similar functions**

`isGemmaModel`, `isZhipuModel` 等同类函数签名使用 `(model?: Model)`（即 `Model | undefined`），而此处显式声明 `Model | null`。`\!model` 同时处理两者，功能上无差异，但建议统一为 `(model?: Model)` 以保持一致性。

</details>

**Review by GeorgeDong32 — CHANGES_REQUESTED** [review]
> [\!NOTE]
> This review was translated by Claude.

## Code Review Summary

This is a small and focused hotfix with a reasonable scope of changes (3 files +17/-3), clear logic, and all CI checks passed.

### Required Changes
- `isDeepSeekModel` lacks unit tests: In `utils.test.ts`, similar functions like `isGemmaModel` and `isGeminiModel` all have test coverage. The newly added `isDeepSeekModel` should have corresponding tests added (matching id/name, null/undefined, non-DeepSeek models)

### Suggested Improvements (non-blocking)
- **Type consistency**: `isDeepSeekModel` uses `Model | null` for its parameter, while `isGemmaModel` and others use `Model | undefined` (`?`). It is recommended to standardize on `(model?: Model)`
- **Magic strings**: `- Do not output DSML tags` is hardcoded within the function body. It is recommended to extract it as a named constant to improve maintainability and searchability

The rest of the changes look good: the call chain is correct, default parameter design is reasonable, and the PR description is complete.

---
<details>
<summary>Original Content</summary>

## Code Review Summary

整体是一个小而精的 hotfix，变更范围合理（3 文件 +17/-3），逻辑清晰，CI 全部通过。

### 需要修改
- `isDeepSeekModel` 缺少单元测试：`utils.test.ts` 中 `isGemmaModel`、`isGeminiModel` 等同类函数均有测试覆盖，新增的 `isDeepSeekModel` 应补充对应测试（匹配 id/name、null/undefined、非 DeepSeek 模型）

### 建议改进（不阻塞）
- **类型一致性**：`isDeepSeekModel` 参数使用 `Model | null`，而 `isGemmaModel` 等使用 `Model | undefined`（`?`），建议统一为 `(model?: Model)`
- **魔法字符串**：`- Do not output DSML tags` 硬编码在函数体内，建议提取为命名常量以提高可维护性和可搜索性

其余变更无问题：调用链路正确、默认参数设计合理、PR 描述完整。

</details>

**Review by GeorgeDong32 — APPROVED** [review]
