### PR TITLE
Fix/notes content search next scroll

### LINKED ISSUE #10867: [Bug]: Error when clicking "Next" in Ctrl+F to search within notes
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.6.5

### Bug Description

Image
In one of the notes, use Ctrl+F to search for keywords, then click "Next" to select the next result. When you need to jump to a result below a certain height on the page, it will start selecting from the beginning.

### Steps To Reproduce

1. Enter the notes
2. Create a new note and write some content (it must be long enough to fill the entire screen, preferably distributing the search keywords as widely as possible)
3. Use Ctrl+F to search for keywords and click next
4. When jumping to the nth one, the selection automatically jumps to the first

### Expected Behavior

Should not jump back to the first

### Relevant Log Output

```shell

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ZKunZhang**
### What this PR does

Before this PR:

- In Notes, using Ctrl+F and clicking "Next" would sometimes jump back to the first match when the target was below the visible area. This was due to page-level scrolling causing selection/index desync.

After this PR:

- "Next" now scrolls within the editor's own scroll container and reliably navigates to the next match. The index only wraps after the last match.

Fixes #10867

### Why we need it and why it was done in this way

- Need: In-editor search should scroll the editor container, not the whole page, to keep the current match and index stable.
- Approach:
  - Use the provided searchTarget (the editor scroll container) to compute relative offsets and call target.scrollTo({ behavior: 'smooth' }) to center the match.
  - Fallback to parentElement.scrollIntoView(...) when the container is not scrollable to preserve compatibility.
  - Add target to the useCallback deps to ensure the latest container reference is used.
- Changed file:
  - src/renderer/src/components/ContentSearch.tsx:165

The following tradeoffs were made:

- Centering the match improves visibility and avoids toolbar overlap but differs from top/bottom alignment preference in some setups.
- Avoided heavier logic (observers/selection plumbing) for simplicity and performance.

The following alternatives were considered:

- Keep scrollIntoView({ block: 'center' }): cannot restrict to a specific container, problem persists.
- CSS scroll-margin-top: harder to maintain and less precise than explicit offset calculation.
- IntersectionObserver / deeper editor integration: unnecessary for this bug's scope.

Links to places where the discussion took place: 

- N/A

### Breaking changes

If this PR introduces breaking changes, please describe the changes and the impact on users.

- None. This only adjusts how the current match is scrolled into view; it does not change search logic, hotkeys, styles, or highlight behavior.

### Special notes for your reviewer

- Verification steps:
  - Create a long note with the keyword spread across the document.
  - Press Ctrl+F, enter the keyword, then press "Next" repeatedly.
  - Expected: smooth in-container scroll to each subsequent match, index increments (e.g., 3/10 → 4/10), wraps back to the first only after the last match.
- Chat view also uses this component; when a container isn't scrollable, it falls back to default scrolling to avoid regressions.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### Release note

```release-note
Fix: Keep Ctrl+F "Next" navigation scrolling within the editor container, preventing premature wrap to the first match.
```

### CODE REVIEW

File: src/renderer/src/store/thunk/messageThunk.ts [hunk 1]
```diff
@@ -1500,10 +1500,15 @@ export const cloneMessagesToNewTopicThunk =
       const filesToUpdateCount: FileMetadata[] = []
       const originalToNewMsgIdMap = new Map<string, string>() // Map original message ID -> new message ID
 
-      // 3. Clone Messages and Blocks with New IDs
+      // 3. First pass: Create ID mappings for all messages
       for (const oldMessage of messagesToClone) {
```
Comment (DeJeune) [inline src/renderer/src/store/thunk/messageThunk.ts:1504]: 之前的提交混进来了

File: src/renderer/src/components/ContentSearch.tsx [hunk 2]
```diff
@@ -181,17 +181,29 @@ export const ContentSearch = React.forwardRef<ContentSearchRef, Props>(
...
+                if (canScroll) {
+                  const containerRect = target.getBoundingClientRect()
+                  const elRect = parentElement.getBoundingClientRect()
+                  // 计算元素相对于容器的可滚动偏移位置
+                  const elementTopWithinContainer = elRect.top - containerRect.top + target.scrollTop
+                  const desiredTop = elementTopWithinContainer - Math.max(0, target.clientHeight - elRect.height) / 2
+                  target.scrollTo({ top: Math.max(0, desiredTop), behavior: 'smooth' })
+                } else {
+                  // 传入的容器不可滚动，回退到浏览器的默认滚动定位
+                  parentElement.scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'nearest' })
```
Comment (DeJeune) [inline src/renderer/src/components/ContentSearch.tsx]: ` parentElement.scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'nearest' }) `封装一个公共函数.

File: src/renderer/src/store/thunk/messageThunk.ts (hunk 1 above)
Comment (ZKunZhang) [reply src/renderer/src/store/thunk/messageThunk.ts:1504]: > 之前的提交混进来了

sorry

File: src/renderer/src/components/ContentSearch.tsx (hunk 2 above)
Comment (ZKunZhang) [reply src/renderer/src/components/ContentSearch.tsx]: > `parentElement.scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'nearest' })`封装一个公共函数.



> `parentElement.scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'nearest' })`封装一个公共函数.

优化好了。

**Comment by EurFelux** [comment]
CI failed

**Comment by ZKunZhang** [comment]
> CI failed

Sorry for forgetting to reply. It has been fixed
