### PR TITLE
fix: correctly pass poe web_search via extra_body when built-in search is enabled

### LINKED ISSUE #13305: [Bug]: Model Built-in Web Search fails for Poe API models due to missing extra_body parameter mapping
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.7.24

### Bug Description

This is a follow-up to #11177, also mentioned in #11710. The previous issue was closed by a stale bot, but the problem persists.

As of Cherry Studio v1.7.24, when using the POE API provider and enabling the [Web Search - Model Built-in] option for models like Gemini-3-Flash, the built-in web search does not take effect. The model behaves as if it has no internet access and states it is in 2024.

According to the official [Poe API documentation](https://creator.poe.com/docs/external-applications/openai-compatible-api) and my own API testing, Poe's OpenAI-compatible API supports `web_search` and `thinking_level` parameters. However, the documentation explicitly states that custom bot parameters must be passed using the extra_body field. Currently, it appears that Cherry Studio does not correctly map the built-in web search UI toggle to the extra_body field in the API request payload for Poe. I tested the Poe API endpoints using a local script and confirmed that the parameters work perfectly when formatted correctly. Refer to Additional Context for full log.

### Steps To Reproduce

1. Configure the POE API correctly in Cherry Studio.
2. Select a Poe model that supports web search (e.g., Gemini-3-Flash).
3. Enable the [Web Search - Model Built-in] toggle.
4. Ask a question requiring real-time internet data (e.g., "Summarize the news from the past week.").
5. Actual Result: The model fails to fetch the latest news and returns outdated information from 2024.

### Expected Behavior

When the [Web Search - Model Built-in] option is enabled, Cherry Studio should correctly pass the web_search: true parameter inside the extra_body object when calling the Poe API, allowing the model to retrieve real-time internet data.

### Relevant Log Output

```shell
Call Chain Windows  -  Gemini-3-Flash.handleMessage  -  Poe.Gemini-3-Flash.chat

Span Details
ID: d5793f052617e654
Node Name: Poe.Gemini-3-Flash.chat
Tag: LLM
Start Time: 2026-03-08 16:52:59.337
End Time: 2026-03-08 16:53:09.764
Spend Time: 10.4s

Inputs: 
{
  "messages": [
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "Summarize the news from the past week."
        }
      ]
    }
  ],
  "abortSignal": {},
  "headers": {
    "HTTP-Referer": "https://cherry-ai.com",
    "X-Title": "Cherry Studio"
  },
  "providerOptions": {
    "poe": {
      "extra_body": {
        "thinking_budget": 12288
      }
    }
  },
  "maxRetries": 0,
  "tools": {}
}

Call Chain Windows  -  Gemini-3-Flash.handleMessage  -  Poe.Gemini-3-Flash.chat - ai.streamText

Span Details
ID: 275c588851049a39
Node Name: ai.streamText
Tag: LLM-STREAM
Start Time: 2026-03-08 16:52:59.338
End Time: 2026-03-08 16:53:09.764
Spend Time: 10.4s

Outputs:
{
  "text": "The past week (May 19–26, 2024) was marked by significant geopolitical shifts, major legal developments, and extreme weather events. Here is a summary of the top stories:\n\n### 1. International Affairs & Geopolitics\n*   **Death of Iran’s President:** Iranian President Ebrahim Raisi and Foreign Minister Hossein Amir-Abdollahian were killed in a helicopter crash in a mountainous region near the Azerbaijan border. While Iran has begun the process of selecting a successor, the event has introduced a period of uncertainty in Middle Eastern politics.\n*   **ICC and ICJ Developments:** The Prosecutor of the International Criminal Court (ICC) requested arrest warrants for Israeli Prime Minister Benjamin Netanyahu, Defense Minister Yoav Gallant, and three Hamas leaders (including Yahya Sinwar) for alleged war crimes. Additionally, the International Court of Justice (ICJ) ordered Israel to immediately halt its military offensive in Rafah, a ruling Israel is unlikely to follow.\n*   **Recognition of Palestine:** Norway, Ireland, and Spain formally announced they would recognize a Palestinian state, a move intended to build momentum for a two-state solution but one that drew sharp condemnation from Israel.\n*   **UK General Election:** In a surprise move, Prime Minister Rishi Sunak called for a general election to be held on July 4. His Conservative Party currently trails the Labour Party significantly in the polls.\n\n### 2. U.S. News & Politics\n*   **Trump \"Hush Money\" Trial:** Testimony concluded in the criminal trial of Donald Trump in New York. Closing arguments are scheduled for Tuesday, after which the jury will begin deliberations to determine if the former president is guilty of falsifying business records.\n*   **Student Debt Relief:** The Biden administration announced the cancellation of another $7.7 billion in student debt for approximately 160,000 borrowers, continuing its piecemeal approach to debt relief.\n*   **Severe Weather:** A series of powerful storms and tornadoes swept through the U.S. Midwest, particularly devastating the town of Greenfield, Iowa. Multiple deaths were reported, and thousands were left without power.\n\n### 3. Business & Technology\n*   **Nvidia’s AI Surge:** Nvidia reported another quarter of record-breaking earnings, with revenue up 262% year-over-year. The company’s stock surged past $1,000 per share, underscoring the massive ongoing investment in Artificial Intelligence hardware.\n*   **OpenAI vs. Scarlett Johansson:** OpenAI faced a PR crisis after actress Scarlett Johansson accused the company of copying her voice for their new ChatGPT \"Sky\" persona after she had explicitly declined to license it. OpenAI has since \"paused\" the use of the voice.\n*   **Microsoft Build:** At its annual developer conference, Microsoft unveiled \"Copilot+ PCs,\" new hardware designed specifically to run AI tasks locally on the device rather than in the cloud.\n\n### 4. Science & Environment\n*   **Papua New Guinea Landslide:** A massive landslide buried a remote village in Papua New Guinea. Local authorities fear that hundreds, possibly over 600 people, may have been killed, though rescue efforts have been hampered by difficult terrain.\n*   **Global Heatwaves:** Extreme heat continued to plague parts of Mexico and India, with temperatures in some regions exceeding 113°F (45°C), leading to dozens of heat-related deaths and power grid failures.\n\n### 5. Culture & Sports\n*   **Cannes Film Festival:** The prestigious festival concluded in France, with the film *Anora* by Sean Baker winning the Palme d'Or, the festival's highest prize.\n*   **NBA/NHL Playoffs:** Both the NBA and NHL reached their Conference Finals stages, with the Boston Celtics and Dallas Mavericks leading their respective series in the NBA.",
  "finishReason": "stop"
}
```

## **[Poe API documentation](https://creator.poe.com/docs/external-applications/openai-compatible-api)**

I tested the Poe API endpoints using a local script and confirmed that the parameters work perfectly when formatted correctly:

```
PS C:\Users\PC> $headers = @{
>>     "Content-Type"  = "application/json"
>>     "Authorization" = "Bearer $apiKey"
>> }
PS C:\Users\PC> $body = @{
>>     model = $model     
>>     messages = @(
>>         @{
>>             role    = "user"
>>             content = "Summarize the news from the past week."
>>         }
>>     )
>>     extra_body = @{
>>         thinking_level = "high"
>>     }
>> } | ConvertTo-Json -Depth 3
PS C:\Users\PC> $Model    
Gemini-3-Flash
PS C:\Users\PC> $apiBase  
https://api.poe.com/v1
PS C:\Users\PC> $response = 0; $response = Invoke-RestMethod -Uri "$apiBase/chat/completions" -Method Post -Headers $headers -Body $body; $response.choices[0].message.content
The past week (May 13–20, 2024) has been dominated by major geopolitical shifts, legal developments in the U.S., and significant advancements (and controversies) in the tech world.

etc.

PS C:\Users\PC> $body = @{                                                                                                                          
>>     model = $model
>>     messages = @(
>>         @{
>>             role    = "user"
>>             content = "Summarize the news from the past week."
>>         }
>>     )
>>     extra_body = @{
>>         web_search     = $true
>>         thinking_level = "high"
>>     }
>> } | ConvertTo-Json -Depth 3
PS C:\Users\PC> $response = 0; $response = Invoke-RestMethod -Uri "$apiBase/chat/completions" -Method Post -Headers $headers -Body $body; $response.choices[0].message.content
The past week (March 1–8, 2026) has been dominated by a massive escalation in the Middle East, significant shifts in global nuclear policy, and major developments in the intersection of AI and warfare. [[1]](https://en.wikipedia.org/wiki/2026)

### **1. Geopolitics: The Iran-Israel-US War**
The most significant story of the week is the outbreak of a direct military conflict between the U.S., Israel, and Iran. [[2]](https://www.youtube.com/watch?v=pJrc4FlIeMY)[[3]](https://www.youtube.com/watch?v=qzQJqCvDijQ)

etc.
```

### PR DESCRIPTION
**Pull request by kovsu**
Fix #13305 

> https://creator.poe.com/docs/external-applications/openai-compatible-api#using-custom-parameters-with-extra_body

```js
import OpenAI from "openai";

const client = new OpenAI({
    apiKey: process.env.POE_API_KEY,
    baseURL: "https://api.poe.com/v1",
});

// Example: Using web search and thinking level with Gemini models
const response = await client.chat.completions.create({
    model: "Gemini-3-Pro",
    messages: [{ role: "user", content: "What are the latest developments in quantum computing?" }],
    extra_body: {
        web_search: true,
        thinking_level: "high"
    }
});
```

### CODE REVIEW

File: src/renderer/src/aiCore/utils/options.ts [hunk 1]
```diff
@@ -634,10 +635,7 @@ function buildGenericProviderOptions(
 
   if (enableWebSearch) {
     const webSearchParams = getWebSearchParams(model)
-    providerOptions = {
-      ...providerOptions,
-      ...webSearchParams
-    }
+    providerOptions = merge({}, providerOptions, webSearchParams)
```
Comment (kovsu) [inline src/renderer/src/aiCore/utils/options.ts:638]:
```ts
// reasoning.ts
if (isOpenAIReasoningModel(model)) {
      return {
        extra_body: {
          reasoning_effort: reasoningEffort === 'auto' ? 'medium' : reasoningEffort
        }
      }
    }
```

如果 providerOptions 和 webSearchParams 都有 `extra_body` 这个参，使用`...` 就没有合并起来而是 webSearchParams 覆盖了 providerOptions。所以这里我们使用 lodash 提供的 `merge` 方法。

**Comment by EurFelux** [comment]
> [!NOTE]
> This comment was translated by Claude.

Perhaps it's time to migrate Poe to the Responses API

---
<details>
<summary>Original Content</summary>

也许应该为Poe迁移到 Responses API 了
</details>

**Comment by kovsu** [comment]
> Perhaps it's time to migrate Poe to the Responses API

I’m glad to do it in a separate PR

**Review by EurFelux — APPROVED** [review]

**Comment by EurFelux** [comment]
> > Perhaps it's time to migrate Poe to the Responses API
> 
> I’m glad to do it in a separate PR

That will help a lot, thank you! :)

**Review by DeJeune — APPROVED** [review]
