### PR TITLE
hotfix(image-generation): fix gpt-image-2 / gpt-image-1.5 failures and stuck pending placeholder

### LINKED ISSUE #14485: [Bug]: 调用gpt-image-2提示Unknown parameter: 'response_format'
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.92

### Bug Description

Image
调用gpt-image-2提示Unknown parameter: 'response_format'，应该是新版不是调用/v1/images/generations引起的，但没有办法进行调整，下面的生成图片图标也无法取消掉。

### Steps To Reproduce

Image
调用gpt-image-2提示Unknown parameter: 'response_format'，应该是新版不是调用/v1/images/generations引起的，但没有办法进行调整，下面的生成图片图标也无法取消掉。

### Expected Behavior

修复模型支持，能成功调用

### Relevant Log Output

```shell

```

### Additional Context

_No response_

### LINKED ISSUE #14540: [Bug]: gpt-2-image error
> [\!NOTE]
> This issue/comment/review was translated by Claude.

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

1.9.2

### Bug Description

{
  "error": {
    "message": "Unknown parameter: 'response_format'.",
    "type": "invalid_request_error",
    "param": "response_format",
    "code": "unknown_parameter"
  }
}

### Steps To Reproduce

{
  "error": {
    "message": "Unknown parameter: 'response_format'.",
    "type": "invalid_request_error",
    "param": "response_format",
    "code": "unknown_parameter"
  }
}

### Expected Behavior

{
  "error": {
    "message": "Unknown parameter: 'response_format'.",
    "type": "invalid_request_error",
    "param": "response_format",
    "code": "unknown_parameter"
  }
}

### Relevant Log Output

```shell

```

### Additional Context

_No response_

---
<details>
<summary>Original Content</summary>

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

1.9.2

### Bug Description

{
  "error": {
    "message": "Unknown parameter: 'response_format'.",
    "type": "invalid_request_error",
    "param": "response_format",
    "code": "unknown_parameter"
  }
}

### Steps To Reproduce

{
  "error": {
    "message": "Unknown parameter: 'response_format'.",
    "type": "invalid_request_error",
    "param": "response_format",
    "code": "unknown_parameter"
  }
}

### Expected Behavior

{
  "error": {
    "message": "Unknown parameter: 'response_format'.",
    "type": "invalid_request_error",
    "param": "response_format",
    "code": "unknown_parameter"
  }
}

### Relevant Log Output

```shell

```

### Additional Context

_No response_

**Original Title:** [Bug]: gpt-2-image报错

</details>

### LINKED ISSUE #14579: [Bug]: gpt-image-1.5 error "response_format": "b64_json" "Unknown parameter: 'response_format'
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

1.9.3

### Bug Description

Image

### Steps To Reproduce

request any prompt to gpt-image-1.5 model

### Expected Behavior

not error

### Relevant Log Output

```shell
Request body values:
{
  "model": "gpt-image-1.5",
  "prompt": "create slide with HandDrawn style",
  "n": 1,
  "size": "1024x1024",
  "response_format": "b64_json"
}

Response body:
{
  "error": {
    "message": "Unknown parameter: 'response_format'.",
    "type": "invalid_request_error",
    "param": "response_format",
    "code": "unknown_parameter"
  }
}

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by DeJeune**
### What this PR does

Before this PR:

- `gpt-image-2` (and any image-edit request routed through AiHubMix / NewAPI / CherryIN) failed with `common.UnmarshalBodyReusable failed: bind request body failed: invalid character '-' in numeric literal`. The providers hard-coded `Content-Type: application/json` in `authHeaders()`, but `OpenAICompatibleImageModel.doGenerate` uses `postFormDataToApi` for `/images/edits` and relies on `fetch` to auto-set `multipart/form-data; boundary=...`. Forcing JSON made the server receive a multipart body under a JSON content-type and choke on the leading `--boundary`.
- Even when the request reached the server, image uploads failed with `unsupported mimetype ('image')` because `collectImagesFromMessages` built data URIs using `block.file.type` — which is the `FileType` enum (`"image"`), not a MIME type.
- Some saved/pasted images produced `ENOENT: ... <uuid>jpg` because `saveBase64Image` / `savePastedImage` return `ext` without the leading dot, and the caller was concatenating `file.id + file.ext`.
- After a successful image generation, a `BeatLoader` placeholder kept spinning next to the finished image. `fetchImageGeneration` only emitted `LLM_RESPONSE_COMPLETE`; the trailing loader in `Blocks/index.tsx` is driven by `isMessageProcessing(message)`, which is only cleared when `onComplete` runs on `BLOCK_COMPLETE`.
- If a `file` chunk arrived without a preceding `IMAGE_CREATED`, the initial UNKNOWN placeholder block was never claimed, leaving an orphan spinner below the image.
- `gpt-image-2` / `gpt-image-1.5` / `gpt-image-1*` / `chatgpt-image-*` generations through any OpenAI-compatible provider still failed with `400 Unknown parameter: 'response_format'` (see #14485, #14540, #14579). The earlier `@ai-sdk/openai@3.0.53` patch (#14488) only covered `OpenAIImageModel` (direct OpenAI + Azure via `@ai-sdk/azure`); `OpenAICompatibleImageModel.doGenerate` unconditionally added `response_format: "b64_json"` to the `/images/generations` body, so every provider whose image model is wired to `OpenAICompatibleImageModel` kept hitting the 400 — including `type: 'openai-compatible'` and the AiHubMix / NewAPI / CherryIN gateway image models in this repo.

After this PR:

- `aihubmix-provider`, `newapi-provider`, and `cherryin-provider` no longer hard-code `Content-Type` in auth headers. `postJsonToApi` still defaults JSON for other endpoints, and `postFormDataToApi` is free to let `fetch` set `multipart/form-data; boundary=...` for `/images/edits`.
- `collectImagesFromMessages` reads via `window.api.file.base64Image(block.file.name)`, which returns a correct `data:image/<ext>;base64,...` URI (with `jpg → jpeg` normalization) and uses the consistent on-disk filename regardless of whether the stored `ext` has a leading dot.
- `fetchImageGeneration` now emits `ChunkType.BLOCK_COMPLETE` before `LLM_RESPONSE_COMPLETE`, so `onComplete` runs and the assistant message transitions out of `PROCESSING`.
- `onImageGenerated` reuses the initial UNKNOWN placeholder when one exists, so a `file` chunk without a prior `IMAGE_CREATED` no longer leaves an orphan spinner.
- `gpt-image-2` is registered in `IMAGE_ENHANCEMENT_MODELS`.
- `patches/@ai-sdk__openai-compatible@2.0.37.patch` is extended with the same `hasDefaultResponseFormat` guard that `@ai-sdk/openai` already uses. `OpenAICompatibleImageModel.doGenerate` now spreads `response_format: "b64_json"` only when the model ID does **not** start with `chatgpt-image-`, `gpt-image-1-mini`, `gpt-image-1.5`, `gpt-image-1`, or `gpt-image-2`. This fixes #14485, #14540, #14579 for `openai-compatible` typed providers and the AiHubMix / NewAPI / CherryIN gateways.

Fixes #14485
Fixes #14540
Fixes #14579

### Why we need it and why it was done in this way

The following tradeoffs were made:

- The `ext`-with-or-without-dot inconsistency exists in historical DB records, so patching only `FileStorage.ts` would not help already-saved rows. The fix uses `file.name` at the consumer side — always the real on-disk filename across every save path — without touching the storage layer.
- The provider `authHeaders()` change could theoretically affect non-JSON, non-multipart requests, but all SDK models in use go through `postJsonToApi`, which already defaults `Content-Type: application/json` internally, so behavior is preserved.
- Extending the `@ai-sdk/openai-compatible` patch rather than overriding `response_format` per-provider keeps the fix in one place and automatically covers every caller of `OpenAICompatibleImageModel` (current and future). The guard list mirrors the upstream `@ai-sdk/openai` list, so the two stay in sync.

The following alternatives were considered:

- Normalizing `ext` in `FileStorage.saveBase64Image` / `savePastedImage`: rejected because it would not repair existing records and could regress other callers that have compensated for the dotless form.
- Overriding `Content-Type` only inside the image model factory: rejected as more surface area than needed; the global `authHeaders()` already defers to `postJsonToApi` defaults.
- Stripping `response_format` in each custom provider (AiHubMix / NewAPI / CherryIN) instead of patching the SDK: rejected — it would leave `type: 'openai-compatible'` users still broken and duplicate the model-prefix list in three places.

Links to places where the discussion took place: #14485, #14540, #14579, #14488

### Breaking changes

None.

### Special notes for your reviewer

Scope is intentionally minimal for the main branch freeze: no refactoring, no new abstractions. Surface changes:

- `authHeaders()` in three custom providers (drops one hard-coded header).
- `collectImagesFromMessages` (one helper, swaps input building).
- `fetchImageGeneration` (one extra chunk emission).
- `onImageGenerated` (placeholder-claim fallback).
- `IMAGE_ENHANCEMENT_MODELS` (one new entry).
- `patches/@ai-sdk__openai-compatible@2.0.37.patch` (adds `hasDefaultResponseFormat` helper + conditional spread of `response_format`; mirrors `@ai-sdk/openai@3.0.53` patch).

Drop the openai-compatible patch addition once `@ai-sdk/openai-compatible` ships the equivalent check upstream.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. Check this only when the PR introduces or changes a user-facing feature or behavior.
- [x] Self-review: I have reviewed my own code (e.g., via [`/gh-pr-review`](/.claude/skills/gh-pr-review/SKILL.md), `gh pr diff`, or GitHub UI) before requesting review from others

### Release note

```release-note
Fix image generation and editing for gpt-image-2 / gpt-image-1.5 / gpt-image-1* / chatgpt-image-* across AiHubMix, NewAPI, CherryIN, Azure OpenAI, and other OpenAI-compatible providers: requests no longer fail with `Unknown parameter: 'response_format'`, multipart content-type, or mimetype errors; generated/pasted images are resolved correctly; and the loading placeholder disappears once the image is rendered.
```

### CODE REVIEW

File: src/renderer/src/services/ApiService.ts [hunk 1]
```diff
@@ -312,12 +311,18 @@ async function collectImagesFromMessages(userMessage: Message, assistantMessage?
...
+  // Also note: `block.file.type` is a FileType enum (e.g. "image"), NOT a MIME
+  // type. `base64Image` derives the real MIME from the extension internally
+  // (and normalizes jpg → image/jpeg).
   const userImageBlocks = findImageBlocks(userMessage)
   for (const block of userImageBlocks) {
     if (block.file) {
-      const base64 = await FileManager.readBase64File(block.file)
-      const mimeType = block.file.type || 'image/png'
-      images.push(`data:${mimeType};base64,${base64}`)
+      const { data } = await window.api.file.base64Image(block.file.name)
```
Comment (GeorgeDong32) [inline src/renderer/src/services/ApiService.ts:324]: **Suggestion: consider guarding against `undefined` data**

```typescript
const { data } = await window.api.file.base64Image(block.file.name)
if (!data) continue // skip if file not found or read failed
images.push(data)
```

If `base64Image` fails to locate the file (e.g. file was moved/deleted externally), `data` would be `undefined` and `images.push(undefined)` would produce an invalid entry in the images array. A quick guard would make this more robust.

Not blocking — the outer `catch` at line 423 handles thrown errors, and `block.file` existence implies a prior successful save.

**Review by GeorgeDong32 — APPROVED** [review]
## Review Summary

Approved. Excellent multi-bug-fix PR with thorough root-cause analysis for each issue.

**5 fixes, all correct and minimal:**
1. **Content-Type hardcoding** — removed from aihubmix, newapi, cherryin; `postJsonToApi` still defaults JSON
2. **MIME type bug** — switched from `block.file.type` (enum) to `window.api.file.base64Image(block.file.name)` with proper MIME resolution
3. **Stuck loader** — `BLOCK_COMPLETE` before `LLM_RESPONSE_COMPLETE` fixes the state machine
4. **Orphan spinner** — reuses `initialPlaceholderBlockId` when no `IMAGE_CREATED` preceded
5. **`response_format` 400** — `hasDefaultResponseFormat` guard mirrors the `@ai-sdk/openai` patch

**Highlights:** PR description is exceptionally thorough, comments explain WHY not WHAT, changeset files included.

One non-blocking suggestion inline on defensive null-checking for `base64Image` return.

**Review by ousugo — APPROVED** [review]
LGTM
