### PR TITLE
fix: get empty response when using MCP by functional method

### LINKED ISSUE #8258: [错误]: MCP 调用无响应
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我的问题不是 [常见问题](https://github.com/CherryHQ/cherry-studio/issues/3881) 中的内容。
- [x] 我已经查看了 **置顶 Issue** 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。

### 平台

Linux

### 版本

v1.5.1

### 错误描述

要求 LLM 使用工具后无响应
Image

已经启用了 fetch 工具
Image

LLM 也有调用的动作
Image

### 重现步骤

1. 将函数调用方式设置为函数(p.s. 提示词好像也有问题)
2. 要求 LLM 调用工具

### 预期行为

Cherry Studio 响应 LLM 的工具调用并将结果加入上下文

### 相关日志输出

```shell

```

### 附加信息

_No response_

### LINKED ISSUE #8273: [错误]: 升级到1.5.1后mcp 无法使用没有返回
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我的问题不是 [常见问题](https://github.com/CherryHQ/cherry-studio/issues/3881) 中的内容。
- [x] 我已经查看了 **置顶 Issue** 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。

### 平台

Windows

### 版本

v1.5.1

### 错误描述

升级到1.5.1后mcp, 没有返回内容，模型是有思考的过程，没有升级之前正常

Image

Image

Image

### 重现步骤

升级到1.5.1后mcp, 没有返回内容，模型是有思考的过程，好像没有去执行mcp

### 预期行为

执行mcp

### 相关日志输出

```shell

```

### 附加信息

_No response_

### LINKED ISSUE #8275: [错误]: 1.5.1 MCP 工具调用怎么了？都跑不动
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我的问题不是 [常见问题](https://github.com/CherryHQ/cherry-studio/issues/3881) 中的内容。
- [x] 我已经查看了 **置顶 Issue** 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。

### 平台

macOS

### 版本

1.5.1

### 错误描述

升级了以后，我所有的 MCP 调用都完成不了，都是给我这个信息：

Image

### 重现步骤

1. 问问题
2. 调用 MCP
3. 出现错误

### 预期行为

能够完成

### 相关日志输出

```shell

```

### 附加信息

_No response_

### LINKED ISSUE #8290: [错误]: 1.5.1版本LLM响应已触发MCP工具调用，Cherry Studio没有执行调用
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我的问题不是 [常见问题](https://github.com/CherryHQ/cherry-studio/issues/3881) 中的内容。
- [x] 我已经查看了 **置顶 Issue** 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。

### 平台

macOS

### 版本

v1.5.1

### 错误描述

升级到1.5.1后，部分LLM在添加MCP后，无法完成工具调用，使用模型为Azure的OpenAI-GPT 4.1，MCP Server配置MicroSandbox代码沙箱，沙箱服务已启动，之前使用kimi k2成功过多次，对话历史如下：

Image

为了观察发生了什么，在Cloudflare上配置AI Gateway观察了一下：
Image

从Cloudflare的日志中可以看到，最后一次用户发送“开始”，LLM的响应是工具调用（<tool_use>\n  <name>MicroSa-sandbox_start</name>\n...），但Cherry Studio侧并没有开始工具调用。

在模型配置处GPT 4.1，启用了工具调用选项：
Image

使用的是默认助手，工具调用方式为提示词：
Image

修改默认助手的工具调用方式为函数后，会报这个错：Cannot read properties of undefined (reading 'function')
Image

### 重现步骤

1. 升级到v1.5.1
2. 配置Azure OpenAI服务提供商，配置GPT-4.1模型（其他的应该也可以，像SIliconflow/Qwen3-32B就不行，只是没有用Cloudflare Gateway观察日志）
3. 安装MicroSandbox，执行msb server start启动沙箱服务，然后执行msb server keygen --expire 3mo获取一个token，配置这MCP Server
Image
4. 在默认助手中，使用如下提示词测试，启用MicroSandbox这个MCP Server

```markdown
帮我使用Python分别实现快速排序、冒泡排序，然后分别创建包含100、1000、10000随机数的数组，分别使用这3组测试数据运行这两个排序算法3次，运行时只统计每次运行耗时即可，**不要输出测试数据和排序结果**，将结果成立成一个报告，报告分别2部分：
1. 两种算法实现的代码，3组测试数据3次运行分别耗时明细，3组测试数据平均耗时表格，3组测试数据平均耗时折线图
2. 两种算法在3组测试水上的平均耗时的对比表格、折线对比图

注意：
1. 你自助完成所有任务即可，不需要向我确认，所有准备工作完成之后，再开始撰写报告
2. 最终的统计图，直接使用Markdown语法展示出来，而不要以超链接的形式添加在报告中
3. 所实现的排序算法，只统计时长即可，**一定不要**把测试数据和排序结果输出
4. 请实现原地排序算法，排序结果不需要返回
```

### 预期行为

能正常执行工具调用

### 相关日志输出

```shell

```

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by EurFelux**
### What this PR does

Before this PR:

After this PR:

包含`tool_call`的chunk，其`delta.content`可能为`null`，没有考虑进去，导致被跳过了。

Fixes #8275 
Fixes #8290 
Fixes #8258
Fixes #8273

### Why we need it and why it was done in this way

The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Breaking changes

If this PR introduces breaking changes, please describe the changes and the impact on users.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### Release note

```release-note

```

### CODE REVIEW

File: src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts [hunk 1]
```diff
@@ -714,6 +715,7 @@ export class OpenAIAPIClient extends OpenAIBaseClient<
               choice.delta &&
               Object.keys(choice.delta).length > 0 &&
               (!('content' in choice.delta) ||
+                choice.delta.content === null ||
```
Comment (DeJeune) [inline src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts]: 不需要判断delta.tool_call吗？

Comment (EurFelux) [reply src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts]: 确实加上稳健一点

**Review by DeJeune — APPROVED** [review]

**Comment by alephpiece** [comment]
这么频繁的 silly 日志会影响性能吗？

**Comment by beyondkmp** [comment]
看起来是测试用的？

**Comment by EurFelux** [comment]
silly是很底层的日志，平时开debug不影响吧

**Comment by alephpiece** [comment]
> silly是很底层的日志，平时开debug不影响吧

它其实就是 console.log 吧？

**Comment by EurFelux** [comment]
> > silly是很底层的日志，平时开debug不影响吧
> 
> 它其实就是 console.log 吧？

是console.log，但日志等级不开到silly就不会输出啊

**Comment by alephpiece** [comment]
> > > silly是很底层的日志，平时开debug不影响吧
> > 
> > 
> > 它其实就是 console.log 吧？
> 
> 是console.log，但日志等级不开到silly就不会输出啊

可能是你这个分支没有更新代码，生产环境还是会打出日志来😂

**Comment by EurFelux** [comment]
> > > > silly是很底层的日志，平时开debug不影响吧
> > > 
> > > 
> > > 它其实就是 console.log 吧？
> > 
> > 
> > 是console.log，但日志等级不开到silly就不会输出啊
> 
> 可能是你这个分支没有更新代码，生产环境还是会打出日志来😂

loggerService里面现在开发环境默认silly等级，后面应该会改吧

**Review by alephpiece — APPROVED** [review]
