### PR TITLE
fix(minapps): openMinApp function doesn't work properly

### LINKED ISSUE #10274: [Bug]: Clicking Releases at the About Page doesn't open in Windows
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.6.0-rc.2

### Bug Description

If I click releases it doesn't do anything

### Steps To Reproduce

Go to the About Page in windows, then click Releases

### Expected Behavior

It should open like a miniapp.

### Relevant Log Output

```shell

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by GeorgeDong32**
### What this PR does

Before this PR:
- openMinApp function doesn't work properly

After this PR:
- Adds support for temporary minapps.
- Uses openSmartMinApp with app logo to open documentation sites.

Fixes #10274

### CODE REVIEW

**Comment by EurFelux** [comment]
@claude review

File: src/renderer/src/components/Icons/MinAppIcon.tsx [hunk 1]
```diff
@@ -11,25 +11,44 @@ interface Props {
...
 const MinAppIcon: FC<Props> = ({ app, size = 48, style, sidebar = false }) => {
+  // First try to find in DEFAULT_MIN_APPS for predefined styling
   const _app = DEFAULT_MIN_APPS.find((item) => item.id === app.id)
 
-  if (!_app) {
-    return null
+  // If found in DEFAULT_MIN_APPS, use predefined styling
+  if (_app) {
+    return (
+      <Container
```
Comment (EurFelux) [inline src/renderer/src/components/Icons/MinAppIcon.tsx]: Could we migrate to tailwind css?

File: src/renderer/src/components/Tab/TabContainer.tsx [hunk 2]
```diff
@@ -45,11 +45,17 @@ interface TabsContainerProps {
   children: React.ReactNode
 }
 
-const getTabIcon = (tabId: string, minapps: any[]): React.ReactNode | undefined => {
+const getTabIcon = (tabId: string, minapps: any[], minAppsCache?: any): React.ReactNode | undefined => {
```
Comment (EurFelux) [inline src/renderer/src/components/Tab/TabContainer.tsx]: Can we use a more specified type instead of any?

File: src/renderer/src/components/Tab/TabContainer.tsx [hunk 3]
```diff
@@ -45,11 +45,17 @@ interface TabsContainerProps {
...
   // Check if it's a minapp tab (format: apps:appId)
   if (tabId.startsWith('apps:')) {
     const appId = tabId.replace('apps:', '')
-    const app = [...DEFAULT_MIN_APPS, ...minapps].find((app) => app.id === appId)
+    let app = [...DEFAULT_MIN_APPS, ...minapps].find((app) => app.id === appId)
+
+    // If not found in default/custom apps, try cache (for temporary apps)
```
Comment (EurFelux) [inline src/renderer/src/components/Tab/TabContainer.tsx]: What if cache is outdated?

File: src/renderer/src/pages/minapps/MinAppPage.tsx [hunk 4]
```diff
@@ -44,11 +44,20 @@ const MinAppPage: FC = () => {
...
+  // Find the app from all available apps (including cached ones)
   const app = useMemo(() => {
     if (!appId) return null
-    return [...DEFAULT_MIN_APPS, ...minapps].find((app) => app.id === appId)
-  }, [appId, minapps])
+
+    // First try to find in default and custom mini-apps
+    let foundApp = [...DEFAULT_MIN_APPS, ...minapps].find((app) => app.id === appId)
+
+    // If not found and we have cache, try to find in cache (for temporary apps)
```
Comment (EurFelux) [inline src/renderer/src/pages/minapps/MinAppPage.tsx:54]: Same here. How could we ensure the cache is truth? If we couldn't find the app in L52, why it could be found in the cache?

File: src/renderer/src/pages/settings/AboutSettings.tsx [hunk 5]
```diff
@@ -309,7 +309,7 @@ const AboutSettings: FC = () => {
         <SettingDivider />
         <SettingRow>
           <SettingRowTitle>
-            <Github size={18} />
+            <GithubOutlined size={18} />
```
[the remark this answers is not in the document]
Comment (GeorgeDong32) [reply src/renderer/src/pages/settings/AboutSettings.tsx:312]: After checking, there are no issues with this code.

File: src/renderer/src/components/Tab/TabContainer.tsx [hunk 6]
```diff
@@ -45,14 +47,40 @@ interface TabsContainerProps {
...
+): React.ReactNode | undefined => {
   // Check if it's a minapp tab (format: apps:appId)
   if (tabId.startsWith('apps:')) {
     const appId = tabId.replace('apps:', '')
-    const app = [...DEFAULT_MIN_APPS, ...minapps].find((app) => app.id === appId)
+    let app = [...DEFAULT_MIN_APPS, ...minapps].find((app) => app.id === appId)
+
+    // If not found in permanent apps, search in temporary apps cache
+    // The cache stores apps opened via openSmartMinapp() for top navbar mode
+    // These are temporary MinApps that were opened but not yet saved to user's config
```
Comment (EurFelux) [inline src/renderer/src/components/Tab/TabContainer.tsx:64]: I'm not sure how could a user open a minApp when it doesn't exist in user's config.

Comment (EurFelux) [reply src/renderer/src/components/Tab/TabContainer.tsx:64]: Do these code run when user config is not loaded?

Comment (GeorgeDong32) [reply src/renderer/src/components/Tab/TabContainer.tsx:64]: 这里只用来以小程序形式打开下面图中的几个网页以及部分设置项的文档，所以是不会存在用户的配置中的，需要特殊处理
PixPin_2025-09-23_23-24-25

Comment (EurFelux) [reply src/renderer/src/components/Tab/TabContainer.tsx:64]: ok
