### PR TITLE
fix(aiCore): handle NVIDIA provider reasoning params via chat_template_kwargs

### LINKED ISSUE #13364: [Discussion]: The "Chain-of-Thought Length" adjustment option does not work when using models provided by NVIDIA
> [!NOTE]
> This issue was translated by Claude.

I tested the `moonshotai/kimi-k2.5` and `qwen/qwen3.5-397b-a17b` models provided by NVIDIA to check whether the reasoning mode can be toggled. I also tested the `kimi-k2.5` model provided by Moonshot AI and the `moonshot-kimi-k2.5` model provided by AiHubMix.

Expected result: When the "Chain-of-Thought Length" option is set to "Off", the chain-of-thought for all four models should be completely disabled; when the option is set to "Deep contemplation" or "Auto", the chain-of-thought for all four models should be enabled.

Actual result: When the "Chain-of-Thought Length" option is set to "Off", the chain-of-thought for `moonshotai/kimi-k2.5` remains enabled, while the chain-of-thought for the other three is disabled; when set to "Deep contemplation" or "Auto", the chain-of-thought for `qwen/qwen3.5-397b-a17b` remains disabled, while the chain-of-thought for the other three is enabled.

In daily use, I have found that similar issues exist with models including but not limited to `z-ai/glm5` and `minimaxai/minimax-m2.5`.

---

<details>
<summary>Original Content</summary>

### Issue Checklist

- [x] I understand that issues are meant for feedback and problem-solving, not for venting, and I will provide as much detail as possible to help resolve the issue.
- [x] I have checked the pinned issues and searched through the existing [open issues](https://github.com/CherryHQ/cherry-studio/issues), [closed issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [discussions](https://github.com/CherryHQ/cherry-studio/discussions) and did not find a similar suggestion.
- [x] I confirm that I am here to ask questions and discuss issues, not to report bugs or request features.

### Platform

Windows

### Version

v1.7.24

### Your Question

我使用英伟达提供的`moonshotai/kimi-k2.5`和`qwen/qwen3.5-397b-a17b`模型，测试是否可以开关推理模式。同时测试了月之暗面提供的`kimi-k2.5`和 AiHubMix 提供的`moonshot-kimi-k2.5`模型。

期望的结果是：当思维链长度选项为关闭时，四个模型的思维链全部关闭；当选项为沉思或者自动时，四个模型的思维链全部打开。

实际的结果是：当思维链长度选项为关闭时，`moonshotai/kimi-k2.5`的思维链仍然保持开启，其它三个的思维链关闭；当为沉思或者自动时，`qwen/qwen3.5-397b-a17b`的思维链仍然保持关闭，其它三个的思维链开启。

在日常的使用中，发现包括但不限于`z-ai/glm5`、`minimaxai/minimax-m2.5`等模型都有类似问题。

### Context

_No response_

### Additional Information

```shell

```

### Priority

Medium (Would like a response soon)
</details>

### PR DESCRIPTION
**Pull request by EurFelux**
### What this PR does

Before this PR:
- NVIDIA provider used a generic `thinking: true` for all reasoning models, which doesn't work correctly for different model families hosted on NVIDIA's API.
- `isSupportedThinkingTokenZhipuModel` didn't match `glm5` (without hyphen) or provider-prefixed IDs like `accounts/fireworks/models/glm-4p7`.
- `thinking_budget` was placed at the wrong nesting level for generic providers using `chat_template_kwargs`.

After this PR:
- NVIDIA provider now passes model-specific reasoning parameters through `chat_template_kwargs` (e.g., `enable_thinking` for Qwen/Zhipu, `thinking` for DeepSeek/Kimi).
- Qwen models on NVIDIA also support `thinking_budget` control.
- `isSupportedThinkingTokenZhipuModel` uses a regex to correctly handle all Zhipu GLM-5/4.5/4.6/4.7 variants.
- `thinking_budget` is now correctly nested inside `chat_template_kwargs` for generic providers.
- Added `thinking_budget` to the `chat_template_kwargs` type definition with a note that mainstream inference backends (e.g., vLLM) may not fully support it yet ([vllm#17887](https://github.com/vllm-project/vllm/issues/17887)).

Fixes #13364

### Why we need it and why it was done in this way

NVIDIA's API requires reasoning parameters to be passed via `chat_template_kwargs` rather than standard provider options. Different model families on NVIDIA use different parameter names (`enable_thinking` vs `thinking`), so model-specific handling is necessary.

The following tradeoffs were made:
- Only mainstream OSS models (Qwen, DeepSeek, Kimi, Zhipu) are covered due to limited NVIDIA API documentation. All parameter mappings were verified against NVIDIA's API.
- `thinking_budget` support in `chat_template_kwargs` is added but may not work on all backends due to upstream limitations (see [vllm#17887](https://github.com/vllm-project/vllm/issues/17887)).

The following alternatives were considered:
- A single generic parameter for all NVIDIA models — rejected because different model families require different parameter names.

### Breaking changes

None.

### Special notes for your reviewer

- The NVIDIA-specific handling is placed before the generic provider checks to ensure it takes priority.
- Both the "reasoning disabled" and "reasoning enabled" code paths are handled for NVIDIA.
- `thinking_budget` in `chat_template_kwargs` has a known upstream limitation — see inline comment and linked vLLM issue.

### Checklist

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. Check this only when the PR introduces or changes a user-facing feature or behavior.
- [x] Self-review: I have reviewed my own code (e.g., via [`/gh-pr-review`](/.claude/skills/gh-pr-review/SKILL.md), `gh pr diff`, or GitHub UI) before requesting review from others

### Release note

```release-note
Fix NVIDIA provider reasoning parameters for Qwen, DeepSeek, Kimi, and Zhipu models by using model-specific chat_template_kwargs
```

### CODE REVIEW

File: src/renderer/src/types/sdk.ts [hunk 1]
```diff
@@ -89,6 +89,9 @@ export type ReasoningEffortOptionalParams = {
   chat_template_kwargs?: {
     thinking?: boolean
     enable_thinking?: boolean
+    // mainstream inference backend does't support thinking_budget, so it may not work as expected
```
Comment (EurFelux) [inline src/renderer/src/types/sdk.ts]:
```suggestion
    // mainstream inference backend doesn't support thinking_budget, so it may not work as expected
```

File: src/renderer/src/aiCore/utils/reasoning.ts [hunk 2]
```diff
@@ -84,6 +84,21 @@ export function getReasoningEffort(assistant: Assistant, model: Model): Reasonin
       return { reasoning: { enabled: false, exclude: true } }
     }
 
+    // nvidia: must use chat_template_kwargs
+    // Since limited documentation, it's hard to find what parameters should be set
+    // only part of mainstream oss model covered, all vefiried by nvidia api
```
Comment (EurFelux) [inline src/renderer/src/aiCore/utils/reasoning.ts]:
```suggestion
    // only part of mainstream oss model covered, all verified by nvidia api
```

File: src/renderer/src/aiCore/utils/reasoning.ts [hunk 3]
```diff
@@ -251,6 +266,27 @@ export function getReasoningEffort(assistant: Assistant, model: Model): Reasonin
     budgetTokens = Math.floor((tokenLimit.max - tokenLimit.min) * effortRatio + tokenLimit.min)
   }
 
+  // nvidia: must use chat_template_kwargs
+  // Since limited documentation, it's hard to find what parameters should be set
+  // only part of mainstream oss model covered, all vefiried by nvidia api
```
Comment (EurFelux) [inline src/renderer/src/aiCore/utils/reasoning.ts]:
```suggestion
  // only part of mainstream oss model covered, all verified by nvidia api
```

File: src/renderer/src/types/sdk.ts (hunk 1 above)
Comment (EurFelux) [inline src/renderer/src/types/sdk.ts]:
```suggestion
    // mainstream inference backend doesn't support thinking_budget, so it may not work as expected
```
