### PR TITLE
fix(agents): use correct SWRInfinite cache key and add optimistic update for session editing

### LINKED ISSUE #13474: [Bug]: Session edit does not optimistically update SWR cache due to SWRInfinite key mismatch
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

All platforms

### Version

latest (main branch)

### Bug Description

`useUpdateSession` uses the global `mutate(listKey, ...)` from `swr` to update the session list cache after editing a session. However, `useSessions` uses `useSWRInfinite`, which stores its cache under a different internal key format (`$inf$` prefix + serialized page key), not the plain `listKey` string.

This means `mutate(listKey, ...)` in `useUpdateSession` **never actually updates the SWRInfinite list cache**. The UI shows stale session data (e.g., old name after rename) until SWR's automatic revalidation kicks in a few seconds later.

**Root cause in code:**

```typescript
// useUpdateSession.ts — uses global mutate with plain string key
mutate<ListAgentSessionsResponse['data']>(
  listKey,  // ❌ This key doesn't match useSWRInfinite's internal cache key
  (prev) => prev?.map((session) => (session.id === result.id ? result : session)) ?? []
)

// useSessions.ts — uses useSWRInfinite, cache key is [base, pageIndex, pageSize]
const getKey = (pageIndex, previousPageData) => {
  return [client.getSessionPaths(agentId).base, pageIndex, pageSize]
}
const { mutate } = useSWRInfinite(getKey, fetcher)
```

Additionally, `useUpdateSession` waits for the API response before updating the cache (no optimistic update), causing unnecessary UI delay.

### Steps To Reproduce

1. Open an Agent with multiple sessions
2. Double-click a session name to rename it
3. Type a new name and press Enter
4. Observe: the session name in the sidebar does NOT update immediately
5. Wait ~2-3 seconds, the name eventually updates via SWR revalidation

### Expected Behavior

The session name should update immediately in the sidebar after editing, without waiting for API response or SWR revalidation.

### Relevant Log Output

```shell
N/A
```

### Additional Context

The fix requires using `unstable_serialize` from `swr/infinite` to generate the correct SWRInfinite cache key, and implementing optimistic updates (update UI before API call, rollback on failure).

### PR DESCRIPTION
**Pull request by EurFelux**
### What this PR does

Before this PR:

Editing a session (e.g., renaming) in the Agent sidebar does not immediately reflect in the UI. The global `mutate(listKey, ...)` in `useUpdateSession` fails to match `useSWRInfinite`'s internal cache key format, so the list cache is never actually updated. The change only appears after SWR's automatic revalidation (~2-3 seconds).

After this PR:

- Session edits are optimistically applied to both the SWRInfinite list cache and the item cache immediately. The UI updates instantly, with rollback on API failure.
- Session name uses Tailwind `truncate` utility instead of a styled-component with `-webkit-line-clamp`. Also cleaned up Tailwind v4 syntax in `shared.tsx` (`text-[var(--color-text)]` → `text-(--color-text)`, `p-[16px]` → `p-4`).
- `DEFAULT_SESSION_PAGE_SIZE` moved to `api/agent.ts` as a shared API-level constant.

Fixes #13474

### Why we need it and why it was done in this way

The following tradeoffs were made:

- Used `unstable_serialize` from `swr/infinite` to generate the correct SWRInfinite cache key. This is the official SWR approach for mutating `useSWRInfinite` data from outside the hook.
- `DEFAULT_SESSION_PAGE_SIZE` lives in `api/agent.ts` because page size is an API-level concern shared by both `useSessions` and `useUpdateSession`.

The following alternatives were considered:

- Moving update logic into `useSessions` hook — rejected because `useUpdateSession` is used independently in multiple places (e.g., `SessionSettingsPopup`).
- Using a filter-based global mutate (`mutate(key => key.includes(...))`) — rejected as it relies on SWR internals and is fragile.
- Exporting the constant from `useSessions.ts` — rejected to avoid a hook module exporting non-hook values.

### Breaking changes

None.

### Special notes for your reviewer

- The `mutateInfiniteList` helper is extracted as a module-level function to avoid recreation on each render.
- Tailwind v4 syntax cleanup in `shared.tsx` is a drive-by fix.

### Checklist

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. Check this only when the PR introduces or changes a user-facing feature or behavior.
- [ ] Self-review: I have reviewed my own code (e.g., via [`/gh-pr-review`](/.claude/skills/gh-pr-review/SKILL.md), `gh pr diff`, or GitHub UI) before requesting review from others

### Release note

```release-note
NONE
```

### CODE REVIEW

File: src/renderer/src/hooks/agents/useUpdateSession.ts [hunk 1]
```diff
@@ -17,20 +39,26 @@ export const useUpdateSession = (agentId: string | null) => {
       const paths = client.getSessionPaths(agentId)
       const listKey = paths.base
       const sessionId = form.id
+      const itemKey = paths.withId(sessionId)
+      const infKey = unstable_serialize(() => [listKey, 0, DEFAULT_SESSION_PAGE_SIZE])
+
```
Comment (kangfenmao) [inline src/renderer/src/hooks/agents/useUpdateSession.ts:44]: **Concern:** `unstable_serialize(() => [listKey, 0, DEFAULT_SESSION_PAGE_SIZE])` hardcodes the default page size. If a caller of `useSessions` passes a custom `pageSize`, the serialized key here won't match the SWRInfinite cache key, causing the optimistic update to silently miss that cache entry.

Consider either:
1. Accept `pageSize` as a parameter in `useUpdateSession`, or
2. Extract the `getKey` function from `useSessions` as a shared utility so both hooks use the same key generation logic.

This would make the coupling between the two hooks explicit and prevent silent cache misses.

File: src/renderer/src/hooks/agents/useUpdateSession.ts [hunk 2]
```diff
@@ -1,12 +1,34 @@
...
 import { useCallback } from 'react'
 import { useTranslation } from 'react-i18next'
 import { mutate } from 'swr'
+import { unstable_serialize } from 'swr/infinite'
 
 import { useAgentClient } from './useAgentClient'
 
+type InfiniteData = ListAgentSessionsResponse[]
+
+const mutateInfiniteList = (
```
Comment (kangfenmao) [inline src/renderer/src/hooks/agents/useUpdateSession.ts:14]: **Nit:** `mutateInfiniteList` is a clean extraction. Consider adding a brief JSDoc noting that the `infKey` must be generated via `unstable_serialize` from `swr/infinite` — this would help future contributors understand the coupling.
