### PR TITLE
fix(agent): stop thinking timer on abort by emitting abort stream part

### LINKED ISSUE #13566: [Bug]: Endless Thinking Time
> [!NOTE]
> This issue was translated by Claude.

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

1.8.0

### Bug Description

https://github.com/user-attachments/assets/3bcaf8a9-8107-4331-afdc-ef83209ff85e

After forcibly stopping the Agent's work, the Agent's thinking time continues to count.

### Steps To Reproduce

Ask an Agent a question and forcibly stop it while it's thinking.

### Expected Behavior

After forcibly stopping the Agent's work, the Agent's thinking time should stop counting.

### Relevant Log Output

```shell

```

### Additional Context

_No response_

---
<details>
<summary>Original Content</summary>

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

1.8.0

### Bug Description

https://github.com/user-attachments/assets/3bcaf8a9-8107-4331-afdc-ef83209ff85e
在强制停止Agent工作后，Agent思考时间依旧继续计算

### Steps To Reproduce

向一个Agent提问，在思考时强制停止

### Expected Behavior

在强制停止Agent工作后，Agent思考时间停止继续计算

### Relevant Log Output

```shell

```

### Additional Context

_No response_
</details>

### PR DESCRIPTION
**Pull request by DeJeune**
### What this PR does

Before this PR:

After force-stopping an Agent while it is thinking, the thinking time counter continues running indefinitely because `callbacks.onError` is never called for agent streams on abort.

After this PR:

The thinking timer stops correctly when the user force-stops an Agent, because the agent SSE stream now emits an `'abort'` stream part before erroring — matching AI SDK stream behavior — so `callbacks.onError` fires and updates block statuses.

Fixes #13566

image

### Why we need it and why it was done in this way

The root cause is in `createSSEReadableStream` (used only for agent streams). Its abort handler called `controller.error()` directly without first enqueuing an `'abort'` TextStreamPart. The standard AI SDK streams emit an `'abort'` part before erroring, which `AiSdkToChunkAdapter.convertAndEmitChunk` converts to a `ChunkType.ERROR` chunk, triggering `callbacks.onError` to update block statuses (STREAMING → PAUSED). Without that stream part, the adapter's `processStream` catch silently swallowed the AbortError, and `onError` was never invoked.

The following tradeoffs were made:

A try/catch wraps the `controller.enqueue()` in case the controller is already closed. This is defensive but necessary since the abort handler can race with a natural stream close.

The following alternatives were considered:

- Patching `AiSdkToChunkAdapter.processStream` to emit the ERROR chunk in the catch block when no error chunk was emitted. Rejected because fixing the upstream source (`createSSEReadableStream`) is cleaner and makes agent streams consistent with AI SDK streams.

### Breaking changes

None.

### Special notes for your reviewer

Single-line root cause: `createSSEReadableStream`'s abort handler → `controller.error()` without prior `controller.enqueue({ type: 'abort' })` → `AiSdkToChunkAdapter` never emits ERROR chunk → `onError` never called → thinking block stays STREAMING.

### Checklist

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: Write code that humans can understand and Keep it simple
- [x] Refactor: You have left the code cleaner than you found it (Boy Scout Rule)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: Not required — bug fix, no user-facing behavior change
- [x] Self-review: I have reviewed my own code before requesting review from others

### Release note

```release-note
fix: Agent thinking timer no longer continues counting after force-stopping the Agent
```

### CODE REVIEW

File: src/renderer/src/store/thunk/messageThunk.ts [hunk 1]
```diff
@@ -253,6 +253,14 @@ const createSSEReadableStream = (
...
       const abortHandler = () => {
         cancelReader(signal.reason ?? 'aborted')
+        // Enqueue an 'abort' stream part before erroring, matching AI SDK stream behavior.
+        // Without this, AiSdkToChunkAdapter never emits the ERROR chunk, so callbacks.onError
+        // is never called and block statuses (e.g., thinking timer) are not updated on abort.
+        try {
+          controller.enqueue({ type: 'abort' } as TextStreamPart<Record<string, any>>)
+        } catch {
+          // Controller may already be closed
+        }
```
Comment (EurFelux) [inline src/renderer/src/store/thunk/messageThunk.ts]: **Concern: wrong layer — this responsibility belongs to a missing middleware, not the SSE parser**

`createSSEReadableStream` is a transport-layer utility (SSE bytes → parsed objects). It shouldn't be responsible for emitting `{ type: 'abort' }` stream parts — that's not a transport concern.

In the normal (non-Agent) chat pipeline, it's the **AI SDK runtime** that handles abort signal → abort chunk conversion. But in the Agent pipeline, AI SDK's chunk types are only used as a **protocol/wire format** — the AI SDK runtime itself is absent. This means nobody is handling the responsibilities that AI SDK normally takes care of, such as translating abort signals into proper stream lifecycle events.

The fix shouldn't go here (transport layer) or in `AiSdkToChunkAdapter` (which adapts protocol, not runtime behavior). What's missing is a **middleware layer between the SSE stream and the adapter** that owns the stream lifecycle — handling abort signals, emitting abort/error chunks, and managing the stream state — the same role AI SDK's runtime plays in the normal chat pipeline.

Without that layer, we'll keep patching AI SDK runtime behavior into places that shouldn't own it.

Comment (EurFelux) [reply src/renderer/src/store/thunk/messageThunk.ts]: Tracking the proposed middleware approach in #13580.

Comment (DeJeune) [reply src/renderer/src/store/thunk/messageThunk.ts]: Good call — you're right that `createSSEReadableStream` is transport and shouldn't own lifecycle concerns.

Updated in 1e12f47: extracted a dedicated `withAbortStreamPart` middleware that sits between the SSE parser and the adapter. It intercepts source stream errors on abort and emits `{ type: 'abort' }` — the same role the AI SDK runtime plays in the normal chat pipeline. `createSSEReadableStream` is now reverted to pure transport.

Pipeline is now: `SSE bytes → createSSEReadableStream (transport) → withAbortStreamPart (lifecycle) → AiSdkToChunkAdapter (protocol)`.

File: src/renderer/src/store/thunk/messageThunk.ts [hunk 2]
```diff
@@ -336,6 +336,47 @@ const createSSEReadableStream = (
...
+        // When the source errors due to abort, emit the abort stream part
+        // so downstream consumers (AiSdkToChunkAdapter) can fire onError.
+        if (signal.aborted) {
+          try {
+            controller.enqueue({ type: 'abort' } as TextStreamPart<Record<string, any>>)
+          } catch {
+            // Controller may already be closed
+          }
+        }
+        controller.close()
```
Comment (EurFelux) [inline src/renderer/src/store/thunk/messageThunk.ts]: The middleware extraction looks great — clean separation of concerns 👍

One issue: the `catch` block silently swallows **non-abort** errors. If `reader.read()` throws for a reason other than abort (e.g. network failure, decoding error), the stream just closes normally via `controller.close()` and downstream has no idea an error occurred.

Consider propagating the error in the non-abort path:

```ts
} catch (error) {
  if (signal.aborted) {
    try {
      controller.enqueue({ type: 'abort' } as TextStreamPart<Record<string, any>>)
    } catch {
      // Controller may already be closed
    }
    controller.close()
  } else {
    controller.error(error)
  }
}
```

This way abort gets the lifecycle treatment, and genuine errors still propagate.

Comment (DeJeune) [reply src/renderer/src/store/thunk/messageThunk.ts]: Good catch — fixed in 63c7612. Non-abort errors now propagate via `controller.error(error)`, only abort gets the lifecycle treatment (enqueue abort part + close).
