### PR TITLE
fix: correct MCP tool parameter parsing and nested schema display

### LINKED ISSUE #13136: bug: Model cannot see tool parameters when calling tools
> [!NOTE]
> This issue was translated by Claude.

### Discussed in https://github.com/CherryHQ/cherry-studio/discussions/13135

<div type='discussions-op-text'>

<sup>Originally posted by **fantasy0v0** March 2, 2026</sup>
Taking DingTalk's todo as an example: https://mcp.dingtalk.com/#/detail?instanceId=30827&detailType=instanceMcpDetail

image

The server returns the parameters and which fields are required within the parameters.

However, in Cherry Studio, only JSDoc is visible, causing the model to pass parameters incorrectly when calling tools.

kimi

deepseek

Cherry Studio version: v1.7.19</div>

---
<details>
<summary>Original Content</summary>

### Discussed in https://github.com/CherryHQ/cherry-studio/discussions/13135

<div type='discussions-op-text'>

<sup>Originally posted by **fantasy0v0** March  2, 2026</sup>
以钉钉的待办为例：https://mcp.dingtalk.com/#/detail?instanceId=30827&detailType=instanceMcpDetail\r\n\r\nimage\r\n\r\n服务器是返回了参数以及参数内需要哪些字段的。\r\n\r\n但是在Cherry Studio里面，却只能看到JSDoc，导致它在调用的时候瞎传参数。\r\n\r\nkimi\r\n\r\ndeepseek\r\n\r\nCherry Studio版本：v1.7.19</div>

</details>

### PR DESCRIPTION
**Pull request by vaayne**
### What this PR does

Before this PR:
- MCP tool parameters were not parsed correctly due to incorrect Zod API usage (`z.parse()` instead of `schema.parse()`)
- MCP settings page only showed top-level properties — nested object schemas (e.g. DingTalk's `PersonalTodoCreateVO`) displayed as a single "Object" row without child fields
- Hub inspect JSDoc output only listed top-level `@param` entries, hiding nested property details

After this PR:
- Zod schema parsing works correctly, so models receive complete parameter schemas
- MCP settings UI recursively renders nested object and array-of-object properties
- Hub inspect JSDoc recursively generates `@param` entries for all nested fields

Fixes #13136

### Why we need it and why it was done in this way

The Zod parsing fix is straightforward — the original code used a non-existent API.

For nested schema display, both the UI component (`McpTool.tsx`) and the JSDoc generator (`format.ts`) were refactored to recurse into nested `object` and `array` item properties. This matches real-world MCP servers (e.g. DingTalk) that wrap parameters in nested objects.

The following alternatives were considered:
- Flattening nested schemas at parse time — rejected because it would lose structural information needed by models

### Breaking changes

None.

### Special notes for your reviewer

The pre-existing typecheck errors in CI (AI SDK version mismatches, missing `partial-json` module, etc.) are unrelated to this PR and exist on `main`.

### Checklist

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: Write code that humans can understand and Keep it simple
- [x] Refactor: You have left the code cleaner than you found it (Boy Scout Rule)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: Not required — no user-facing documentation changes needed
- [x] Self-review: I have reviewed my own code before requesting review from others

### Release note

```release-note
Fixed MCP tool parameter parsing and added support for displaying nested object properties in tool inspector UI and hub inspect output.
```

### Images
image
image

### CODE REVIEW

**Review by EurFelux — COMMENTED** [review]
> [!NOTE]
> This issue/comment/review was translated by Claude.
> 
> Although it's not standard usage, `z.parse` does exist in the type declaration file and is actually available. I don't think the root cause of the problem is here.
> 
> ---
> <details>
> <summary>Original Content</summary>
> 
> 尽管不是标准用法，但`z.parse`确实存在于类型声明文件中并且实际可用。我想问题的根因并不在这里
> 
> </details>

**Comment by vaayne** [comment]
> [!NOTE]
> This comment was translated by Claude.

@EurFelux That's not the issue, it's related to MCP itself. I'm looking for native MCP tests because I found that Cherry's built-in works fine. It should be that some parameters were converted incorrectly during the conversion process.

---
<details>
<summary>Original Content</summary>

@EurFelux 问题不是这个，和 MCP 本身相关，我在找原生的 MCP 测试，因为我发现 cherry 内置的是可以 work 的，应该是转换的时候有些参数转换错了
</details>

File: src/main/services/MCPService.ts [hunk 1]
```diff
@@ -848,8 +847,8 @@ class McpService {
       tools.map((tool: SDKTool) => {
         const serverTool: MCPTool = {
           ...tool,
-          inputSchema: z.parse(MCPToolInputSchema, tool.inputSchema),
-          outputSchema: tool.outputSchema ? z.parse(MCPToolOutputSchema, tool.outputSchema) : undefined,
+          inputSchema: MCPToolInputSchema.parse(tool.inputSchema),
```
Comment (DeJeune) [inline src/main/services/MCPService.ts:850]: **Good catch:** `z.parse(schema, data)` is a `zod/v4/core` standalone API, not available from the standard `import * as z from 'zod'`. Switching to `schema.parse(data)` is the correct fix. The `import * as z` removal is also correct since these were the only two call sites.

File: src/main/mcpServers/hub/format.ts [hunk 2]
```diff
@@ -48,6 +48,57 @@ function schemaToParamType(prop: PropertySchema): string {
...
+    // Recurse into array item properties
+    if ((prop.type as string) === 'array' && prop.items) {
+      const items = prop.items as PropertySchema
+      if ((items.type as string) === 'object' && items.properties) {
+        const itemProps = items.properties as Record<string, PropertySchema>
+        const itemRequired = new Set<string>(
+          Array.isArray(items.required) ? (items.required as string[]) : []
+        )
+        appendPropertyParams(lines, itemProps, itemRequired, `${prefix}.${propName}[]`, depth + 1)
+      }
```
Comment (DeJeune) [inline src/main/mcpServers/hub/format.ts:93]: **Nit — no recursion depth guard:** Both `appendPropertyParams` (here) and `renderSchemaProperties` / `renderPropertyValue` (in the UI) recurse without a depth limit. In practice MCP tool schemas are shallow so this is fine, but if an MCP server ever returns a schema with circular `$ref` references, this would stack-overflow. A simple `maxDepth` parameter (e.g., default 5) would be a cheap safety net. Not blocking, just something to consider.

File: src/renderer/src/pages/settings/MCPSettings/McpTool.tsx [hunk 3]
```diff
@@ -31,77 +31,100 @@ const MCPToolsSection = ({ tools, server, onToggleTool, onToggleAutoApprove }: M
...
+  }
+
+  const MAX_NESTING_DEPTH = 5
+
+  // Render a single property's value (type badge, description, enum, nested properties)
+  const renderPropertyValue = (prop: any, depth: number = 0) => {
+    const itemType = prop.type === 'array' && prop.items?.type ? `${prop.items.type}[]` : prop.type
+
+    return (
+      <Flex vertical gap={4}>
```
Comment (DeJeune) [inline src/renderer/src/pages/settings/MCPSettings/McpTool.tsx:58]: **Nice improvement:** Displaying array item types as `type[]` (e.g., `string[]`) instead of just `array` is a good UX touch — it gives users more information at a glance about what the parameter expects.

File: src/renderer/src/pages/settings/MCPSettings/McpTool.tsx [hunk 4]
```diff
@@ -31,77 +31,100 @@ const MCPToolsSection = ({ tools, server, onToggleTool, onToggleAutoApprove }: M
...
+            <Typography.Text type="secondary">
+              {t('settings.mcp.tools.inputSchema.enum.allowedValues')}
+            </Typography.Text>
+            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginTop: 4 }}>
+              {prop.enum.map((value: string, idx: number) => (
+                <Tag key={idx}>{value}</Tag>
+              ))}
+            </div>
+          </div>
+        )}
```
Comment (DeJeune) [inline src/renderer/src/pages/settings/MCPSettings/McpTool.tsx:81]: **Nit:** The hardcoded `items:` label here is not internationalized, unlike other UI text in this component which uses `t(...)`. Consider using a translation key for consistency, e.g. `t('settings.mcp.tools.inputSchema.items')` or similar.
