### PR TITLE
fix: improve CLI tools path handling for special characters (issue #11995)

### LINKED ISSUE #11995: [Bug]: Unable to start any CLI code tools through Cherry Studio's code tool in specific directories
> [!NOTE]
> This issue/comment/review was translated by Claude.

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.7.5

### Bug Description

When using Cherry Studio to start the code tool, I discovered that CLI code tools cannot be launched in specific folders (none of them work). The CLI displays:
================================================
Cherry Studio CLI Tool Launcher
Tool: claude-code
Directory: C:\Users\Administrator\Desktop\ai-chat-service\cargo-ai-chat-service(back)
Time: 2025/12/18 17:08:53
================================================
Press any key to continue . . .
PS C:\Users\Administrator\Desktop\ai-chat-service\cargo-ai-chat-service(back)>

and I can start my own downloaded Claude Code in the current directory, and this problem doesn't occur in other directories.

### Steps To Reproduce

1. Select the current specific folder as the working directory: C:\Users\Administrator\Desktop\ai-chat-service\cargo-ai-chat-service(back)
2. Click to launch

### Expected Behavior

Launch Claude Code

### Relevant Log Output

```shell
仅有i18n错误
es-BLVcOTW8.js:85 <error> [i18n:label] Missing key b255de1c-a3ab-4cb2-8941-609d686fe368
processLog @ es-BLVcOTW8.js:85
error @ es-BLVcOTW8.js:116
getLabel @ store-DXyPvFNZ.js:23539
getProviderLabel @ store-DXyPvFNZ.js:23610
(anonymous) @ store-DXyPvFNZ.js:264599
CodeToolsPage @ store-DXyPvFNZ.js:264584
renderWithHooks @ client-DNI3-9fK.js:2858
updateFunctionComponent @ client-DNI3-9fK.js:4242
beginWork @ client-DNI3-9fK.js:4632
performUnitOfWork @ client-DNI3-9fK.js:6607
workLoopSync @ client-DNI3-9fK.js:6511
renderRootSync @ client-DNI3-9fK.js:6495
performWorkOnRoot @ client-DNI3-9fK.js:6253
performSyncWorkOnRoot @ client-DNI3-9fK.js:7061
flushSyncWorkAcrossRoots_impl @ client-DNI3-9fK.js:6984
processRootScheduleInMicrotask @ client-DNI3-9fK.js:7004
(anonymous) @ client-DNI3-9fK.js:7065
es-BLVcOTW8.js:85 <error> [i18n:label] Missing key b255de1c-a3ab-4cb2-8941-609d686fe368
processLog @ es-BLVcOTW8.js:85
error @ es-BLVcOTW8.js:116
getLabel @ store-DXyPvFNZ.js:23539
getProviderLabel @ store-DXyPvFNZ.js:23610
(anonymous) @ store-DXyPvFNZ.js:264599
CodeToolsPage @ store-DXyPvFNZ.js:264584
renderWithHooks @ client-DNI3-9fK.js:2858
updateFunctionComponent @ client-DNI3-9fK.js:4242
beginWork @ client-DNI3-9fK.js:4632
performUnitOfWork @ client-DNI3-9fK.js:6607
workLoopSync @ client-DNI3-9fK.js:6511
renderRootSync @ client-DNI3-9fK.js:6495
performWorkOnRoot @ client-DNI3-9fK.js:6253
performSyncWorkOnRoot @ client-DNI3-9fK.js:7061
flushSyncWorkAcrossRoots_impl @ client-DNI3-9fK.js:6984
processRootScheduleInMicrotask @ client-DNI3-9fK.js:7004
(anonymous) @ client-DNI3-9fK.js:7065
```

### Additional Context

See attachment for directory structure
Environment description: I use PowerShell to start the project
My successful launch uses PowerShell 7, while Cherry Studio uses the system's built-in PowerShell to launch Claude Code. The corresponding system version is: Windows 11 25H2
Additional note: I only encountered this problem in this specific directory. The parent directory and other directories don't have this issue, but subdirectories also have this problem

---
<details>
<summary>Original Content</summary>

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.7.5

### Bug Description

在使用cherry studio启动code 工具的时候，发现特定文件夹下无法启动cli code工具（全部的都不可以）的问题。
cli显示：
================================================
Cherry Studio CLI Tool Launcher
Tool: claude-code
Directory: C:\Users\Administrator\Desktop\ai-chat-service\cargo-ai-chat-service(back)
Time: 2025/12/18 17:08:53
================================================
Press any key to continue . . .
PS C:\Users\Administrator\Desktop\ai-chat-service\cargo-ai-chat-service(back)>

并且我在当前的目录下可以启动自己下载的claude code，并且在其他的目录没有上述的问题

### Steps To Reproduce

1. 工作目录选择当前的特定的文件夹：C:\Users\Administrator\Desktop\ai-chat-service\cargo-ai-chat-service(back)
2. 点击启动

### Expected Behavior

启动claude code

### Relevant Log Output

```shell
仅有i18n错误
es-BLVcOTW8.js:85 <error> [i18n:label] Missing key b255de1c-a3ab-4cb2-8941-609d686fe368
processLog @ es-BLVcOTW8.js:85
error @ es-BLVcOTW8.js:116
getLabel @ store-DXyPvFNZ.js:23539
getProviderLabel @ store-DXyPvFNZ.js:23610
(anonymous) @ store-DXyPvFNZ.js:264599
CodeToolsPage @ store-DXyPvFNZ.js:264584
renderWithHooks @ client-DNI3-9fK.js:2858
updateFunctionComponent @ client-DNI3-9fK.js:4242
beginWork @ client-DNI3-9fK.js:4632
performUnitOfWork @ client-DNI3-9fK.js:6607
workLoopSync @ client-DNI3-9fK.js:6511
renderRootSync @ client-DNI3-9fK.js:6495
performWorkOnRoot @ client-DNI3-9fK.js:6253
performSyncWorkOnRoot @ client-DNI3-9fK.js:7061
flushSyncWorkAcrossRoots_impl @ client-DNI3-9fK.js:6984
processRootScheduleInMicrotask @ client-DNI3-9fK.js:7004
(anonymous) @ client-DNI3-9fK.js:7065
es-BLVcOTW8.js:85 <error> [i18n:label] Missing key b255de1c-a3ab-4cb2-8941-609d686fe368
processLog @ es-BLVcOTW8.js:85
error @ es-BLVcOTW8.js:116
getLabel @ store-DXyPvFNZ.js:23539
getProviderLabel @ store-DXyPvFNZ.js:23610
(anonymous) @ store-DXyPvFNZ.js:264599
CodeToolsPage @ store-DXyPvFNZ.js:264584
renderWithHooks @ client-DNI3-9fK.js:2858
updateFunctionComponent @ client-DNI3-9fK.js:4242
beginWork @ client-DNI3-9fK.js:4632
performUnitOfWork @ client-DNI3-9fK.js:6607
workLoopSync @ client-DNI3-9fK.js:6511
renderRootSync @ client-DNI3-9fK.js:6495
performWorkOnRoot @ client-DNI3-9fK.js:6253
performSyncWorkOnRoot @ client-DNI3-9fK.js:7061
flushSyncWorkAcrossRoots_impl @ client-DLVcOTW8.js:6984
processRootScheduleInMicrotask @ client-DNI3-9fK.js:7004
(anonymous) @ client-DNI3-9fK.js:7065
```

### Additional Context

目录的结构见附件
[tree.txt](https://github.com/user-attachments/files/24232045/tree.txt)
环境说明：
我使用powershell启动项目
我自己启动成功用的是 powershell 7
cherry studio使用系统原装的powershell启动的claude code。对应的系统版本为：windows 11 25h2
额外说明：
我只在这个目录触发了这个问题，上一级目录和其他目录没有发现问题，但是子目录也有这个问题
</details>

### PR DESCRIPTION
**Pull request by GeorgeDong32**
### What this PR does

Before this PR:
- CLI tools could fail to start when run from directories containing special characters (e.g., parentheses).

After this PR:
- Windows .bat generation uses pushd/popd instead of cd to better handle special characters and restore the original directory.
- Directory existence is validated before attempting to change directory.
- PowerShell path escaping improved by wrapping paths in double quotes and escaping internal quotes.
- Error handling enhanced with more detailed diagnostic messages when directory change fails.

Fixes #11995

### Why we need it and why it was done in this way

The following tradeoffs were made:
- Using pushd/popd adds a dependency on built-in shell behavior but ensures correct directory handling and cleanup across Windows shells.

The following alternatives were considered:
- Continue using cd with complex escaping (rejected due to unreliable behavior with special characters).

Links to places where the discussion took place: 

### Breaking changes

None

### Special notes for your reviewer

- Verify Windows .bat and PowerShell scripts in directories with various special characters (e.g., parentheses, quotes, spaces).

### Checklist

- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: Write code that humans can understand and keep it simple
- [ ] Documentation: User-guide update not required

Release note

```release-note
fix: CLI tools on Windows now correctly handle paths with special characters by using pushd/popd, validating directories, improving PowerShell escaping, and providing better diagnostics.
```

### CODE REVIEW

**Comment by kangfenmao** [comment]
> [!NOTE]
> This comment was translated by Claude.

Not working.

image

main branch

image

---

<details>
<summary>Original Content</summary>

not woking

image

main branch

image

</details>

**Comment by GeorgeDong32** [comment]
> [!NOTE]
> This comment was translated by Claude.

I'll test it again tonight. I can launch it with PowerShell/Windows Terminal/Alacritty on my side.

---
<details>
<summary>Original Content</summary>

我晚上再测一下，我这边选PowerShell/WIndows Terminal/Alacritty 都能拉起
</details>

**Comment by GeorgeDong32** [comment]
> [!NOTE]
> This comment was translated by Claude.

I tested on Windows and most paths are handled correctly now. Except for some versions of Qwen Code that have compatibility issues with Bun and cannot start, everything else works normally.

---
<details>
<summary>Original Content</summary>

我这边测Windows上能正常处理大部分路径了，除了Qwen Code部分版本用Bun有兼容性问题启动不了，其它都挺正常的
</details>

**Comment by DeJeune** [comment]
> [!NOTE]
> This comment was translated by Claude.

Resolve merge conflicts.

---
<details>
<summary>Original Content</summary>

解下冲突
</details>

File: src/main/services/CodeToolsService.ts [hunk 1]
```diff
@@ -717,42 +717,53 @@ class CodeToolsService {
...
           'echo Cherry Studio CLI Tool Launcher',
-          `echo Tool: ${cliTool}`,
-          `echo Directory: ${directory}`,
+          `echo Tool: ${escapeBatchText(cliTool)}`,
+          `echo Directory: ${escapeBatchText(directory)}`,
           `echo Time: ${new Date().toLocaleString()}`,
           'echo ================================================',
           '',
+          ':: Verify directory exists (using single-line format to avoid () parsing issues)',
+          `if not exist "${directory.replace(/%/g, '%%')}" echo ERROR: Directory does not exist & echo Target: ${escapeBatchText(directory)} & pause & exit /b 1`,
```
Comment (beyondkmp) [inline src/main/services/CodeToolsService.ts]: Using if not exist ... echo ... & pause & exit /b 1 makes only the first echo conditional in CMD; pause and exit /b 1 run unconditionally. This causes the script to stop before running the CLI command even when the directory exists. Please switch to a control-flow form where the whole failure branch is conditional (for example: if not exist "..." goto :missing_dir).

File: src/main/services/CodeToolsService.ts [hunk 2]
```diff
@@ -777,14 +788,25 @@ class CodeToolsService {
...
             logger.warn(`Failed to cleanup temp bat file: ${error}`)
           }
-        }, 10 * 1000) // Delete temp file after 10 seconds
+        }
+
+        // Set timeout for cleanup
+        setTimeout(cleanup, 30 * 1000) // Delete temp bat file after 30 seconds
+
+        // Ensure cleanup on process exit
+        process.on('exit', cleanup)
```
Comment (beyondkmp) [inline src/main/services/CodeToolsService.ts]: This adds a new process-level exit listener on every run invocation and never removes it. Over time this accumulates listeners, can trigger MaxListenersExceededWarning, and keeps closures alive longer than needed. Consider using process.once for a shared cleanup handler or removing the listener after cleanup runs.

File: src/main/services/CodeToolsService.ts [hunk 3]
```diff
@@ -717,42 +717,53 @@ class CodeToolsService {
...
+          '',
           ':: Change to target directory',
-          `cd /d "${directory}" || (`,
-          '  echo ERROR: Failed to change directory',
-          `  echo Target directory: ${directory}`,
-          '  pause',
-          '  exit /b 1',
-          ')',
+          `pushd "${directory.replace(/%/g, '%%')}"`,
+          'if %ERRORLEVEL% neq 0 echo ERROR: Failed to change directory & pause & exit /b 1',
```
Comment (beyondkmp) [inline src/main/services/CodeToolsService.ts]: Same CMD control-flow issue here: with if %ERRORLEVEL% neq 0 echo ... & pause & exit /b 1, only the first echo is guarded by the if. The pause/exit run regardless of ERRORLEVEL, so the script exits before executing the command even after a successful pushd.

**Comment by kangfenmao** [comment]
@beyondkmp It can be reviewed again
