### PR TITLE
fix(aiCore): improve PDF processing robustness for aggregator providers

### LINKED ISSUE #13603: [Bug]: native PDF file uploading is unavailable for some providers
### Issue Checklist

- [x] I understand that issues are for reporting problems and requesting features, not for off-topic comments, and I will provide as much detail as possible to help resolve the issue.
- [x] I have checked the pinned issues and searched through the existing [open issues](https://github.com/CherryHQ/cherry-studio/issues), [closed issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [discussions](https://github.com/CherryHQ/cherry-studio/discussions) and did not find a similar suggestion.
- [x] I have provided a short and descriptive title so that developers can quickly understand the issue when browsing the issue list, rather than vague titles like "A suggestion" or "Stuck."
- [x] The latest version of Cherry Studio does not include the feature I am suggesting.

### Platform

macOS

### Version

v1.8.0

### Bug Description

Native PDF file upload works with some builtin providers (e.g., Google/Gemini) but fails on others (e.g., cherryin) even though the underlying model supports PDF input.

### Root Cause

`supportsPdfInput()` in `modelCapabilities.ts` checks against an AI SDK provider ID whitelist:
```
'openai', 'azure-openai', 'anthropic', 'google', 'google-generative-ai', 'google-vertex', 'bedrock', 'amazon-bedrock'
```

The cherryin provider has type `new-api`, so `getAiSdkProviderId()` does not resolve to any of these whitelisted IDs. As a result, `supportsPdfInput()` returns `false` for cherryin, and the PDF falls back to text extraction instead of being sent natively.

### Expected Behavior

PDF files should be sent natively (as file/document parts) for any provider whose underlying model API supports PDF input, including `new-api` type providers like cherryin that proxy to PDF-capable APIs.

### Relevant Code

- `src/renderer/src/aiCore/prepareParams/modelCapabilities.ts` → `supportsPdfInput()` (whitelist check)
- `src/renderer/src/aiCore/provider/factory.ts` → `getAiSdkProviderId()` (provider ID resolution)
- `src/renderer/src/aiCore/prepareParams/fileProcessor.ts:205` (PDF handling decision point)

### LINKED ISSUE #13638: [Bug]: PDF files silently dropped from messages — 5 failure paths with no user notification
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

macOS

### Version

v1.8.1

### Bug Description

PDF file processing has **5 silent failure paths** that cause files to be silently dropped from messages without any user notification. Users experience this as "PDF not working" or "no response" when uploading PDFs, especially files larger than ~10MB.

This is a consolidation of multiple related reports: #13422, #13603, #12890, #13416, #11841, #13105.

#### Root Cause Analysis (Source Code)

**5 Silent Failure Paths Identified:**

| # | Location | Trigger | Behavior |
|---|----------|---------|----------|
| 1 | `fileProcessor.ts:219` | PDF exceeds provider size limit | `logger.warn()` only — file silently excluded from request |
| 2 | `fileProcessor.ts:216` | Gemini/OpenAI File API upload fails | Silent fallback to text extraction — no UI notification |
| 3 | `fileProcessor.ts:76` | Text extraction fails (officeparser error/OOM) | `logger.warn()` only — file silently excluded |
| 4 | `messageConverter.ts:159` | Both native processing AND text extraction fail | File omitted from message entirely — no notification |
| 5 | `FileStorage.ts:521` | officeparser throws on corrupted/complex PDF | Error may propagate or be swallowed depending on caller |

**Processing Pipeline:**
```
User uploads PDF
  → supportsPdfInput(model)?
    → Yes: Check file size vs getFileSizeLimit()
      → Within limit: base64 encode and send ✅
      → Exceeds limit + supportsLargeFileUpload(): Try File API
        → Success ✅
        → Failure: Silent fallback to text extraction ⚠️ (path #2)
      → Exceeds limit + no large file support: return null → silent fallback ⚠️ (path #1)
    → No: Direct text extraction
      → Success: Send as text part ✅
      → Failure: File silently dropped ❌ (path #3 → #4)
```

**Provider Whitelist Issue** (related to #13603):
`supportsPdfInput()` (`modelCapabilities.ts:55-68`) hardcodes a provider ID whitelist: `openai`, `azure-openai`, `anthropic`, `google`, `google-generative-ai`, `google-vertex`, `bedrock`. Aggregator providers (CherryIN, NewAPI-type with `new-api` type) are NOT whitelisted, so ALL PDFs fall back to text extraction regardless of the underlying model's capability.

**Size Limits Are API Limits, NOT Cherry Studio Limits:**
- Anthropic: 32MB (API doc)
- Gemini inline_data: 20MB (File API supports up to 2GB)
- Other providers: Infinity (code returns `Infinity` at `modelCapabilities.ts:112`)
- There is NO hardcoded 10MB limit in Cherry Studio — the "10MB failure" users report is caused by text extraction failing on large PDFs (officeparser OOM/timeout)

### Steps To Reproduce

1. Upload a PDF file >10MB in a conversation using any provider
2. Send a message asking about the PDF content
3. The model responds as if no PDF was attached
4. No error message, toast, or warning is shown
5. Only `logger.warn()` entries appear in log files

### Expected Behavior

1. When a PDF cannot be processed, show a clear Toast notification to the user
2. Explain WHY it failed (size limit, extraction error, unsupported provider)
3. Suggest alternatives (use a different provider, reduce file size, try text-only mode)
4. Never silently drop files from a message

### Relevant Log Output

```shell
[warn] PDF file document.pdf exceeds size limit (15728640 > 10485760)
[warn] Failed to extract text from document: Error: officeparser timeout
[warn] File document.pdf could not be processed in any format, skipping
```

### Suggested Fix (3 Layers)

---

#### Layer 1 — Toast Error Notification (Quick Win, v1.8.1)

Use the existing `window.toast` API (`components/TopView/toast.tsx`) to add user-facing notifications at all 5 silent failure paths. The `window.toast` API supports `error`/`warning`/`info`/`success`/`loading` types with `{ title, description }` structured content.

**Path #1: PDF exceeds size limit → `window.toast.warning`**

```typescript
// fileProcessor.ts:219 — Currently: logger.warn() → return null (silent)
logger.warn(`PDF file ${file.origin_name} exceeds size limit (${file.size} > ${fileSizeLimit})`)
window.toast.warning({
  title: i18n.t('chat.input.pdf.exceeds_limit', {
    name: file.origin_name,
    size: formatBytes(file.size),
    limit: formatBytes(fileSizeLimit)
  }),
  description: i18n.t('chat.input.pdf.exceeds_limit_hint'),
  timeout: 5000
})
```

Toast preview:
> ⚠️ **'report.pdf' (45MB) exceeds model limit (32MB)**
> Automatically switched to text extraction. For native PDF parsing, use a model that supports large files (e.g., Gemini) or reduce file size.

**Path #2: File API upload failed → `window.toast.info`**

```typescript
// fileProcessor.ts:216 — Currently: logger.warn() → silent fallback to text extraction
logger.warn(`Failed to upload large PDF ${file.origin_name} via File API`, error as Error)
window.toast.info({
  title: i18n.t('chat.input.pdf.upload_failed_fallback', { name: file.origin_name }),
  description: i18n.t('chat.input.pdf.upload_failed_fallback_hint'),
  timeout: 3000
})
```

Toast preview:
> ℹ️ **'report.pdf' failed to upload via File API**
> Automatically switched to text extraction. Some formatting may be lost.

**Path #3: Text extraction failed → `window.toast.error`**

```typescript
// fileProcessor.ts:76 — Currently: logger.warn() → return null (file excluded)
logger.warn(`Failed to extract text from ${file.origin_name}`, error as Error)
window.toast.error({
  title: i18n.t('chat.input.pdf.extract_failed', { name: file.origin_name }),
  description: i18n.t('chat.input.pdf.extract_failed_hint'),
  timeout: 8000
})
```

Toast preview:
> ❌ **'report.pdf' text extraction failed**
> File not included in message. Possible causes: file too large, scanned/image-based PDF, or corrupted format. Try using a model with native PDF support (GPT-4o / Claude / Gemini).

**Path #4: Both native + text extraction failed → `window.toast.error`**

```typescript
// messageConverter.ts:159 — Currently: logger.warn() → file removed from message entirely
logger.warn(`File ${file.origin_name} could not be processed in any format, skipping`)
window.toast.error({
  title: i18n.t('chat.input.pdf.process_failed', { name: file.origin_name }),
  description: i18n.t('chat.input.pdf.process_failed_hint'),
  timeout: 8000
})
```

Toast preview:
> ❌ **'report.pdf' processing failed, file not sent**
> File could not be processed in any format and was removed from the message. Try: check if file is corrupted, use a smaller file, or switch to a model with native PDF support.

**Toast Behavior:**

| Scenario | Toast Type | Duration | Reason |
|----------|-----------|----------|--------|
| Size limit exceeded, fallback to text | `warning` | 5s | Degraded but still functional |
| File API failed, fallback to text | `info` | 3s | Auto-degraded, low priority |
| Text extraction failed | `error` | 8s | File lost, needs attention |
| Both methods failed, file not sent | `error` | 8s | Most severe, user must know |
| Multiple files fail simultaneously | Individual toasts | — | Ant Design Message auto-stacks |

**i18n Keys:**

```json
// zh-cn.json
"chat.input.pdf.exceeds_limit": "「{{name}}」({{size}}) 超出当前模型限制 ({{limit}})",
"chat.input.pdf.exceeds_limit_hint": "已自动转为文本提取模式。如需原生 PDF 解析，请使用支持大文件的模型（如 Gemini）或缩小文件",
"chat.input.pdf.upload_failed_fallback": "「{{name}}」无法通过 File API 上传",
"chat.input.pdf.upload_failed_fallback_hint": "已自动转为文本提取模式，部分格式信息可能丢失",
"chat.input.pdf.extract_failed": "「{{name}}」文本提取失败",
"chat.input.pdf.extract_failed_hint": "文件未包含在消息中。可能原因：文件过大、扫描件/图片型 PDF 或格式损坏。建议使用支持原生 PDF 的模型（GPT-4o / Claude / Gemini）",
"chat.input.pdf.process_failed": "「{{name}}」处理失败，文件未发送",
"chat.input.pdf.process_failed_hint": "文件无法以任何方式处理，已从消息中移除。建议：检查文件是否损坏、尝试更小的文件、或切换到支持原生 PDF 的模型"

// en-us.json
"chat.input.pdf.exceeds_limit": "'{{name}}' ({{size}}) exceeds model limit ({{limit}})",
"chat.input.pdf.exceeds_limit_hint": "Automatically switched to text extraction. For native PDF parsing, use a model that supports large files (e.g., Gemini) or reduce file size",
"chat.input.pdf.upload_failed_fallback": "'{{name}}' failed to upload via File API",
"chat.input.pdf.upload_failed_fallback_hint": "Automatically switched to text extraction. Some formatting may be lost",
"chat.input.pdf.extract_failed": "'{{name}}' text extraction failed",
"chat.input.pdf.extract_failed_hint": "File not included in message. Possible causes: file too large, scanned/image-based PDF, or corrupted format. Try using a model with native PDF support (GPT-4o / Claude / Gemini)",
"chat.input.pdf.process_failed": "'{{name}}' processing failed, file not sent",
"chat.input.pdf.process_failed_hint": "File could not be processed in any format and was removed from the message. Try: check if file is corrupted, use a smaller file, or switch to a model with native PDF support"
```

---

#### Layer 2 — Dynamic PDF Capability Detection (v1.8.1)

**Recommended: Model ID regex matching** (same pattern as `isVisionModel()`)

Instead of hardcoding provider IDs in `supportsPdfInput()`, detect PDF capability by matching model IDs — this automatically supports ALL aggregator providers (CherryIN, NewAPI, OpenRouter, etc.) without maintaining a provider whitelist.

This follows the proven 3-layer detection architecture already used by `isVisionModel()` (`vision.ts:249-267`):

```typescript
// Layer 1: User manual override (via ModelCapability)
// Layer 2: Model ID regex matching (provider-independent)
// Layer 3: Provider whitelist fallback (existing logic)

const PDF_CAPABLE_MODELS = [
  // OpenAI — GPT-4o+ supports PDF
  'gpt-4o(?:-[\\w-]+)?',
  'gpt-4\\.1(?:-[\\w-]+)?',
  'gpt-4\\.5(?:-[\\w-]+)?',
  'gpt-5(?:-[\\w-]+)?',
  'chatgpt-4o(?:-[\\w-]+)?',
  'o1(?:-[\\w-]+)?',
  'o3(?:-[\\w-]+)?',
  'o4(?:-[\\w-]+)?',
  // Anthropic — Claude 3+ all series
  'claude-3(?:-[\\w-]+)?',
  'claude-haiku-4(?:-[\\w-]+)?',
  'claude-sonnet-4(?:-[\\w-]+)?',
  'claude-opus-4(?:-[\\w-]+)?',
  // Google — Gemini 1.5+ all series
  'gemini-1\\.5(?:-[\\w-]+)?',
  'gemini-2\\.0(?:-[\\w-]+)?',
  'gemini-2\\.5(?:-[\\w-]+)?',
  'gemini-3(?:\\.\\d)?-(?:flash|pro)(?:-[\\w-]+)?',
  'gemini-(?:flash|pro|flash-lite)-latest',
  'gemini-exp(?:-[\\w-]+)?',
  // Alibaba — Qwen document series
  'qwen-long', 'qwen-doc(?:-[\\w-]+)?',
  'qwen-vl(?:-[\\w-]+)?', 'qwen2\\.5-vl(?:-[\\w-]+)?', 'qwen3-vl(?:-[\\w-]+)?',
]

const PDF_EXCLUDED_MODELS = [
  'gpt-4-\\d+-preview',  // Old GPT-4 variants
  'gpt-4-turbo-preview', 'gpt-4-32k', 'gpt-4-\\d+',
  'o1-mini',  // o1-mini doesn't support file input
]

const PDF_CAPABLE_REGEX = new RegExp(
  `\\b(?!(?:${PDF_EXCLUDED_MODELS.join('|')})\\b)(${PDF_CAPABLE_MODELS.join('|')})\\b`, 'i'
)

export function supportsPdfInput(model: Model): boolean {
  // Layer 1: User override (v2.0.0 — requires ModelType expansion)
  const userOverride = isUserSelectedModelType(model, 'pdf')
  if (userOverride !== undefined) return userOverride

  // Layer 2: Model ID regex — works across ALL providers
  const modelId = getLowerBaseModelName(model.id)
  if (PDF_CAPABLE_REGEX.test(modelId)) return true

  // Layer 3: Provider whitelist fallback (existing logic)
  return modelSupportValidator(model, {
    supportedModels: ['qwen-long', 'qwen-doc'],
    supportedProviders: [
      'openai', 'azure-openai', 'anthropic',
      'google', 'google-generative-ai', 'google-vertex',
      'bedrock', 'amazon-bedrock'
    ]
  })
}
```

**Why regex matching > provider whitelist:**

| Dimension | Provider whitelist (current) | Model ID regex (proposed) |
|-----------|------------------------------|--------------------------|
| Aggregator providers | Must add each one manually | Auto-support via model name |
| New provider launches | Must add to whitelist | Auto-detected |
| User custom models | Not supported | Supported (user override) |
| Maintenance cost | High (provider list grows) | Medium (regex list, same as vision) |
| Code pattern consistency | Inconsistent | Same as `isVisionModel()` |

**How it solves the aggregator problem:**
```
User selects claude-3.5-sonnet on CherryIN
  → model.id = "claude-3.5-sonnet", model.provider = "cherryin"
  → Current: cherryin not in whitelist → ❌ falls back to text extraction
  → Proposed: PDF_CAPABLE_REGEX.test("claude-3.5-sonnet") → ✅ native PDF

User selects openai/gpt-4o on OpenRouter
  → model.id = "openai/gpt-4o"
  → getLowerBaseModelName() → "gpt-4o"
  → PDF_CAPABLE_REGEX.test("gpt-4o") → ✅ native PDF
```

**Migration Plan:**
- **v1.8.1**: Add regex matching + provider whitelist (Layer 2 + Layer 3). Skip Layer 1 (user override) to avoid `ModelType` changes blocked by v2 restriction.
- **v2.0.0**: Add `'pdf'` to `ModelType`, enable user manual override in model settings UI, show PDF tag on model cards.

---

#### Layer 3 — Robust Large File Processing (v2.0.0)

1. **Timeout protection** for `officeparser` text extraction:
   ```typescript
   const timeout = file.size > 10 * MB ? 60_000 : 30_000
   return Promise.race([
     officeparser.parseOfficeAsync(filePath),
     new Promise((_, reject) => setTimeout(() => reject(new Error('PDF extraction timeout')), timeout))
   ])
   ```

2. **Page-range extraction** for oversized PDFs (extract first N pages instead of failing entirely)

3. **Upload-time size pre-check** via `window.toast.warning` when user selects a file exceeding the model's limit (before sending the message)

**Related Issues:** #13422, #13603, #12890, #13416, #11841, #13105
**Related PRs:** #12557 (feat(v2): Refactor File Processing — open)
**External feedback:** [linux.do thread](https://linux.do/t/topic/1783581) — community post about PDF >10MB parsing failures

### Additional Context

**Files to modify:**

| File | Change | Layer | Risk |
|------|--------|-------|------|
| `src/renderer/src/aiCore/prepareParams/fileProcessor.ts` | Add `window.toast` at 3 failure points | Layer 1 | Low |
| `src/renderer/src/aiCore/prepareParams/messageConverter.ts` | Add `window.toast.error` on dual failure | Layer 1 | Low |
| `src/renderer/src/aiCore/prepareParams/modelCapabilities.ts` | Rewrite `supportsPdfInput()` with regex | Layer 2 | Medium |
| `src/renderer/src/i18n/locales/zh-cn.json` | Add `chat.input.pdf.*` keys | Layer 1 | Low |
| `src/renderer/src/i18n/locales/en-us.json` | Add `chat.input.pdf.*` keys | Layer 1 | Low |
| `src/renderer/src/types/index.ts` | Add `'pdf'` to `ModelType` (v2.0.0) | Layer 2 | Medium (v2) |
| `src/main/services/FileStorage.ts` | Add timeout protection | Layer 3 | Medium |

### PR DESCRIPTION
**Pull request by EurFelux**
### What this PR does

Before this PR:
- `supportsPdfInput()` hardcodes a provider ID whitelist, causing aggregator providers (cherryin, new-api type) to always fall back to text extraction even when the underlying model supports native PDF.
- 5 places where PDF processing fails silently — files get dropped from messages with no user notification.

After this PR:
- Message preparation always produces the richest representation (FilePart) for all PDFs regardless of provider.
- A new `pdfCompatibilityPlugin` middleware handles compatibility by converting PDF FileParts to TextParts for providers that don't support native PDF input, using `pdf-parse` 2.x to extract text directly from FilePart data in the renderer process.
- All 5 failure paths now show user-facing toast notifications (warnings/errors).
- `pdf-parse` upgraded to 2.x (browser-compatible, TypeScript, extracts text from buffer/base64 directly).
- New shared utility `extractPdfText()` for PDF text extraction from any data format.

Fixes #13603, fixes #13638

### Why we need it and why it was done in this way

The following tradeoffs were made:
- The plugin uses `provider.type` (API protocol) instead of `getAiSdkProviderId()` to determine PDF support, because aggregator providers (cherryin, new-api, gateway) resolve to non-standard AI SDK IDs but speak standard protocols that support PDF.
- `pdf-parse` 2.x is used directly in the renderer process to extract text from base64 PDF data, eliminating the need for IPC calls or providerOptions workarounds.
- The plugin runs for every request but short-circuits immediately for supported providers (Set lookup).

The following alternatives were considered:
- Extending the whitelist to cover more providers — rejected because it's a whack-a-mole approach.
- Using `getAiSdkProviderId()` — rejected because it returns unreliable IDs for aggregator providers.
- Pre-extracting text in fileProcessor and passing via providerOptions — rejected as it misuses providerOptions and adds unnecessary IO for native providers.
- Adding IPC methods for buffer-based text extraction — rejected as pdf-parse 2.x runs directly in renderer.

Links to places where the discussion took place:
- #13603 (provider whitelist issue)
- #13638 (silent failure paths)

### Breaking changes

None. This is a transparent improvement — providers that previously supported native PDF still get FileParts, and providers that didn't now get TextParts instead of silently dropped files.

### Special notes for your reviewer

- `pdf-parse` upgraded from 1.1.1 to 2.4.5. The existing patch (`patches/pdf-parse-npm-1.1.1-04a6109b2a.patch`) is for the indirect dependency (via `office-text-extractor`) and remains untouched.
- `@langchain/community` has a peer dep on `pdf-parse@1.1.1` but only `VoyageEmbeddings` is imported from it — `PDFLoader` is not used, so the peer warning is harmless.
- **NOTE**: The `pdf-parse` peer dependency warning for `@langchain/community` is safe **only** when `PDFLoader` is not being used. If `PDFLoader` is ever imported in the future, this incompatibility must be addressed.
- `qwen-long`/`qwen-doc` models use `handleLargeFileUpload` → `fileid://` reference → `SystemModelMessage`. They never reach the plugin as FilePart, so they are unaffected.
- Non-PDF documents (Word, Excel) still return `null` from `convertFileBlockToFilePart` and use the text fallback path unchanged.
- `isPdfFilePart` is a proper TypeScript type guard. No `as` type assertions in the plugin code.

### Checklist

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. Check this only when the PR introduces or changes a user-facing feature or behavior.
- [x] Self-review: I have reviewed my own code (e.g., via [`/gh-pr-review`](/.claude/skills/gh-pr-review/SKILL.md), `gh pr diff`, or GitHub UI) before requesting review from others

### Release note

```release-note
Improved PDF file processing: aggregator providers (cherryin, new-api, etc.) now correctly handle native PDF input instead of always falling back to text extraction. Added user-facing notifications when PDF processing fails instead of silently dropping files.
```

### CODE REVIEW

**Comment by EurFelux** [comment]
## Self-Review: PR #13641 (Updated — includes commit `280096c`)

### Changes Since Last Review

Major refactoring in commit `280096c`:
- **pdf-parse upgraded from 1.x to 2.x** — new API using `PDFParse` class
- **New shared utility `packages/shared/utils/pdf.ts`** — `extractPdfText()` works in both Node.js and browser
- **Plugin now extracts text directly** from base64 data via pdf-parse, instead of relying on pre-extracted text in `providerOptions`
- **fileProcessor.ts simplified** — no more pre-extraction or `providerOptions.cherryStudio.pdfTextContent` hack
- Tests updated accordingly

This is a cleaner design — text extraction now happens at the right layer (the plugin that needs it), not upstream.

### Issues

#### 1. Bundle size impact of pdfjs-dist in renderer (Medium)

pdf-parse 2.x depends on `pdfjs-dist@5.4.296`, which is a ~2MB+ library. Since the plugin runs in the renderer process and imports `@shared/utils/pdf`, pdfjs-dist will be bundled into the renderer bundle.

Previously, PDF text extraction happened via IPC (`window.api.file.read()`) in the main process, keeping pdfjs-dist out of the renderer. Consider:
- Whether the bundle size increase is acceptable
- Whether the extraction could still be done via IPC for non-native providers to keep the renderer bundle lean
- Running `pnpm analyze:renderer` to measure actual impact

#### 2. Dead code: `supportsPdfInput` and `PDF_NATIVE_PROVIDER_IDS` (Low — unchanged from previous review)

Still no consumers for these exports after `fileProcessor.ts` removed its import. Consider removing or marking as `@deprecated`.

### Verified — No Issues

- **extractPdfText utility**: Well-designed with proper `destroy()` cleanup in `finally` blocks, handles multiple input types (base64, Uint8Array, ArrayBuffer, URL)
- **Type safety improved**: `isPdfFilePart()` type guard is cleaner than the previous `any` casts
- **`hasPdf` early-exit**: Smart optimization to avoid creating new objects for messages without PDFs
- **Tests**: Both the shared utility tests (with real minimal PDF) and plugin tests (with mocks) are solid
- **Toast notifications**: All failure paths covered
- **Plugin execution order**: `enforce: 'pre'` remains correct

---

**Resolution:**
- Issue 1 (bundle size): Accepted — pdf-parse 2.x in renderer is acceptable for now.
- Issue 2 (dead code): Fixed in commit d7ab2dee8 — removed `supportsPdfInput` and `PDF_NATIVE_PROVIDER_IDS`.

File: packages/shared/utils/pdf.ts [hunk 1]
```diff
@@ -0,0 +1,39 @@
+import { PDFParse } from 'pdf-parse'
+
+/**
+ * Extract text content from PDF data.
+ * Works in both Node.js and browser environments (pdf-parse 2.x).
+ *
+ * @param data - PDF content as Uint8Array, ArrayBuffer, base64-encoded string, or URL
+ * @returns Extracted text content
+ */
+export async function extractPdfText(data: Uint8Array | ArrayBuffer | string | URL): Promise<string> {
```
Comment (beyondkmp) [inline packages/shared/utils/pdf.ts:10]: > [!NOTE]
> This comment was translated by Claude.

Wouldn't it be better to put this in the main process? Running it with Node.js might provide better performance. If the browser needs it, just call directly through IPC.

---
<details>
<summary>Original Content</summary>

这个放到main process 是不是更好，nodejs来运行，性能可能会更好，如果browser需要的话，直接通过ipc调用。

</details>

File: packages/shared/utils/pdf.ts [hunk 2]
```diff
@@ -0,0 +1,39 @@
+import { PDFParse } from 'pdf-parse'
```
Comment (beyondkmp) [inline packages/shared/utils/pdf.ts:1]: > [!NOTE]
> This comment was translated by Claude.

Can this library only extract text from normal PDFs? If the PDF is not normal, such as a scanned document, it probably cannot extract any text.

---
<details>
<summary>Original Content</summary>

这个库是不是只能提取正常的pdf的，如果是不太正常的，比如扫描的，应该是提取不了任何文字出来

</details>

File: packages/shared/utils/pdf.ts (hunk 1 above)
Comment (EurFelux) [reply packages/shared/utils/pdf.ts:10]: > [!NOTE]
> This comment was translated by Claude.

Both are compatible, but going through IPC requires a bit more modification.

---
<details>
<summary>Original Content</summary>

都兼容，走 ipc 要多改一点
</details>

File: packages/shared/utils/pdf.ts (hunk 2 above)
Comment (EurFelux) [reply packages/shared/utils/pdf.ts:1]: > [!NOTE]
> This issue/comment/review was translated by Claude.

This requires OCR

---
<details>
<summary>Original Content</summary>

这种要走 ocr
</details>

File: packages/shared/utils/pdf.ts (hunk 1 above)
Comment (EurFelux) [reply packages/shared/utils/pdf.ts:10]: > [!NOTE]
> This comment was translated by Claude.

URL type cannot go through IPC, so it's handled in the renderer, other types go through IPC

---
<details>
<summary>Original Content</summary>

URL 类型走不了 ipc，放 renderer 处理了，其他类型走 ipc 了

</details>

Comment (DeJeune) [inline packages/shared/utils/pdf.ts:10]: > [!NOTE]
> This comment was translated by Claude.

Consider adding a TODO.

---
<details>
<summary>Original Content</summary>
可以加个TODO
</details>

File: src/renderer/src/aiCore/plugins/pdfCompatibilityPlugin.ts [hunk 3]
```diff
@@ -0,0 +1,103 @@
...
+ * because aggregator providers (cherryin, new-api, gateway) resolve to
+ * non-standard AI SDK IDs but still speak a protocol that supports PDF.
+ */
+const PDF_NATIVE_PROVIDER_TYPES = new Set<ProviderType>([
+  'openai', // OpenAI-compatible API (includes aggregators like cherryin)
+  'openai-response', // OpenAI Responses API
+  'anthropic', // Anthropic API
+  'gemini', // Google Gemini API
+  'azure-openai', // Azure OpenAI
+  'vertexai', // Google Vertex AI
```
Comment (DeJeune) [inline src/renderer/src/aiCore/plugins/pdfCompatibilityPlugin.ts:31]: > [!NOTE]
> This comment was translated by Claude.

Also aihubmix

---
<details>
<summary>Original Content</summary>
还有aihubmix
</details>

Comment (DeJeune) [reply src/renderer/src/aiCore/plugins/pdfCompatibilityPlugin.ts:31]: > [!NOTE]
> This comment was translated by Claude.

Of course, it's possible that by the time it reaches the downstream, it may already be actualProvider.

---
<details>
<summary>Original Content</summary>

当然可能走到下游已经是actualProvider了

</details>

File: packages/shared/utils/pdf.ts (hunk 1 above)
Comment (EurFelux) [reply packages/shared/utils/pdf.ts:10]: what todo

Comment (DeJeune) [reply packages/shared/utils/pdf.ts:10]: > [!NOTE]
> This comment was translated by Claude.

Just change it to OCR later.

---
<details>
<summary>Original Content</summary>
就是后面换成OCR
</details>

**Review by DeJeune — APPROVED** [review]
LGTM

File: packages/shared/utils/pdf.ts (hunk 1 above)
Comment (EurFelux) [reply packages/shared/utils/pdf.ts:10]: > [!NOTE]
> This comment was translated by Claude.

OCR should go through a service, not in this util. Let's keep this function pure, and also determining what scenarios need OCR is a problem in itself.

---
<details>
<summary>Original Content</summary>

OCR需要走service，不能放到这个util里。让这个函数保持pure吧，而且判断什么场景下需要ocr也是个问题

</details>

**Review by MyPrototypeWhat — APPROVED** [review]

**Comment by kangfenmao** [comment]
image

We need to see if this needs to be modified.

**Comment by EurFelux** [comment]
> [!NOTE]
> This comment was translated by Claude.

This only affects `pdf-parse@v1`; the directory structure in v2 is completely different. I'm also not entirely sure why this needs to be excluded, but it does not affect the operation of `pdf-parse@v2`.

---
<details>
<summary>Original Content</summary>

这个只影响`pdf-parse@v1`, v2的目录结构完全不同。我也不是很清楚为什么这里要排除掉，但不影响`pdf-parse@v2`的运行

</details>

**Comment by kangfenmao** [comment]
(index):10 <warn> [pdfCompatibilityPlugin] Failed to extract text from PDF somefile.pdf: Error: Error invoking remote method 'pdf:extractText': Error: Setting up fake worker failed: "Cannot find module '/Users/user/Code/cherry-studio/out/main/pdf.worker.mjs' imported from /Users/user/Code/cherry-studio/out/main/index.js".
