### PR TITLE
fix: 修复数据目录迁移的bug

### LINKED ISSUE #7389: [错误]: 数据目录自定义 resource busy or locked
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我的问题不是 [常见问题](https://github.com/CherryHQ/cherry-studio/issues/3881) 中的内容。
- [x] 我已经查看了 **置顶 Issue** 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。

### 平台

Windows

### 版本

v1.4.4

### 错误描述

修改目录时出现错误，尝试了本地目录和OneDrive目录
Image

### 重现步骤

1. 设置
2. 数据设置
3. 数据目录
4. 修改目录
5. 选择一个目录
6. 开启复制数据
7. 确认

### 预期行为

成功切换目录

### 相关日志输出

```shell
[2025-06-20 14:07:21.439] [error] Failed to copy user data: Error: EBUSY: resource busy or locked, copyfile '******\CherryStudio\Network\Cookies' -> '******\cherry-stuido-data\Network\Cookies'
    at async copyFile (node:internal/fs/promises:615:10)
    at async _copyFile (node:internal/fs/cp/cp:260:3)
    at async copyDir (node:internal/fs/cp/cp:320:19)
    at async mkDirAndCopy (node:internal/fs/cp/cp:309:3)
    at async copyDir (node:internal/fs/cp/cp:320:19)
    at async ******\cherry-studio\1.4.4\resources\app.asar\out\main\index.js:313581:7
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:89248)
```

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by beyondkmp**
### What this PR does

Before this PR:
1. 会在默认的app data目录产生一个Data文件，主要是initappdata的时机比import的还晚，import里面有一些初始化的会先去getappdata导致出问题了。
2. 如果有多个app同时运行，只要一个app设置了，其它app再启动也会用同样的。
3. 开发环境也会读取data config配置

After this PR:
1. 将initappdata移到最前面，确保最早初始化。
2. 配置更改为如下格式，可以确保多个app之间的数据不影响
3. 开发环境直接禁用data config配置。

其它小优化：
1. 在copy数据之前，先flush数据，会将storage/cookies的数据先flush硬盘，避免占用问题。
2. 新路径不为空的时候，弹出确认提示
3. 新路径不为空，默认不复制数据，需要用户自己打开。

Fixes #7389 #7373

### Why we need it and why it was done in this way

The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Breaking changes

If this PR introduces breaking changes, please describe the changes and the impact on users.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### Release note

```release-note

```

### CODE REVIEW

**Comment by beyondkmp** [comment]
打开多个mini app的时候去修改目录，会报下面的错误
“”“
16:13:55.828 > Failed to copy user data: Error: EBUSY: resource busy or locked, copyfile 'C:\Users\payne\cherry-test\Partitions\webview\Network\Cookies' -> 'C:\Users\payne\SynologyDrive\cherry-studio\Partitions\webview\Network\Cookies'
    at async copyFile (node:internal/fs/promises:615:10)
    at async _copyFile (node:internal/fs/cp/cp:260:3)
    at async copyDir (node:internal/fs/cp/cp:320:19)
    at async mkDirAndCopy (node:internal/fs/cp/cp:309:3)
    at async copyDir (node:internal/fs/cp/cp:320:19)
    at async mkDirAndCopy (node:internal/fs/cp/cp:309:3)
    at async copyDir (node:internal/fs/cp/cp:320:19)
    at async mkDirAndCopy (node:internal/fs/cp/cp:309:3)
    at async copyDir (node:internal/fs/cp/cp:320:19)
    at async C:\Users\payne\Code\cherry-studio\out\main\index.js:313806:7
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:89248)
”“”

**Comment by beyondkmp** [comment]
目前逻辑有修改：
1. 如果不选择复制数据，直接重启一次就生效。
2. 如果选择复制数据，重启app，复制数据，复制完成后再重启一次。这样可以避免各种各样的复制问题的。

**Comment by beyondkmp** [comment]
测试结果：

https://github.com/user-attachments/assets/e18587e4-4bd6-46a7-b890-d996a24989a7

File: src/main/bootstrap.ts [hunk 1]
```diff
@@ -0,0 +1,3 @@
+import { initAppDataDir } from './utils/file'
+
+process.env.NODE_ENV !== 'development' && initAppDataDir()
```
Comment (0xfullex) [inline src/main/bootstrap.ts]: 建议用isPackage来作为是否发布是发布的应用的判断

Comment (beyondkmp) [reply src/main/bootstrap.ts]: 很好的建议。fixed.

**Review by 0xfullex — APPROVED** [review]

**Comment by PaTTeeL** [comment]
> 目前逻辑有修改：
> 
> 1. 如果不选择复制数据，直接重启一次就生效。
> 2. 如果选择复制数据，重启app，复制数据，复制完成后再重启一次。这样可以避免各种各样的复制问题的。

这是第一次的弹窗
image

这是第二次的弹窗
image

windows x64便携版，从1.4.3升级1.4.5，乍一看是没有“ 1. 如果不选择复制数据，直接重启一次就生效。”这个选项的，我是进来看到这个pr才感觉会有二次弹窗，备份了以后才敢点确定的，感觉这两个弹窗顺序反了，选择新路径后先给出迁移模式的选择界面，选完以后再弹窗做覆盖或者保留的二次提示？

**Comment by beyondkmp** [comment]
@PaTTeeL 很好的建议，有修改在 #7471 了
