### PR TITLE
fix: inaccurate temperature param

### LINKED ISSUE #5733: [错误]: Gemini 2.5 系列模型（以及所有推理模型）使用 OpenAI 兼容格式的API时温度和topP设置无效
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我的问题不是 [常见问题](https://github.com/CherryHQ/cherry-studio/issues/3881) 中的内容。
- [x] 我已经查看了 **置顶 Issue** 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。

### 平台

Windows

### 版本

1.2.10

### 错误描述

Image
如图所示，Gemini 2.5 系列模型（包括 2.5 pro 和 2.5 flash ）在使用openai兼容格式的API时，不会上传用户手动设置的 temperature 参数和 topP 参数（API 供应商选择的是OpenAI）。
~~但是Gemini 2.5 系列模型以外的模型都是可以正常上传这两个参数的~~
不止Gemini 2.5 系列的模型，还有所有使用OpenAI兼容格式API的带有下图`推理`选项的模型

Image

### 重现步骤

1.在Cherry Studio助手设置里调整temperature和topP这两个参数
2.按Ctrl+shift+i
~~3.选择Gemini 2.5 系列的模型并向其发送任意消息~~
3.使用任意open兼容格式API下的推理模型，向其发送任意消息

### 预期行为

会正常上传temperature和topP参数

### 相关日志输出

```shell

```

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by DeJeune**
### What this PR does

根据模型名称判断是否支持温度

Before this PR:

温度判断不准确

After this PR:

温度判断准确

Fixes #5733 #5454

### Why we need it and why it was done in this way

The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Breaking changes

If this PR introduces breaking changes, please describe the changes and the impact on users.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### Release note

```release-note

```

### CODE REVIEW

File: src/renderer/src/providers/AiProvider/GeminiProvider.ts [hunk 1]
```diff
@@ -379,8 +379,8 @@ export default class GeminiProvider extends BaseProvider {
       safetySettings: this.getSafetySettings(),
       // generate image don't need system instruction
       systemInstruction: isGemmaModel(model) ? undefined : systemInstruction,
-      temperature: assistant?.settings?.temperature,
-      topP: assistant?.settings?.topP,
+      temperature: this.getTemperature(assistant, model),
```
Comment (MyPrototypeWhat) [inline src/renderer/src/providers/AiProvider/GeminiProvider.ts:382]: gemini temperature似乎始终是true？

Comment (DeJeune) [reply src/renderer/src/providers/AiProvider/GeminiProvider.ts:382]: image

昨天也测了一下
