### PR TITLE
fix: install or uninstall button state issues in plugin browser

### LINKED ISSUE #13093: [Bug]: PluginBrowser uninstalls single skill instead of entire package
Thank you for taking the time to fill out this bug report!
Before submitting this issue, please make sure that you have understood the [FAQ](https://docs.cherry-ai.com/question-contact/questions) and [Knowledge Science](https://docs.cherry-ai.com/question-contact/knowledge)

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform
macOS

### Version
latest

### Bug Description

In the PluginBrowser component (`PluginBrowser.tsx`), when uninstalling a plugin that is part of a plugin package (e.g., a package containing multiple skills), only a single skill is uninstalled instead of the entire package.

**Root Cause**: The `handleUninstall` function in `PluginBrowser.tsx` always calls `onUninstall(filename, type)` without checking if the plugin belongs to a package. It should call `onUninstallPackage(packageName)` when the plugin has a `packageName`.

**Expected Behavior**: When uninstalling a plugin that belongs to a package, the entire package should be uninstalled (all skills/plugins in that package), not just the single item.

**Current Behavior** (buggy):
- User clicks uninstall on a plugin that is part of a package
- Only that single plugin/skill is uninstalled
- The rest of the package remains installed

### Steps To Reproduce

1. Install a plugin package that contains multiple skills (e.g., `agent-sdk-dev`)
2. Go to the plugin browser in settings
3. Find one of the skills from that package
4. Click the uninstall button
5. Observe: Only that single skill is uninstalled, not the entire package

### Expected Behavior

When uninstalling a plugin that belongs to a package:
- Either uninstall the entire package at once, OR
- Show a confirmation dialog asking if user wants to uninstall the single item or the entire package

#### Architecture Issue

This bug highlights a deeper architecture problem: **`InstalledPluginsList` and `PluginBrowser` have duplicated but inconsistent plugin management logic**.

The `InstalledPluginsList` component already has the correct logic:
- It groups plugins by `packageName`
- It has a separate "Uninstall Package" button that calls `uninstallPackage`
- It distinguishes between single plugin uninstall and package uninstall

But `PluginBrowser` lacks this logic entirely.

#### Recommended Architecture Fix

Instead of fixing this bug in two places separately, consider creating a **shared hook or utility** that both components can use:

```typescript
// Proposed: shared hook usePluginUninstallLogic
const { handleUninstall, handleUninstallPackage } = usePluginUninstallLogic({
  onUninstall: (filename, type) => Promise<void>,
  onUninstallPackage: (packageName) => Promise<void>
})
```

This would ensure:
1. Consistent behavior between both components
2. Single source of truth for plugin management logic
3. Easier maintenance and testing

Related code location:
- `src/renderer/src/pages/settings/AgentSettings/components/PluginsSettings/components/PluginBrowser.tsx`
- `src/renderer/src/pages/settings/AgentSettings/components/PluginsSettings/components/InstalledPluginsList.tsx` (for reference - correct implementation)

### LINKED ISSUE #13094: [Bug]: Plugin install button changes back to Install instead of showing Uninstall after installation
Thank you for taking the time to fill out this bug report!
Before submitting this issue, please make sure that you have understood the [FAQ](https://docs.cherry-ai.com/question-contact/questions) and [Knowledge Science](https://docs.cherry-ai.com/question-contact/knowledge)

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that a rough idea of what to expect when flipping through the list developers can quickly identify of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform
macOS

### Version
latest

### Bug Description

In the PluginBrowser component, after successfully installing a plugin, the loading button does not change to "Uninstall" - it changes back to "Install" instead. This is caused by the installed state not being refreshed in time.

### Root Cause

The root cause is in `usePlugins.ts`, in the `executeAction` function:

```typescript
const executeAction = useCallback(
  async <TResult>(...): Promise<...> => {
    setLoading(true)
    try {
      const result = await action()
      if (result.success) {
        onSuccess?.()  // Called WITHOUT await!
        return { success: true, data: result.data as TResult }
      }
      // ...
    } finally {
      setLoading(false)
    }
  },
  [onSuccess]
)
```

The `onSuccess?.()` (which calls `refresh()`) is called **without await**, so when `handleInstall` awaits `onInstall()`, it only waits for the installation API to complete, not for the refresh to finish.

**Timeline of the bug**:
1. User clicks Install → `setLoading(true)` in `handleInstall`
2. `await onInstall()` completes → installation API done, but `refresh()` still running
3. `setLoading({ id: loadingKey, value: false })` executes immediately
4. At this point, `installedPlugins` still has old data (refresh not complete)
5. `isPluginInstalled(plugin)` returns `false`
6. Button shows "Install" instead of "Uninstall"

### Steps To Reproduce

1. Go to the plugin browser in settings
2. Find a plugin that is not installed
3. Click the Install button
4. Observe: After installation completes, the button changes back to "Install" instead of showing "Uninstall"

### Expected Behavior

After successful installation, the button should change to "Uninstall" to indicate the plugin is now installed.

### Additional Context

The same issue likely exists for uninstall operations.

### Suggested Fix

In `src/renderer/src/hooks/usePlugins.ts`, change `executeAction` to await `onSuccess?.()`:

```typescript
if (result.success) {
  await onSuccess?.()  // Add await here!
  return { success: true, data: result.data as TResult }
}
```

This ensures that when `onInstall()` returns, the `refresh()` has already completed, and `installedPlugins` will have the latest data.

Related code location:
- `src/renderer/src/hooks/usePlugins.ts:59-80` (executeAction function)
- `src/renderer/src/pages/settings/AgentSettings/components/PluginsSettings/components/PluginBrowser.tsx:181-193`

### PR DESCRIPTION
**Pull request by kovsu**
Fix #13093, Fix #13094 

除了这两个 Issue 提到的问题外，这个 PR 的还修复了一个问题就是点击安装 插件 A 后，插件 A 的按钮状态会变为 安装中，但是这时候如果去点击安装 插件 B，插件 A 的按钮状态就会变成 安装。

### CODE REVIEW

**Comment by EurFelux** [comment]
> [!NOTE]
> This issue/comment/review was translated by Claude.

#13095 addressed the installation status issue. The original plan was to continue fixing #13093 and #13094 after #13095 was merged. Please consider the solution based on #13095.

---
<details>
<summary>Original Content</summary>

#13095 处理了安装状态的问题。原本计划 #13093 与 #13094 在 #13095 合并以后继续修复。请基于 #13095 考虑修复方案。

</details>

File: src/renderer/src/pages/settings/AgentSettings/components/PluginsSettings/components/PluginBrowser.tsx [hunk 1]
```diff
@@ -51,7 +58,7 @@ export const PluginBrowser: FC<PluginBrowserProps> = ({ installedPlugins, onInst
   const activeType = kind ?? internalActiveType
   const showTypeTabs = kind === undefined
   const [sortOption, setSortOption] = useState<MarketplaceSort>('relevance')
-  const [actioningPlugin, setActioningPlugin] = useState<string | null>(null)
+  const [actioningPlugins, setActioningPlugins] = useState<Set<string>>(new Set())
```
Comment (EurFelux) [inline src/renderer/src/pages/settings/AgentSettings/components/PluginsSettings/components/PluginBrowser.tsx]: 该Set仍然是组件级别的。对于可能耗时较长的安装过程，如果用户关闭组件再打开，安装状态就会被重置。这正是我在 #13095 中解决的问题。

Comment (kovsu) [reply src/renderer/src/pages/settings/AgentSettings/components/PluginsSettings/components/PluginBrowser.tsx]: 那我等 #13095 合并吧

**Comment by EurFelux** [comment]
#13095 merged. Please merge/rebase main.

File: src/renderer/src/utils/createKeyedSignal.ts
Comment (kovsu) [inline src/renderer/src/utils/createKeyedSignal.ts:1]: 这个方法是为了解决这个问题：

1. 组件A挂载 → 点击安装 → API 请求发出
2. 切换页面 → 组件A卸载
3. 组件B挂载 → refresh_B() 获取列表 → 此时安装还没完成 → 显示"安装"
4. 安装完成 → onSuccess(refresh_A) → setState 到已卸载的组件A → 无效
5. 组件B 不知道安装已完成 → 一直显示"安装"

复现视频

https://github.com/user-attachments/assets/c05987c1-e1a1-46ca-88af-a5f0bcb77847

File: src/renderer/src/utils/createKeyedSignal.ts [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+      try {
+        cb()
+      } catch {
+        /* listener errors must not break the emit loop */
+      }
+    })
+  }
+
+  return { subscribe, emit }
+}
```
Comment (EurFelux) [inline src/renderer/src/utils/createKeyedSignal.ts]: **Suggestion: Use existing `EventEmitter` instead of introducing a new abstraction**

The project already has a well-established event pub/sub mechanism via `EventService.ts` (based on [Emittery](https://github.com/sindresorhus/emittery)):

```typescript
// src/renderer/src/services/EventService.ts
import Emittery from 'emittery'
export const EventEmitter = new Emittery()
```

It's used extensively throughout the codebase (20+ call sites). Introducing `createKeyedSignal` creates a **second event system** that serves the same purpose, which increases cognitive overhead for future contributors.

You could achieve the same result with:

```typescript
// In EventService.ts, add:
INSTALLED_PLUGINS_CHANGED: 'INSTALLED_PLUGINS_CHANGED',

// In useInstalledPlugins:
const unsubscribe = EventEmitter.on(
  EVENT_NAMES.INSTALLED_PLUGINS_CHANGED + ':' + agentId,
  refresh
)

// In usePluginActions:
EventEmitter.emit(EVENT_NAMES.INSTALLED_PLUGINS_CHANGED + ':' + agentId)
```

This pattern (dynamic key concatenation) is already used in the project, e.g. `LOCATE_MESSAGE + ':' + message.id` in `MessagesService.ts:89`.

Benefits:
- No new file needed
- Consistent with existing patterns
- All event names discoverable in one place (`EVENT_NAMES`)
- Emittery provides richer features (typed events, `once`, async support) for free

File: src/renderer/src/hooks/usePlugins.ts [hunk 3]
```diff
@@ -66,7 +74,7 @@ export function usePluginActions(agentId: string, onSuccess?: () => void) {
       try {
         const result = await action()
         if (result.success) {
-          onSuccess?.()
+          installedPluginsSignal.emit(agentId)
```
Comment (EurFelux) [inline src/renderer/src/hooks/usePlugins.ts]: **Potential issue: Race condition may still cause button flicker**

`emit()` synchronously triggers `refresh()`, but `refresh()` is async (it calls `window.api.claudeCodePlugin.listInstalled()`). The `executeAction` doesn't await the refresh completion before returning.

Timeline:
1. `install()` succeeds → `emit(agentId)` triggers `refresh()` (async, not awaited)
2. `executeAction` returns → caller's `finishLoading()` fires → spinner disappears
3. But `refresh()` hasn't completed yet → `installedPlugins` still has stale data → button briefly shows "Install"
4. `refresh()` completes → re-render → button changes to "Uninstall"

This is the same underlying timing issue from #13094 (the old `onSuccess?.()` was also fire-and-forget). The window is short, but on slow networks it could be noticeable.

If you switch to `EventEmitter` (Emittery), you get async listener support for free and could `await` the emit.

**Review by EurFelux — COMMENTED** [review]
Nice fix for #13093 and #13094! The signal-based decoupling of `usePluginActions` from `useInstalledPlugins` is a good design improvement, and the package uninstall logic is correct.

**Main suggestion:** Please consider using the existing `EventEmitter` (Emittery-based, in `EventService.ts`) instead of introducing `createKeyedSignal`. The project already has a well-established event system used in 20+ places — adding a second one increases cognitive overhead without clear benefit. See inline comment for a concrete migration path.

**Minor concern:** The race condition from #13094 may not be fully resolved since `emit()` triggers `refresh()` without awaiting it. Switching to Emittery would also help here, as it supports async listeners natively.
