### PR TITLE
fix: prevent empty baseURL/region string in Bedrock provider config

### LINKED ISSUE #14423: [Bug]: AWS Bedrock requests fail with "failed to fetch"
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

1.9.1

### Bug Description

AWS Bedrock requests always fail with a `failed to fetch` error when using the built-in AWS Bedrock provider with its default configuration. The root cause is likely that an empty string `apiHost` (the default value in `SYSTEM_PROVIDERS` config) is passed as `baseURL: ""` into `createAmazonBedrock()` from `@ai-sdk/amazon-bedrock`, causing every request to be sent to an invalid URL.

**Root cause analysis:**

The default AWS Bedrock provider config in `src/renderer/src/config/providers.ts` has `apiHost: ""`:

```typescript
'aws-bedrock': {
  id: 'aws-bedrock',
  apiKey: '',
  apiHost: '',   // ← empty string by default
  ...
}
```

In `buildBedrockConfig()` (`src/renderer/src/aiCore/provider/providerConfig.ts`), this empty string flows through as `ctx.baseConfig.baseURL = ""` and is spread directly into the provider settings:

```typescript
// authType === 'apiKey' path:
return { ...base, providerSettings: { ...ctx.baseConfig, region, apiKey: getAwsBedrockApiKey() } }
//                                    ^^^^^^^^^^^^^^^^
//                                    spreads baseURL: "" into providerSettings
```

Inside `@ai-sdk/amazon-bedrock`, the base URL is constructed as follows:

```typescript
const getBedrockRuntimeBaseUrl = () => {
  return withoutTrailingSlash(
    options.baseURL != null   // ← uses != null (loose), NOT !== undefined
      ? options.baseURL       // "" != null is TRUE, so "" is used as-is
      : `https://bedrock-runtime.${region}.amazonaws.com`
  ) ?? `https://bedrock-runtime.us-east-1.amazonaws.com`;
  //  ↑ this fallback also never triggers because withoutTrailingSlash("") returns ""
};
```

Because `"" != null` evaluates to `true` (loose equality), the SDK treats the empty string as a valid, intentional base URL override. `withoutTrailingSlash("")` returns `""`, and `"" ?? fallback` also keeps `""`. The final request URL becomes `""/model/{modelId}/converse` — an entirely invalid URL — causing the `failed to fetch` error.

The same issue likely affects both `apiKey` auth and `iam` auth paths. Additionally, if `region` is also left empty (the default is `""`), and `baseURL` were somehow fixed, the SDK would construct `https://bedrock-runtime..amazonaws.com` (missing the region segment), which is equally broken. Both values need to be guarded against empty strings.

### Steps To Reproduce

1. Open Cherry Studio (any recent version).
2. Go to **Settings → Providers**, find the built-in **AWS Bedrock** provider.
3. Set auth type to **API Key**, fill in a valid Bedrock API Key and a valid Region (e.g. `us-east-1`).
4. Add a AWS Bedrock model and send any message.
5. The request fails immediately with `failed to fetch`.

### Expected Behavior

When **API Host** is left empty (the default), the SDK should automatically construct the correct endpoint URL from the configured Region:
`https://bedrock-runtime.{region}.amazonaws.com`

### Relevant Log Output

```shell

```

### Additional Context

**Affected file:** `src/renderer/src/aiCore/provider/providerConfig.ts`, function `buildBedrockConfig()`

**Introduced by:** Likely to be the `refactor: migrate to ai sdk v6 Phase 3` commit (~2 weeks ago), which migrated Bedrock to use `@ai-sdk/amazon-bedrock` directly.

**Proposed fix** (2-line change):

```typescript
function buildBedrockConfig(ctx: BuilderContext): ProviderConfig<'bedrock'> {
  const authType = getAwsBedrockAuthType()
- const region = getAwsBedrockRegion()
+ const region = getAwsBedrockRegion() || undefined  // prevent empty string → malformed URL

  const base = { providerId: 'bedrock' as const, endpoint: ctx.endpoint }
+ // Empty string baseURL passes the SDK's `!= null` guard and is used as-is,
+ // resulting in invalid request URLs. Convert to undefined so the SDK
+ // constructs the correct endpoint from region automatically.
+ const baseURL = ctx.baseConfig.baseURL || undefined

  if (authType === 'apiKey') {
-   return { ...base, providerSettings: { ...ctx.baseConfig, region, apiKey: getAwsBedrockApiKey() } }
+   return { ...base, providerSettings: { ...ctx.baseConfig, baseURL, region, apiKey: getAwsBedrockApiKey() } }
  }
  return {
    ...base,
    providerSettings: {
      ...ctx.baseConfig,
+     baseURL,
      region,
      accessKeyId: getAwsBedrockAccessKeyId(),
      secretAccessKey: getAwsBedrockSecretAccessKey()
    }
  }
}
```

### PR DESCRIPTION
**Pull request by Tsudrat**
### What this PR does

Before this PR: When a user configures the built-in AWS Bedrock provider (leaving **API Host** blank, which is the default), every request fails immediately with `failed to fetch`. This happens regardless of whether API Key or IAM authentication is used, and regardless of whether the Region and credentials are correctly filled in.

After this PR: The SDK correctly constructs the endpoint URL from the configured Region automatically (e.g. `https://bedrock-runtime.us-east-1.amazonaws.com`), and requests should succeed normally.

Fixes #14423

### Why we need it and why it was done in this way

`buildBedrockConfig()` spreads `ctx.baseConfig` (which contains `baseURL: ""` when the user leaves API Host blank) directly into the `providerSettings` passed to `createAmazonBedrock()`.

Inside `@ai-sdk/amazon-bedrock`, the base URL selection logic uses a loose `!= null` check:

```/dev/null/sdk-snippet.js#L1-5
// Inside @ai-sdk/amazon-bedrock: bedrock-provider.ts
const getBedrockRuntimeBaseUrl = () => {
  return withoutTrailingSlash(
    options.baseURL != null        // "" != null → true (empty string passes this check!)
      ? options.baseURL            // → uses "" as the base URL
      : `https://bedrock-runtime.${region}.amazonaws.com`
  ) ?? `https://bedrock-runtime.us-east-1.amazonaws.com`;
  // The ?? fallback also never triggers: withoutTrailingSlash("") returns ""
};
```

Because `"" != null` is `true`, an empty string is treated as a valid, intentional base URL. Every request then goes to `""/model/{modelId}/converse` — an invalid URL — causing the `failed to fetch` failure.

The fix converts both `baseURL` and `region` from empty string to `undefined` before passing them to the SDK. `undefined != null` is `false`, so the SDK correctly falls back to constructing the proper endpoint from the region. The same guard on `region` prevents a secondary issue where an empty region would produce a malformed URL like `https://bedrock-runtime..amazonaws.com`.

The following tradeoffs were made:

- Using `|| undefined` (falsy check) rather than a strict `=== ""` check, so any other whitespace-only or otherwise empty value is also handled safely.
- The fix is applied only inside `buildBedrockConfig()` and does not affect any other provider.

The following alternatives were considered:

- Patching the `@ai-sdk/amazon-bedrock` package — rejected because the SDK's behavior is internally consistent.

Links to places where the discussion took place: 

### Breaking changes

None.

If this PR introduces breaking changes, please describe the changes and the impact on users.

### Special notes for your reviewer

The changed function is `buildBedrockConfig()` in `src/renderer/src/aiCore/provider/providerConfig.ts`. The diff is minimal: one variable extraction for `baseURL`, one `|| undefined` guard on `region`, and the propagation of `baseURL` into both return paths.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. Check this only when the PR introduces or changes a user-facing feature or behavior.
- [x] Self-review: I have reviewed my own code (e.g., via [`/gh-pr-review`](/.claude/skills/gh-pr-review/SKILL.md), `gh pr diff`, or GitHub UI) before requesting review from others

### Release note

```release-note
Fixed AWS Bedrock requests failing with "failed to fetch" when API Host is left blank (the default). The SDK endpoint should now be correctly derived from the configured Region.
```

### CODE REVIEW

**Review by DeJeune — APPROVED** [review]

File: src/renderer/src/aiCore/provider/providerConfig.ts [hunk 1]
```diff
@@ -209,17 +209,20 @@ function buildOllamaConfig(ctx: BuilderContext): ProviderConfig<'ollama'> {
 
 function buildBedrockConfig(ctx: BuilderContext): ProviderConfig<'bedrock'> {
   const authType = getAwsBedrockAuthType()
-  const region = getAwsBedrockRegion()
+  const region = getAwsBedrockRegion() || undefined
```
Comment (kangfenmao) [inline src/renderer/src/aiCore/provider/providerConfig.ts]: This should trim the stored region before applying the fallback. `AwsBedrockSettings` persists the raw input value, so values like `us-east-1 ` or whitespace-only strings remain truthy here and still get passed to the Bedrock SDK, which interpolates them into URLs such as `https://bedrock-runtime.us-east-1 .amazonaws.com` or `https://bedrock-runtime.   .amazonaws.com`. Using `getAwsBedrockRegion().trim() || undefined` would make the new guard cover the same user-input cases that `routeToEndpoint()` already covers for `baseURL`.

**Review by kangfenmao — CHANGES_REQUESTED** [review]
Found one small but user-visible edge case in the Bedrock region normalization. The default empty API Host path looks fixed, but the region should be trimmed before falling back so pasted/trailing whitespace does not still produce malformed Bedrock runtime URLs.

**Comment by kangfenmao** [comment]
> [\!NOTE]
> This comment was translated by Claude.

Let me provide some background on my inline comment to explain why this modification is worth including together.

The main issue this PR fixes is that the built-in AWS Bedrock provider has an empty string as the default `apiHost`. Previously, the configuration would pass `baseURL: ''` to `@ai-sdk/amazon-bedrock`, while the SDK uses checks like `options.baseURL ?? defaultUrl`. An empty string is not `null/undefined`, so the SDK treats it as an explicitly configured baseURL, ultimately constructing an invalid request URL and triggering `failed to fetch`.

Converting empty `baseURL` to `undefined` in the PR is the right direction, allowing the SDK to automatically construct an endpoint like `https://bedrock-runtime.us-east-1.amazonaws.com` based on the region.

The edge case I pointed out is in the `region` line:

```ts
const region = getAwsBedrockRegion() || undefined
```

This only handles truly empty strings `''`. However, the Bedrock settings page currently saves the region input value as-is without trimming. If users copy and paste with trailing spaces, like `us-east-1 `, or enter whitespace-only strings, these values remain truthy in JavaScript and won't fallback to `undefined`, so they'll still be directly inserted into the URL by the SDK, resulting in something like:

```text
https://bedrock-runtime.us-east-1 .amazonaws.com
https://bedrock-runtime.   .amazonaws.com
```

In other words, this PR has fixed the failure caused by the default empty API Host, but whitespace characters in region input can still cause similar malformed URL issues. It's recommended to change this to:

```ts
const region = getAwsBedrockRegion().trim() || undefined
```

This covers empty strings, whitespace-only strings, and normal regions with leading/trailing spaces simultaneously. This change remains minimal and consistent with the current hotfix scope.

---
<details>
<summary>Original Content</summary>

补充解释一下我刚才 inline comment 的背景，方便判断这个修改为什么值得一起收掉。

这个 PR 修的主问题是：AWS Bedrock 的内置 provider 默认 `apiHost` 为空字符串。之前配置会把 `baseURL: ''` 传给 `@ai-sdk/amazon-bedrock`，而 SDK 用的是 `options.baseURL ?? defaultUrl` 这一类判断。空字符串不是 `null/undefined`，所以 SDK 会把它当成用户明确配置的 baseURL，最终拼出无效请求地址并触发 `failed to fetch`。

PR 里把空 `baseURL` 转成 `undefined` 是正确方向，这样 SDK 才会根据 region 自动构造类似 `https://bedrock-runtime.us-east-1.amazonaws.com` 的 endpoint。

我指出的边界在 `region` 这行：

```ts
const region = getAwsBedrockRegion() || undefined
```

这只处理真正的空字符串 `''`。但 Bedrock 设置页目前会原样保存 region 输入值，没有 trim。如果用户复制粘贴时留下尾随空格，例如 `us-east-1 `，或者输入了 whitespace-only 字符串，这些值在 JS 里仍然是 truthy，不会 fallback 到 `undefined`，于是仍会被 SDK 直接插进 URL，变成类似：

```text
https://bedrock-runtime.us-east-1 .amazonaws.com
https://bedrock-runtime.   .amazonaws.com
```

也就是说，这个 PR 已经修掉了"默认空 API Host"导致的失败，但 region 输入里的空白字符仍可能造成同类的 malformed URL。建议把这里改成：

```ts
const region = getAwsBedrockRegion().trim() || undefined
```

这样可以同时覆盖空字符串、纯空白字符串，以及带前后空格的正常 region。这个改动仍然很小，和当前 hotfix 的范围一致。

</details>

**Review by kangfenmao — APPROVED** [review]
Thanks for the update. The Bedrock config now normalizes both empty baseURL and trimmed/empty region before handing settings to the SDK, which addresses the malformed endpoint cases I flagged. I don't see further blocking issues in this narrow hotfix.
