### PR TITLE
fix(backup): defer auto backup during streaming response

### LINKED ISSUE #13216: [Bug]: Auto WebDAV Backup Interrupts Streaming Response Causing Conversation Truncation and Freeze
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.7.23

### Bug Description

Image
When using Cherry Studio chatting with AI and enabling automatic WebDAV backup (every 15 minutes), if a backup is triggered while the AI is streaming a response, the current conversation may be saved in an incomplete state.

After the backup syncs to other devices:
- The last AI message is truncated (only partially saved)
- The conversation becomes stuck in that state
- The message cannot continue generating
- It is impossible to send new messages in that conversation
- The conversation appears permanently locked in a “half-response” state
- This makes the conversation unusable.

### Steps To Reproduce

1. Enable WebDAV auto backup (set interval to 15 minutes).
2. Start a conversation with AI.
3. Wait until close to the backup trigger time.
4. Let the AI generate a longer streaming response.
5. Ensure the backup triggers during the streaming response.
6. Open Cherry Studio on another synced device (or allow sync to complete).
7. Observe the conversation state.

### Expected Behavior

- Backup should not interrupt an ongoing streaming response.
- Conversations should only be saved in a consistent state.
- After sync, the conversation should remain editable.
- If interruption happens, the system should allow regeneration or recovery.

### Relevant Log Output

```shell

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by GeorgeDong32**
### What this PR does

Before this PR:
- Auto backup (WebDAV, S3, local) could trigger during an ongoing streaming response
- This caused incomplete conversation state to be saved
- Synced devices would receive truncated/unusable conversations
- Users experienced "half-response" frozen state with no way to recover

After this PR:
- Auto backup checks if any topic is currently streaming before starting
- Backup is deferred until all streaming responses complete
- Conversations are only backed up in consistent states
- No more conversation truncation or freeze issues during backup

Fixes #13216

### Why we need it and why it was done in this way

The issue occurs when auto backup triggers during an active streaming response. The backup captures an incomplete state of the conversation, which then syncs to other devices and causes permanent corruption.

**Tradeoffs made:**
- Backup is deferred rather than cancelled - ensures backup still happens eventually
- Simple state check (`loadingByTopic`) rather than complex queuing mechanism
- Minimal code change to reduce risk

**Alternatives considered:**
- Pause streaming during backup - would affect user experience
- Queue backup requests - more complex implementation
- Skip backup entirely if streaming - could miss backup window

### Breaking changes

None

### Special notes for your reviewer

The fix adds a streaming detection check in `performAutoBackup` function. It checks the Redux state `loadingByTopic` to determine if any topic is currently receiving a streaming response. If streaming is detected, the backup is deferred (the next scheduled backup will handle it).

### Checklist

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: Write code that humans can understand and Keep it simple
- [ ] Refactor: N/A - minimal bug fix
- [ ] Upgrade: N/A - no data schema changes
- [ ] Documentation: N/A - internal bug fix, no user-facing changes to document
- [x] Self-review: Completed

### Release note

```release-note
Fix auto backup interrupting streaming responses, preventing conversation truncation and freeze issues
```

### CODE REVIEW

File: src/renderer/src/services/BackupService.ts [hunk 1]
```diff
@@ -657,6 +657,16 @@ export function startAutoSync(immediate = false, type?: BackupType) {
       return
     }
 
+    // Check if any topic is currently streaming/loading
+    const state = store.getState()
+    const anyTopicLoading = Object.values(state.messages.loadingByTopic).some((loading) => loading === true)
+
+    if (anyTopicLoading) {
+      logger.info(`${logPrefix} Streaming in progress, deferring backup`)
+      scheduleNextBackup('fromNow', backupType)
```
Comment (zhibisora) [inline src/renderer/src/services/BackupService.ts:666]: **Suggestion:** This fixes the corruption risk well. As a follow-up, consider retrying soon after streaming finishes (or using a short backoff) instead of rescheduling from . With longer sync intervals,  postpones a due backup by a full cycle, while a pending-or-short-retry approach would stay closer to the PR description of deferring until streaming completes.
