### PR TITLE
fix: prepend node directory to PATH for sudo OpenClaw install/uninstall

### LINKED ISSUE #13333: [Bug]: OpenClaw installation fails for nvm/Homebrew users — sudo retry cannot find node
### Issue Checklist\n\n- [x] I have searched through the existing issues and did not find a similar report.\n- [x] I have provided a short and descriptive title.\n\n### Platform\n\nmacOS\n\n### Version\n\nv1.7.24\n\n### Bug Description\n\nOpenClaw 一键安装在 macOS 上失败。安装过程中出现两个错误：\n\n1. **第一次 npm 安装失败（exit code 243）**：Electron 内部 spawn 的 npm 进程异常退出\n2. **sudo 重试失败（exit code 127）**：`@expo/sudo-prompt` 提权后，root 的 PATH 不包含 nvm/homebrew 路径，导致 `env: node: No such file or directory`\n\n### Root Cause\n\n`OpenClawService.ts` 中构造 sudo 命令时，没有将 node 所在目录注入 PATH：\n\n```typescript\n// 当前代码\nconst npmCommand = `\"${npmPath}\" install -g openclaw@latest`\n// npm 的 shebang 是 #!/usr/bin/env node\n// sudo 环境的 PATH 只有 /usr/bin:/bin:/usr/sbin:/sbin\n// 找不到 node → env: node: No such file or directory\n```\n\n### Fix\n\n在 sudo 命令前注入 node 目录到 PATH：\n\n```typescript\nconst nodeDir = path.dirname(npmPath)\nconst npmCommand = `export PATH=\"${nodeDir}:$PATH\" && \"${npmPath}\" install -g openclaw@latest`\n```\n\n### Error Log\n\n```\nInstalling OpenClaw with command: /usr/local/bin/npm install -g openclaw@latest\nOpenClaw install failed with code 243\nPermission denied, retrying with sudo-prompt...\nSudo install failed: Command failed: \"/usr/local/bin/npm\" install -g openclaw@latest\nenv: node: No such file or directory\n```\n\n### Environment\n\n- macOS with nvm (node v24.14.0) + homebrew (node v25.8.0)\n- npm shebang: `#!/usr/bin/env node`\n- `@expo/sudo-prompt` uses osascript, root PATH doesn't include nvm/homebrew dirs\n\n### PR\n\n#13356

### PR DESCRIPTION
**Pull request by SiinXu**
### What this PR does

Before this PR:
When OpenClaw one-click install fails and retries with `sudo` via `@expo/sudo-prompt`, the root user's PATH doesn't include nvm/homebrew directories where `node` lives. Since npm's shebang is `#!/usr/bin/env node`, this causes `env: node: No such file or directory` (exit code 127).

After this PR:
Prepend npm's parent directory to PATH in the sudo command string on macOS/Linux. Windows is unaffected (npm uses `.cmd` shims without shebangs).

Fixes #13333

### Why we need it and why it was done in this way

N/A

### Breaking changes

N/A

### Special notes for your reviewer

- `install()`: Prepend `nodeDir` to PATH in sudo retry command
- `uninstall()`: Same fix for sudo retry command

### Checklist

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. Check this only when the PR introduces or changes a user-facing feature or behavior.
- [ ] Self-review: I have reviewed my own code (e.g., via [`/gh-pr-review`](/.claude/skills/gh-pr-review/SKILL.md), `gh pr diff`, or GitHub UI) before requesting review from others

### Release note

```release-note
fix: prepend node directory to PATH for sudo OpenClaw install/uninstall
```

### CODE REVIEW

**Review by MontaEllis8 — APPROVED** [review]
> [!NOTE]
> This issue/comment/review was translated by Claude.

✅ Code Review Passed

Fixed PATH issue, improved sudo installation.

Recommend merging.

**Review by MontaEllis8 — APPROVED** [review]
✅ Code Review Passed

Code review passed, recommended for merge.

File: src/main/services/OpenClawService.ts [hunk 1]
```diff
@@ -244,8 +244,14 @@ class OpenClawService {
...
     if (registryArg) npmArgs.push(registryArg)
 
-    // Keep the command string for logging and sudo retry
-    const npmCommand = `"${npmPath}" install -g ${packageName} ${registryArg}`.trim()
+    // Keep the command string for logging and sudo retry.
+    // On macOS/Linux, prepend npm's parent dir to PATH so that sudo (which runs in a
+    // clean environment without user PATH) can resolve `node` via npm's shebang
+    // (#!/usr/bin/env node).
+    const nodeDir = path.dirname(npmPath)
+    const npmCommand = isWin
```
Comment (EurFelux) [inline src/main/services/OpenClawService.ts:252]: [nit] Edge case: when `findExecutableInEnv('npm')` returns `null`, `npmPath` falls back to `'npm'`, and `path.dirname('npm')` returns `'.'`. This would make the sudo command become:

```sh
export PATH=".:$PATH" && "npm" install -g ...
```

Prepending `.` to root's PATH is a minor security anti-pattern (current directory in PATH can lead to unintended binary execution). Though practically harmless since it's a one-shot sudo command, consider adding a guard:

```ts
const nodeDir = path.dirname(npmPath)
const pathPrefix = nodeDir !== '.' ? `export PATH="${nodeDir}:$PATH" && ` : ''
```

Not blocking — just a robustness note.
