### PR TITLE
fix(search): prevent empty activeTools when web search is the only tool

### LINKED ISSUE #14465: [Bug]: Built-in web search can repeat excessively and consume huge tokens
## Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the FAQ.
- [x] I've looked at pinned issues and searched for existing open issues, closed issues, and discussions, no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

## Platform

macOS

## Version

v1.9.2

## Bug Description

When an assistant has built-in web search enabled, the `buildin_web_search` tool can be invoked repeatedly during a single assistant response. In the reported case, one response produced many separate search result/citation groups and consumed more than 120k tokens.

Observed symptoms:

- Multiple search result groups are shown in one response, such as 17, 20, 5, 6, 6, 3, and 20 search results.
- Multiple citation blocks are created for the same assistant response.
- Token usage can become extremely high, for example `Tokens: 122737`.

This makes web search unexpectedly expensive and can slow down or disrupt the conversation.

## Steps To Reproduce

1. Configure an assistant with a web search provider enabled.
2. Ask a question that triggers built-in web search.
3. Let the assistant stream the response.
4. Observe that `buildin_web_search` may be called repeatedly in the same response, producing many search/citation groups and very high token usage.

## Expected Behavior

Built-in web search should have a bounded per-response budget. A single assistant response should not repeatedly call `buildin_web_search` and append multiple large search result payloads unless explicitly allowed.

Expected behavior for the default path:

- Execute built-in web search at most once per assistant response.
- Reuse the first search result if the model attempts to call the tool again.
- Limit and deduplicate prepared search queries.
- Keep URLs compact in search results to reduce token overhead.

## Relevant Log Output

```shell
N/A
```

## Additional Context

The screenshots supplied with the report show repeated search result groups and a token counter above 122k tokens.

### PR DESCRIPTION
**Pull request by TakotsuboChen**
### What this PR does

Before this PR:

When `prepareStep` filtered the built-in web search tool out of `activeTools` after it had been called once, it could produce `activeTools: []` — an empty array. The AI SDK forwarded this as `tools: []` to the Anthropic API, which rejects it with a 400 error: *"tools: array must contain at least 1 element if present"*. This truncated the assistant's response mid-stream after the first web search completed.

After this PR:

When filtering the built-in web search tool would leave `activeTools` empty, `prepareStep` returns without setting `activeTools` instead. The AI SDK then passes all available tools to the model. The tool's internal `cachedSearchResultsPromise` already prevents actual re-searching, so the behaviour goal of `0636b601f` is preserved.

Fixes #14465 (regression introduced by the fix in `0636b601f`)

### Why we need it and why it was done in this way

The following tradeoffs were made:

The upstream fix in `0636b601f` correctly prevents repeated web searches but introduced a regression when web search is the *only* tool: the empty `activeTools` array reaches Anthropic and triggers a 400. The fix here is minimal — one guard before returning `{ activeTools: filteredTools }`.

The following alternatives were considered:

- Removing the `prepareStep` hook entirely: rejected because it would re-introduce runaway repeated searches.
- Returning `{ activeTools: undefined }` explicitly: equivalent to returning `undefined`/`stepConfig`; chose the latter for clarity.

### Breaking changes

None.

### Special notes for your reviewer

The `cachedSearchResultsPromise` closure in `WebSearchTool` is the mechanism that prevents re-searching when web search remains visible in subsequent steps. This was introduced in `0636b601f` and is relied upon here.

### Checklist

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: Write code that humans can understand and Keep it simple
- [x] Refactor: You have left the code cleaner than you found it
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: Not required — internal bug fix, no user-facing behaviour change beyond fixing the truncation.
- [x] Self-review: I have reviewed my own code before requesting review from others

### Release note

```release-note
Fixed built-in web search truncating the assistant response when web search was the only active tool.
```

### CODE REVIEW

**Review by DeJeune — APPROVED** [review]

File: src/renderer/src/aiCore/plugins/searchOrchestrationPlugin.ts [hunk 1]
```diff
@@ -350,14 +350,15 @@ export const searchOrchestrationPlugin = (
...
-                  }
-                : stepConfig
+              if (!hasWebSearchCall) return stepConfig
+              const filteredTools = (stepConfig?.activeTools ?? Object.keys(params.tools!)).filter(
+                (toolName) => toolName !== BUILTIN_WEB_SEARCH_TOOL_NAME
+              )
+              // When web search is the only tool, don't set activeTools to [] — Anthropic
+              // rejects empty tools arrays. The tool's internal cache (cachedSearchResultsPromise)
+              // already prevents actual re-searching.
+              if (filteredTools.length === 0) return stepConfig
```
Comment (ousugo) [inline src/renderer/src/aiCore/plugins/searchOrchestrationPlugin.ts:360]: **[B6]** 这里修复了 web search 作为唯一工具时会把 activeTools 过滤成空数组的问题，但当前没有看到覆盖这个边界条件的回归测试。建议补一条单测，至少断言当 web search 已经调用过一次且没有其他工具可用时，这个分支不会让 AI SDK 最终收到空的 tools 数组；否则后续只要 prepareStep 或 WebSearchTool 的缓存语义有变动，这个 Anthropic 400 很容易再次回归。

**Review by ousugo — COMMENTED** [review]
整体实现方向正确，提交了一条非阻塞建议：为 web search 作为唯一工具时的空 activeTools 回归补一条单测，避免后续再次触发 Anthropic 400。

**Review by ousugo — APPROVED** [review]

**Comment by TakotsuboChen** [comment]
> [\!NOTE]
> This comment was translated by Claude.

@Copilot Re the `...stepConfig` concern: in JavaScript/TypeScript, spreading `undefined` in an object literal is perfectly safe — `{ ...undefined, activeTools: filteredTools }` is well-defined behavior per the ES2018 spec and is equivalent to `{ activeTools: filteredTools }`. It never throws. (oxlint's *'Empty fallbacks in spreads are unnecessary'* rule exists precisely for this reason — it rejects `?? {}` as redundant.) No change needed here.

@ousugo Thank you for the approval and suggestions\! I completely agree with adding unit tests; however, since this is a hotfix for main, I hope to keep the scope of changes minimal, and unit tests can follow up in a subsequent PR (or be included together in v2 PR #14261).

---
<details>
<summary>Original Content</summary>

@Copilot Re the `...stepConfig` concern: in JavaScript/TypeScript, spreading `undefined` in an object literal is perfectly safe — `{ ...undefined, activeTools: filteredTools }` is well-defined behavior per the ES2018 spec and is equivalent to `{ activeTools: filteredTools }`. It never throws. (oxlint's *'Empty fallbacks in spreads are unnecessary'* rule exists precisely for this reason — it rejects `?? {}` as redundant.) No change needed here.

@ousugo 感谢批准和建议！补单测的方向完全认同；鉴于这是针对 main 的 hotfix，希望保持改动范围最小，单测可以在后续 PR 中跟进（或在 v2 PR #14261 里一并加入）。

</details>

**Review by GeorgeDong32 — APPROVED** [review]
## Code Review Summary

**Overall**: Clean and minimal hotfix. Correctly addresses a regression where web search as the only active tool produces `activeTools: []`, causing Anthropic API 400.

### Correctness ✅

The guard `if (filteredTools.length === 0) return stepConfig` correctly prevents the empty array case while preserving the original behavior for all other scenarios:

| Scenario | Behavior | Correct? |
|---|---|---|
| No web search call | Returns `stepConfig` unchanged | ✅ |
| Web search + other tools | Filters out web search from `activeTools` | ✅ |
| Web search is only tool | Returns `stepConfig` (keeps all tools visible) | ✅ |

The `cachedSearchResultsPromise` mechanism in `WebSearchTool` guarantees no redundant searches when tools remain in the list — the inline comment correctly documents this invariant.

### Code Quality ✅

- Refactoring from ternary to guard-clause + linear flow improves readability
- Inline comment clearly explains the Anthropic API constraint (`tools: []` rejection)
- Scope is strictly minimal — no unnecessary changes, fits main branch hotfix policy

### Design Decision 👍

Returning `stepConfig` (with all tools) rather than `{ activeTools: undefined }` is the right call — semantically clearer and functionally equivalent since the SDK treats missing `activeTools` as "use all tools."

### Non-blocking Note

Agree with @ousugo's suggestion to add a unit test covering the "web search as only tool" regression case in a follow-up PR or v2 #14261.

### CI Status

basic-checks ✅ | general-test ✅ | render-test ✅
