### PR TITLE
fix: upgrade ollama provider to 3.3.1

### LINKED ISSUE #11612: Bug: ollama cannot disable qwen3 thinking mode
> [!NOTE]
> This issue was translated by Claude.

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

macOS

### Version

1.7.1

### Bug Description

Image

### Steps To Reproduce

1. Create a new default assistant, select ollama qwen3
2. Default is non-thinking mode, correctly carries no_think
3. Switch to thinking mode, correctly carries think
4. Switch back to non-thinking mode, cannot handle correctly
5. Create new session, also cannot handle correctly, delete entire assistant and start over, return to step 1

### Expected Behavior

Thinking mode carries think, non-thinking mode carries no_think

### Relevant Log Output

```shell

```

### Additional Context

_No response_

---
<details>
<summary>Original Content</summary>

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

macOS

### Version

1.7.1

### Bug Description

Image

### Steps To Reproduce

1. 新建一个默认助手，选择ollama qwen3
2. 默认是非思考模式，正确携带了no_think
3. 切换到思考模式，正确携带think
4. 切换到非思考模式，无法正确处理
5. 新建会话，也无法正确处理，删掉整个助手重来，回到1

### Expected Behavior

思考模式携带think，非思考模式携带 no_think

### Relevant Log Output

```shell

```

### Additional Context

_No response_

</details>

### LINKED ISSUE #12642: [Bug]: Ollama local model thinking chain display anomaly
> [!NOTE]
> This issue was translated by Claude.

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

1.7.15

### Bug Description

When using the Ollama local model `deepseek-r1:8b-0528-qwen3-q8_0` in Cherry Studio, the thinking chain (reasoning process) is not displayed, but it appears when running directly in Ollama, as shown in the image. The deep thinking switch for this model is enabled in Cherry Studio.

Another minor issue: the thinking chain for other thinking chain models runs to the bottom, which may or may not be related to this issue (see GLM screenshot).

Image

### Steps To Reproduce

Image
The model outputs responses instantly on Cherry Studio, which doesn't feel like the thinking process is hidden. Here the 💡 for deep thinking is default and cannot be clicked.

Image
Direct conversation in Ollama will output the complete thinking process.

Image
The deep thinking tags for the model are all enabled.

Image
Minor issue with thinking chain misalignment for other models.

### Expected Behavior

Can normally view the thinking chain or toggle the thinking chain.

### Relevant Log Output

```shell

```

### Additional Context

_No response_

---
<details>
<summary>Original Content</summary>

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

1.7.15

### Bug Description

我在cherrystudio使用ollama本地模型deepseek-r1:8b-0528-qwen3-q8_0时，一直没有思维链，但是直接在ollama上运行时是有的，如图所示，cherrystudio中该模型的深度思考开关都是开着的。
另一个小问题，其他思维链模型，思维链会跑到底部去，不知是否和此有关（见GLM的截图）。

Image

### Steps To Reproduce

Image
cherrystudio上模型是秒输出的回答，感觉不像是隐藏了思考过程。这里深度思考的💡是默认的，无法点击的

Image
直接在ollama上的对话，是会完整输出思考过程的。

Image
模型的深度思考标签都是开着的

Image

其他模型的思维链异位小问题

### Expected Behavior

可以正常看到思维链，或者开关思维链

### Relevant Log Output

```shell

```

### Additional Context

_No response_

</details>

### LINKED ISSUE #13083: [Bug]: Ollama DeepSeek-R1 reasoning content missing <think> tag, causing folding failure (Related to #12642)
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.7.19

### Bug Description

I am experiencing a persistent issue where the reasoning content (thought chain) of DeepSeek-R1 via Ollama is not being correctly captured by the UI's folding window.

After inspecting the raw stream, I found that the opening <think> tag is missing, while the closing </think> tag is present. This prevents the parser from identifying the start of the reasoning block. Meanwhile it is noteworthy that the official Deepseek API works perfectly (opening tag is present or handled correctly).

This issue seems very similar to the one reported in #12642, but it persists in the latest version of Cherry Studio.

Image

Image

### Steps To Reproduce

1.Connect to a local Ollama instance with deepseek-r1:8b (or any R1 variant).
2.Send a prompt that triggers a reasoning process.
3.Observe that the reasoning text appears as plain text in the main chat body instead of a collapsible window.

### Expected Behavior

The UI should correctly recognize the start of the reasoning phase and encapsulate it within the folding component.

### Relevant Log Output

```shell
Below is the raw output after me asking "Solve: x^2+3x+1=0, Do Some Deep Thinking":

## 🤖 Assistant


I need to solve the equation x² + 3x + 1 = 0. It's a quadratic equation, so I should use the quadratic formula. The general form is ax² + bx + c = 0, and the formula is x = [-b ± √(b² - 4ac)] / (2a).

Here, a = 1, b = 3, and c = 1. So, plugging in:

First, the discriminant D = b² - 4ac = 3² - 4×1×1 = 9 - 4 = 5.

Then, x = [-3 ± √5] / 2.

So, the solutions are x = [-3 + √5]/2 and x = [-3 - √5]/2.

I should verify that. Let me check with the quadratic formula again.

a = 1, b = 3, c = 1.

D = b² - 4ac = 9 - 4 = 5.

√D = √5.

Then x = [-3 ± √5]/2.

Yes, that seems correct.

I could factor it or use completing the square, but the quadratic formula is straightforward.

Let me see if it factors nicely. x² + 3x + 1. I need two numbers that multiply to 1 and add to 3. The factors of 1 are 1 and 1, but 1 + 1 = 2, not 3. Or -1 and -1, but (-1)×(-1)=1 and (-1)+(-1)=-2, not 3. So no integer factors, so the quadratic formula is the way to go.

Completing the square: x² + 3x + 1 = 0.

x² + 3x = -1.

Now, to complete the square: take half of 3, which is 1.5, square it, 2.25.

So, x² + 3x + 2.25 = -1 + 2.25

(x + 1.5)² = 1.25

Then x + 1.5 = ±√(1.25)

√(1.25) = √(5/4) = √5 / 2

So x = -1.5 ± √5 / 2

Which is the same as [-3/2 ± √5/2] = [-3 ± √5]/2

Same as before.

Now, I think I should leave the answer in exact form, not decimal, because the problem says "solve" and it's a quadratic.

So, the solutions are x = [-3 + √5]/2 and x = [-3 - √5]/2.

I should present it nicely.

Sometimes people write it as x = \frac{-3 \pm \sqrt{5}}{2}

But I think that's fine.

Now, to box the answer, I need to show both solutions.

The problem says "solve", so I should provide both.

I think that's it.

I could think about the graph or something, but for solving, this should be sufficient.

Let me calculate numerical values to verify.

√5 ≈ 2.236

So x = [-3 + 2.236]/2 ≈ (-0.764)/2 ≈ -0.382

And x = [-3 - 2.236]/2 ≈ (-5.236)/2 ≈ -2.618

Now, plug into original equation.

First, x ≈ -0.382

(-0.382)^2 = approximately 0.146

3*(-0.382) ≈ -1.146

Plus 1, so 0.146 - 1.146 + 1 = -1 + 1 = 0, approximately.

Similarly, x ≈ -2.618

(-2.618)^2 ≈ 6.854

3*(-2.618) ≈ -7.854

Plus 1, so 6.854 - 7.854 + 1 = -1 + 1 = 0.

Yes, it works.

So, I think that's the solution.

The problem says "Do Some Deep Thinking", maybe there's another way.

Perhaps I can think in terms of the roots.

Or maybe consider the discriminant, which is 5, so two real roots.

But I think I've covered it.

Another way: the sum of roots is -b/a = -3, product is c/a = 1.

With roots approximately -0.382 and -2.618, sum -3, product about (-0.382)*(-2.618) ≈ 1, yes.

But not necessary.

I think I'm overthinking.

So, the solution is x = \frac{-3 \pm \sqrt{5}}{2}

Now, for the boxed answer, I should write it properly.

I think it's fine.

Sometimes people write it as x = \frac{-3 + \sqrt{5}}{2} or x = \frac{-3 - \sqrt{5}}{2}

But in one box or two.

I think for the format, I can write both.

Since it's a solve, I should present it clearly.

I think I'll go with that.
</think>
The equation to solve is \(x^2 + 3x + 1 = 0\).

This is a quadratic equation of the form \(ax^2 + bx + c = 0\) with \(a = 1\), \(b = 3\), and \(c = 1\).

Using the quadratic formula:

\[
x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
\]

First, calculate the discriminant:

\[
D = b^2 - 4ac = 3^2 - 4 \cdot 1 \cdot 1 = 9 - 4 = 5
\]

Then,

\[
x = \frac{-3 \pm \sqrt{5}}{2}
\]

Thus, the solutions are:

\[
x = \frac{-3 + \sqrt{5}}{2} \quad \text{and} \quad x = \frac{-3 - \sqrt{5}}{2}
\]

These can also be verified by completing the square or by checking the sum and product of the roots, which are consistent with the quadratic equation.

The numerical approximations are approximately \(x \approx -0.382\) and \(x \approx -2.618\), and both satisfy the original equation.

\boxed{x = \dfrac{-3 + \sqrt{5}}{2}} \quad \text{or} \quad \boxed{x = \dfrac{-3 - \sqrt{5}}{2}}

Observation: The <think> tag is missing at the beginning of the stream.
```

### Additional Context

1. Comparison with Official API: 
The issue does NOT occur when using the official DeepSeek API, which suggests that Cherry Studio's parser might be handling the Ollama stream differently or expecting a specific token that Ollama is suppressing.

2. Model Template Analysis:
I have exported the template of the model I am using (see attached `temp_template.txt`). I suspect the conditional logic `{{- if and $.IsThinkSet (not $.Think) -}}` in the template might be causing the `<think>` tag to be omitted or incorrectly formatted during streaming.

3. Reproducibility:
This issue is consistently reproducible with the official Ollama `deepseek-r1:8b` model and other fine-tuned variants.

[temp_template.txt](https://github.com/user-attachments/files/25580916/temp_template.txt)

### PR DESCRIPTION
**Pull request by Pleasurecruise**
### What this PR does

Before this PR:

After this PR:

continue #12526 

Fix #11612 Fix #12642 Fix #13083

### Why we need it and why it was done in this way

The following tradeoffs were made:

Bump ollama-ai-provider-v2 from 1.5.5 to 3.3.1 and update its patch filename. Update pnpm lock entries for the new provider version and related provider deps. Adjust compiled dist files to expose ollama provider option types and add support for the expanded "think" option (boolean | 'low' | 'medium' | 'high'). Add a new ollamaReasoningOrderMiddleware to reorder reasoning stream parts ahead of text/tool parts and wire it into AiSdkMiddlewareBuilder when reasoning is enabled. Update options builder to use OllamaProviderOptions and map assistant reasoning_effort (including explicitly disabling thinking when reasoning is off).

The following alternatives were considered:

Links to places where the discussion took place: 

### Breaking changes

If this PR introduces breaking changes, please describe the changes and the impact on users.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. Check this only when the PR introduces or changes a user-facing feature or behavior.
- [x] Self-review: I have reviewed my own code (e.g., via [`/gh-pr-review`](/.claude/skills/gh-pr-review/SKILL.md), `gh pr diff`, or GitHub UI) before requesting review from others

### Release note

```release-note

```

### CODE REVIEW

File: src/renderer/src/aiCore/plugins/ollamaReasoningOrderPlugin.ts [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+        stream: stream.pipeThrough(
+          new TransformStream<LanguageModelV2StreamPart, LanguageModelV2StreamPart>({
+            transform(chunk, controller) {
+              if (chunk.type === 'reasoning-start') {
+                hasReasoning = true
+                isActiveReasoning = true
+                reasoningId = chunk.id
+                controller.enqueue(chunk)
+                flushBufferedText(controller)
+                return
```
Comment (Pleasurecruise) [inline src/renderer/src/aiCore/plugins/ollamaReasoningOrderPlugin.ts]: **Bug:** Calling `flushBufferedText` immediately after enqueuing `reasoning-start` causes any text that was buffered *before* reasoning arrived to be emitted between `reasoning-start` and the first `reasoning-delta`. This defeats the purpose of the re-ordering middleware — if Ollama streams `text-start` → `text-delta` → `reasoning-start` → `reasoning-delta`, the output after this transform will be:

`reasoning-start` → `text-start` → `text-delta` → `reasoning-delta` → `reasoning-end`

…which is still interleaved, not correctly ordered.

The buffered text should only be flushed **after** `reasoning-end` (or after the synthetic `reasoning-end` emitted by `endActiveReasoning` in the `text-start` handler). Remove the `flushBufferedText` call here and move it to the `reasoning-end` handler instead.

File: src/renderer/src/aiCore/plugins/ollamaReasoningOrderPlugin.ts [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+              }
+
+              if (chunk.type === 'reasoning-delta') {
+                hasReasoning = true
+                controller.enqueue(chunk)
+                flushBufferedText(controller)
+                return
```
Comment (Pleasurecruise) [inline src/renderer/src/aiCore/plugins/ollamaReasoningOrderPlugin.ts]: **Bug (same root cause):** `flushBufferedText` here is also incorrect for the same reason. By the time `reasoning-delta` arrives, if there was any buffered text it was already emitted at `reasoning-start` time, so this call is redundant in the normal path. But if text somehow accumulates *between* `reasoning-start` and a subsequent `reasoning-delta` (e.g., a late `text-start` that is re-buffered), flushing mid-reasoning is still wrong.

Remove this call as well; the single `flushBufferedText` in the `reasoning-end` handler is sufficient.

File: src/renderer/src/aiCore/plugins/ollamaReasoningOrderPlugin.ts [hunk 3]
```diff
@@ -0,0 +1,115 @@
...
+              }
+
+              if (chunk.type === 'reasoning-end') {
+                isActiveReasoning = false
+                controller.enqueue(chunk)
+                return
+              }
```
Comment (Pleasurecruise) [inline src/renderer/src/aiCore/plugins/ollamaReasoningOrderPlugin.ts]: **Missing flush:** This is where `flushBufferedText` should be called. After emitting `reasoning-end`, all reasoning content is complete — this is the correct point to release the buffered text chunks:

```ts
if (chunk.type === 'reasoning-end') {
  isActiveReasoning = false
  controller.enqueue(chunk)
  flushBufferedText(controller)  // ← add this
  return
}
```

With this change (and the two calls above removed), the stream will always be ordered as: all reasoning → then text, regardless of the raw order from Ollama.

File: src/renderer/src/aiCore/plugins/ollamaReasoningOrderPlugin.ts [hunk 4]
```diff
@@ -0,0 +1,115 @@
...
+
+              // End reasoning before text starts
+              if (chunk.type === 'text-start') {
+                endActiveReasoning(controller)
+                if (!hasReasoning) {
+                  bufferedText.push(chunk)
+                  return
+                }
+                controller.enqueue(chunk)
+                return
```
Comment (Pleasurecruise) [inline src/renderer/src/aiCore/plugins/ollamaReasoningOrderPlugin.ts]: **Nit / edge case:** When `text-start` triggers `endActiveReasoning` (the synthetic `reasoning-end` path), any still-buffered text won't be flushed at that point because `endActiveReasoning` only enqueues the synthetic event — it doesn't call `flushBufferedText`. If the fix above (flush in `reasoning-end`) is applied to the explicit event, consider whether `endActiveReasoning` should also trigger a flush. Otherwise, text buffered before a reasoning block that never emits `reasoning-end` may be flushed at the wrong time.

One approach: after the call to `endActiveReasoning`, also call `flushBufferedText` here:

```ts
if (chunk.type === 'text-start') {
  endActiveReasoning(controller)
  flushBufferedText(controller) // flush any pre-reasoning text after the synthetic reasoning-end
  ...
}
```

File: src/renderer/src/aiCore/plugins/ollamaReasoningOrderPlugin.ts [hunk 5]
```diff
@@ -0,0 +1,115 @@
...
+              endActiveReasoning(controller)
+              flushBufferedText(controller)
+            }
+          })
+        ),
+        ...rest
+      }
+    }
+  }
+}
```
Comment (Pleasurecruise) [inline src/renderer/src/aiCore/plugins/ollamaReasoningOrderPlugin.ts]: **Nit / missing tests:** No tests were added for this new middleware. Given that the buffering/reordering logic is non-trivial and the bug described above shows it's easy to get wrong, unit tests covering at least these scenarios would be valuable:

1. Normal order: reasoning chunks arrive before text (no reordering needed)
2. Inverted order: text arrives before reasoning-start (should be reordered)
3. No reasoning at all: text-only stream (buffered text should be flushed at finish)
4. Incomplete reasoning: reasoning-start emitted but no reasoning-end before text-start (synthetic end path)

See other middlewares in this directory for test patterns.

**Review by Pleasurecruise — COMMENTED** [review]
## Overall Assessment

This PR correctly upgrades `ollama-ai-provider-v2` from 1.5.5 to 3.3.1, updates the patch file to expose the expanded `think: boolean | 'low' | 'medium' | 'high'` option, and adds an `ollamaReasoningOrderMiddleware` to address stream ordering issues. The dependency bump, lock file updates, and `options.ts` logic are all sound. However, the core buffering logic in `wrapStream` has a significant bug that would produce the same incorrect interleaved output it was intended to prevent.

## Critical / Significant

### Bug: `flushBufferedText` called at wrong points in `wrapStream`
**File:** `ollamaReasoningOrderMiddleware.ts`, lines 55 and 62

When text chunks arrive *before* `reasoning-start` (the exact scenario this middleware targets), they are buffered in `bufferedText`. The intent is to hold them until reasoning is complete and then emit them. However, the current code calls `flushBufferedText` inside the `reasoning-start` and `reasoning-delta` handlers, which emits the buffered text **mid-reasoning**:

Stream in: `text-start` → `text-delta` → `reasoning-start` → `reasoning-delta` → `reasoning-end`

Stream out (current): `reasoning-start` → `text-start` → `text-delta` → `reasoning-delta` → `reasoning-end`

The correct fix is to remove `flushBufferedText` from `reasoning-start` and `reasoning-delta`, and instead call it in the `reasoning-end` handler (and in `endActiveReasoning` for the synthetic end path triggered by `text-start`). See inline comments for details.

## Minor / Nit

- **Missing tests** for the new middleware. The buffering logic is non-trivial and the bug above demonstrates how easy it is to get it wrong. Tests for at least the 4 key scenarios (normal order, inverted order, no reasoning, incomplete reasoning) would give confidence in any future changes.

## Positives

- `wrapGenerate` (non-streaming) reordering is correct and clean.
- Explicit `think: false` when reasoning is disabled (fixing issue #11612) is the right fix — previously the option was simply omitted, which may leave model-side thinking state ambiguous.
- Switching from `OllamaCompletionProviderOptions` to `OllamaProviderOptions` is the correct type to use for chat-model provider options.
- The `gpt-oss` model branch correctly maps `'low'/'medium'/'high'` effort values to the new string-union `think` parameter.
- Dependency upgrade, patch rename, and lock file entries are consistent and clean.

File: src/renderer/src/aiCore/plugins/ollamaReasoningOrderPlugin.ts
Comment (EurFelux) [inline src/renderer/src/aiCore/plugins/ollamaReasoningOrderPlugin.ts:1]: > [!NOTE]
> This comment was translated by Claude.

#10545 did something similar. It's worth investigating deeply why this issue has appeared again, as this issue may occur not only on ollama.

---
<details>
<summary>Original Content</summary>

#10545 做过类似的事情，值得深入调查一下问题再次出现的原因，因为这个问题可能不止在ollama上出现。

</details>

Comment (Pleasurecruise) [reply src/renderer/src/aiCore/plugins/ollamaReasoningOrderPlugin.ts:1]: > [!NOTE]
> This comment was translated by Claude.

The patch mainly fixes the thinking depth configuration bug
- The original code, when `enableReasoning` is enabled, only performed a simple check `think = !['none', undefined].includes(reasoningEffort)` for non-gpt-oss models, causing `think` to be false when `reasoning_effort` is undefined, which actually did not enable thinking
- For gpt-oss models, the old code did not handle the case where `reasoningEffort === 'none'` and other unexpected values
- When `enableReasoning` is disabled, the old code does not explicitly pass `think: false`, causing Ollama to still maintain the default thinking behavior (fixes #11612)

The middleware mainly fixes the issue of incorrect order of reasoning content and text content
https://github.com/nordwestt/ollama-ai-provider-v2/blob/063ac6f8f84e3a691f1b8dd9ca1665a6ece4cff7/src/responses/ollama-responses-stream-processor.ts#L170-L177

```
processDelta(delta, controller) {
      this.processTextContent(delta, controller);  // ← Process text first
      this.processThinking(delta, controller);      // ← Then process reasoning
      this.processToolCalls(delta, controller);
}
```
  ollama-ai-provider-v2@3.3.1, when processing each streaming delta, always calls processTextContent (emits text-start/text-delta) first, then calls processThinking (emits reasoning-start/reasoning-delta)

---
<details>
<summary>Original Content</summary>

patch主要修复的是思考深度配置bug
- 原来代码在`enableReasoning` 开启时，对于非 gpt-oss 模型只做了简单判断`think = !['none', undefined].includes(reasoningEffort)`，导致 `reasoning_effort` 为 undefined 时 think 为 false，实际上没有启用思考
- 对 gpt-oss 模型，旧代码未处理 `reasoningEffort === 'none'` 和其他非预期值的情况
- 当`enableReasoning` 关闭时，旧代码不会显式传`think: false`，导致 Ollama 仍可能保持默认的思考行为（修复 #11612）
中间件主要修复的是推理内容和文本内容顺序错误的问题
https://github.com/nordwestt/ollama-ai-provider-v2/blob/063ac6f8f84e3a691f1b8dd9ca1665a6ece4cff7/src/responses/ollama-responses-stream-processor.ts#L170-L177
```
processDelta(delta, controller) {                                                                                                                                            this.processTextContent(delta, controller);  // ← 先处理文本
      this.processThinking(delta, controller);      // ← 再处理推理                                                                                                            this.processToolCalls(delta, controller);                                 }
```
  ollama-ai-provider-v2@3.3.1 在处理每个流式 delta 时，固定先调用 processTextContent（发出 text-start/text-delta），再调用 processThinking（发出reasoning-start/reasoning-delta）

</details>

**Comment by DeJeune** [comment]
> [!NOTE]
> This issue/comment/review was translated by Claude.

Are ai sdk v5 and v6 compatible?

---
<details>
<summary>Original Content</summary>

ai sdk v5和v6是兼容的吗

</details>
