### PR TITLE
fix(aiCore): FinalChunkConsumerMiddleware throw error

### LINKED ISSUE #8984: [错误]: 1.5.5版本 Claude官方API 使用任何key都提示通过
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我的问题不是 [常见问题](https://github.com/CherryHQ/cherry-studio/issues/3881) 中的内容。
- [x] 我已经查看了 **置顶 Issue** 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。
- [x] 我确认我正在使用最新版本的 Cherry Studio。

### 平台

Windows

### 版本

1.5.5

### 错误描述

Image
Image

### 重现步骤

在key处输入任意文字都提示通过

### 预期行为

响应正确

### 相关日志输出

```shell

```

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by EurFelux**
### What this PR does

修复FinalChunkConsumerMiddleware中错误无法被ErrorHandlerMiddleware捕获的问题，并优化日志输出格式

Fixes #8984

### Why we need it and why it was done in this way

The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Breaking changes

If this PR introduces breaking changes, please describe the changes and the impact on users.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### Release note

```release-note

```

### CODE REVIEW

**Review by alephpiece — APPROVED** [review]

File: src/renderer/src/aiCore/middleware/common/FinalChunkConsumerMiddleware.ts [hunk 1]
```diff
@@ -85,9 +85,15 @@ const FinalChunkConsumerMiddleware: CompletionsMiddleware =
               logger.warn(`Received undefined chunk before stream was done.`)
             }
           }
-        } catch (error) {
+        } catch (error: any) {
           logger.error(`Error consuming stream:`, error as Error)
-          throw error
+          // FIXME: 临时解决方案。该中间件的异常无法被 ErrorHandlerMiddleware捕获。
+          if (params.onError) {
+            params.onError(error)
```
Comment (MyPrototypeWhat) [inline src/renderer/src/aiCore/middleware/common/FinalChunkConsumerMiddleware.ts:92]: 这里的错误会冒泡到messageThunk中的catch里吧？

Comment (EurFelux) [reply src/renderer/src/aiCore/middleware/common/FinalChunkConsumerMiddleware.ts:92]: checkApi没有走messageThunk，而且捕获不到错误
