### PR TITLE
fix: parse DeepSeek DSML tool-call markup into AI SDK tool calls

### LINKED ISSUE #14714: [Bug]: DeepSeek V4-pro web search outputs raw DSML tool_calls tokens instead of invoking the tool
> [\!NOTE]
> This issue was translated by Claude.

### Platform

macOS

### Version

v1.9.4 (draft)

### Bug Description

When using `agent/deepseek-v4-pro` (CherryIN provider) with built-in web search enabled, the model emits the raw DSML tool-call protocol syntax as plain message text instead of having the client parse it as a tool invocation. The web search itself does fire (the citations card with "5 search results / 5 cited sources" appears earlier in the message), but the final assistant turn ends up showing protocol tokens to the user with no actual answer content.

Concretely the message body contains, verbatim:

```
< | DSML | tool_calls>
< | DSML | invoke name="builtin_web_search">
< | DSML | parameter name="additionalContext" string="true">DeepSeek V4 发布 特性 性能 评测 2025</ | DSML | parameter>
</ | DSML | invoke>
</ | DSML | tool_calls>
```

This looks like a tool-use parser miss for DeepSeek V4-pro: the DSML wrapper tokens that should be intercepted and turned into a tool-call UI block are leaking into the rendered text. Same provider + similar request on `deepseek-v3.2` does not exhibit this — the issue appears tied to V4-pro's tool-use formatting.

deepseek-v4-pro emitting raw DSML tool_calls in chat

### Steps to Reproduce

1. Provider: CherryIN
2. Model: `agent/deepseek-v4-pro`
3. Enable built-in web search (globe toggle in the composer)
4. Send: 搜一下 DeepSeek V4 的资料 (or any query that triggers a follow-up web search)
5. Observe the assistant turn

### Expected Behavior

After the web search runs, the assistant should produce a normal natural-language summary citing the 5 sources. The DSML protocol tokens (`< | DSML | tool_calls>`, `< | DSML | invoke …>`, etc.) should never be visible in the rendered message.

### Actual Behavior

- ✅ Thinking blocks render (1.5s, 1.3s)
- ✅ "5 个搜索结果" / "5 个引用内容" cards appear
- ❌ Final answer is replaced by raw DSML tool_calls XML — user sees protocol syntax, not an answer
- ❌ The conversation turn is effectively wasted; the user has to retry

### Severity

P0 — main path is blocked. The user asks a question, web search succeeds, but no answer text is produced. The visible output is internal protocol noise. Single-turn conversations using V4-pro + web search are unusable.

### Possibly Related

- #14671 (DeepSeek search-result annotations not displayed) — different (annotations vs tool-call token leak), but both touch DeepSeek + web search rendering.

### Environment

- App: Cherry Studio 社区版 v1.9.4 (draft)
- OS: macOS
- Provider: CherryIN (gateway-class)
- Model: `agent/deepseek-v4-pro`

---
<details>
<summary>Original Content</summary>

### 现象

v1.9.4 (draft)、CherryIN provider、模型 `agent/deepseek-v4-pro`，开启内置网络搜索后，模型把 DSML 工具调用协议的 raw token 当作正文输出到聊天区，没有触发客户端的工具调用 UI。web search 实际跑成了（消息中段已经出现"5 个搜索结果 / 5 个引用内容"卡片），但最终回答位置展示的是：

```
< | DSML | tool_calls>
< | DSML | invoke name="builtin_web_search">
< | DSML | parameter name="additionalContext" string="true">DeepSeek V4 发布 特性 性能 评测 2025</ | DSML | parameter>
</ | DSML | invoke>
</ | DSML | tool_calls>
```

应该被前端拦截、转成工具调用 UI 的 DSML 包裹 token 直接泄露到了渲染文本里。同 provider 下 deepseek-v3.2 不复现这个问题，看起来是 V4-pro 工具调用语法的解析适配缺失。

### 复现步骤

1. provider 选 CherryIN
2. 模型选 `agent/deepseek-v4-pro`
3. 开启内置网络搜索
4. 发送：搜一下 DeepSeek V4 的资料
5. 观察助手回复

### 期望

搜索完成后，助手应该输出引用了 5 个搜索结果的自然语言总结。DSML 协议 token 不应该出现在最终消息中。

### 优先级

P0：主路径阻塞。用户问完问题、search 成功，但看不到答案，只有协议语法。V4-pro + web search 单轮基本不可用。

### 相关 issue

- #14671（DeepSeek 搜索结果 annotations 不展示）— 现象不同（annotations 缺失 vs DSML token 泄露），但同样在 DeepSeek + web search 渲染链上。
</details>

### PR DESCRIPTION
**Pull request by DeJeune**
### What this PR does

Before this PR:
DeepSeek models could leak DSML tool-call markup (e.g. `<｜｜DSML｜｜tool_calls>`, `<｜｜DSML｜｜invoke name="...">`) as plain text into the assistant response when the upstream inference engine failed to parse it into structured tool calls. The agent loop saw `finishReason: stop` and terminated without dispatching the intended tools, leaving raw markup visible to users. Prompt-level mitigations (suppression instruction in system prompt or tool result) were unreliable because DSML emission is driven by tokenizer-level patterns rather than instruction following.

After this PR:
A new middleware plugin `deepseekDsmlParserPlugin` intercepts streaming and non-streaming responses for DeepSeek models, runs a state-machine parser over text deltas, and converts complete `<｜｜DSML｜｜tool_calls>...</｜｜DSML｜｜tool_calls>` blocks into proper AI SDK `tool-input-start` / `tool-input-delta` / `tool-input-end` / `tool-call` events. `finishReason` is rewritten from `stop` to `tool-calls` so the agent loop continues and dispatches the recovered tool calls. Plain text and unclosed/partial blocks are handled with chunk-boundary buffering and a fallback that re-emits buffered content as text.

Fixes #14714

### Why we need it and why it was done in this way

The following tradeoffs were made:
- Parsing in middleware (rather than client-side post-processing) preserves the agent loop. Just stripping DSML would leave intended tool calls undispatched and break multi-step search flows.
- A state-machine over `text-delta` chunks (rather than a one-shot regex on the full string) keeps streaming UX and handles tags split across SSE chunk boundaries (e.g. `<` / `｜｜DSML｜｜` / `tool` / `_calls` / `>` arriving in separate chunks, as observed in real responses).
- A 64KB swallow buffer cap with text fallback prevents the parser from indefinitely withholding content if a DSML block is truncated.

The following alternatives were considered:
- Appending a "Do not output DSML tags" suppression to the system prompt — verified ineffective because DSML emission is a tokenizer-level entrenched pattern, not instruction-driven.
- Stripping DSML residues with a post-processor — would break agent mode by discarding the intended tool calls.
- Forcing `tools: undefined` on the synthesis step — only fixes one of several leakage scenarios and still loses the parallel-call intent.

Links to places where the discussion took place: https://github.com/CherryHQ/cherry-studio/issues/14714 (and the prior partial fix in #14721 covering only the web-search tool-result side)

### Breaking changes

None.

### Special notes for your reviewer

- This PR targets `main` as a hotfix from `hotfix/deepseek-dsml-parser`, following the pattern of #14721. Scope is limited to fixing user-visible DeepSeek tool-call leakage; no refactoring is included.
- Real DSML token format uses **double** full-width vertical bars: `<｜｜DSML｜｜...>` (each `｜` is U+FF5C). Confirmed against captured live SSE samples; do not "correct" to single-bar form.
- The plugin is gated by `isDeepSeekModel(model)` in `PluginBuilder.ts`, so non-DeepSeek paths are not affected.
- 8 unit tests in `deepseekDsmlParserPlugin.test.ts` cover the captured SSE sample, lifecycle ordering, finishReason rewrite, no-DSML-leak invariant, mixed text+DSML, plain-text passthrough, unclosed-block fallback, and tag-split-across-chunks recovery.

### Checklist

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. Check this only when the PR introduces or changes a user-facing feature or behavior.
- [x] Self-review: I have reviewed my own code (e.g., via [`/gh-pr-review`](/.claude/skills/gh-pr-review/SKILL.md), `gh pr diff`, or GitHub UI) before requesting review from others

### Release note

```release-note
Fix DeepSeek responses leaking DSML tool-call markup as plain text. The renderer now parses DSML blocks into proper AI SDK tool calls so multi-step web search and other agent flows resume correctly when the upstream parser fails.
```

### CODE REVIEW

File: src/renderer/src/aiCore/plugins/searchOrchestrationPlugin.ts [hunk 1]
```diff
@@ -138,9 +137,10 @@ async function analyzeSearchIntent(
       hasKnowledgeSearch: needKnowledgeExtract
     })
 
-    const { text: result } = await generateText({
-      model: context.model as LanguageModel,
-      prompt: formattedPrompt
+    const result = await fetchGenerate({
```
Comment (zhangjiadi225) [inline src/renderer/src/aiCore/plugins/searchOrchestrationPlugin.ts:140]: **[A3]** After this change, intent-analysis failures no longer preserve the existing fallback behavior. `fetchGenerate` catches errors internally and returns an empty string, so the outer `catch` here will not run. `extractInfoFromXML("")` then returns an empty object, which means the web/knowledge search tools are not added. Previously, a generation failure reached `getFallbackResult()`, allowing search to continue with the original user question as the fallback query. Please check for an empty `result.trim()` and return `getFallbackResult()` in that case, or use a generation path that propagates errors so the existing fallback path is preserved.

**Review by zhangjiadi225 — COMMENTED** [review]
Found one search fallback regression that should be addressed. I reviewed the WebSearchTool cache concern as well, but it matches the existing test contract, so I did not file it as a review comment.

File: src/renderer/src/aiCore/plugins/searchOrchestrationPlugin.ts (hunk 1 above)
Comment (DeJeune) [reply src/renderer/src/aiCore/plugins/searchOrchestrationPlugin.ts:140]: Good catch — fixed in ad071a413. Since `fetchGenerate` swallows errors and returns `''`, the outer `catch` indeed never fired. Added an empty-result check that routes through `getFallbackResult()` so search still runs against the original user question.

**Review by zhangjiadi225 — APPROVED** [review]
Approved.

File: src/renderer/src/aiCore/plugins/deepseekDsmlParserPlugin.ts [hunk 2]
```diff
@@ -0,0 +1,307 @@
...
+        if (before) newContent.push({ ...part, text: before })
+        for (const call of calls) {
+          newContent.push({
+            type: 'tool-call',
+            toolCallId: generateToolCallId(),
+            toolName: call.toolName,
+            input: JSON.stringify(call.args)
+          })
+        }
+        if (after) newContent.push({ ...part, text: after })
```
Comment (jidan745le) [inline src/renderer/src/aiCore/plugins/deepseekDsmlParserPlugin.ts]: > [\!NOTE]
> This comment was translated by Claude.

**[A1]** In non-streaming `wrapGenerate`, each text part only processes the first `<｜｜DSML｜｜tool_calls>` block. Subsequent complete DSML blocks remain in `after` as plain text and are output. When `streamOutput: false`, it goes through `simulateStreamingMiddleware -> wrapGenerate`, so multiple DSML blocks may still leak. Suggestion: either loop-parse blocks within each text part until no complete blocks remain, or reuse the same parser logic.

---
<details>
<summary>Original Content</summary>

**[A1]** 非流式 `wrapGenerate` 每个 text part 只处理第一个 `<｜｜DSML｜｜tool_calls>` block，后续完整 DSML block 会留在 `after` 里作为普通文本继续输出。`streamOutput: false` 时会走 `simulateStreamingMiddleware -> wrapGenerate`，所以多段 DSML 仍可能泄漏。建议把 text part 里的 block 循环解析到没有下一个完整 block，或复用同一套 parser 逻辑。

</details>

File: src/renderer/src/aiCore/plugins/deepseekDsmlParserPlugin.ts [hunk 3]
```diff
@@ -0,0 +1,307 @@
...
+            input: inputJson
+          })
+        }
+
+        if (calls.length > 0) {
+          extractedToolCalls = true
+          logger.info(`Parsed ${calls.length} DSML tool call(s)`, {
+            tools: calls.map((c) => c.toolName)
+          })
+        } else {
```
Comment (jidan745le) [inline src/renderer/src/aiCore/plugins/deepseekDsmlParserPlugin.ts]: > [\!NOTE]
> This comment was translated by Claude.

> **[A3]** When the streaming path encounters a closed DSML block that cannot be parsed into an invoke, it only logs a warning, then clears the buffer, and does not fall back to outputting the original content. This will silently swallow the model output and make the "fallback to text on parse failure" behavior incomplete. It is recommended to re-emit the original `TOOL_CALLS_OPEN + blockContent + TOOL_CALLS_CLOSE` as a `text-delta` when `calls.length === 0`, or explicitly treat this case as a deliberate drop and add tests.

---
<details>
<summary>Original Content</summary>

**[A3]** 流式路径遇到已闭合但无法解析出 invoke 的 DSML block 时，只记录 warning，然后清空 buffer，不会 fallback 输出原内容。这会静默吞掉模型输出，也会让"解析失败时回退为文本"的行为不完整。建议在 `calls.length === 0` 时把原始 `TOOL_CALLS_OPEN + blockContent + TOOL_CALLS_CLOSE` 作为 `text-delta` 重新发出，或明确把这种情况作为 deliberate drop 并补测试。

</details>

**Review by jidan745le — COMMENTED** [review]
Reviewed the DSML parser hotfix and left two inline comments around parser fallback and multi-block handling.

File: src/renderer/src/aiCore/plugins/deepseekDsmlParserPlugin.ts (hunk 2 above)
Comment (DeJeune) [reply src/renderer/src/aiCore/plugins/deepseekDsmlParserPlugin.ts]: Fixed in cdbb775f7. `wrapGenerate` now loops through each text part, extracting every complete `<｜｜DSML｜｜tool_calls>` block instead of stopping after the first. Added a test (`extracts multiple DSML blocks within a single text part`) covering the leak you described.

File: src/renderer/src/aiCore/plugins/deepseekDsmlParserPlugin.ts (hunk 3 above)
Comment (DeJeune) [reply src/renderer/src/aiCore/plugins/deepseekDsmlParserPlugin.ts]: Fixed in cdbb775f7. When `calls.length === 0`, both the streaming `drainDsmlBuffer` and the non-streaming `wrapGenerate` now re-emit the original `TOOL_CALLS_OPEN + blockContent + TOOL_CALLS_CLOSE` as text instead of silently dropping it. Added tests in both paths (`emits the original DSML markup as text when a closed block has no parseable invoke` and `preserves a closed DSML block that contains no parseable invoke as text`).

**Review by jidan745le — APPROVED** [review]
LGTM. Re-reviewed cdbb775f7; the DSML multi-block parsing and unparseable-block fallback issues are fixed with targeted tests, and CI is green.

**Review by jidan745le — APPROVED** [review]
