### PR TITLE
fix(codeblock): copy modified content after edit

### LINKED ISSUE #12808: [Bug]: Code block copy the original text after saving changes
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.7.16

### Bug Description

Image
like this, if I change something and hit save button, then I press copy button, I get the original text instead of the changed version.

### Steps To Reproduce

change and save and copy (in code block)

### Expected Behavior

fix it. I'm not sure if this issue occurs in copy button at the bottom of the reply.

### Relevant Log Output

```shell

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by GeorgeDong32**
### What this PR does

Before this PR:
- The Copy button on code blocks copied the original source content even if the user had edited the code in the editor.

After this PR:
- The copy action uses the editor's current content so modified code is copied.
- Added getContent method to CodeEditorHandles interface.
- handleCopySource now retrieves content via editor ref (with fallback to children prop if editor ref is unavailable).

Fixes #12808

### Why we need it and why it was done in this way

The following tradeoffs were made:
- Using editor ref ensures we copy live edits; falling back to children preserves behavior when the editor instance is not present.

### Breaking changes

- None

### Special notes for your reviewer

- Ensure the editor ref implements getContent; otherwise the fallback will be used.

### Checklist

- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: Write code that humans can understand and Keep it simple
- [ ] Refactor: Left the code cleaner than found
- [ ] Upgrade: Considered upgrade flow impact
- [ ] Documentation: User-guide update not required

### Release note

```release-note
fix(codeblock): copy modified content after edit
```

### CODE REVIEW

File: src/renderer/src/components/CodeBlockView/view.tsx [hunk 1]
```diff
@@ -128,7 +128,9 @@ export const CodeBlockView: React.FC<Props> = memo(({ children, language, onSave
   }, [])
 
   const handleCopySource = useCallback(() => {
-    navigator.clipboard.writeText(children.trimEnd())
+    // Prioritize getting content from editor, fallback to children
+    const content = sourceViewRef.current?.getContent?.() ?? children
```
Comment (EurFelux) [inline src/renderer/src/components/CodeBlockView/view.tsx]: > [!NOTE]
> This issue/comment/review was translated by Claude.

The dependency array of `handleCopySource` only has `[children, t]`, but it now reads the editor content through `sourceViewRef.current?.getContent?.()`.

This won't cause a bug because `sourceViewRef` is a ref (reference is stable), and `getContent` reads `editorViewRef.current.state.doc` in real-time each time it's called, so it can get the latest content even if it's not in the dependency array.

However, I suggest adding a comment explaining why the dependency array doesn't need to include the ref, so other developers won't misunderstand it as an omission.

(nit, non-blocking)

---
<details>
<summary>Original Content</summary>

`handleCopySource` 的依赖数组只有 `[children, t]`，但现在它通过 `sourceViewRef.current?.getContent?.()` 读取编辑器内容。

这不会导致 bug，因为 `sourceViewRef` 是一个 ref（引用稳定），`getContent` 每次调用都会实时读取 `editorViewRef.current.state.doc`，所以即使不在依赖数组中也能拿到最新内容。

不过建议加一个注释说明为什么依赖数组不需要包含 ref，这样其他开发者不会误解为遗漏。

(nit, non-blocking)

</details>

File: src/renderer/src/components/CodeEditor/index.tsx [hunk 2]
```diff
@@ -185,10 +186,17 @@ const CodeEditor = ({
...
-    scrollToLine
-  }))
+  useImperativeHandle(
+    ref,
+    () => ({
+      save: handleSave,
+      scrollToLine,
+      getContent: () => {
+        return editorViewRef.current?.state.doc.toString() ?? ''
+      }
```
Comment (EurFelux) [inline src/renderer/src/components/CodeEditor/index.tsx]: Good catch adding the dependency array `[handleSave, scrollToLine]` to `useImperativeHandle` — the previous code was missing it entirely, which meant the handle object was stale if `handleSave` or `scrollToLine` changed.

One thought: `getContent` captures `editorViewRef` via closure, and `editorViewRef` is a stable ref, so it doesn't need to be in the deps array. This is fine. But to be explicit and consistent, consider extracting `getContent` into a `useCallback`:

```tsx
const getContent = useCallback(() => {
  return editorViewRef.current?.state.doc.toString() ?? ''
}, [])
```

Then pass it to the handle object. This keeps `useImperativeHandle` lean and makes `getContent` reusable if needed elsewhere.

(suggestion, non-blocking)

File: src/renderer/src/components/CodeBlockView/view.tsx [hunk 3]
```diff
@@ -128,7 +128,9 @@ export const CodeBlockView: React.FC<Props> = memo(({ children, language, onSave
   }, [])
 
   const handleCopySource = useCallback(() => {
-    navigator.clipboard.writeText(children.trimEnd())
+    // Prioritize getting content from editor, fallback to children
```
Comment (EurFelux) [inline src/renderer/src/components/CodeBlockView/view.tsx]: > [!NOTE]
> This issue/comment/review was translated by Claude.

Note: In the same file, `handleDownloadSource` (line 135-150) and `handleRunScript` (line 152-170) also directly use `children` instead of the editor's latest content. This means that if users edit the code and then download or run it, they will still get the original content, not the edited version.

It is recommended to apply this pattern consistently to `handleDownloadSource` and `handleRunScript`, otherwise it will cause an inconsistent user experience: copying gives the modified content, but downloading and running give the original content.

(issue, non-blocking — can be a follow-up)

---
<details>
<summary>Original Content</summary>

注意：同一个文件中的 `handleDownloadSource`（line 135-150）和 `handleRunScript`（line 152-170）也直接使用了 `children` 而非编辑器的最新内容。这意味着如果用户编辑了代码后下载或运行，得到的仍然是原始内容，而不是编辑后的版本。

建议将此 pattern 统一应用到 `handleDownloadSource` 和 `handleRunScript`，否则会造成不一致的用户体验：复制得到的是修改后的内容，但下载和运行得到的却是原始内容。

(issue, non-blocking — 可以作为 follow-up)

</details>

**Review by EurFelux — COMMENTED** [review]
> [!NOTE]
> This issue/comment/review was translated by Claude.

## Review Summary

This is a concise, focused bug fix that resolves the issue where copying still retrieved the original content after editing code blocks. The implementation approach is reasonable—exposing `getContent` through `useImperativeHandle`, prioritizing fetching the latest content from the editor when copying, and retaining the fallback.

### Highlights
- Correctly uses optional chaining `?.getContent?.()` for safe access, ensuring compatibility under `CodeViewer` (non-editing mode)
- Fixed the missing dependency array for `useImperativeHandle`, which is a valuable accompanying fix

### Points to Note
- **Consistency Issue**: `handleDownloadSource` and `handleRunScript` also use `children`, so downloading/running after editing will get the original content. Suggested to handle uniformly as a follow-up
- Two minor suggestions, both non-blocking

Overall: LGTM, the fix direction is correct and the scope of changes is reasonable.

File: src/renderer/src/components/CodeBlockView/view.tsx [hunk 4]
```diff
@@ -128,7 +128,9 @@ export const CodeBlockView: React.FC<Props> = memo(({ children, language, onSave
...
+    const content = sourceViewRef.current?.getContent?.() ?? children
+    navigator.clipboard.writeText(content.trimEnd())
     window.toast.success(t('code_block.copy.success'))
```
Comment (EurFelux) [inline src/renderer/src/components/CodeBlockView/view.tsx]: `navigator.clipboard.writeText` returns `Promise<void>`, but there's no `await` here, causing:
1. The toast pops up before the clipboard write is complete
2. If the write fails (e.g., browser permission denied), the error is silently swallowed, and the user sees "Copy successful" but it didn't actually copy

Suggested change:

```tsx
const handleCopySource = useCallback(async () => {
  const content = sourceViewRef.current?.getContent?.() ?? children
  try {
    await navigator.clipboard.writeText(content.trimEnd())
    window.toast.success(t('code_block.copy.success'))
  } catch {
    window.toast.error(t('code_block.copy.failed'))
  }
}, [children, t])
```

Note this is a pre-existing issue (the original code didn't await either), but since this line is being changed, it's good to fix it while we're here.

---

> [!NOTE]
> This comment was translated by Claude.

---

<details>
<summary>Original Content</summary>

`navigator.clipboard.writeText` 返回 `Promise<void>`，但这里没有 `await`，导致：
1. toast 在剪贴板写入完成之前就弹出了
2. 如果写入失败（例如浏览器权限被拒绝），错误会被静默吞掉，用户看到"复制成功"但实际没复制上

建议改为：

```tsx
const handleCopySource = useCallback(async () => {
  const content = sourceViewRef.current?.getContent?.() ?? children
  try {
    await navigator.clipboard.writeText(content.trimEnd())
    window.toast.success(t('code_block.copy.success'))
  } catch {
    window.toast.error(t('code_block.copy.failed'))
  }
}, [children, t])
```

注意这是一个 pre-existing issue（原来的代码就没 await），不过既然改到了这一行，顺手修掉也挺好。

</details>

**Review by EurFelux — COMMENTED** [review]
> [!NOTE]
> This review was translated by Claude.

Adding one more missed point: `navigator.clipboard.writeText` is an asynchronous API, currently there is no await, the toast will pop up prematurely and errors will be silently swallowed. Although this is a pre-existing issue, since this line is being changed this time, it is recommended to fix it by the way.

---
<details>
<summary>Original Content</summary>

补充一个遗漏的点：`navigator.clipboard.writeText` 是异步 API，当前没有 await，toast 会提前弹出且错误被静默吞掉。虽然是 pre-existing issue，但既然这次改动了这一行，建议顺手修复。

</details>

**Review by DeJeune — APPROVED** [review]
