### PR TITLE
fix(agents): sync agent settings changes to active session

### LINKED ISSUE #14197: [Bug]: Agent permission mode changes do not take effect in current session
> [\!NOTE]
> This issue was translated by Claude.

### Issue Checklist
- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform
macOS

### Version
v1.9.1

### Bug Description
After modifying an Agent's permission mode (e.g., switching to fully automatic mode) in settings, the change does not take effect in the current session. The user must create a new session for the updated permission mode to apply.

### Steps To Reproduce
1. Open an Agent conversation
2. Go to Agent settings and change the permission mode (e.g., to fully automatic)
3. Return to the current conversation
4. The permission mode is still the old one
5. Only after creating a new session does the new permission mode apply

### Expected Behavior
Permission mode changes should take effect immediately in the current session (hot reload) without requiring a new session.

### Additional Context
**Priority: P1**

Found during v1.9.1 system testing.

---

<details>
<summary>Original Content</summary>

修改 Agent 权限模式（如切换到全自动模式）后，当前会话不生效，必须新开会话。

优化建议：权限模式修改应支持当前会话热生效。

</details>

### PR DESCRIPTION
**Pull request by DeJeune**
### What this PR does

Before this PR:
When modifying agent-level settings (permission mode, model, allowed tools, MCPs, instructions) via the Agent Settings popup, changes only took effect in newly created sessions. The currently active session kept using stale configuration, requiring users to create a new session to see the update.

After this PR:
Agent settings changes are automatically synced to all sessions belonging to that agent. Sessions where the user has intentionally customized a field are left untouched.

Fixes #14197

### Why we need it and why it was done in this way

The agent–session architecture uses a snapshot model: sessions inherit agent configuration at creation time and then diverge independently. This is correct for session-level overrides, but when users edit agent-level settings (the "template"), they expect changes to apply to existing conversations.

The sync is implemented in the backend `AgentService.updateAgent`: after updating the agent, it queries all sessions for that agent and compares each session field against the agent's **old** value. If they match, the session inherited the default and receives the new value. If they differ, the user customized that field on the session, so it's skipped.

The frontend `useUpdateAgent` hook revalidates the active session's SWR cache so the UI reflects changes immediately.

The following tradeoffs were made:
- Comparison is done on serialized (JSON string) values for simplicity and correctness with complex fields like `configuration` and `allowed_tools`.
- Sync failure is logged but does not fail the agent update.

The following alternatives were considered:
- Frontend-only sync (read active session from Redux, call updateSession API): rejected because it only syncs the active session and relies on ephemeral UI state.
- Tracking a `customized_fields` set on each session: rejected as over-engineered; comparing against old values achieves the same result without schema changes.

### Breaking changes

None.

### Special notes for your reviewer

The synced fields are: `model`, `plan_model`, `small_model`, `allowed_tools`, `configuration`, `mcps`, `instructions`. Identity/workspace fields (`name`, `description`, `accessible_paths`) are intentionally excluded.

### Checklist

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. Check this only when the PR introduces or changes a user-facing feature or behavior.
- [x] Self-review: I have reviewed my own code (e.g., via [`/gh-pr-review`](/.claude/skills/gh-pr-review/SKILL.md), `gh pr diff`, or GitHub UI) before requesting review from others

### Release note

```release-note
Agent settings changes (permission mode, model, tools, etc.) now take effect immediately in all sessions without requiring a new session. Sessions with user-customized fields are preserved.
```

### CODE REVIEW

File: src/main/services/agents/services/AgentService.ts [hunk 1]
```diff
@@ -383,9 +383,75 @@ export class AgentService extends BaseService {
...
+          if (oldAgentValue === sessionValue) {
+            sessionUpdateData[field] = serializedUpdates[field] ?? null
+          }
+        }
+
+        if (Object.keys(sessionUpdateData).length > 0) {
+          sessionUpdateData.updated_at = now
+          await database.update(sessionsTable).set(sessionUpdateData).where(eq(sessionsTable.id, session.id))
+        }
+      }
```
Comment (EurFelux) [inline src/main/services/agents/services/AgentService.ts]: Session updates are not wrapped in a transaction. If the process crashes mid-loop, some sessions would be updated while others remain stale, leading to inconsistent state.

Consider wrapping the loop in a `database.transaction()`:
```typescript
await database.transaction(async (tx) => {
  for (const session of sessions) {
    // ...comparison logic...
    if (Object.keys(sessionUpdateData).length > 0) {
      sessionUpdateData.updated_at = now
      await tx.update(sessionsTable).set(sessionUpdateData).where(eq(sessionsTable.id, session.id))
    }
  }
})
```

This also has the benefit of being faster on SQLite — batching writes in a single transaction avoids per-statement fsync overhead.

File: src/main/services/agents/services/AgentService.ts [hunk 2]
```diff
@@ -383,9 +383,75 @@ export class AgentService extends BaseService {
...
+    if (changedFields.length === 0) return
+
+    try {
+      const sessions = await database.select().from(sessionsTable).where(eq(sessionsTable.agent_id, agentId))
+
+      if (sessions.length === 0) return
+
+      const now = new Date().toISOString()
+      const serializedUpdates = this.serializeJsonFields(updates)
+      const serializedOldAgent = this.serializeJsonFields(oldAgent)
```
Comment (EurFelux) [inline src/main/services/agents/services/AgentService.ts]: `this.serializeJsonFields(updates)` is already computed in the calling method `updateAgent` at line 365. Consider passing the pre-computed `serializedUpdates` as a parameter to avoid redundant work.

Similarly, `serializedOldAgent` round-trips through deserialize→serialize (the `existing` entity was deserialized from DB, then re-serialized here). While JSON key order is generally preserved through `JSON.parse` → `JSON.stringify`, be aware that any intermediate transformation (e.g. Zod schema parsing in `convertToEntity`) could theoretically reorder keys, causing the string comparison to mismatch even when values are semantically equal. In practice this is unlikely, but worth a defensive note.

File: src/main/services/agents/services/AgentService.ts [hunk 3]
```diff
@@ -383,9 +383,75 @@ export class AgentService extends BaseService {
...
+  private async syncSettingsToSessions(
+    database: Awaited<ReturnType<typeof this.getDatabase>>,
+    agentId: string,
+    oldAgent: AgentEntity,
+    updates: UpdateAgentRequest
+  ): Promise<void> {
+    const syncFields = ['model', 'plan_model', 'small_model', 'allowed_tools', 'configuration', 'mcps', 'instructions']
+
+    // Collect only the fields that were actually changed
+    const changedFields = syncFields.filter((field) => Object.prototype.hasOwnProperty.call(updates, field))
```
Comment (EurFelux) [inline src/main/services/agents/services/AgentService.ts]: This only checks whether the field **exists** in `updates`, not whether the value actually **changed**. If a caller sends `{ model: "same-model-as-before" }`, every session would get a redundant UPDATE.

Consider also filtering out no-op changes:
```typescript
const changedFields = syncFields.filter((field) => {
  if (!Object.prototype.hasOwnProperty.call(updates, field)) return false
  return serializedUpdates[field] !== serializedOldAgent[field]
})
```
(This also requires moving the serialize calls above this filter.)

File: src/renderer/src/hooks/agents/useUpdateAgent.ts [hunk 4]
```diff
@@ -26,6 +27,16 @@ export const useUpdateAgent = () => {
...
         }
+
+        // Backend syncs agent settings to all sessions (skipping user-customized fields).
+        // Revalidate the active session's SWR cache so the UI picks up changes immediately.
+        const { activeSessionIdMap } = store.getState().runtime.chat
+        const activeSessionId = activeSessionIdMap[form.id]
+        if (activeSessionId) {
+          const sessionKey = client.getSessionPaths(form.id).withId(activeSessionId)
+          void mutate(sessionKey)
+        }
```
Comment (EurFelux) [inline src/renderer/src/hooks/agents/useUpdateAgent.ts:40]: Two observations:

1. Direct `store.getState()` access in a hook is a pragmatic choice here (avoids adding `activeSessionIdMap` to `useCallback` deps), but it's worth a brief inline comment explaining why we're bypassing the React-Redux `useSelector` pattern.

2. This only revalidates the **currently active** session. Other sessions belonging to the same agent may also have been synced by the backend but won't refresh until the user navigates to them (at which point SWR's stale-while-revalidate kicks in). This is probably fine for UX — just calling it out for awareness.

**Review by EurFelux — COMMENTED** [review]
Nice approach — the "compare against old agent value" strategy is clean and avoids schema changes. A few suggestions, the most impactful being wrapping session updates in a transaction for both correctness and SQLite write performance.

Edit: This review is completed by Claude, no human comments involved

File: src/main/services/agents/services/AgentService.ts [hunk 5]
```diff
@@ -383,9 +383,75 @@ export class AgentService extends BaseService {
...
+   * should receive the new value. If they differ, the user customized that field on
+   * the session, so we skip it.
+   */
+  private async syncSettingsToSessions(
+    database: Awaited<ReturnType<typeof this.getDatabase>>,
+    agentId: string,
+    oldAgent: AgentEntity,
+    updates: UpdateAgentRequest
+  ): Promise<void> {
+    const syncFields = ['model', 'plan_model', 'small_model', 'allowed_tools', 'configuration', 'mcps', 'instructions']
```
Comment (EurFelux) [inline src/main/services/agents/services/AgentService.ts:417]: The fundamental issue this PR tries to solve is real — users expect agent setting changes to take effect immediately. But the approach of blanket-syncing all fields to all sessions doesn't hold up under architectural scrutiny.

**The settings in `syncFields` are not all the same kind of setting.** In Claude Code's framework:

- **Permission mode** → session-level; the agent itself doesn't own this setting
- **Model** → user-level (in Cherry Studio's multi-agent design, this maps to agent-level)
- **Allowed tools / MCPs** → project-level + user-level, with merge semantics (project-level wins)
- **Instructions** → multi-layered (user / project / session)

This PR treats them all identically — "if the session value matches the old agent value, overwrite it" — which erases the distinction between levels.

**The deeper question this exposes:** if agent settings are always synced down to sessions, what is the purpose of having session-level settings at all? Why not just read from the agent config directly and let sessions only store true overrides? The current snapshot-then-sync model creates a worst-of-both-worlds situation: sessions carry copies of agent state, but those copies are forcibly kept in sync, so they're neither independent nor derived.

Before implementing a sync mechanism, the architecture needs to answer:
1. Which settings are agent-level defaults vs. session-level overrides?
2. Should sessions inherit from agents at read time (derived) rather than copy at write time (snapshot)?
3. How do project-level settings (tools, MCPs) interact with agent-level and session-level?

Without answering these, this PR risks cementing an architecture that will need to be reworked.

**Review by EurFelux — CHANGES_REQUESTED** [review]
Thanks for identifying a real pain point — users do expect agent setting changes to apply immediately, and that's worth solving.

However, this PR addresses the surface symptom without examining the underlying architectural problem. The core issue is that our agent/session setting model doesn't distinguish between setting levels: some settings are semantically agent-level defaults, some are session-level, and some should be project-level. Blindly syncing all of them from agent to session is a shortcut that:

1. **Ignores setting semantics** — permission mode is inherently session-scoped, model config is agent-scoped, tools/MCPs span project and agent levels. Treating them uniformly is incorrect.
2. **Creates a contradictory model** — if agent settings always sync to sessions, session-level settings have no real independence. The snapshot model loses its purpose.
3. **Doesn't consider alternatives** — e.g., should sessions *derive* certain fields from the agent at read time instead of copying at write time? Should the UI distinguish which settings are "agent defaults" vs "session overrides"?

I'd suggest stepping back and thinking about:
- What level does each setting belong to?
- Which settings should sync (agent-level defaults) vs. which should not (session-level)?
- Can copy/UX guide users to understand the distinction rather than hiding it behind implicit sync?

This needs a clearer design before implementation.

**Review by DeJeune — COMMENTED** [review]
Thanks for the thorough architectural analysis. You're right that the settings have different semantic levels and the current snapshot-then-sync model is not the ideal long-term solution.

The deeper questions you raised — setting level taxonomy, derived-at-read vs snapshot-at-write, project/agent/session layering — are exactly the kind of design work that belongs in the v2 refactor. The `main` branch is under code freeze and this hotfix is intentionally minimal: fix the immediate UX pain (P1 bug) without introducing architectural changes.

For v2, the direction you suggest (sessions deriving certain fields from the agent at read time, with explicit session-level overrides) is worth exploring. I'll open an issue to track this as part of the v2 agent/session settings redesign.

**Review by EurFelux — APPROVED** [review]
Acceptable as a v1 workaround. The architectural concerns (setting level taxonomy, derived vs snapshot model) are tracked for v2.

File: src/main/services/agents/services/AgentService.ts [hunk 6]
```diff
@@ -383,9 +383,80 @@ export class AgentService extends BaseService {
...
+
+      if (sessions.length === 0) return
+
+      const now = new Date().toISOString()
+
+      await database.transaction(async (tx) => {
+        for (const session of sessions) {
+          const sessionUpdateData: Partial<Record<string, unknown>> = {}
+
+          for (const field of changedFields) {
```
Comment (GeorgeDong32) [inline src/main/services/agents/services/AgentService.ts:439]: > [\!NOTE]
> This issue/comment/review was translated by Claude.

**Suggestion: Add unit tests to cover sync logic**

The current PR lacks unit tests. It is recommended to add the following test scenarios:

1. **Normal sync**: When session value matches oldAgent value, it should be updated correctly
2. **Skip custom**: When session value differs from oldAgent value, that field should be skipped
3. **Error isolation**: Sync failures should not prevent the agent update from succeeding
4. **JSON field comparison**: Verify the comparison behavior of complex fields like `configuration`, `mcps`, etc.
5. **Empty session list**: Should exit gracefully when there are no sessions

Reference test framework: `vitest`, reference directory: `src/main/services/agents/__tests__/`

---
<details>
<summary>Original Content</summary>

**建议：添加单元测试覆盖同步逻辑**

当前 PR 缺少单元测试，建议添加以下测试场景：

1. **正常同步**：session 值与 oldAgent 值匹配时，应正确更新
2. **跳过自定义**：session 值与 oldAgent 值不匹配时，应跳过该字段
3. **错误隔离**：同步失败时不应影响 agent 更新的成功
4. **JSON 字段比较**：验证 `configuration`、`mcps` 等复杂字段的比较行为
5. **空 session 列表**：无 session 时应优雅退出

参考测试框架：`vitest`，参考目录：`src/main/services/agents/__tests__/`

</details>

File: src/main/services/agents/services/AgentService.ts [hunk 7]
```diff
@@ -383,9 +383,80 @@ export class AgentService extends BaseService {
...
+
+    // Only sync fields that are present in the update AND actually changed
+    const changedFields = syncFields.filter((field) => {
+      if (!Object.prototype.hasOwnProperty.call(serializedUpdates, field)) return false
+      return (serializedUpdates[field] ?? null) !== (serializedOldAgent[field] ?? null)
+    })
+    if (changedFields.length === 0) return
+
+    try {
+      const sessions = await database.select().from(sessionsTable).where(eq(sessionsTable.agent_id, agentId))
```
Comment (GeorgeDong32) [inline src/main/services/agents/services/AgentService.ts:429]: > [\!NOTE]
> This comment was translated by Claude.

**✅ Good Practice: Using Transactions to Wrap Batch Updates**

Using `database.transaction()` to wrap all session updates is the correct approach, ensuring:
1. Atomicity: Either all succeed or all are rolled back
2. Performance: Reduces database connection overhead
3. Consistency: Avoids data inconsistency from partial updates

---
<details>
<summary>Original Content</summary>

**✅ 良好实践：使用事务包装批量更新**

这里使用 `database.transaction()` 包装所有 session 更新是正确的做法，确保：
1. 原子性：要么全部成功，要么全部回滚
2. 性能：减少数据库连接开销
3. 一致性：避免部分更新导致数据不一致

</details>

File: src/renderer/src/hooks/agents/useUpdateAgent.ts [hunk 8]
```diff
@@ -26,6 +27,18 @@ export const useUpdateAgent = () => {
...
         }
+
+        // Backend syncs agent settings to all sessions (skipping user-customized fields).
+        // Revalidate the active session's SWR cache so the UI picks up changes immediately.
+        // Other sessions refresh via SWR stale-while-revalidate when navigated to.
+        // Using store.getState() instead of useSelector to avoid adding reactive deps to useCallback.
+        const { activeSessionIdMap } = store.getState().runtime.chat
+        const activeSessionId = activeSessionIdMap[form.id]
+        if (activeSessionId) {
+          const sessionKey = client.getSessionPaths(form.id).withId(activeSessionId)
```
Comment (GeorgeDong32) [inline src/renderer/src/hooks/agents/useUpdateAgent.ts:38]: > [\!NOTE]
> This comment was translated by Claude.

**✅ Good Practice: Correctly Trigger SWR Cache Update**

Using `store.getState()` instead of `useSelector` here is reasonable:
- Avoids additional dependencies from `useCallback`
- Reads once only after success, no need for reactive subscription
- `void mutate()` correctly handles async operations

However, suggest adding optional chaining protection:
```typescript
const activeSessionId = activeSessionIdMap?.[form.id]
```
To guard against edge cases where `activeSessionIdMap` might be undefined.

---
<details>
<summary>Original Content</summary>

**✅ 良好实践：正确触发 SWR 缓存更新**

这里使用 `store.getState()` 而非 `useSelector` 是合理的：
- 避免 `useCallback` 产生额外的依赖
- 只在成功后一次性读取，无需响应式订阅
- `void mutate()` 正确处理异步操作

但建议添加可选链保护：
```typescript
const activeSessionId = activeSessionIdMap?.[form.id]
```
以防 `activeSessionIdMap` 为 undefined 的边缘情况。

</details>

File: src/main/services/agents/services/AgentService.ts [hunk 9]
```diff
@@ -383,9 +383,80 @@ export class AgentService extends BaseService {
...
+      await database.transaction(async (tx) => {
+        for (const session of sessions) {
+          const sessionUpdateData: Partial<Record<string, unknown>> = {}
+
+          for (const field of changedFields) {
+            const oldAgentValue = serializedOldAgent[field] ?? null
+            const sessionValue = (session as Record<string, unknown>)[field] ?? null
+
+            // Only sync if session still has the agent's old value (not user-customized)
+            if (oldAgentValue === sessionValue) {
```
Comment (GeorgeDong32) [inline src/main/services/agents/services/AgentService.ts]: > [\!NOTE]
> This issue/comment/review was translated by Claude.

**⚠️ Bug: Unstable JSON Field Comparison**

For the `allowed_tools` field, the string `===` comparison here may produce incorrect results:

**Root Cause**:
1. `oldAgent` comes from `getAgent()`, its `allowed_tools` has been normalized by `normalizeAllowedTools()` (legacy ID → canonical ID)
2. `session` is queried directly from the database, `allowed_tools` may still be in the original legacy ID format
3. Even if semantically identical, the normalized JSON string differs from the original string

**Example**:
```
oldAgent.allowed_tools: "[\"mcp__serverName__toolName\"]"  // canonical
session.allowed_tools:   "[\"mcp_serverId_toolName\"]"     // legacy
// Comparison result: false, but they are semantically "inherited same value"
```

**Suggested Fix**: Normalize the session's `allowed_tools` before comparison, or use deep comparison instead of string comparison.

**Impact Scope**: Only affects users with legacy MCP tool ID format data, new users are unaffected.

---
<details>
<summary>Original Content</summary>

**⚠️ Bug: JSON 字段比较不稳定**

对于 `allowed_tools` 字段，这里的字符串 `===` 比较可能产生错误结果：

**问题根因**：
1. `oldAgent` 来自 `getAgent()`，其 `allowed_tools` 已被 `normalizeAllowedTools()` 规范化（legacy ID → canonical ID）
2. `session` 直接从数据库查询，`allowed_tools` 可能仍是原始 legacy ID 格式
3. 即使语义相同，规范化后的 JSON 字符串与原始字符串不同

**示例**：
```
oldAgent.allowed_tools: "[\"mcp__serverName__toolName\"]"  // canonical
session.allowed_tools:   "[\"mcp_serverId_toolName\"]"     // legacy
// 比较结果: false，但它们语义上是"继承的相同值"
```

**建议修复**：对 session 的 `allowed_tools` 也进行规范化后再比较，或使用深度比较而非字符串比较。

**影响范围**：仅影响使用 legacy MCP tool ID 格式的旧数据用户，新用户不受影响。

</details>

**Review by GeorgeDong32 — CHANGES_REQUESTED** [review]
> [\!NOTE]
> This review was translated by Claude.

## Review Summary

Reasonable bug fix, but there is a bug that affects users with old data.

### 🔴 Must Fix

**allowed_tools JSON comparison is unstable** (line 431-435)

oldAgent is normalized via normalizeAllowedTools, while session retains the original format. String === comparison will return false when semantically identical, causing sessions to be incorrectly skipped.

Suggestion: Apply normalization to sessions as well, or use deep comparison.

### 🟡 Suggestions

1. Add unit tests to cover synchronization logic
2. Frontend optional chaining protection for activeSessionIdMap

### ✅ Good Practices

- Transaction-wrapped batch updates
- Error isolation doesn't affect main flow
- Proper use of store.getState()

### Conclusion

Request Changes - Please fix the comparison issue before merging.

File: src/main/services/agents/services/AgentService.ts [hunk 10]
```diff
@@ -382,10 +382,90 @@ export class AgentService extends BaseService {
     }
 
     const database = await this.getDatabase()
+
+    // Read the raw agent row before updating — getAgent() normalizes allowed_tools
+    // (legacy ID → canonical ID), but sessions store the original format. We need
+    // the raw DB values so string comparison against sessions is accurate.
```
Comment (GeorgeDong32) [inline src/main/services/agents/services/AgentService.ts:388]: > [\!NOTE]
> This comment was translated by Claude.

**✅ Perfect Fix: Using Original DB Rows for Comparison**

This modification correctly addresses the `allowed_tools` JSON comparison issue raised earlier:

- `getAgent()` normalizes `allowed_tools` (legacy ID → canonical ID)
- Sessions store the original format
- `rawOldAgent` is read directly from DB, preserving the original JSON string format
- Both sides compare in original format, so `===` comparison is accurate

The comments clearly explain the design decisions, and the code is clean and efficient.

---
<details>
<summary>Original Content</summary>

**✅ 完美修复：使用原始 DB 行进行比较**

这个修改正确解决了之前提出的 `allowed_tools` JSON 比较问题：

- `getAgent()` 会规范化 `allowed_tools`（legacy ID → canonical ID）
- Session 存储原始格式
- 直接从 DB 读取 `rawOldAgent`，保留原始 JSON 字符串格式
- 两边比较都是原始格式，`===` 比较准确

注释清晰说明了设计决策，代码简洁高效。

</details>

**Review by GeorgeDong32 — APPROVED** [review]
> [\!NOTE]
> This review was translated by Claude.

## Review Summary

All previously raised blocking issues have been fixed, and the code quality is good.

### ✅ Fix Verification

| Issue | Status |
|------|------|
| allowed_tools JSON comparison unstable | ✅ Fixed - Using rawOldAgent to preserve original format |
| Optional chaining protection for activeSessionIdMap | ✅ Fixed |
| Transaction wrapping for batch updates | ✅ Implemented |
| Filtering meaningless changes | ✅ Implemented |

### 🎯 Conclusion

Code logic is correct, error handling is comprehensive, and comments are clear. Approved.

---
<details>
<summary>Original Content</summary>

## Review Summary

之前提出的阻塞问题已全部修复，代码质量良好。

### ✅ 修复验证

| 问题 | 状态 |
|------|------|
| allowed_tools JSON 比较不稳定 | ✅ 已修复 - 使用 rawOldAgent 保留原始格式 |
| 可选链保护 activeSessionIdMap | ✅ 已修复 |
| 事务包装批量更新 | ✅ 已实现 |
| 过滤无意义变更 | ✅ 已实现 |

### 🎯 结论

代码逻辑正确，错误处理完善，注释清晰。Approve。

</details>
