### PR TITLE
fix(code): validate working directory before launching code tool (#13904)

### LINKED ISSUE #13904: [Bug]: Code tool shows launch success but no interface appears when configured working directory does not exist
> [!NOTE]
> This issue was translated by Claude.

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.8.4

### Bug Description

If the working directory configured in the code tool does not exist. For example, if the folder has been deleted for some reason, but Cherry Studio still has a historical memory of this folder path in the working directory input text box, when starting the code tool, it will show launch success, but there is no code tool (e.g., Claude Code) interface appearing.

Image

### Steps To Reproduce

1. In Code Tool - Working Directory, set it to the `D:\\test` folder path; configure other parameters normally; select Claude Code tool and click launch;
2. At this point, the `Claude Code` tool interface appears normally;
3. Delete the `D:\\test` folder path from the disk;
4. At this point, `Code Tool - Working Directory` still displays as the `D:\\test` folder path;
5. Click the `>_ Launch` button, at this point a `✓ Launch Success` prompt appears, but no code tool (e.g., `Claude Code`) interface appears.

### Expected Behavior

There are 2 expected behaviors:
1. When the code tool interface does not appear in step 5 above after clicking the `>_ Launch` button, can there be an error prompt `Path does not exist`, and do not show the `✓ Launch Success` prompt, because at this point it has not launched successfully;
2. Another behavior is, before clicking the `>_ Launch` button, directly display `Path does not exist` in red text next to the working directory text box, and the `>_ Launch` button is grayed out and unavailable.

### Relevant Log Output

```shell
N/A
```

### Additional Context

_No response_

---
<details>
<summary>Original Content</summary>

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.8.4

### Bug Description

代码工具中已设置的工作目录如不存在。例如因为某些原因删除了该文件夹，但是Cherry Studio仍有历史记忆此文件夹的路径在工作目录输入文本框中，此时，启动代码工具会显示启动成功，但没有代码工具（例如Claude Code）界面出现的问题。

Image

### Steps To Reproduce

1. 代码工具 - 工作目录，设置为`D:\\test`文件夹路径；其他参数正常设置；选择Claude Code代码工具点击启动；
2. 此时`Claude Code`代码工具界面正常出现；
3. 在磁盘上删除`D:\\test`文件夹路径；
4. 此时，`代码工具 - 工作目录`，仍显示为`D:\\test`文件夹路径；
5. 点击`>_启动`按钮，此时出现`✓启动成功`提示，但是没有代码工具（例如`Claude Code`）界面出现。

### Expected Behavior

期待表现行为有2种：
1. 上述5. 点击`>_启动`按钮步骤无法出现代码工具界面时，能否有报错提示`路径不存在`，并且不要出现`✓启动成功`提示，因为此时并没有启动成功。
2. 另一种行为是，在点击`>_启动`按钮`前，直接在工作目录文本框旁边用红字提示`路径不存在`，并且`>_启动`按钮`未灰色不可用。

### Relevant Log Output

```shell
N/A
```

### Additional Context

_No response_

</details>

### PR DESCRIPTION
**Pull request by 404-Page-Found**
### What this PR does

Before this PR:
- Clicking "Launch" for a Code tool could show a "Launch success" toast even if the configured working directory no longer existed, and no tool UI would appear.

After this PR:
- Await the main process `codeTools.run` result and show success only when it returns `{ success: true }`.
- Define a `CodeToolsRunResult` interface in `packages/shared/` and apply it to the return types of `CodeToolsService.run()` and the preload `codeTools.run` binding, ensuring type-safe contract between main and renderer processes.

Fixes #13904

### Why this change

Provides clearer UX and prevents misleading success notifications when the working directory is missing. The renderer-side directory pre-check was removed after review feedback — the main process `CodeToolsService.run()` already validates directory existence via `fs.existsSync()` and returns `{ success: false, message }`, so relying on that single source of truth avoids IPC overhead and TOCTOU race conditions.

### Files changed
- `src/renderer/src/pages/code/CodeToolsPage.tsx` — await `codeTools.run`, handle `success`/`error` branches
- `packages/shared/config/types.ts` — add `CodeToolsRunResult` interface
- `src/main/services/CodeToolsService.ts` — apply `CodeToolsRunResult` return type
- `src/preload/index.ts` — apply `CodeToolsRunResult` return type
- `tsconfig.tsbuildinfo` — remove accidentally committed build artifact

### Release note
```release-note
Bugfix: Only show code tool launch success when the process actually starts, and add type-safe return type for codeTools.run (fixes #13904)
```

### CODE REVIEW

File: src/renderer/src/pages/code/CodeToolsPage.tsx [hunk 1]
```diff
@@ -321,6 +330,20 @@ const CodeToolsPage: FC = () => {
     setIsLaunching(true)
 
     try {
+      // Verify working directory exists before preparing environment
+      if (currentDirectory) {
+        try {
+          const isDir = await window.api.file.isDirectory(currentDirectory)
+          if (!isDir) {
```
Comment (GeorgeDong32) [inline src/renderer/src/pages/code/CodeToolsPage.tsx]: **i18n key 缺失**

`code.launch.workdir_not_found` 和 `code.launch.workdir_check_failed` 这两个 key 未添加到任何语言文件中（en-us、zh-cn 及其余 9 个 locale 均缺失）。

虽然代码用了 `|| 'Path does not exist'` 做英文兜底，但非英文用户会看到硬编码英文 fallback，体验不佳。

建议：
1. 在 `en-us.json` 和 `zh-cn.json` 的 `code.launch` 下补充这两个 key
2. 运行 `pnpm i18n:sync && pnpm i18n:translate` 自动补全其他语言

File: src/renderer/src/pages/code/CodeToolsPage.tsx [hunk 2]
```diff
@@ -321,6 +330,20 @@ const CodeToolsPage: FC = () => {
...
+            window.toast.error(t('code.launch.workdir_not_found') || 'Path does not exist')
+            return
+          }
+        } catch (err) {
+          logger.error('Failed to check working directory existence:', err as Error)
+          window.toast.error(t('code.launch.workdir_check_failed') || 'Failed to check working directory')
+          return
```
Comment (GeorgeDong32) [inline src/renderer/src/pages/code/CodeToolsPage.tsx]: **冗余校验 — 考虑移除 renderer 侧目录检查**

主进程 `CodeToolsService.run()`（L819-827）已经做了 `fs.existsSync(directory)` 校验并返回 `{ success: false, message: '...' }`：

```typescript
// CodeToolsService.ts L819-827
if (!directory || !fs.existsSync(directory)) {
  return { success: false, message: `Directory does not exist: ${directory}`, command: '' }
}
```

而 `executeLaunch` 已经正确 await 了 `run` 的结果并处理 `success: false`，因此这段 renderer 侧的 `isDirectory` 检查是多余的，且带来：
- **多一次 IPC 调用**增加延迟
- **TOCTOU 竞态**：目录在校验后被删除
- 两处重复校验逻辑增加维护负担

建议移除此 block，仅依赖主进程返回值处理失败情况。

File: src/renderer/src/pages/code/CodeToolsPage.tsx [hunk 3]
```diff
@@ -280,8 +280,17 @@ const CodeToolsPage: FC = () => {
...
+    try {
+      const result = await window.api.codeTools.run(selectedCliTool, modelId, currentDirectory, env, runOptions)
+      if (result && result.success) {
+        window.toast.success(t('code.launch.success'))
+      } else {
+        window.toast.error(result?.message || t('code.launch.error'))
+      }
+    } catch (error) {
+      logger.error('codeTools.run failed:', error as Error)
+      window.toast.error(t('code.launch.error'))
```
Comment (GeorgeDong32) [inline src/renderer/src/pages/code/CodeToolsPage.tsx:292]: **`void` → `await` 改进很好**

将 fire-and-forget 的 `void` 改为 `await` 并正确处理 `success`/`error` 分支是核心修复，解决了 "目录不存在时仍显示启动成功" 的问题。

这一点没有争议，是 PR 的核心价值。

**Comment by 404-Page-Found** [comment]
> [!NOTE]
> This issue/comment/review was translated by Claude.

Removed redundant `isDirectory` validation on the renderer side, now relying solely on the main process `CodeToolsService.run()`'s `fs.existsSync` check to eliminate TOCTOU race conditions and unnecessary IPC overhead. Missing i18n keys (`workdir_not_found` / `workdir_check_failed`) were also cleaned up. TypeScript compilation passed.

---
<details>
<summary>Original Content</summary>

已移除 renderer 侧冗余的 `isDirectory` 校验，仅依赖主进程 `CodeToolsService.run()` 的 `fs.existsSync` 检查，消除 TOCTOU 竞态和多余 IPC 开销。缺失的 i18n key（`workdir_not_found` / `workdir_check_failed`）也一并清理。TypeScript 编译通过。

</details>

File: tsconfig.tsbuildinfo
Comment (EurFelux) [inline tsconfig.tsbuildinfo:1]: remove this

File: src/renderer/src/pages/code/CodeToolsPage.tsx [hunk 4]
```diff
@@ -280,8 +280,17 @@ const CodeToolsPage: FC = () => {
...
 
-    void window.api.codeTools.run(selectedCliTool, modelId, currentDirectory, env, runOptions)
-    window.toast.success(t('code.launch.success'))
+    try {
+      const result = await window.api.codeTools.run(selectedCliTool, modelId, currentDirectory, env, runOptions)
+      if (result && result.success) {
+        window.toast.success(t('code.launch.success'))
+      } else {
+        window.toast.error(result?.message || t('code.launch.error'))
+      }
```
Comment (EurFelux) [inline src/renderer/src/pages/code/CodeToolsPage.tsx:289]: `window.api.codeTools.run`缺少返回类型的注释，此处对返回数据的解析依赖`CodeCliService`的已有实现，但未进行任何类型检查。一旦`CodeCliService`的接口改变，这里的解析也将静默出现错误。

并非该 PR 的问题，仅记录。

**Comment by EurFelux** [comment]
> [!NOTE]
> This issue/comment/review was translated by Claude.

After the change scope changes, the PR body should also be updated accordingly.

---
<details>
<summary>Original Content</summary>

变更面发生改变后，PR body 也应同步更新

</details>

**Comment by 404-Page-Found** [comment]
> [!NOTE]
> This issue/comment/review was translated by Claude.

Made the following updates based on review feedback:

1. Defined the `CodeToolsRunResult` interface in `packages/shared/config/types.ts` and applied it to the return types of `CodeToolsService.run()` and preload `codeTools.run` to ensure type safety.
2. Removed the accidentally committed `tsconfig.tsbuildinfo` build artifact.

Please review again, thank you!

---
<details>
<summary>Original Content</summary>

已根据 review 反馈做出以下更新：

1. 在 `packages/shared/config/types.ts` 中定义 `CodeToolsRunResult` 接口，并应用于 `CodeToolsService.run()` 和 preload `codeTools.run` 的返回类型，确保类型安全。
2. 移除了误提交的 `tsconfig.tsbuildinfo` 构建产物。

请各位 reviewer 再次检查，谢谢！

</details>

**Review by EurFelux — APPROVED** [review]
