### PR TITLE
fix: enhance provider handling and API key rotation logic in AiProvider

### LINKED ISSUE #11583: [Bug]: “检测全部密钥”功能未能使用正确密钥以获取结果
> [!NOTE]
> This issue/comment/review was translated by Claude.

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.7.1

### Bug Description

Incorrect key display: Even when the detection result shows "Failed" and prompts "Authentication Fails, Your api key: ****aaaa is invalid", the actual key marked as invalid (****aaaa) is not the current key being detected or causing the failure. According to the screenshot, this incorrect key is another key fragment.
Results do not match expectations: After clicking the detect button on multiple keys, their status should accurately reflect the validity of the current key. However, when detection fails, the error message shows a key that doesn't match the keys in the list, making it impossible for users to accurately determine which key has failed and the specific reason for the failure. This indicates that the application may be incorrectly using rotated API keys when sending validation requests or processing returned results.

Image

Note: Here you can see the left side apikey ends with 7c3, not aaa as shown in the error.

Image

The actual error is from another apikey

At the same time, checking network access requests shows that no request was sent with the key ending in 7c3.

### Steps To Reproduce

1. Open cherry studio --> Settings --> Model Services
2. Enter any model platform with existing available apikey
3. Enter the corresponding key management interface
4. Add a completely wrong key
5. Click "Detect All Keys"
6. Problem occurs

### Expected Behavior

Correctly display the corresponding results for each api_key.

### Relevant Log Output

```shell

```

### Additional Context

This bug can be fully reproduced on my machine, and the error location is identical each time. It might be due to incorrect calling of rotated apikey code.

---
<details>
<summary>Original Content</summary>

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.7.1

### Bug Description

错误的密钥显示： 即使检测结果显示失败并提示 Authentication Fails, Your api key: ****aaaa is invalid，但实际被标记为无效的密钥 ****aaaa 并非当前正在检测或导致失败的密钥。根据截图显示，该错误的密钥是另一个密钥片段。
结果与预期不符： 多个密钥在点击检测按钮后，其状态应该准确反映当前密钥的有效性。然而，目前检测失败时显示的错误信息中的密钥与列表中的密钥不匹配，导致用户无法准确判断哪个密钥失效以及失效的具体原因。这表明在发送验证请求或处理返回结果时，应用程序可能错误地使用了轮换的 API 密钥。

Image

注：此处可见左侧 apikey 结尾为 7c3 而并非错误显示中的 aaa

Image

实际错误的是另一个apikey

同时查找网络访问请求发现并未发送 7c3 结尾密钥

### Steps To Reproduce

1.打开cherry studio --> 设置 --> 模型服务
2.进入任意一个已有可用 apikey 的模型平台
3.进入对应密钥管理界面
4.添加一个完全错误的密钥
5.点击 "检测所有密钥"
6.出现问题

### Expected Behavior

正确展示每个 api_key 的对应结果

### Relevant Log Output

```shell

```

### Additional Context

这个 bug 在本机上可完全复现，同时每次的错误位置完全相同，可能是错误调用了轮换apikey的代码

</details>

### PR DESCRIPTION
**Pull request by DeJeune**
### What this PR does

Before this PR:

image

After this PR:

image

Fixes #11583

### Why we need it and why it was done in this way

The following tradeoffs were made:

修改之前所有业务方法都复用了api key轮换逻辑，但是check api方法不需要这个逻辑，因此将这个逻辑提到了api service层，然后传到Provider的永远是格式化后的单个apikey

这样的改动更简单，而且方便v2来重构。当然也观察到现在apiservice的不同业务方法又有许多重复的逻辑，但没办法一劳永逸的解决这个问题，会影响bugfix的效率

Links to places where the discussion took place: 

### Special notes for your reviewer

测试聊天界面依然正常轮换

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### Release note

```release-note

```

### CODE REVIEW

File: src/renderer/src/services/ApiService.ts [hunk 1]
```diff
@@ -95,7 +98,15 @@ export async function fetchChatCompletion({
...
-  const AI = new AiProviderNew(assistant.model || getDefaultModel())
+
+  // Get base provider and apply API key rotation
+  const baseProvider = getProviderByModel(assistant.model || getDefaultModel())
+  const providerWithRotatedKey = {
+    ...cloneDeep(baseProvider),
+    apiKey: getRotatedApiKey(baseProvider)
+  }
+
+  const AI = new AiProviderNew(assistant.model || getDefaultModel(), providerWithRotatedKey)
```
Comment (EurFelux) [inline src/renderer/src/services/ApiService.ts:108]: > [!NOTE]
> This review comment was translated by Claude.

This involves a design issue. If you pass in a provider, it won't go through internal processing like API host formatting. You can refer to #11604 for the changes regarding `index_new.ts`.

---
<details>
<summary>Original Content</summary>

这里涉及到一个设计上的问题，如果你传入一个provider，那么它不会经过api host format等内部处理。可以看看 #11604 关于 `index_new.ts` 的改动。

</details>

File: src/renderer/src/aiCore/index_new.ts [hunk 2]
```diff
@@ -91,8 +91,13 @@ export default class ModernAiProvider {
...
-      this.actualProvider = provider || getActualProvider(modelOrProvider)
-      // 只保存配置，不预先创建executor
+      if (provider) {
+        // 使用传入的 provider（可能包含轮换后的 key）
+        this.actualProvider = provider
+      } else {
+        // 获取默认 provider 并生成配置
+        this.actualProvider = getActualProvider(modelOrProvider)
+      }
       this.config = providerToAiSdkConfig(this.actualProvider, modelOrProvider)
```
Comment (DeJeune) [inline src/renderer/src/aiCore/index_new.ts:96]: > [!NOTE]
> This issue/comment/review was translated by Claude.

This will still be executed, where formatting and other operations are performed in povidertoaisdkconfig @EurFelux

---
<details>
<summary>Original Content</summary>

这里还是会走的，在povidertoaisdkconfig进行format等操作 @EurFelux
</details>

Comment (EurFelux) [reply src/renderer/src/aiCore/index_new.ts:96]: > [!NOTE]
> This issue/comment/review was translated by Claude.

Not really, this function handles config, but the apihost still exists inside the provider. The API host format operation is actually in `getActualProvider`.

---
<details>
<summary>Original Content</summary>
没有吧，这个函数处理config，但apihost仍然存在provider里面的。api host format操作实际上在`getActualProvider`里面
</details>

Comment (DeJeune) [reply src/renderer/src/aiCore/index_new.ts:96]: > [!NOTE]
> This issue/comment/review was translated by Claude.

You're right, I was looking at the wrong branch (there's a branch where I made this change). Do we need to promote this function up? In that case, each business method would be written once, and we can refactor it again when v2 comes.

---
<details>
<summary>Original Content</summary>

确实，我看错分支了（有个分支我改掉了），那需要把这个函数提升上来？这样的话每个业务方法都写一遍就好了，等v2再来重新改
</details>

Comment (EurFelux) [reply src/renderer/src/aiCore/index_new.ts:96]: > [!NOTE]
> This issue/comment/review was translated by Claude.

I made a version in 11604, you can take a look

---
<details>
<summary>Original Content</summary>

我在11604改了一版可以看看
</details>

Comment (DeJeune) [reply src/renderer/src/aiCore/index_new.ts:96]: > [!NOTE]
> This issue/comment/review was translated by Claude.

Merged

---
<details>
<summary>Original Content</summary>

合并进来了
</details>

**Review by 0xfullex — CHANGES_REQUESTED** [review]
[!NOTE]
> This issue/comment/review was translated by Claude.

## PR Review Summary

Thanks for this PR! Moving the API key rotation logic from the provider layer to the ApiService layer is the correct approach and will resolve issue #11583. However, I found several issues that need to be fixed in the implementation.

---

## 🚨 Critical Issues (Must Fix)

### 1. \`getRotatedApiKey\` crashes when \`apiKey\` is undefined

**Location:** \`src/renderer/src/services/ApiService.ts\`

\`\`\`typescript
function getRotatedApiKey(provider: Provider): string {
  const keys = provider.apiKey.split(',').map((key) => key.trim())  // Crashes if apiKey is undefined
\`\`\`

For providers like \`ollama\`, \`lmstudio\`, \`vertexai\`, \`aws-bedrock\`, \`copilot\` that don't need API keys, \`apiKey\` might be \`undefined\` or empty string, which will cause \`TypeError: Cannot read property 'split' of undefined\`.

**Suggested fix:**
\`\`\`typescript
function getRotatedApiKey(provider: Provider): string {
  if (!provider.apiKey || provider.apiKey.trim() === '') {
    return ''
  }
  const keys = provider.apiKey.split(',').map((key) => key.trim()).filter(Boolean)
  // ... rest of logic
}
\`\`\`

### 2. \`checkApiProvider\` logic is inverted, preventing custom providers from being validated

**Location:** \`src/renderer/src/services/ApiService.ts\`

**Current code:**
\`\`\`typescript
if (isSystemProvider(provider) && !NOT_SUPPORT_API_KEY_PROVIDERS.includes(provider.id)) {
\`\`\`

This logic only validates API keys for system providers. **Custom/non-system providers will not be validated**, which is a regression issue.

**Original logic:**
\`\`\`typescript
if (
  provider.id !== 'ollama' &&
  provider.id !== 'lmstudio' &&
  provider.type !== 'vertexai' &&
  provider.id !== 'copilot'
) {
\`\`\`

The original code validates all providers except those in the specific exclusion list.

**Suggested fix:**
\`\`\`typescript
const isExcludedProvider = isSystemProvider(provider) && NOT_SUPPORT_API_KEY_PROVIDERS.includes(provider.id)
if (!isExcludedProvider) {
  if (!provider.apiKey) {
    // ... error handling
  }
}
\`\`\`

### 3. \`cherryai\` was removed from the exemption list

**Location:** \`src/renderer/src/utils/provider.ts\`

Original \`hasApiKey\` included \`cherryai\`:
\`\`\`typescript
if (['ollama', 'lmstudio', 'vertexai', 'cherryai'].includes(provider.id)) return true
\`\`\`

But \`NOT_SUPPORT_API_KEY_PROVIDERS\` doesn't include \`cherryai\`, which will cause problems for \`cherryai\` provider users.

**Suggestion:** Add \`'cherryai'\` to \`NOT_SUPPORT_API_KEY_PROVIDERS\`.

---

## ⚠️ Important Issues (Recommended to fix)

### 4. Missing \`vertexai\` type check

The original code checked \`provider.type !== 'vertexai'\`, but the new code only checks \`provider.id\`. If there's a provider with \`type\` \`'vertexai'\` but a different \`id\`, it will be incorrectly required to validate an API key.

### 5. Silent fallback when key is removed

When \`keys.indexOf(lastUsedKey)\` returns \`-1\`, calculating \`(-1 + 1) % keys.length = 0\` will silently fall back to the first key without any logs. Consider adding logging for this situation.

### 6. \`fetchModels\` silently returns empty array

\`\`\`typescript
try {
  return await AI.models()
} catch (error) {
  return []  // No logs, hiding authentication failures, rate limiting, and other errors
}
\`\`\`

Consider adding error logging for debugging.

---

## 💡 Suggestions

1. **Filter empty keys:** \`const keys = provider.apiKey.split(',').map((key) => key.trim()).filter(Boolean)\`

2. **Extract repeated logic:** The \`cloneDeep(provider) + getRotatedApiKey\` pattern is repeated 5+ times, consider extracting it as a helper function

3. **Translate Chinese comments:** For consistency, consider translating the Chinese documentation in \`getRotatedApiKey\` to English

---

## ✅ Pros

1. **Correct architecture direction** - Moving key rotation to ApiService layer is reasonable
2. **Proper use of \`cloneDeep\`** - Avoids modifying the original provider object
3. **Created centralized constant \`NOT_SUPPORT_API_KEY_PROVIDERS\`** - Reduces magic strings
4. **Fixed real bugs** - The fix for checkApi not rotating keys is correct

---

**Recommendation:** Please fix Critical Issues 1-3 before merging. These issues will cause:
- Providers that don't need API keys (ollama, lmstudio, etc.) to crash
- Custom providers to skip API key validation
- Problems with \`cherryai\` providers

---
<details>
<summary>Original Content</summary>
## PR Review Summary

感谢这个 PR！将 API key 轮换逻辑从 provider 层移到 ApiService 层的思路是正确的，能够解决 #11583 的问题。但是在实现上发现了几个需要修复的问题。

---

## 🚨 Critical Issues (必须修复)

### 1. \`getRotatedApiKey\` 在 \`apiKey\` 为 undefined 时会崩溃

**位置:** \`src/renderer/src/services/ApiService.ts\`

\`\`\`typescript
function getRotatedApiKey(provider: Provider): string {
  const keys = provider.apiKey.split(',').map((key) => key.trim())  // 如果 apiKey 是 undefined 会崩溃
\`\`\`

对于 \`ollama\`, \`lmstudio\`, \`vertexai\`, \`aws-bedrock\`, \`copilot\` 等不需要 API key 的 provider，\`apiKey\` 可能是 \`undefined\` 或空字符串，会导致 \`TypeError: Cannot read property 'split' of undefined\`。

**建议修复:**
\`\`\`typescript
function getRotatedApiKey(provider: Provider): string {
  if (!provider.apiKey || provider.apiKey.trim() === '') {
    return ''
  }
  const keys = provider.apiKey.split(',').map((key) => key.trim()).filter(Boolean)
  // ... rest of logic
}
\`\`\`

### 2. \`checkApiProvider\` 逻辑反转导致自定义 Provider 不会被验证

**位置:** \`src/renderer/src/services/ApiService.ts\`

**当前代码:**
\`\`\`typescript
if (isSystemProvider(provider) && !NOT_SUPPORT_API_KEY_PROVIDERS.includes(provider.id)) {
\`\`\`

这个逻辑只会验证系统 provider 的 API key。**自定义/非系统 provider 将不会被验证**，这是一个回归问题。

**原始逻辑:**
\`\`\`typescript
if (
  provider.id !== 'ollama' &&
  provider.id !== 'lmstudio' &&
  provider.type !== 'vertexai' &&
  provider.id !== 'copilot'
) {
\`\`\`

原始代码会验证所有 provider，除了特定的排除列表。

**建议修复:**
\`\`\`typescript
const isExcludedProvider = isSystemProvider(provider) && NOT_SUPPORT_API_KEY_PROVIDERS.includes(provider.id)
if (!isExcludedProvider) {
  if (!provider.apiKey) {
    // ... error handling
  }
}
\`\`\`

### 3. \`cherryai\` 从豁免列表中被移除

**位置:** \`src/renderer/src/utils/provider.ts\`

原始 \`hasApiKey\` 包含 \`cherryai\`:
\`\`\`typescript
if (['ollama', 'lmstudio', 'vertexai', 'cherryai'].includes(provider.id)) return true
\`\`\`

但 \`NOT_SUPPORT_API_KEY_PROVIDERS\` 不包含 \`cherryai\`，这会导致 \`cherryai\` provider 用户遇到问题。

**建议:** 将 \`'cherryai'\` 添加到 \`NOT_SUPPORT_API_KEY_PROVIDERS\`。

---

## ⚠️ Important Issues (建议修复)

### 4. 缺少 \`vertexai\` 类型检查

原始代码检查 \`provider.type !== 'vertexai'\`，但新代码只检查 \`provider.id\`。如果有 provider 的 \`type\` 是 \`'vertexai'\` 但 \`id\` 不同，会被错误地要求验证 API key。

### 5. Key 被移除时静默回退

当 \`keys.indexOf(lastUsedKey)\` 返回 \`-1\` 时，计算 \`(-1 + 1) % keys.length = 0\` 会静默回退到第一个 key，没有任何日志。建议添加日志记录这种情况。

### 6. \`fetchModels\` 静默返回空数组

\`\`\`typescript
try {
  return await AI.models()
} catch (error) {
  return []  // 没有任何日志，隐藏了认证失败、限流等错误
}
\`\`\`

建议添加错误日志以便调试。

---

## 💡 Suggestions

1. **过滤空 key:** \`const keys = provider.apiKey.split(',').map((key) => key.trim()).filter(Boolean)\`

2. **提取重复逻辑:** \`cloneDeep(provider) + getRotatedApiKey\` 模式重复了 5+ 次，可以考虑提取为辅助函数

3. **翻译中文注释:** 为了一致性，可以考虑将 \`getRotatedApiKey\` 的中文文档翻译成英文

---

## ✅ 优点

1. 架构方向正确 - 将 key 轮换移到 ApiService 层是合理的
2. 正确使用 \`cloneDeep\` - 避免修改原始 provider 对象
3. 创建了集中的常量 \`NOT_SUPPORT_API_KEY_PROVIDERS\` - 减少魔法字符串
4. 解决了真实的 bug - checkApi 不应该轮换 key 的修复是正确的

---

**建议:** 请修复 Critical Issues 1-3 后再合并。这些问题会导致：
- 不需要 API key 的 provider (ollama, lmstudio 等) 崩溃
- 自定义 provider 跳过 API key 验证
- \`cherryai\` provider 出现问题
</details>

**Review by 0xfullex — APPROVED** [review]
## Review Summary

All previously identified issues have been addressed in the latest commit. ✅

### Issues Fixed:
| Issue | Status |
|-------|--------|
| **Critical #1**: `getRotatedApiKey` crashes when `apiKey` is undefined | ✅ Fixed |
| **Critical #2**: `checkApiProvider` logic inverted for custom providers | ✅ Fixed |
| **Critical #3**: `cherryai` removed from exemption list | ✅ Fixed |
| **Important #4**: Missing `vertexai` type check | ✅ Fixed |
| **Important #5**: Silent fallback when key is removed | ✅ Fixed |
| **Important #6**: `fetchModels` silently returns empty array | ✅ Fixed |

### Key Improvements:
- Proper null/undefined handling in `getRotatedApiKey`
- Custom providers are now correctly validated
- `cherryai` explicitly handled in `hasApiKey`
- Both ID-based and type-based exclusion lists implemented
- Debug/error logging added for edge cases

LGTM! 🚀
