### PR TITLE
fix(images/edits): default to image/png when file has no extension

### LINKED ISSUE #14608: [Bug]: When calling `/v1/images/edits`, the image is uploaded with an unfinished MIME type `image`
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

1.9.3

### Bug Description

Got response from server backend:
```
{
  "error": {
    "message": "Invalid 'input[0].content[1].image_url'. Expected a base64-encoded data URL with an image MIME type (e.g. 'data:image/png;base64,aW1nIGJ5dGVzIGhlcmU='), but got unsupported MIME type 'image'.",
    "type": "invalid_request_error",
    "param": "input[0].content[1].image_url",
    "code": "invalid_value"
  }
}
```

The server backend, which is [CLIProxyAPI](https://github.com/router-for-me/CLIProxyAPI), seems not happy with MIME type being just `image`, also the part for image file has a name of `blob`, so the server will have no clue what type/format the image is.

---

Image

### Steps To Reproduce

Send a prompt+image to the server, which is [CLIProxyAPI](https://github.com/router-for-me/CLIProxyAPI) in my case.

### Expected Behavior

The server accepts the task (probably with MIME indicated clearly) and proceed with image edits/generation.

### Relevant Log Output

```shell

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by LWWZH**
### What this PR does

Fixes the `/v1/images/edits` API call failing with "unsupported MIME type 'image'" when the image file has no extension (e.g., blob files).

Before this PR:
- Image files without extensions (blobs) would produce invalid MIME type `image/`
- Server rejected requests with "Invalid 'input[0].content[1].image_url'. Expected a base64-encoded data URL with an image MIME type..."

After this PR:
- `base64Image()` in `src/main/utils/file.ts:293-304` and `src/main/services/FileStorage.ts:649-663` now defaults to `image/png` when the file extension is missing or empty
- API requests now include valid MIME types like `data:image/png;base64,...`

Fixes #14608

### Why we need it and why it was done in this way

The issue occurred when users uploaded images that had no file extension. The code would construct MIME type as `image/${ext}` where `ext` was empty, resulting in `image/` - an invalid MIME type.

The fix adds a guard: `const mime = ext ? \`image/${ext}\` : 'image/png'`

### Tradeoffs

- None: This is a minimal safety fallback that only affects files without extensions

### Special notes for your reviewer

- 2 files modified with identical fix
- No behavior change for files with valid extensions

### Release note

```release-note
Fixed image edit API failing when uploaded images have no file extension by defaulting to image/png MIME type
```

### CODE REVIEW

**Review by ousugo — APPROVED** [review]
LGTM

File: src/main/services/FileStorage.ts [hunk 1]
```diff
@@ -653,8 +653,9 @@ class FileStorage {
     const filePath = path.join(this.storageDir, id)
     const data = await fs.promises.readFile(filePath)
     const base64 = data.toString('base64')
-    const ext = path.extname(filePath).slice(1) == 'jpg' ? 'jpeg' : path.extname(filePath).slice(1)
-    const mime = `image/${ext}`
+    const rawExt = path.extname(filePath).slice(1)
+    const ext = rawExt === 'jpg' ? 'jpeg' : rawExt
+    const mime = ext ? `image/${ext}` : 'image/png'
```
Comment (GeorgeDong32) [inline src/main/services/FileStorage.ts:658]: **✅ 修复有效**

改进点：
- 避免重复调用 `path.extname()` (性能优化)
- 变量命名清晰 (`rawExt`, `ext`)
- 正确处理空扩展名的边界情况

**💡 建议**：可考虑添加单元测试覆盖以下场景：
- 文件无扩展名 → `image/png`
- `.jpg` 文件 → `image/jpeg`
- `.png` 文件 → `image/png`

File: src/main/utils/file.ts [hunk 2]
```diff
@@ -294,8 +294,9 @@ export async function base64Image(file: FileMetadata): Promise<{ mime: string; b
   const filePath = path.join(getFilesDir(), `${file.id}${file.ext}`)
   const data = await fs.promises.readFile(filePath)
   const base64 = data.toString('base64')
-  const ext = path.extname(filePath).slice(1) == 'jpg' ? 'jpeg' : path.extname(filePath).slice(1)
-  const mime = `image/${ext}`
+  const rawExt = path.extname(filePath).slice(1)
+  const ext = rawExt === 'jpg' ? 'jpeg' : rawExt
+  const mime = ext ? `image/${ext}` : 'image/png'
```
Comment (GeorgeDong32) [inline src/main/utils/file.ts:299]: **✅ 逻辑一致**

与 `FileStorage.ts:656-658` 保持相同的修复逻辑，符合最小变更原则。

**Review by GeorgeDong32 — APPROVED** [review]
## 📋 Code Review Summary

### ✅ 修复正确性

修复有效，解决了文件无扩展名时 MIME 类型为 `image/` (无效) 的问题，改为默认 `image/png`。

**改进点：**
- 避免重复调用 `path.extname()` (性能优化)
- 变量命名清晰 (`rawExt`, `ext`)
- 两处修改保持一致性
- 符合最小变更原则

### ⚠️ 建议：添加单元测试

两个函数均无测试覆盖，建议在后续 PR 中添加测试场景。

### 📝 最终结论

**Approve** — 修复有效，无安全风险，代码质量良好。
