### PR TITLE
fix: Format provider API hosts in API server & refactor shared utilities

### LINKED ISSUE #13192: [Bug]: API Server does not format provider apiHost, causing 404 on chat completions
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

macOS

### Version

v1.7.23

### Bug Description

The API Server (`src/main/apiServer`) does not apply any `apiHost` formatting when reading provider configurations from the Redux store. This causes requests to be sent to incorrect paths, resulting in 404 errors from upstream providers.

**Root Cause:**

In `src/main/apiServer/utils/index.ts`, `getAvailableProviders()` reads providers directly from the Redux store without formatting their `apiHost`. When the OpenAI SDK client is created in `resolveProviderContext()`, the raw unformatted `apiHost` is passed as `baseURL`:

```typescript
// Current (broken): apiHost is used as-is
const client = new OpenAI({
  baseURL: provider.apiHost,  // e.g., "http://localhost:11434" — missing /v1!
  apiKey: provider.apiKey
})
```

The renderer-side (`aiCore`) always calls `adaptProvider()` → `formatProviderApiHost()` before using a provider, which normalizes the `apiHost` (e.g., appending `/v1` for OpenAI-compatible providers). The API Server skips this step entirely.

**Inconsistency:**

| Context | Behavior |
|---------|---------|
| Renderer (aiCore) | Calls `formatProviderApiHost()`, appends `/v1` → requests go to `/v1/chat/completions` ✅ |
| API Server (main) | Uses raw `apiHost` from Redux store → requests go to `/chat/completions` ❌ |

**Additional Finding:**

`formatVertexApiHost()` in `src/renderer/src/utils/api.ts` unnecessarily reads `project` and `location` from `store.getState().llm.settings.vertexai`, even though `VertexProvider` type already contains `project` and `location` fields directly. This store dependency can be eliminated, making the function a pure function suitable for sharing.

### Steps To Reproduce

1. Enable API Server in Cherry Studio settings
2. Add a provider configured as OpenAI-compatible (e.g., Ollama with `apiHost = http://localhost:11434`)
3. Send a `POST /v1/chat/completions` request to the API Server with model `<provider-id>:<model-id>`
4. Observe 404 error

### Expected Behavior

The API Server should apply the same `apiHost` formatting as the renderer-side `adaptProvider()` / `formatProviderApiHost()`. For OpenAI-compatible providers, `http://localhost:11434` should be normalized to `http://localhost:11434/v1` before creating the OpenAI SDK client.

### Relevant Log Output

```
# Cherry Studio API Server log
{"error":{"headers":{},"requestID":null,"status":404},"level":"error","message":"Error processing streaming chat completion","model":"107a079e-a151-4795-b887-5c75737c222e:qwen3:0.6b","timestamp":"2026-03-04 12:06:07"}
{"error":{"headers":{},"requestID":null,"status":404},"level":"error","message":"Chat completion error","timestamp":"2026-03-04 12:06:07"}

# Ollama server log (confirms wrong path received)
[GIN] 2026/03/04 - 12:06:07 | 404 |      18.041µs |  127.0.0.1 | POST  "/chat/completions"
[GIN] 2026/03/04 - 12:06:22 | 200 |   2.98832025s |  127.0.0.1 | POST  "/v1/chat/completions"
```

### Additional Context

Related to #13188 — that issue describes a user failing to use the API Server with an Ollama provider. The `provider_not_found` error seen there and the 404 seen here share the same underlying cause: the API Server does not normalize provider configuration the same way the renderer does.

**Proposed Fix:**

Extract shared pure functions (no store dependency) into a new `packages/shared/aiCore/provider.ts`:
- `formatProviderApiHost(provider)` — covers all provider types including vertex (using `VertexProvider.project`/`.location` fields directly instead of store)
- `formatOllamaApiHost`, `formatAzureOpenAIApiHost`, `formatVertexApiHost` (refactored as pure functions)
- `isOllamaProvider`, `isAnthropicProvider`, etc.

Then in `src/main/apiServer/utils/index.ts`, apply formatting in `getAvailableProviders()`:

```typescript
import { formatProviderApiHost } from '@shared/aiCore/provider'

const formattedProviders = supportedProviders.map((p) => formatProviderApiHost(p))
CacheService.set(PROVIDERS_CACHE_KEY, formattedProviders, PROVIDERS_CACHE_TTL)
return formattedProviders
```

**Files to modify:**
- `packages/shared/aiCore/provider.ts` ← new file
- `src/renderer/src/utils/api.ts` ← re-export from shared
- `src/renderer/src/utils/provider.ts` ← re-export from shared
- `src/renderer/src/aiCore/provider/providerConfig.ts` ← import from shared
- `src/main/apiServer/utils/index.ts` ← apply `formatProviderApiHost`

### PR DESCRIPTION
**Pull request by EurFelux**
### What this PR does

Before this PR:

The API server used raw provider `apiHost` values from Redux without formatting. This meant provider-specific URL transformations (e.g., appending `/v1`, Ollama `/api` suffix, Azure `/openai` suffix) were skipped, causing upstream API calls to hit incorrect URLs (often resulting in 404 errors). Additionally, shared utility functions (API host formatting, provider type checks, Claude provider constants) were tightly coupled to the renderer process and unavailable to the main process.

After this PR:

- API utility functions (`formatApiHost`, `withoutTrailingSlash`, `hasAPIVersion`, etc.) are moved to `packages/shared/utils/api/`
- Provider type check functions (`isAnthropicProvider`, `isOllamaProvider`, etc.) are moved to `packages/shared/aiCore/provider/utils/`
- Provider-specific API host formatters (`formatOllamaApiHost`, `formatAzureOpenAIApiHost`) are moved to `packages/shared/aiCore/provider/utils/api.ts`
- `CLAUDE_SUPPORTED_PROVIDERS` / `CLAUDE_OFFICIAL_SUPPORTED_PROVIDERS` constants are moved to `packages/shared/config/providers.ts`
- A main-process version of `formatProviderApiHost` is created at `src/main/aiCore/provider/providerConfig.ts`
- The API server now formats provider API hosts before caching/using them, fixing 404 errors caused by unformatted URLs

Fixes #13192

### Why we need it and why it was done in this way

The following tradeoffs were made:

- A separate `formatProviderApiHost` implementation exists in the main process (`src/main/aiCore/provider/providerConfig.ts`) alongside the renderer version. This is because the Vertex API host formatter in the renderer depends on the Redux store directly, while the main process version uses `reduxService`. A `// WARNING` comment is added to remind developers to keep them in sync.
- Renderer-side modules re-export from shared for backward compatibility, avoiding a large-scale import path migration across the codebase.

The following alternatives were considered:

- Fully unifying the renderer and main process `formatProviderApiHost` was considered but deferred due to the Vertex provider's dependency on different store access patterns (#13194).

### Breaking changes

None. All existing renderer imports continue to work via re-exports.

### Special notes for your reviewer

- The core bug fix is in `src/main/apiServer/utils/index.ts` — providers are now formatted via `formatProviderApiHost()` before being cached.
- Most of the diff is moving code from renderer to shared packages with no logic changes.
- The `Revert "refactor: Add const assertions to provider arrays"` commit reverts an earlier attempt that caused issues.

### Checklist

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. Check this only when the PR introduces or changes a user-facing feature or behavior.
- [x] Self-review: I have reviewed my own code (e.g., via [`/gh-pr-review`](/.claude/skills/gh-pr-review/SKILL.md), `gh pr diff`, or GitHub UI) before requesting review from others

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by EurFelux** [comment]
> [!NOTE]
> This issue/comment/review was translated by Claude.

## Self Review Fixes (`b9f8d920c`)

Performed a self review of this branch and identified and fixed 3 issues:

### 1. `Promise.allSettled` Silently Losing Providers (Medium Severity)
**File**: `src/main/apiServer/utils/index.ts`

Previously, `getAvailableProviders()` used `Promise.allSettled` + `.filter(fulfilled)`. If `formatProviderApiHost` threw an exception for a provider, that provider would silently disappear without any error logs.

**Fix**: Changed to iterate through results and use `logger.warn` to output the `providerId` and failure reason for `rejected` results.

### 2. Direct Internal Module Path Imports (Code Style)
**File**: `src/renderer/src/utils/api.ts`

`import { withoutTrailingSlash } from '@shared/utils/api/utils'` directly referenced an internal implementation file, exposing the module's internal structure.

**Fix**: Changed to import from the public entry point `@shared/utils`.

### 3. Inconsistent Re-export Paths (Code Cleanliness)
**File**: `src/renderer/src/utils/provider.ts`

Re-exports used `@shared/aiCore/provider/utils/types`, while imports in the same file used `@shared/aiCore/provider/utils`, creating inconsistent paths.

**Fix**: Unified to use `@shared/aiCore/provider/utils`.

---
<details>
<summary>Original Content</summary>

## Self Review 修复 (`b9f8d920c`)

对本分支进行了 self review，发现并修复了 3 个问题：

### 1. `Promise.allSettled` 静默丢失 provider（中等严重）
**文件**: `src/main/apiServer/utils/index.ts`

之前 `getAvailableProviders()` 中使用 `Promise.allSettled` + `.filter(fulfilled)` 的写法，如果 `formatProviderApiHost` 对某个 provider 抛出异常，该 provider 会静默消失，没有任何错误日志。

**修复**: 改为遍历 results，对 `rejected` 的结果用 `logger.warn` 输出 `providerId` 和失败原因。

### 2. 内部模块路径直接引用（代码规范）
**文件**: `src/renderer/src/utils/api.ts`

`import { withoutTrailingSlash } from '@shared/utils/api/utils'` 直接引用了内部实现文件，暴露了模块内部结构。

**修复**: 改为从公共入口 `@shared/utils` 导入。

### 3. re-export 路径不一致（代码洁净度）
**文件**: `src/renderer/src/utils/provider.ts`

re-export 使用 `@shared/aiCore/provider/utils/types`，而同文件 import 使用 `@shared/aiCore/provider/utils`，路径不一致。

**修复**: 统一使用 `@shared/aiCore/provider/utils`。

</details>

File: src/renderer/src/aiCore/provider/providerConfig.ts [hunk 1]
```diff
@@ -72,6 +72,7 @@ function handleSpecialProviders(model: Model, provider: Provider): Provider {
  * @param provider - The provider whose API host is to be formatted.
  * @returns A new provider instance with the formatted API host.
  */
+// WARNING: if any changes are made here, please sync it to shared/aiCore/provider/providerConfig.ts:formatProviderApiHost
```
Comment (DeJeune) [inline src/renderer/src/aiCore/provider/providerConfig.ts]: **Bug:** Incorrect file path in the WARNING comment. The main-process version is at `src/main/aiCore/provider/providerConfig.ts`, not `shared/aiCore/provider/providerConfig.ts`.

```suggestion
// WARNING: if any changes are made here, please sync it to src/main/aiCore/provider/providerConfig.ts:formatProviderApiHost
```

File: src/main/aiCore/provider/utils/api.ts [hunk 2]
```diff
@@ -0,0 +1,19 @@
+import { reduxService } from '@main/services/ReduxService'
+import { formatApiHost, withoutTrailingSlash } from '@shared/utils'
+import { trim } from 'lodash'
+
+// NOTE: Since #13194, it's re-written with reduxService
+// See: renderer/src/utils/api.ts: formatVertexApiHost
+export async function formatVertexApiHost(host: string): Promise<string> {
+  const { projectId: project, location } = (await reduxService.select('llm.settings.vertexai')) as {
+    projectId: string
+    location: string
```
Comment (DeJeune) [inline src/main/aiCore/provider/utils/api.ts:10]: **Nit:** Variable `host` on line 10 shadows the function parameter `host` on line 3. Consider renaming it to `baseHost` or `vertexHost` to avoid confusion.

```suggestion
  const trimmedHost = withoutTrailingSlash(trim(host))
  if (\!trimmedHost || trimmedHost.endsWith('aiplatform.googleapis.com')) {
    const baseHost =
      location == 'global' ? 'https://aiplatform.googleapis.com' : `https://${location}-aiplatform.googleapis.com`
    return `${formatApiHost(baseHost)}/projects/${project}/locations/${location}`
```

File: src/main/aiCore/provider/utils/api.ts [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+  }
```
Comment (DeJeune) [inline src/main/aiCore/provider/utils/api.ts:11]: **Nit:** Loose equality (`==`) used for string comparison. Should be strict equality (`===`) for consistency with the rest of the codebase.

```suggestion
      location === 'global' ? 'https://aiplatform.googleapis.com' : `https://${location}-aiplatform.googleapis.com`
```

File: src/renderer/src/store/settings.ts [hunk 4]
```diff
@@ -38,8 +38,8 @@ import type {
   OpenAIReasoningSummary,
   OpenAIVerbosity
 } from '@renderer/types/aiCoreTypes'
-import { uuid } from '@renderer/utils'
 import { API_SERVER_DEFAULTS, UpgradeChannel } from '@shared/config/constant'
```
Comment (DeJeune) [inline src/renderer/src/store/settings.ts:41]: **Nit:** This import change from `@renderer/utils` to `uuid` directly appears unrelated to the PR's scope (API host formatting / shared utility refactor). Was this intentional or a leftover from another change? If intentional, it might be worth mentioning in the PR description.

File: src/main/aiCore/provider/providerConfig.ts [hunk 5]
```diff
@@ -0,0 +1,59 @@
...
+/**
+ * Format and normalize the API host URL for a provider.
+ * Handles provider-specific URL formatting rules (e.g., appending version paths, Azure formatting).
+ *
+ * @param provider - The provider whose API host is to be formatted.
+ * @returns A new provider instance with the formatted API host.
+ */
+export async function formatProviderApiHost(provider: Provider): Promise<Provider> {
+  // NOTE: It's async to support Vertex API host formatting
+  // Original implementation: src/renderer/src/aiCore/provider/providerConfig.ts
```
Comment (DeJeune) [inline src/main/aiCore/provider/providerConfig.ts]: **Significant:** This main-process `formatProviderApiHost` is a near-duplicate of the renderer version at `src/renderer/src/aiCore/provider/providerConfig.ts:formatProviderApiHost`. Having two copies that must be manually kept in sync is fragile. A few differences stand out:

1. This version is `async` (returns `Promise<Provider>`) because of Vertex, while the renderer version is sync.
2. The renderer version uses `formatVertexApiHost(formatted)` (passing the full provider), while this version uses `formatVertexApiHost(formatted.apiHost)` (passing just the string). These are actually different functions with different signatures.

Consider adding a corresponding WARNING comment here pointing back to the renderer version, so the sync obligation is visible from both sides.

File: packages/shared/aiCore/provider/utils/__tests__/api.test.ts [hunk 6]
```diff
@@ -0,0 +1,83 @@
...
+    it('handles multiple suffix combinations correctly', () => {
+      expect(formatOllamaApiHost('https://api.ollama.com/v1/chat')).toBe('https://api.ollama.com/v1/api')
+      expect(formatOllamaApiHost('https://api.ollama.com/chat/v1')).toBe('https://api.ollama.com/api')
+      expect(formatOllamaApiHost('https://api.ollama.com/api/chat')).toBe('https://api.ollama.com/api/api')
+    })
+
+    it('preserves complex paths while handling suffixes', () => {
+      expect(formatOllamaApiHost('https://api.ollama.com/custom/path')).toBe('https://api.ollama.com/custom/path/api')
+      expect(formatOllamaApiHost('https://api.ollama.com/custom/path/')).toBe('https://api.ollama.com/custom/path/api')
+      expect(formatOllamaApiHost('https://api.ollama.com/custom/path/v1')).toBe(
```
Comment (DeJeune) [inline packages/shared/aiCore/provider/utils/__tests__/api.test.ts:52]: **Nit:** These test cases document what looks like surprising behavior:
- `/v1/chat` → `/v1/api` (only `/chat` stripped, `/v1` kept because it's not trailing)
- `/api/chat` → `/api/api` (double `/api`)

This is pre-existing behavior so not blocking, but worth a comment explaining why these are the expected results, so future maintainers don't misread these as bugs.

**Review by DeJeune — COMMENTED** [review]
## Overall Assessment

Good PR that addresses a real bug — the API server was using raw provider `apiHost` values without formatting, causing 404s. The fix in `src/main/apiServer/utils/index.ts` is clean and well-structured with proper error handling via `Promise.allSettled`.

The bulk of the diff is a mechanical move of shared utilities from renderer to `packages/shared/`, which is a sound architectural decision. Tests are comprehensive and CI is green.

## Findings

### Significant
- **Dual `formatProviderApiHost` sync risk**: The main-process and renderer versions have subtle differences (async vs sync, different `formatVertexApiHost` signatures). The WARNING comment on the renderer side points to the wrong file path (`shared/` instead of `src/main/`). Consider adding a bidirectional WARNING so the sync obligation is visible from both files.

### Minor
- Variable shadowing (`host`) in `formatVertexApiHost`
- Loose equality (`==`) instead of strict (`===`) for string comparison
- Unrelated `uuid` import change in `settings.ts`
- Surprising test expectations in `formatOllamaApiHost` could use explanatory comments

## Positives
- Excellent test coverage for the moved utilities
- `Promise.allSettled` usage in the core fix gracefully handles per-provider formatting failures
- Re-exports for backward compatibility is a pragmatic approach
- PR description is thorough with clear explanation of tradeoffs

File: src/renderer/src/store/settings.ts (hunk 4 above)
Comment (EurFelux) [reply src/renderer/src/store/settings.ts:41]: > [!NOTE]
> This comment was translated by Claude.

Because if we don't make this change, test errors will occur. The uuid imported from renderer/utils is undefined at runtime, likely caused by circular dependencies in the complex dependency chain. Since it's too difficult to troubleshoot, here we directly changed to use the uuid package, and the runtime behavior remains unchanged.

---
<details>
<summary>Original Content</summary>
因为若不更改就会出现测试错误，从renderer/utils中导入的uuid在运行时为undefined，估计是在复杂的依赖链中出现循环依赖导致的。由于过于难以排查，这里直接改成使用uuid包，运行时行为不变。
</details>

File: packages/shared/aiCore/provider/utils/__tests__/api.test.ts (hunk 6 above)
Comment (EurFelux) [reply packages/shared/aiCore/provider/utils/__tests__/api.test.ts:52]: > [!NOTE]
> This issue/comment/review was translated by Claude.

> From the blame view, this test case was added by @DeJeune in #11611, so you should check whether this part meets expectations.

---
<details>
<summary>Original Content</summary>

从blame来看，这部分用例是在 #11611 中由 @DeJeune  添加的，因此你应该检查一下这一段是否符合预期。

</details>

File: src/main/aiCore/provider/utils/api.ts (hunk 2 above)
Comment (EurFelux) [reply src/main/aiCore/provider/utils/api.ts:10]: renamed to `fallbackHost`

File: src/main/aiCore/provider/utils/api.ts (hunk 3 above)
Comment (EurFelux) [reply src/main/aiCore/provider/utils/api.ts:11]: applied

File: src/main/aiCore/provider/providerConfig.ts (hunk 5 above)
Comment (EurFelux) [reply src/main/aiCore/provider/providerConfig.ts]: comment added

**Comment by DeJeune** [comment]
> [!NOTE]
> This issue/comment/review was translated by Claude.

Looks like there's some overlap with #11495. Once that merges, I can reduce the code size in this PR.

---
<details>
<summary>Original Content</summary>

看起来和 #11495 有一部分是重合的，这样合并之后，我这个pr就可以少点代码量了

</details>

**Comment by EurFelux** [comment]
Will resolve conflicts later
