### PR TITLE
fix(aiCore): fix temperature/topP incorrectly disabled when reasoning_effort is default

### LINKED ISSUE #13503: [Bug]: Cherry Studio is not sending model parameters to the LLM
> [!NOTE]
> This issue was translated by Claude.

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.7.25

### Bug Description

Cherry Studio is not sending model parameters to the LLM

Image

Image

### Steps To Reproduce

Check or set LLM parameters, then start a conversation

### Expected Behavior

Send model parameters to the LLM

### Relevant Log Output

```shell

```

### Additional Context

_No response_

---
<details>
<summary>Original Content</summary>

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.7.25

### Bug Description

cherry studio 没有把模型参数发给大模型
Image

Image

### Steps To Reproduce

检查或设置大模型参数，然后对话

### Expected Behavior

把模型参数发给大模型

### Relevant Log Output

```shell

```

### Additional Context

_No response_

</details>

### PR DESCRIPTION
**Pull request by EurFelux**
### What this PR does

Before this PR:
- When `reasoning_effort` was set to `"default"`, temperature and topP parameters were incorrectly suppressed because `"default"` is a truthy string value.
- Claude 3.7/4.0/4.5 models had no dedicated thinking model type, falling back to `"default"` which gave them generic reasoning effort options. Users could not select `"none"` to disable thinking even though the Anthropic API supports it.
- TopP was fully disabled for Claude reasoning models with reasoning effort set, instead of being clamped to a valid range.
- Parameter adjustments (e.g., temperature clamping, topP disabling) happened silently with no user-visible feedback.

After this PR:
- Explicitly checks `reasoning_effort !== 'default'` and `reasoning_effort !== 'none'` so that temperature and topP are only disabled for actual reasoning effort values.
- Adds a `'claude'` thinking model type for Claude 3.7/4.0/4.5 that supports `'none'` but not `'xhigh'` (options: `['default', 'none', 'low', 'medium', 'high']`).
- TopP is clamped to `[0.95, 1]` for Claude reasoning models with thinking enabled, instead of being fully disabled.
- Refactors `getTemperature`/`getTopP` by inlining helper functions and moving enable-checks to the top as early returns.
- Adds `logger.info` messages so users can see when parameters are adjusted or disabled in the log (e.g., temperature clamped, topP dropped due to mutual exclusivity).

Fixes #13503

### Why we need it and why it was done in this way

The following tradeoffs were made:
- Inlined `getTemperatureValue`/`getTopPValue` helper functions — they added indirection without value, and the enable-check was buried at the end instead of being a clear early return.
- Added `logger.info` for user-visible feedback on parameter adjustments — info level is visible in user logs, helping users understand why their settings were modified.
- Clamped topP to `[0.95, 1]` per [Anthropic extended thinking docs](https://platform.claude.com/docs/en/build-with-claude/extended-thinking#feature-compatibility) rather than fully disabling it.
- Added a separate `'claude'` thinking type instead of reusing `'claude46'`, since Claude 3.7/4.0/4.5 do not support `xhigh` reasoning effort.

The following alternatives were considered:
- Keeping the helper functions but fixing only the `reasoning_effort` check — rejected because the refactor makes the logic significantly easier to follow.
- Using a single `'claude'` type for all Claude models — rejected because 4.6 supports `xhigh` which older models don't.

### Breaking changes

None

### Special notes for your reviewer

- The `enableTemperature`/`enableTopP` checks are moved to the top of each function as early returns, making the control flow clearer.
- Temperature now falls back to `DEFAULT_ASSISTANT_SETTINGS.temperature` and the `isMaxTemperatureOneModel` clamp always runs (previously skipped when temperature was `0`).
- The Claude branch is placed first in `_getThinkModelType` for early matching.

### Checklist

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. Check this only when the PR introduces or changes a user-facing feature or behavior.
- [ ] Self-review: I have reviewed my own code (e.g., via [`/gh-pr-review`](/.claude/skills/gh-pr-review/SKILL.md), `gh pr diff`, or GitHub UI) before requesting review from others

### Release note

```release-note
Fix temperature and topP parameters being incorrectly disabled when reasoning effort is set to "default" or "none" for Claude reasoning models. Add "none" option to disable thinking for Claude 3.7/4.0/4.5 models. TopP is now clamped to [0.95, 1] when thinking is enabled instead of being fully disabled.
```

### CODE REVIEW

File: src/renderer/src/aiCore/prepareParams/modelParameters.ts [hunk 1]
```diff
@@ -17,77 +18,99 @@ import {
...
     return undefined
   }
+
   if (!isSupportTopPModel(model, assistant)) {
+    logger.info(`Model ${model.id} does not support topP, disabling topP.`)
     return undefined
   }
+
   if (isTemperatureTopPMutuallyExclusiveModel(model) && assistant.settings?.enableTemperature) {
+    logger.info(`Model ${model.id} only accepts one of temperature and top, disabling topP.`)
```
Comment (EurFelux) [inline src/renderer/src/aiCore/prepareParams/modelParameters.ts]: > [!NOTE]
> This issue/comment/review was translated by Claude.

**[C5]** Typo: `"only accepts one of temperature and top, disabling topP."` → Should be `"temperature and topP"`, to keep the wording consistent with lines 68 and 89.

---
<details>
<summary>Original Content</summary>

**[C5]** Typo: `"only accepts one of temperature and top, disabling topP."` → 应为 `"temperature and topP"`，与第 68 行和第 89 行的措辞保持一致。
</details>
