### PR TITLE
fix: code editor style

### LINKED ISSUE #9304: [错误]: 删除代码编辑器中的代码导致出现大量空白区域
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我的问题不是 [常见问题](https://github.com/CherryHQ/cherry-studio/issues/3881) 中的内容。
- [x] 我已经查看了 **置顶 Issue** 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。
- [x] 我确认我正在使用最新版本的 Cherry Studio。

### 平台

macOS

### 版本

0368583cfc7ae8992a31c77b42e7ae53b5bbd7a9

### 错误描述

Image

### 重现步骤

输入一些代码再删掉即可触发

### 预期行为

保持稳定

### 相关日志输出

```shell

```

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by EurFelux**
### What this PR does

- 修复cm-announced导致滚动条出现大量空白区域的问题
- 修复自动补全被隐藏的问题

Fixes #9304

### Why we need it and why it was done in this way

The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Breaking changes

If this PR introduces breaking changes, please describe the changes and the impact on users.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### Release note

```release-note

```

### CODE REVIEW

**Review by eeee0717 — APPROVED** [review]

**Review by GeorgeDong32 — APPROVED** [review]

File: src/renderer/src/components/CodeBlockView/view.tsx [hunk 1]
```diff
@@ -370,7 +370,7 @@ const SplitViewWrapper = styled.div<{ $isSpecialView: boolean; $isSplitView: boo
   &:not(:has(+ [class*='Container'])) {
     // 特殊视图的 header 会隐藏，所以全都使用圆角
     border-radius: ${(props) => (props.$isSpecialView ? '8px' : '0 0 8px 8px')};
-    overflow: hidden;
+    /* overflow: hidden; */
```
Comment (alephpiece) [inline src/renderer/src/components/CodeBlockView/view.tsx]: 这个会破坏别的样式，我看看怎么改一下
