### PR TITLE
fix(websearch-rag): rag error

### LINKED ISSUE #10059: [Bug]: RAG压缩失败：`TypeError: Cannot read properties of undefined (reading 'framework')`
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.6.0-beta.7

### Bug Description

`builtin_web_search`搜索工具的搜索步骤返回结果正常，但是RAG上下文压缩失败返回空结果，报错`[WebSearchService] RAG compression failed, will return empty results: Error: Error invoking remote method 'knowledge-base:reset': TypeError: Cannot read properties of undefined (reading 'framework')`

### Steps To Reproduce

1. 启动 Cherry Studio，进入搜索工具功能模块。
2. 开启 RAG 压缩模式，选择任意嵌入模型和重排模型。
3. 构建提示词，明确指令大语言模型（LLM）调用 builtin_web_search 搜索工具。
4. 在已开启 RAG 压缩模式的配置下，使用上述构建好的提示词触发搜索工具执行。

结果：
- `createToolBlock_baseBlock`正常
- `search`正常返回结果
- RAG上下文压缩失败，报错`[WebSearchService] RAG compression failed, will return empty results: Error: Error invoking remote method 'knowledge-base:reset': TypeError: Cannot read properties of undefined (reading 'framework')`

### Expected Behavior

RAG上下文压缩能正常返回保留的搜索结果

### Relevant Log Output

```shell
Console报错信息：`[WebSearchService] RAG compression failed, will return empty results: Error: Error invoking remote method 'knowledge-base:reset': TypeError: Cannot read properties of undefined (reading 'framework')`

其他日志在cosole和调用链中没有记录
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by eeee0717**
### What this PR does

Before this PR:

fix #10059

After this PR:

Fixes #

### Why we need it and why it was done in this way

The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Breaking changes

If this PR introduces breaking changes, please describe the changes and the impact on users.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### Release note

```release-note

```

### CODE REVIEW

**Comment by eeee0717** [comment]
> [!NOTE]
> This issue/comment was translated by Claude.

@alephpiece There is another problem here. When creating a RAG knowledge base from web content, the path cannot be found. I suspect that the requestId contains `/`, but it cannot be resolved. Please help me check when you have time.

```bash
Error in faiss::FileIOReader::FileIOReader(const char *) at /Users/fan/Developer/faiss-node/deps/faiss/faiss/impl/io.cpp:68: Error: 'f' failed: could not open /Users/xxxx/Library/Application Support/CherryStudioDev/Data/KnowledgeBase/websearch-compression-openai-compatible-moonshotai/kimi-k2-0905-1757388760425-crsh58e5ql5/faiss.index for reading: No such file or directory
```

---
<details>
<summary>Original Content</summary>

@alephpiece There is another problem here. When creating a rag knowledge base on the Internet, you will not find the path. I suspect that the requestId exists `/`, but it cannot be solved. Please help me see it when I have time.
```bash
Error in faiss::FileIOReader::FileIOReader(const char *) at /Users/fan/Developer/faiss-node/deps/faiss/faiss/impl/io.cpp:68: Error: 'f' failed: could not open /Users/xxxx/Library/Application Support/CherryStudioDev/Data/KnowledgeBase/websearch-compression-openai-compatible-moonshotai/kimi-k2-0905-1757388760425-crsh58e5ql5/faiss.index for reading: No such file or directory
```

</details>

File: src/main/services/knowledge/LangChainFramework.ts [hunk 1]
```diff
@@ -103,6 +103,8 @@ export class LangChainFramework implements IKnowledgeFramework {
     if (fs.existsSync(dbPath)) {
       fs.rmSync(dbPath, { recursive: true })
     }
+    // 立即重建空索引，避免随后加载时报错
+    await this.createDatabase(base)
```
Comment (alephpiece) [inline src/main/services/knowledge/LangChainFramework.ts:107]: 这样能行吗

**Review by DeJeune — APPROVED** [review]

**Review by alephpiece — APPROVED** [review]
