### PR TITLE
fix: Selected area in code block changes after scrolling

### LINKED ISSUE #11441: [Bug]: Selected area in code block changes after scrolling
> [!NOTE]
> This issue/comment/review was translated by Claude.

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.6.7

### Bug Description

When selecting partial code in a code block, the selected area changes after scrolling the code block.

### Steps To Reproduce

1. Select partial code (L1-L40)

Image

2. Release the left mouse button and scroll the code block
3. A portion of the selected area is lost

Image

### Expected Behavior

Normal code block selection

### Relevant Log Output

```shell

```

### Additional Context

It seems that the event of releasing the left mouse button is not triggered properly.

---
<details>
<summary>Original Content</summary>
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.6.7

### Bug Description

代码块中选中部分代码，滚动代码块后选中区域会变化

### Steps To Reproduce

1.选中部分代码（L1-L40）

Image

2.松开鼠标左键，滚动代码块
3.有一段选中的区域丢失了

Image

### Expected Behavior

正常选中代码块

### Relevant Log Output

```shell

```

### Additional Context

似乎是松开鼠标左键的事件没有正常触发
</details>

### PR DESCRIPTION
**Pull request by ZKunZhang**
### What this PR does

Before this PR:
- Copying code from collapsed code blocks would lose content from lines not currently rendered by
  virtual scroll
- When selecting text across many lines in collapsed state, the selection highlight would disappear as the user scrolls
- Users had to manually expand code blocks before copying to ensure complete content

After this PR:
- Copy operation extracts complete content from original source data, regardless of virtual scroll
  state
- Multi-line selection in collapsed state automatically expands the code block to prevent selection loss
- Auto-expand only triggers when `codeCollapsible` setting is enabled
- Comprehensive logging added for debugging selection and copy issues

Fixes #11441

### Why we need it and why it was done in this way

**Problem:**
CodeViewer uses virtual scrolling (`@tanstack/react-virtual`) to optimize performance with large code blocks. In collapsed state
(maxHeight: 350px), only visible rows are rendered in DOM. When users try to copy text spanning multiple lines, unrendered rows are not included in
the browser's clipboard, resulting in incomplete copied content.

**Solution:**
1. **Selection Tracking**: Implement `saveSelection()` to capture logical position (line number + character offset) instead of relying on DOM nodes
2. **Custom Copy Handler**: Intercept `copy` event and extract complete text from `rawLines` array based on saved selection
3. **Auto-Expand**: Detect multi-line selections via `selectionchange` event and auto-expand when in collapsed state to prevent visual selection loss

The following tradeoffs were made:
- Removed selection restoration mechanism (which caused more issues than it solved due to virtual scroll conflicts)
- Accepted that visual selection highlight may be lost when scrolling in collapsed state (inherent virtual scroll limitation)
- Chose auto-expand over attempting to maintain selection across virtual scroll boundaries for better UX

The following alternatives were considered:
- Temporarily disable virtual scroll during selection (rejected: performance impact)
- Increase overscan dramatically (rejected: memory overhead)
- Show tooltip instead of auto-expand (rejected: requires extra user action)

Links to places where the discussion took place: 

### Breaking changes
None. This is a pure enhancement that improves existing functionality without changing any public APIs or data structures.

### Special notes for your reviewer
**Testing focus areas:**
1. Collapsed state + multi-line selection → should auto-expand
2. Copy in collapsed state → content should be complete
3. Setting `codeCollapsible = false` → auto-expand should not trigger
4. Console logs → verify selection tracking works correctly

**Key files changed:**
- `CodeViewer.tsx`: Added selection tracking and custom copy handler
- `CodeBlockView/view.tsx`: Pass `onRequestExpand` callback to CodeViewer

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### Release note

```release-note
fix: Improve code block copy functionality in collapsed state

- Copying code from collapsed code blocks now includes all selected lines, even those not visible due to virtual scrolling
- Multi-line selection in collapsed code blocks automatically expands the block to maintain selection visibility
- Auto-expand only activates when "Code block collapsible" setting is enabled
```

### CODE REVIEW

**Comment by DeJeune** [comment]
image

> [!NOTE]
> This issue/comment/review was translated by Claude.

It's possible for two items to be selected.

---
<details>
<summary>Original Content</summary>

有可能出现选中两个的情况

</details>

**Comment by ZKunZhang** [comment]
> image
> Note
> 
> This issue/comment/review was translated by Claude.
> 
> It's possible for two items to be selected.
> 
> Original Content
> 有可能出现选中两个的情况

Scoped selection handling to the current CodeViewer. Added selectionBelongsToViewer and use it to gate saveSelection, the copy handler, and collapsed auto- expand; if the selection is outside this viewer we clear saved state and do nothing, so two blocks cannot appear selected at once. Virtual-scroll behavior is preserved—custom copy still reconstructs full text from rawLines when needed

File: src/renderer/src/components/CodeViewer.tsx [hunk 1]
```diff
@@ -112,6 +136,203 @@ const CodeViewer = ({
...
+          })
+
+          event.clipboardData?.setData('text/plain', fullText)
+          event.preventDefault()
+        } catch (error) {
+          logger.error('Custom copy failed', { error })
+        }
+      }
+    },
+    [saveSelection, rawLines, expanded]
```
Comment (EurFelux) [inline src/renderer/src/components/CodeViewer.tsx]: there's a warning

File: src/renderer/src/components/CodeViewer.tsx [hunk 2]
```diff
@@ -112,6 +136,203 @@ const CodeViewer = ({
...
+      endOffset: end.offset
+    })
+
+    return {
+      startLine: start.line,
+      startOffset: start.offset,
+      endLine: end.line,
+      endOffset: end.offset
+    }
+  }, [])
```
Comment (EurFelux) [inline src/renderer/src/components/CodeViewer.tsx]: there's a warning

**Review by EurFelux — CHANGES_REQUESTED** [review]
Seems ok, but warnings should be resolved

**Review by 0xfullex — CHANGES_REQUESTED** [review]
## PR Review: Request Changes

Thank you for this well-thought-out fix for the virtual scroll copy issue! The approach of tracking logical selection positions and using a custom copy handler is solid. However, there are a few critical issues that should be addressed before merging.

---

### Critical Issues (Must Fix)

#### 1. Silent Clipboard Failure
**Location:** `CodeViewer.tsx` - `handleCopy` function

```typescript
event.clipboardData?.setData('text/plain', fullText)
event.preventDefault()
```

The optional chaining on `clipboardData` combined with unconditional `event.preventDefault()` means if `clipboardData` is null (which can happen in certain browser/Electron contexts), the copy silently fails - user presses Ctrl+C, sees no error, but clipboard is empty/stale.

**Suggested fix:**
```typescript
if (!event.clipboardData) {
  logger.warn('clipboardData unavailable, using browser default copy')
  return // Let browser handle default copy
}

event.clipboardData.setData('text/plain', fullText)
event.preventDefault() // Only prevent default AFTER successful write
```

Also move `event.preventDefault()` to after the successful `setData` call, and don't call it in the catch block.

---

#### 2. Missing `selectionBelongsToViewer` in Dependency Arrays
**Location:** `CodeViewer.tsx`

Both `saveSelection` and `handleCopy` use `selectionBelongsToViewer` but don't include it in their dependency arrays:

```typescript
const saveSelection = useCallback((): SavedSelection | null => {
  // Uses selectionBelongsToViewer
}, []) // Missing dependency

const handleCopy = useCallback((event: ClipboardEvent) => {
  // Uses selectionBelongsToViewer  
}, [saveSelection, rawLines, expanded]) // Missing dependency
```

**Fix:**
```typescript
}, [selectionBelongsToViewer])  // for saveSelection

}, [saveSelection, rawLines, expanded, selectionBelongsToViewer])  // for handleCopy
```

---

### Important Issues (Should Fix)

#### 3. Unused `isRestoringSelectionRef`
The ref is declared but never set to `true`, making the check in `handleScroll` dead code:
```typescript
const isRestoringSelectionRef = useRef(false)
// ...
if (isRestoringSelectionRef.current) return  // Always false
```

Either remove it or add a comment explaining why it's reserved for future use.

---

#### 4. `onRequestExpand` Not Passed to CodeEditor
In `view.tsx`, `onRequestExpand` is only passed to `CodeViewer`, not `CodeEditor`. If `codeEditor.enabled` is true, the auto-expand feature won't work. Consider whether this is intentional or if it should be added to `CodeEditor` as well.

---

### Minor Suggestions

1. Consider adding JSDoc to `SavedSelection` interface clarifying the coordinate system (0-indexed, character offset vs byte offset)

2. The comment `// 滚动事件处理：保存选择用于复制，但不恢复（避免选择高亮问题）` mentions restoration but `isRestoringSelectionRef` is never used - consider updating the comment or removing the ref

---

### What's Good

- ✅ Follows CLAUDE.md logging conventions with `loggerService.withContext('CodeViewer')`
- ✅ Good scoping with `selectionBelongsToViewer` to prevent cross-talk between code blocks
- ✅ Proper event listener cleanup in useEffect
- ✅ Well-documented `onRequestExpand` prop with JSDoc
- ✅ Thoughtful UX with auto-expand on multi-line selection

---

Please address the critical issues and the PR should be good to merge. Happy to re-review after updates!

File: src/renderer/src/components/CodeViewer.tsx (hunk 1 above)
Comment (ZKunZhang) [reply src/renderer/src/components/CodeViewer.tsx]: > there's a warning

done

File: src/renderer/src/components/CodeViewer.tsx (hunk 2 above)
Comment (ZKunZhang) [reply src/renderer/src/components/CodeViewer.tsx]: > there's a warning

done

**Review by EurFelux — COMMENTED** [review]
## Code Review Summary

Thank you for this comprehensive fix\! The solution is well-thought-out and the PR description is excellent. However, there are some important issues that need to be addressed before merging.

### 🚨 Blocking Issues

1. **Selection detection bug** - The `selectionBelongsToViewer` function may incorrectly handle cross-boundary selections (when user drags from outside into the viewer or vice versa)

2. **Performance concern** - The document-level `selectionchange` listener needs debouncing to avoid performance issues when multiple CodeViewer instances exist

### 📝 Specific Code Issues

**1. Fix `selectionBelongsToViewer` logic:**
```typescript
// Current implementation may fail for cross-boundary selections
// Suggested fix:
const selectionBelongsToViewer = useCallback((sel: Selection | null) => {
  const scroller = scrollerRef.current
  if (\!scroller || \!sel || sel.rangeCount === 0) return false
  
  // Check if selection intersects with scroller
  const range = sel.getRangeAt(0)
  return scroller.contains(range.commonAncestorContainer)
}, [])
```

**2. Debounce the selectionchange handler:**
```typescript
const handleSelectionChange = useMemo(() => 
  debounce(() => {
    const selection = window.getSelection()
    if (\!selectionBelongsToViewer(selection)) return
    // ... rest of logic
  }, 100), 
  [selectionBelongsToViewer, expanded, onRequestExpand]
)
```

**3. Always use custom copy in collapsed state:**
```typescript
// Current: const needsCustomCopy = \!expanded || isMultiLine
// Suggested: const needsCustomCopy = \!expanded
// Reason: Single-line copies below virtual scroll overscan could still fail
```

**4. Translate Chinese comments to English** - Lines 188, 275, 407 have Chinese comments that should be in English per codebase conventions

### 💡 Suggestions for Improvement

1. **Extract to custom hook** - Consider creating `useCodeSelection.ts` to reduce CodeViewer complexity
2. **Add throttling to scroll handler** - The scroll handler could cause performance issues without throttling
3. **Add comprehensive logging** - Include visible line ranges and selection age in debug logs

### ✅ What I Like

- Excellent use of centralized logging (`loggerService`)
- Smart approach using logical positions instead of DOM nodes
- Well-documented tradeoffs and alternatives
- Performance-conscious design avoiding expensive solutions

Please address the blocking issues and I'll approve. Great work overall\!

**Comment by ZKunZhang** [comment]
> ## Code Review Summary
> Thank you for this comprehensive fix! The solution is well-thought-out and the PR description is excellent. However, there are some important issues that need to be addressed before merging.
> 
> ### 🚨 Blocking Issues
> 1. **Selection detection bug** - The `selectionBelongsToViewer` function may incorrectly handle cross-boundary selections (when user drags from outside into the viewer or vice versa)
> 2. **Performance concern** - The document-level `selectionchange` listener needs debouncing to avoid performance issues when multiple CodeViewer instances exist
> 
> ### 📝 Specific Code Issues
> **1. Fix `selectionBelongsToViewer` logic:**
> 
> ```ts
> // Current implementation may fail for cross-boundary selections
> // Suggested fix:
> const selectionBelongsToViewer = useCallback((sel: Selection | null) => {
>   const scroller = scrollerRef.current
>   if (\!scroller || \!sel || sel.rangeCount === 0) return false
>   
>   // Check if selection intersects with scroller
>   const range = sel.getRangeAt(0)
>   return scroller.contains(range.commonAncestorContainer)
> }, [])
> ```
> 
> **2. Debounce the selectionchange handler:**
> 
> ```ts
> const handleSelectionChange = useMemo(() => 
>   debounce(() => {
>     const selection = window.getSelection()
>     if (\!selectionBelongsToViewer(selection)) return
>     // ... rest of logic
>   }, 100), 
>   [selectionBelongsToViewer, expanded, onRequestExpand]
> )
> ```
> 
> **3. Always use custom copy in collapsed state:**
> 
> ```ts
> // Current: const needsCustomCopy = \!expanded || isMultiLine
> // Suggested: const needsCustomCopy = \!expanded
> // Reason: Single-line copies below virtual scroll overscan could still fail
> ```
> 
> **4. Translate Chinese comments to English** - Lines 188, 275, 407 have Chinese comments that should be in English per codebase conventions
> 
> ### 💡 Suggestions for Improvement
> 1. **Extract to custom hook** - Consider creating `useCodeSelection.ts` to reduce CodeViewer complexity
> 2. **Add throttling to scroll handler** - The scroll handler could cause performance issues without throttling
> 3. **Add comprehensive logging** - Include visible line ranges and selection age in debug logs
> 
> ### ✅ What I Like
> * Excellent use of centralized logging (`loggerService`)
> * Smart approach using logical positions instead of DOM nodes
> * Well-documented tradeoffs and alternatives
> * Performance-conscious design avoiding expensive solutions
> 
> Please address the blocking issues and I'll approve. Great work overall!

done

**Review by EurFelux — COMMENTED** [review]
## Code Review

### Overview
Excellent PR that fixes a critical UX issue with text selection and copy operations in collapsed code blocks. The solution is well-researched and documented, but there's a **critical bug** that will prevent the feature from working.

---

## 🚨 Critical Issue: Missing `data-index` Attribute

The entire selection tracking system relies on finding elements with `data-index` attributes:

```typescript
// In findLineAndOffset function
if (!element || !element.hasAttribute('data-index')) {
  logger.warn('Could not find data-index element', ...)
  return null
}
```

**However**, the `VirtualizedRow` component (line 258) doesn't add this attribute:

```typescript
return (
  <div className="line">  // ❌ Missing data-index!
    {showLineNumbers && <span className="line-number">{index + 1}</span>}
```

**Fix required** in `src/renderer/src/components/CodeViewer.tsx:258`:

```diff
  return (
-   <div className="line">
+   <div className="line" data-index={index}>
      {showLineNumbers && <span className="line-number">{index + 1}</span>}
```

Without this, selection tracking will fail silently with warnings, and the custom copy handler won't work.

---

## ✅ Strengths

1. **Excellent documentation**: Clear explanation of the problem, solution, and tradeoffs
2. **Smart approach**: Using logical positions (line + offset) instead of DOM nodes is the right way to handle virtual scrolling
3. **Good defensive coding**: 
   - Selection ownership validation prevents interference
   - Proper fallbacks (`rawLines[i] || ''`)
   - Respects user settings (`codeCollapsible`)
4. **Comprehensive logging**: Will help debug production issues
5. **Auto-expand UX**: Smart decision to prevent selection loss

---

## 💡 Suggestions for Improvement

### 1. Performance - Debounce Timing
The 100ms debounce might feel sluggish for auto-expand:

```typescript
debounce(() => { ... }, 100)
```

Consider reducing to 50ms for better responsiveness.

### 2. Error Handling - Copy Handler
Add explicit check before accessing clipboardData:

```typescript
if (needsCustomCopy) {
  if (!event.clipboardData) {
    logger.error('ClipboardData not available')
    return
  }
  
  try {
    // ... existing logic ...
    event.clipboardData.setData('text/plain', fullText)  // Remove optional chaining
```

### 3. Code Quality - Mixed Languages
Some comments are in Chinese (line 58: "Shiki 流式代码高亮组件"), which is inconsistent with the primarily English codebase. Consider translating for maintainability.

---

## 🧪 Additional Testing Recommended

Beyond the manual testing mentioned in the PR:

- Multiple code blocks on same page (verify selection isolation)
- Very large files (10k+ lines) for performance
- Keyboard selection (Shift+arrows, Ctrl+A)
- Fast scrolling during selection
- Cross-platform verification (macOS/Linux in addition to Windows)

---

## 📝 Summary

**Status**: Request Changes

This is a well-designed solution to a real problem, but the missing `data-index` attribute is a blocker. Once that's added and verified, this will be ready to merge.

**Required**:
- Add `data-index={index}` to VirtualizedRow component

**Recommended**:
- Improve error handling in copy handler
- Consider reducing debounce delay

Great work on the thorough investigation and documentation! 🎉

**Comment by ZKunZhang** [comment]
> [!NOTE]
> This issue/comment/review was translated by Claude.

> ## Code Review - Request Changes
> Thank you for fixing most of the previously raised issues! The code quality has significantly improved. However, there are still two issues that need to be handled:
> 
> ### 🔴 Issues to Fix
> #### 1. clipboardData silent failure (Medium Priority)
> **Location:** `src/renderer/src/components/CodeViewer.tsx:327-328`
> 
> Current code:
> 
> ```ts
> event.clipboardData?.setData('text/plain', fullText)
> event.preventDefault()
> ```
> 
> **Issue:** If `clipboardData` is null (which might happen in certain browser/Electron contexts), the optional chain will skip `setData`, but `preventDefault()` still executes, causing users to press Ctrl+C with no response and empty/stale clipboard content.
> 
> **Suggested fix:**
> 
> ```ts
> if (!event.clipboardData) {
>   logger.warn('clipboardData unavailable, using browser default copy')
>   return  // Let browser handle default copy
> }
> event.clipboardData.setData('text/plain', fullText)
> event.preventDefault()
> ```
> 
> #### 2. isRestoringSelectionRef dead code (Low Priority)
> **Location:** `src/renderer/src/components/CodeViewer.tsx:96, 245`
> 
> ```ts
> const isRestoringSelectionRef = useRef(false)  // declaration
> // ...
> if (isRestoringSelectionRef.current) return  // check, but never true
> ```
> 
> This ref is never set to `true`, causing the check to never trigger.
> 
> **Suggestion:** Remove this dead code, or add comments explaining why it's kept (if reserved for future use).
> 
> ### ℹ️ Notes (Non-blocking)
> * **onRequestExpand not passed to CodeEditor** - Noted that `onRequestExpand` is only passed to `CodeViewer` not `CodeEditor`. If this is intentional design, please ignore.
> * **Chinese comments** - There's a mix of Chinese and English comments in the code. Since other files in the project have similar situations, this might be a project convention, so not requiring modification.
> 
> Please fix the above two issues and I'll approve this PR. The overall implementation approach is very good! 👍
> 
> I've fixed these two issues.

---
<details>
<summary>Original Content</summary>

> ## Code Review - Request Changes
> 感谢修复了之前提出的大部分问题！代码质量明显改善。但还有两个问题需要处理：
> 
> ### 🔴 需要修复的问题
> #### 1. clipboardData 静默失败 (Medium Priority)
> **位置:** `src/renderer/src/components/CodeViewer.tsx:327-328`
> 
> 当前代码：
> 
> ```ts
> event.clipboardData?.setData('text/plain', fullText)
> event.preventDefault()
> ```
> 
> **问题：** 如果 `clipboardData` 为 null（在某些浏览器/Electron 上下文中可能发生），可选链会跳过 `setData`，但 `preventDefault()` 仍然执行，导致用户按 Ctrl+C 没有任何反应且剪贴板内容为空/过期。
> 
> **建议修复：**
> 
> ```ts
> if (!event.clipboardData) {
>   logger.warn('clipboardData unavailable, using browser default copy')
>   return  // 让浏览器处理默认复制
> }
> event.clipboardData.setData('text/plain', fullText)
> event.preventDefault()
> ```
> 
> #### 2. isRestoringSelectionRef 死代码 (Low Priority)
> **位置:** `src/renderer/src/components/CodeViewer.tsx:96, 245`
> 
> ```ts
> const isRestoringSelectionRef = useRef(false)  // 声明
> // ...
> if (isRestoringSelectionRef.current) return  // 检查，但永远为 false
> ```
> 
> 这个 ref 从未被设置为 `true`，导致检查永远不会触发。
> 
> **建议：** 移除这段死代码，或添加注释说明为什么保留它（如果是为将来预留）。
> 
> ### ℹ️ 说明（非阻塞）
> * **onRequestExpand 未传给 CodeEditor** - 注意到 `onRequestExpand` 只传给 `CodeViewer` 而非 `CodeEditor`。如果这是有意设计请忽略。
> * **中文注释** - 代码中有中英文注释混杂。既然项目其他文件也有类似情况，这可能是项目惯例，不强求修改。
> 
> 请修复上述两个问题后，我会批准此 PR。整体实现方案很好！👍
> 
> 我修复这两个问题了。

</details>

**Comment by EurFelux** [comment]
I've seen the latest code. `isRestoringSelectionRef` is still always false, and clipboard problem is still not fixed too.

**Comment by ZKunZhang** [comment]
> I've seen the latest code. is still always false, and clipboard problem is still not fixed too.`isRestoringSelectionRef`

Could you please take another look? It has been fixed.

**Comment by EurFelux** [comment]
@0xfullex
