### PR TITLE
fix: fallback when invalid reasoning effort

### LINKED ISSUE #8610: [错误]: 多模型思维链设置的统一问题
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我的问题不是 [常见问题](https://github.com/CherryHQ/cherry-studio/issues/3881) 中的内容。
- [x] 我已经查看了 **置顶 Issue** 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。

### 平台

macOS

### 版本

v 1.5.3

### 错误描述

在话题界面设置带“自动”思维链的模型时，艾特调用包括o系列模型，会显示400、无法识别auto参数。猜测是个参数的命名有关。
浮想斟酌和沉思三个选项下，无此问题

Image

### 重现步骤

1. 话题模型设置为gemini 2.5
2.@调用openai官方的o系列模型
3.报错400

### 预期行为

所有模型能否共用一套思维链设置参数？

### 相关日志输出

```shell

```

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by EurFelux**
### What this PR does

选择的 reasoning effort 无效时会自动回退到有效的选项

Fixes #8610

### Why we need it and why it was done in this way

The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Breaking changes

If this PR introduces breaking changes, please describe the changes and the impact on users.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### Release note

```release-note

```

### CODE REVIEW

File: src/renderer/src/config/models.ts [hunk 1]
```diff
@@ -271,6 +271,56 @@ export const CLAUDE_SUPPORTED_WEBSEARCH_REGEX = new RegExp(
...
+  qwen: ['off', ...MODEL_SUPPORTED_REASONING_EFFORT.qwen] as const,
+  qwen_3235ba22b_thinking: [...MODEL_SUPPORTED_REASONING_EFFORT.qwen_3235ba22b_thinking] as const,
+  doubao: ['off', ...MODEL_SUPPORTED_REASONING_EFFORT.doubao] as const,
+  hunyuan: ['off', ...MODEL_SUPPORTED_REASONING_EFFORT.hunyuan] as const,
+  zhipu: ['off', ...MODEL_SUPPORTED_REASONING_EFFORT.zhipu] as const,
+  perplexity: [...MODEL_SUPPORTED_REASONING_EFFORT.perplexity] as const
+} as const
+
+export const getThinkModelType = (model: Model): ThinkingModelType => {
+  if (isSupportedReasoningEffortGrokModel(model)) {
```
Comment (GeorgeDong32) [inline src/renderer/src/config/models.ts]: 这里是不是判错了，应该是GeminiModel吧

**Review by GeorgeDong32 — CHANGES_REQUESTED** [review]

File: src/renderer/src/config/models.ts (hunk 1 above)
Comment (EurFelux) [reply src/renderer/src/config/models.ts]: fixed

**Review by GeorgeDong32 — APPROVED** [review]
