### PR TITLE
fix(reasoning): thinking control for ds v3.1 of tencent platform

### LINKED ISSUE #10328: [Bug]: Deepseek v3.1-terminus chain-of-thought settings not displayed consistently across model providers
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

macOS

### Version

v1.5.11

### Bug Description

A model I often use is Deepseek's v3.1. Recently, they just updated to the latest version, v3.1-terminus. The current issue is that some model providers correctly enable the chain-of-thought length setting, like ByteDance's Volcano. Some don't display this switch and can only customize parameters in the model settings, like the API access provided by Tencent Cloud.

### Steps To Reproduce

ByteDance's access point:   https://ark.cn-beijing.volces.com/api/v3/chat/completions
Model name:  deepseek-v3-1-terminus
Tencent Cloud's access point:   https://api.lkeap.cloud.tencent.com/v1/chat/completions
Model name:  deepseek-v3.1-terminus

### Expected Behavior

Since this model is Deepseek's latest model, can all v3.1-terminus be correctly provided with chain-of-thought length and switch settings?

### Relevant Log Output

```shell

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by GeorgeDong32**
### What this PR does

Before this PR:
- Tencent TI and Hunyuan reasoning backends lacked proper "thinking" configuration support.

After this PR:
- Adds Hunyuan and Tencent TI "thinking" configuration to the reasoning module.

Fixes #10328

### CODE REVIEW

**Comment by GeorgeDong32** [comment]
@claude review

**Review by beyondkmp — APPROVED** [review]

File: src/renderer/src/aiCore/utils/reasoning.ts [hunk 1]
```diff
@@ -112,6 +112,13 @@ export function getReasoningEffort(assistant: Assistant, model: Model): Reasonin
           return {
             enable_thinking: true
           }
+        case SystemProviderIds.hunyuan:
+        case SystemProviderIds['tencent-cloud-ti']:
+          return {
```
Comment (EurFelux) [inline src/renderer/src/aiCore/utils/reasoning.ts]: 相同格式的，跟下面豆包合并就可以了

**Comment by EurFelux** [comment]
main force pushed

File: package.json [hunk 2]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "CherryStudio",
-  "version": "1.6.0-rc.4",
+  "version": "1.6.0-rc.5",
```
Comment (EurFelux) [inline package.json]: should revert

Comment (GeorgeDong32) [reply package.json]: Done
