### PR TITLE
fix(openai): Gemma system message

### LINKED ISSUE #9543: [错误]: Gemma模型没有传递系统提示词
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我的问题不是 [常见问题](https://github.com/CherryHQ/cherry-studio/issues/3881) 中的内容。
- [x] 我已经查看了 **置顶 Issue** 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。
- [x] 我确认我正在使用最新版本的 Cherry Studio。

### 平台

Windows

### 版本

v1.5.7

### 错误描述

使用Llama.cpp运行的模型，使用Ollama和自定义服务商配置，都无法正确传递系统提示词，其它模型正常，直接调用OpenAI兼容接口也正常，使用的是mlabonne/gemma-3-27b-it-abliterated-GGUF的gemma-3-27b-it-abIiterated.q4_k_m.gguf模型

Image

### 重现步骤

1. 使用Docker运行模型
2. 配置服务商
3. 配置系统提示词
4. 对话

### 预期行为

正常传递系统提示词，符合人设预期

### 相关日志输出

```shell

```

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by EurFelux**
### What this PR does

给 OpenAI API 的 Gemma 模型适配 System Message，不要直接删掉，而是转换成 User Message

Fixes #9543

### Why we need it and why it was done in this way

The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Breaking changes

If this PR introduces breaking changes, please describe the changes and the impact on users.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### Release note

```release-note

```

### CODE REVIEW

**Review by beyondkmp — APPROVED** [review]

File: src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts [hunk 1]
```diff
@@ -588,9 +588,13 @@ export class OpenAIAPIClient extends OpenAIBaseClient<
 
         // 4. 最终请求消息
         let reqMessages: OpenAISdkMessageParam[]
-        if (!systemMessage.content || isNotSupportSystemMessageModel(model)) {
+        if (!systemMessage.content) {
           reqMessages = [...userMessages]
         } else {
+          if (isNotSupportSystemMessageModel(model)) {
```
Comment (DeJeune) [inline src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts]: 多个user消息在一起会不会出问题

Comment (EurFelux) [reply src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts]: openrouter没问题，可以多测一下

Comment (EurFelux) [reply src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts]: 和第一条用户消息连在一起吧，这样健壮一点

Comment (EurFelux) [reply src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts]: 简单测了一下，感觉还ok

**Review by DeJeune — APPROVED** [review]
