### PR TITLE
fix: capture detailed error response body for reranker API failures

### LINKED ISSUE #10825: [Bug]: qwen3-reranker not available
> [!NOTE]
> This issue/comment/review was translated by Claude.

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.6.4

### Bug Description

Image

always happens. no exception. but the embedding model is fine. this screenshot is that i asked deepseek3.1ter to return the whole err report if it occurs. it only shows 400 without details. i don't know why. aihubmix says it's not their responsibility.

### Steps To Reproduce

qwen3-8b-reranker in aihubmix, knowledge base

### Expected Behavior

fix it

### Relevant Log Output

```shell

```

### Additional Context

_No response_

---
<details>
<summary>Original Content</summary>

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.6.4

### Bug Description

Image

always happens. no exception. but the embedding model is fine. this screenshot is that i asked deepseek3.1ter to return the whole err report if it occurs. it only shows 400 without details. i don't know why. aihubmix says it's not their responsibility.

### Steps To Reproduce

qwen3-8b-reranker in aihubmix, knowledge base

### Expected Behavior

fix it

### Relevant Log Output

```shell

```

### Additional Context

_No response_

</details>

### PR DESCRIPTION
**Pull request by ZKunZhang**
Previously, when reranker API returned 400 or other error status codes, only the HTTP status and status text were captured, without reading the actual error response body that contains detailed error information.

This commit fixes the issue by:
- Reading the error response body (as JSON or text) before throwing error
- Attaching the response details to the error object
- Including responseBody in formatErrorMessage output

This will help diagnose issues like "qwen3-reranker not available" by showing the actual error message from the API provider.

### What this PR does

**Before this PR:**

When reranker API returns an error (e.g., 400 Bad Request), only generic HTTP status information was captured:

```json
{
  "url": "https://aihubmix.com/v1/rerank",
  "message": "HTTP 400: ",
  "requestBody": {...}
}
```

Users could not see the actual error message from the API provider, making it impossible to diagnose the root cause (e.g., invalid model name, missing permissions, etc.).

**After this PR:**

The complete error response body is now captured and displayed:

```json
{
  "url": "https://aihubmix.com/v1/rerank",
  "message": "HTTP 400: Bad Request",
  "status": 400,
  "statusText": "Bad Request",
  "responseBody": {
    "error": {
      "message": "Model 'qwen3-reranker-8b' is not available",
      "type": "invalid_request_error",
      "code": "model_not_found"
    }
  },
  "requestBody": {...}
}
```

This provides clear, actionable error information for debugging.

Fixes #10825

### Why we need it and why it was done in this way

**Problem:**
Users were unable to diagnose reranker API failures because error messages only showed "HTTP 400" without the detailed error information returned by the API provider. This made it impossible to determine whether the issue was due to:
- Invalid model name
- Missing API permissions
- Unsupported endpoint
- Request format errors
- Other provider-specific issues

**Solution:**
Read the complete HTTP response body before throwing the error and attach it to the error object. This approach:
1. Maintains backward compatibility - Only adds new information, doesn't change existing behavior
2. Handles multiple formats gracefully - Tries JSON first, falls back to text, then null
3. Minimal performance impact - Only executes in error cases
4. No risk of crashes - Multiple try-catch blocks ensure safe error handling

The following tradeoffs were made:
- Reads the entire response body into memory (acceptable since error responses are typically small)
- Adds minimal processing time during error scenarios (acceptable trade-off for better diagnostics)

The following alternatives were considered:
- Logging only (rejected: users need to see errors in the UI)
- Partial error message extraction (rejected: might miss important details)
- Separate API endpoint for debugging (rejected: too complex for this use case)

Links to places where the discussion took place: 

### Breaking changes

If this PR introduces breaking changes, please describe the changes and the impact on users.

None. This PR only enhances error messages by adding additional information. All existing error handling code continues to work as before.

### Special notes for your reviewer

**Testing suggestions:**
1. Configure a knowledge base with an invalid reranker model name
2. Trigger a knowledge base search that would invoke the reranker
3. Verify that the error message now includes the responseBody field with detailed API error information

**Files changed:**
- src/main/knowledge/reranker/BaseReranker.ts: Added responseBody to error details
- src/main/knowledge/reranker/GeneralReranker.ts: Read and attach response body to error object

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### Release note

```release-note
fix: Capture detailed error response body for reranker API failures. When reranker API returns error status codes (400, 401, etc.), the full error response from the API provider is now displayed, making it easier to diagnose issues like invalid model names or permission problems.
```

### CODE REVIEW

File: src/main/knowledge/reranker/GeneralReranker.ts [hunk 1]
```diff
@@ -17,7 +17,27 @@ export default class GeneralReranker extends BaseReranker {
...
+        } catch {
+          // If response body is not JSON, try to read as text
+          try {
+            errorBody = await response.text()
+          } catch {
+            errorBody = null
+          }
+        }
+
+        const error = new Error(`HTTP ${response.status}: ${response.statusText}`)
```
Comment (DeJeune) [inline src/main/knowledge/reranker/GeneralReranker.ts]: 这里可以新建一个`ReRank Error`类

Comment (ZKunZhang) [reply src/main/knowledge/reranker/GeneralReranker.ts]: > 这里可以新建一个`ReRank Error`类

Ok, I'll make some adjustments.  
done

File: src/main/knowledge/reranker/GeneralReranker.ts [hunk 2]
```diff
@@ -17,7 +17,27 @@ export default class GeneralReranker extends BaseReranker {
...
+        try {
+          errorBody = await response.json()
+        } catch {
+          // If response body is not JSON, try to read as text
+          try {
+            errorBody = await response.text()
+          } catch {
+            errorBody = null
+          }
+        }
```
[the remark this answers is not in the document]
Comment (ZKunZhang) [reply src/main/knowledge/reranker/GeneralReranker.ts:43]: > Reading the response body multiple times may cause issues. Once a response body is consumed (by `response.json()` or `response.text()`), it cannot be read again. The current nested try-catch structure could attempt to read the same response body twice, which would fail. Consider using `response.clone()` or checking the response content-type header to determine the appropriate parsing method.

done

**Review by DeJeune — APPROVED** [review]
