### PR TITLE
fix: handle symlinks during backup copy

### LINKED ISSUE #14360: [Bug]: Backup fails on Windows with EPERM when trying to run backup without admin privileges on v1.9.1
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.9.1

### Bug Description

The backup process fails entirely when it encounters symbolic links on Windows. 

This is a Windows error where the backup process is trying to create a symlink, but on Windows, creating symlinks requires elevated privileges (administrator) or Windows Developer Mode to be enabled.

CherryStudio's backup is attempting to recreate symlinks from the skills system, but Windows blocks this without admin rights. The backup process fails entirely instead of handling this gracefully

Image

### Steps To Reproduce

1. Install v1.9.1 (find-skills is a built-in skill in Cherry Studio)
2. Run CherryStudio backup as a non-admin user without enabling Windows Developer Mode
3. Backup fails with EPERM: operation not permitted, symlink

### Expected Behavior

Backup should complete successfully

### Relevant Log Output

```shell
Error invoking remote method 'backup:backupToLocalDir': 
Error: EPERM: operation not permitted, symlink 
'...\Data\Skills\find-skills' -> '...\backup\temp\...\skills\find-skills'
```

### Additional Context

- Backup fails when running as standard user (non-admin, Windows Developer Mode disabled)
- Backup complete without any problem when Cherry Studio run with admin privileges

### PR DESCRIPTION
**Pull request by kangfenmao**
### What this PR does

Before this PR:

Windows backups could fail for non-admin users when the Data directory contained symlinks, because the backup copy attempted to recreate symlink entries and hit `EPERM: operation not permitted, symlink`.

After this PR:

Backup copy dereferences valid symlinks and stores the target file or directory contents in the backup. Broken or unreadable symlinks are skipped with a warning. Restore copy skips symlink entries from old or handcrafted backup archives instead of following them.

Fixes #14360

### Why we need it and why it was done in this way

The following tradeoffs were made:

This preserves usable backup content instead of preserving filesystem-level symlink identity. Restored symlinked skills become regular files/directories, which avoids requiring elevated Windows privileges.

The following alternatives were considered:

Copying symlink entries directly was considered, but it can still fail on Windows without administrator privileges or Developer Mode. Skipping symlinks entirely was also considered, but that can omit useful skill content from backups.

Links to places where the discussion took place: https://github.com/CherryHQ/cherry-studio/issues/14360

### Breaking changes

None.

### Special notes for your reviewer

This is intentionally scoped as a `main` hotfix. It only changes BackupManager's file copy behavior and related tests.

Validated locally with:

- `pnpm test:main src/main/services/__tests__/BackupManager.test.ts`
- `pnpm typecheck:node`
- `pnpm format`
- `pnpm test`
- `pnpm lint`
- `git diff --check`

`pnpm lint` still prints an unrelated existing React Hooks warning in `src/renderer/src/pages/settings/ProviderSettings/ModelList/ManageModelsPopup.tsx:177`, but exits successfully.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. Check this only when the PR introduces or changes a user-facing feature or behavior.
- [x] Self-review: I have reviewed my own code (e.g., via [`/gh-pr-review`](/.claude/skills/gh-pr-review/SKILL.md), `gh pr diff`, or GitHub UI) before requesting review from others

### Release note

```release-note
Fix Windows backup failures caused by symlinks in the Data directory when running without administrator privileges.
```

### CODE REVIEW

**Comment by GeorgeDong32** [comment]
## Code Review: Symlink Backup Handling

Overall this is a clean, well-scoped hotfix. The refactoring into `getEffectiveEntryStats`, `createCopyProgressHandler`, and the backup/restore `dereferenceSymlinks` option split is well thought out. Tests are thorough.

### One Gap: Circular Symlink Protection

The current implementation lacks protection against circular symlinks. While unlikely in the Data directory in practice, a malicious or accidental symlink loop (e.g., `dir/link -> dir`) would cause infinite recursion in `getDirSize` and `copyDirWithProgress`, eventually crashing with a stack overflow.

We have a local branch (`14208-fix-backup-symlink`) that addresses the same issue and includes circular symlink detection using a `visited Set<string>` + `fs.realpath`:

```typescript
// In getDirSize, countFiles, copyDir:
const visitedSet = new Set<string>()

const realPath = await fs.realpath(dirPath)
if (visitedSet.has(realPath)) {
  logger.warn('[getDirSize] Circular symlink detected, skipping', { path: dirPath })
  return 0 // or return for void functions
}
visitedSet.add(realPath)
```

### Suggested Enhancement

Consider adding circular detection to `getDirSize` and `copyDirWithProgress` — a small addition that prevents a hard-to-debug crash edge case:

- `getDirSize`: pass a `visited` set through recursive calls, bail out on `realpath` revisits
- `copyDirWithProgress`: same pattern in the `copyDir` inner function

This can be a follow-up if you'd prefer to keep this PR minimal.

### Minor Observations (non-blocking)

1. **Backup vs Restore strategy**: The `dereferenceSymlinks: false` on restore is the right call — skipping symlinks from backup archives avoids creating dangling links on the target system.
2. **Test quality**: Good coverage of valid/broken symlink cases. The `createStats`/`createDirent` helpers keep tests readable.

---

*Note: We have a local branch addressing the same #14360 issue with a different approach (incremental changes + circular detection). Happy to share the full diff if useful.*

File: src/main/services/BackupManager.ts [hunk 1]
```diff
@@ -809,22 +826,54 @@ class BackupManager {
...
+      const entry = await this.getEffectiveEntryStats(fullPath, options)
+
+      if (!entry) {
+        continue
+      }
+
+      if (entry.stats.isDirectory()) {
+        if (entry.isSymlink) {
+          try {
+            size += await this.getDirSize(fullPath, options)
```
Comment (404-Page-Found) [inline src/main/services/BackupManager.ts]: **[A2]** Track visited real paths before recursing into symlinked directories. A symlink that points back to an ancestor can make both getDirSize and copyDirWithProgress recurse indefinitely. Please add a visited-set guard around the resolved target path before descending.

**Review by 404-Page-Found — CHANGES_REQUESTED** [review]
The symlink handling change still needs cycle protection before it is safe to merge.

**Review by DeJeune — COMMENTED** [review]
Review notes on symlink copy behavior — see three inline comments. Overall the dereference-on-backup / skip-on-restore split is sound and the cycle guard is a nice touch; a few refinements before this lands.

File: src/main/services/BackupManager.ts [hunk 2]
```diff
@@ -809,24 +826,72 @@ class BackupManager {
...
+  ) {
+    let copiedSize = 0
+
+    return (size: number) => {
+      copiedSize += size
+      const progress =
+        totalSize > 0
+          ? Math.min(endProgress, startProgress + Math.floor((copiedSize / totalSize) * (endProgress - startProgress)))
+          : endProgress
+      onProgress({ stage, progress, total: 100 })
```
Comment (DeJeune) [inline src/main/services/BackupManager.ts:850]: **Progress IPC throttle is gone.**

The old `copyDirWithProgress` only invoked `onProgress` when the integer percent advanced by ≥5% (or on the last file). Here the handler fires once per file copied, and each call goes straight to `mainWindow.webContents.send(channel, processData)` in `onProgress` above.

A Data directory with thousands of small files (embeddings, caches, chat history) will now flood the renderer with IPC messages during backup/restore. Worth re-adding a cheap gate here, e.g.:

```ts
let lastReported = startProgress
return (size: number) => {
  copiedSize += size
  const progress = totalSize > 0
    ? Math.min(endProgress, startProgress + Math.floor((copiedSize / totalSize) * (endProgress - startProgress)))
    : endProgress
  if (progress === lastReported && copiedSize < totalSize) return
  lastReported = progress
  onProgress({ stage, progress, total: 100 })
}
```

That also makes the new behavior strictly an improvement on the old throttle (which had a correctness bug — it summed only the sizes of files that happened to cross the 5% boundary, so the bar never reached 100%).

File: src/main/services/BackupManager.ts [hunk 3]
```diff
@@ -927,58 +992,105 @@ class BackupManager {
...
+  }
+
+  private async getSymlinkTargetStats(sourcePath: string, options: CopyDirOptions): Promise<Stats | null> {
+    if (!options.dereferenceSymlinks) {
+      logger.warn('[BackupManager] Skipping symlink during restore', { path: sourcePath })
+      return null
+    }
+
+    try {
+      return await fs.stat(sourcePath)
```
Comment (DeJeune) [inline src/main/services/BackupManager.ts]: **External symlinks get silently expanded into the backup.**

`fs.stat` + `fs.copy(..., { dereference: true })` happily follows absolute links pointing outside the Data root. A stray `ln -s ~/Downloads cherry-studio/Data/Skills/foo` (or a package manager that drops a symlink to a system dir) will drag the entire target tree into the archive. For a Windows user hitting this bug today, the common cases are probably benign, but the blast radius is large and the symptom (huge or stuck backup) is hard to diagnose.

Consider gating dereference on `realpath(target).startsWith(sourceRoot)` — dereference when internal, skip + `logger.warn` when external. At minimum, log each dereferenced target so an oversized backup can be traced.

File: src/main/services/BackupManager.ts [hunk 4]
```diff
@@ -927,58 +992,105 @@ class BackupManager {
...
+      return { isSymlink: false, stats }
+    }
+
+    const targetStats = await this.getSymlinkTargetStats(sourcePath, options)
+    return targetStats ? { isSymlink: true, stats: targetStats } : null
+  }
+
+  private async getSymlinkTargetStats(sourcePath: string, options: CopyDirOptions): Promise<Stats | null> {
+    if (!options.dereferenceSymlinks) {
+      logger.warn('[BackupManager] Skipping symlink during restore', { path: sourcePath })
```
Comment (DeJeune) [inline src/main/services/BackupManager.ts]: **Warning text hardcodes a caller context.**

`getSymlinkTargetStats` logs *“Skipping symlink during restore”* whenever `dereferenceSymlinks: false`. It happens to only be reached from the restore paths today, but the helper's contract is about the option, not the caller. The next time someone calls `copyDirWithProgress` with `dereferenceSymlinks: false` from a non-restore code path, this log will lie.

Phrase it in terms of the option, e.g. `'[BackupManager] Skipping symlink (dereferenceSymlinks=false)'`, and include `path`.

File: src/main/services/BackupManager.ts (hunk 2 above)
Comment (GeorgeDong32) [inline src/main/services/BackupManager.ts:850]: **Progress IPC throttle is gone.**

The old `copyDirWithProgress` only invoked `onProgress` when the integer percent advanced by ≥5% (or on the last file). Here the handler fires once per file copied, and each call goes straight to `mainWindow.webContents.send(channel, processData)`.

A Data directory with thousands of small files (embeddings, caches, chat history) will now flood the renderer with IPC messages during backup/restore. Worth re-adding a cheap gate:

```ts
let lastReported = startProgress
return (size: number) => {
  copiedSize += size
  const progress = totalSize > 0
    ? Math.min(endProgress, startProgress + Math.floor((copiedSize / totalSize) * (endProgress - startProgress)))
    : endProgress
  if (progress === lastReported && copiedSize < totalSize) return
  lastReported = progress
  onProgress({ stage, progress, total: 100 })
}
```

This also fixes the old throttle's correctness bug (it summed only files crossing the 5% boundary, so the bar never reached 100%).

File: src/main/services/BackupManager.ts [hunk 5]
```diff
@@ -927,58 +992,105 @@ class BackupManager {
...
+            } catch (error) {
+              if (!entry.isSymlink) {
+                throw error
+              }
+              await fs.remove(destPath).catch(() => {})
+              this.logSkippedSymlink(sourcePath, error)
+            }
+          } else if (entry.stats.isFile()) {
+            if (entry.isSymlink) {
+              await fs.copy(sourcePath, destPath, { dereference: true })
```
Comment (GeorgeDong32) [inline src/main/services/BackupManager.ts:1047]: **External symlinks get silently expanded into the backup.**

`fs.stat` + `fs.copy(..., { dereference: true })` happily follows absolute links pointing outside the Data root. A stray `ln -s ~/Downloads cherry-studio/Data/Skills/foo` (or a package manager that drops a symlink to a system dir) will drag the entire target tree into the archive. For a Windows user hitting this bug today, common cases are probably benign, but the blast radius is large and the symptom (huge or stuck backup) is hard to diagnose.

Consider gating dereference on `realpath(target).startsWith(sourceRoot)` — dereference when internal, skip + `logger.warn` when external. At minimum, log each dereferenced target so an oversized backup can be traced.

File: src/main/services/BackupManager.ts (hunk 4 above)
Comment (GeorgeDong32) [inline src/main/services/BackupManager.ts]: **Warning text hardcodes a caller context.**

`getSymlinkTargetStats` logs *"Skipping symlink during restore"* whenever `dereferenceSymlinks: false`. It happens to only be reached from the restore paths today, but the helper's contract is about the option, not the caller. The next time someone calls `copyDirWithProgress` with `dereferenceSymlinks: false` from a non-restore code path, this log will be misleading.

Phrase it in terms of the option, e.g. `'[BackupManager] Skipping symlink (dereferenceSymlinks=false)'`, and include `path`.

**Review by GeorgeDong32 — CHANGES_REQUESTED** [review]
## Code Review: PR #14471 — `fix: handle symlinks during backup copy`

Overall this is a well-scoped hotfix with solid architecture. The refactoring into `getEffectiveEntryStats`, `createCopyProgressHandler`, and the backup/restore `dereferenceSymlinks` option split is well thought out. The circular symlink detection via `enterDirectory` + `activeDirectoryRealPaths` is a good addition.

### Three items before merge

Three refinements to address — all non-critical but worth fixing before landing:

1. **Progress IPC throttle is gone** (line 844) — The old handler only fired when the integer percent advanced by ≥5%. The new one fires on every file. For a Data directory with thousands of small files, this floods the renderer with IPC messages. Worth re-adding a cheap gate.

2. **External symlinks get silently expanded into the backup** (line 1033) — `fs.copy(..., { dereference: true })` follows absolute links pointing outside the Data root. A stray `ln -s ~/Downloads` could drag unintended content into the archive. Consider gating on `realpath(target).startsWith(sourceRoot)` or at minimum logging each dereferenced target.

3. **Warning text hardcodes a caller context** (line 1078) — `'Skipping symlink during restore'` conflates the option value with the caller's intent. Phrase it in terms of the option: `'Skipping symlink (dereferenceSymlinks=false)'`.

### Minor (non-blocking)

- `getDirSize` signature change from 1 to 2 required args is fine at call sites, but a default `options` param would be safer for future callers.
- `else if (entry.isSymlink)` fallback branch (line ~1039) is technically correct but could use a comment explaining when it's reached.

---

Overall code quality is strong. The test coverage for symlink scenarios is thorough and the error handling is comprehensive. These three items are straightforward to address.

**Comment by kangfenmao** [comment]
After testing, the repair is effective
