### PR TITLE
fix: Update the state of the last message block as a fallback

### LINKED ISSUE #6059: [错误]: 当已经返回空回复时，界面仍在转圈等待输出
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我的问题不是 [常见问题](https://github.com/CherryHQ/cherry-studio/issues/3881) 中的内容。
- [x] 我已经查看了 **置顶 Issue** 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。

### 平台

Windows

### 版本

v1.3.4

### 错误描述

data: {"id": "chatcmpl-keepalive", "object": "chat.completion.chunk", "created": 1747381602, "model": "[PAY]gemini-2.5-pro-preview-03-25-auto", "choices": [{"delta": {"content": ""}, "index": 0, "finish_reason": null}]}

data: {"id": "chatcmpl-keepalive", "object": "chat.completion.chunk", "created": 1747381603, "model": "[PAY]gemini-2.5-pro-preview-03-25-auto", "choices": [{"delta": {"content": ""}, "index": 0, "finish_reason": null}]}

data: {"id": "chatcmpl-1747381602", "object": "chat.completion.chunk", "created": 1747381604, "model": "[PAY]gemini-2.5-pro-preview-03-25-auto", "choices": [{"index": 0, "delta": {}, "finish_reason": "stop"}]}

data: [DONE]
模型已经返回了空回复

Image

### 重现步骤

模型空回复时出现

### 预期行为

ui界面不应继续等待返回

### 相关日志输出

```shell

```

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by DeJeune**
### What this PR does

Before this PR:

image

image

After this PR:

image

image

Fixes #6059 

### Why we need it and why it was done in this way

The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Breaking changes

If this PR introduces breaking changes, please describe the changes and the impact on users.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### Release note

```release-note

```

### CODE REVIEW

File: src/renderer/src/store/thunk/messageThunk.ts [hunk 1]
```diff
@@ -622,6 +622,14 @@ const fetchAndProcessAssistantResponseImpl = async (
...
           const finalContextWithAssistant = [...contextForUsage, finalAssistantMsg]
 
+          if (lastBlockId) {
+            const changes: Partial<MessageBlock> = {
+              status: MessageBlockStatus.SUCCESS
+            }
+            dispatch(updateOneBlock({ id: lastBlockId, changes }))
+            saveUpdatedBlockToDB(lastBlockId, assistantMsgId, topicId, getState)
+          }
+
```
Comment (MyPrototypeWhat) [inline src/renderer/src/store/thunk/messageThunk.ts:632]: 加这个判断是因为有块的complete没正确执行吗

Comment (DeJeune) [reply src/renderer/src/store/thunk/messageThunk.ts:632]: 会出现如思考块会出现直接达到最大长度就被截断（思考还没完成），还有空回复（没有任何消息块一直pending）
主要为了兜底这些边界条件

**Review by MyPrototypeWhat — APPROVED** [review]
