### PR TITLE
Fix/translate selection

### LINKED ISSUE #8924: [错误]: qwen-mt-plus模型使用划词助手翻译时翻译两次
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我的问题不是 [常见问题](https://github.com/CherryHQ/cherry-studio/issues/3881) 中的内容。
- [x] 我已经查看了 **置顶 Issue** 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。
- [x] 我确认我正在使用最新版本的 Cherry Studio。

### 平台

Windows

### 版本

v1.5.4

### 错误描述

上一个版本的翻译模型我用的deepseek-v3一切正常，这个版本支持qwen-mt后我把翻译模型换成了qwen-mt-plus，然后划词助手翻译就会翻译两次（内置翻译应用正常），如图所示

Image

Image

Image

若继续换成deepseek-v3模型则正常，其他模型没试过

### 重现步骤

1.使用qwen-mt-plus模型
Image

2.使用划词助手翻译
Image

### 预期行为

预期应该只翻译一次，如下图使用deepseek-v3

Image

### 相关日志输出

```shell

```

### 附加信息

补充：qwen-mt-turbo模型也有这个问题，用的是阿里云百炼的api

### PR DESCRIPTION
**Pull request by EurFelux**
### What this PR does

- 重构翻译接口，将`fetchTranslate`迁移到`TranslateService`并不再导出，外部统一使用导出的`translateText`函数。
- 修复了划词翻译处理了多余块的问题。QwenMT会输出两个`finish_reason: stop`的块，没处理好。

Fixes #8924

### Why we need it and why it was done in this way

The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Breaking changes

If this PR introduces breaking changes, please describe the changes and the impact on users.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### Release note

```release-note

```

### CODE REVIEW

File: src/renderer/src/services/TranslateService.ts [hunk 1]
```diff
@@ -1,10 +1,80 @@
...
+    enableReasoning,
+    onResponse
+  }
+
+  const AI = new AiProvider(provider)
+
+  try {
+    return (await AI.completions(params)).getText() || ''
+  } catch (error: any) {
+    return ''
```
Comment (GeorgeDong32) [inline src/renderer/src/services/TranslateService.ts]: 这里要不把错误写到日志或者传到UI显示一下方便用户判断问题

Comment (EurFelux) [reply src/renderer/src/services/TranslateService.ts]: done
