### PR TITLE
fix: better mcp tool match and feedback

### LINKED ISSUE #8823: [错误]:
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我的问题不是 [常见问题](https://github.com/CherryHQ/cherry-studio/issues/3881) 中的内容。
- [x] 我已经查看了 **置顶 Issue** 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。
- [x] 我确认我正在使用最新版本的 Cherry Studio。

### 平台

macOS

### 版本

1.5.1

### 错误描述

首先是1.5.3 MCP调用有问题，所以版本回退到了1.5.1，对话中能正常调用到mcp了
在测试时发现调用MCP时，总是调用第一个工具。
LLM已经正常解析到了第二个工具的参数，但是总是把第二个工具的参数塞到第一个工具执行

### 重现步骤

Image
MCP里面有2个工具，
调用时，第二个工具的参数准备好了，但是调用了第一个工具

Image

### 预期行为

我重新修改了一下mcp中的工具的顺序，其他保持不变

Image

调用了第一个

Image

### 相关日志输出

```shell

```

### 附加信息

在MCP设置 -> 这个MCP -> 工具 这里，这2个工具名字旁边的tooltip 显示ID是一样的，这个是否有影响？

Image

### PR DESCRIPTION
**Pull request by EurFelux**
### What this PR does

- 处理了匹配到多个MCP工具的情况并提供警告
- 未匹配到MCP工具时反馈给用户

Fixes #8823

### Why we need it and why it was done in this way

The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Breaking changes

If this PR introduces breaking changes, please describe the changes and the impact on users.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### Release note

```release-note

```

### CODE REVIEW

File: src/renderer/src/utils/mcp-tools.ts [hunk 1]
```diff
@@ -358,11 +370,17 @@ export function mcpToolsToAnthropicTools(mcpTools: MCPTool[]): Array<ToolUnion>
 
 export function anthropicToolUseToMcpTool(mcpTools: MCPTool[] | undefined, toolUse: ToolUseBlock): MCPTool | undefined {
   if (!mcpTools) return undefined
-  const tool = mcpTools.find((tool) => tool.id === toolUse.name)
-  if (!tool) {
+  const tools = mcpTools.filter((tool) => tool.id === toolUse.name)
+  if (tools.length === 0) {
+    logger.warn('No MCP Tool found for tool call:', toolUse)
```
Comment (GeorgeDong32) [inline src/renderer/src/utils/mcp-tools.ts]: 直接打印ToolUse会不会太大了，可不可以打印ToolName，需要检查的时候再倒回去trace里找

Comment (EurFelux) [reply src/renderer/src/utils/mcp-tools.ts]: 对于用户可见的日志来说确实有点太大了
