### PR TITLE
fix(reset): close all DBs before restore/reset; clear entire Data/ on factory reset

### LINKED ISSUE #12837: [Bug]: Factory reset does not clear agents.db, memories.db, KnowledgeBase, and Notes
## Bug Description

The factory reset function (`Settings > Data > Reset Data`) does not fully clear the `Data/` directory. Several main-process-managed databases and file stores survive a reset, leaving behind user data that should be wiped.

### Current reset behavior (`BackupService.ts:reset()`)

```typescript
await localStorage.clear()       // ✅ Clears browser localStorage (Redux persisted state)
await clearDatabase()             // ✅ Clears IndexedDB/Dexie tables (topics, message_blocks, settings, etc.)
await window.api.file.clear()    // ⚠️ ONLY clears Data/Files/ via FileStorage.clear()
```

### Data NOT cleared after factory reset

| Data | Path | Storage Type |
|------|------|-------------|
| `agents.db` | `{userData}/Data/agents.db` | SQLite (main process, Drizzle ORM) |
| `memories.db` | `{userData}/Data/Memory/memories.db` | SQLite (main process, MemoryService) |
| KnowledgeBases | `{userData}/Data/KnowledgeBase/` | Vector stores / SQLite |
| Notes | `{userData}/Data/Notes/` | Files on disk |

### Root Cause

- `FileStorage.clear()` only removes `this.storageDir` (`Data/Files/`), not the entire `Data/` directory or other subdirectories.
- `agents.db` and `memories.db` are SQLite databases managed by main process services — there is no IPC channel to clear them from the renderer-side reset flow.
- `KnowledgeBase/` and `Notes/` directories are simply never referenced in the reset logic.

## Steps To Reproduce

1. Create some agents, add memories, create a knowledge base, and add notes
2. Go to Settings > Data > Reset Data
3. Confirm the reset (double confirmation)
4. After the app reloads, check `{userData}/Data/` directory
5. `agents.db`, `Memory/`, `KnowledgeBase/`, and `Notes/` still contain data

## Expected Behavior

A factory reset should clear **all** user data, including agents, memories, knowledge bases, and notes. Either:
1. Add IPC channels for each main-process service to clear its data, and call them during reset, or
2. Clear the entire `Data/` directory (minus `occupiedDirs` like `logs`) during reset

## Additional Context

Related to #12830 (moving `agents.db` into `Data/` directory) — that PR makes `agents.db` part of backup/restore, but doesn't address the incomplete reset. This issue pre-dates that PR.

### LINKED ISSUE #12838: [Bug]: Restoring backup causes cascading failures: auth mismatch (403) and stale DB connection (500)
## Bug Description

After restoring data from a backup (or resetting data), agent functionality breaks in **two distinct layers**, each requiring a different level of restart to resolve:

### Layer 1: Auth Mismatch → 403 (Silent Failure) — Pre-exists on main

After restore/reset, the renderer reloads and picks up the **new auth config**, but the ApiServer in the main process still holds the **old auth config** in memory. This causes **all API requests to return 403 Forbidden silently** — no error is shown to the user.

**This issue pre-exists on the main branch.** On main, since `agents.db` is outside `Data/` and not part of backup/restore, the agents list itself isn't affected by restore. However, the auth mismatch still causes silent 403 failures on all agent API calls. In practice:

- After a **data reset**: the agents list appears empty (expected behavior), so users may not immediately notice the 403 problem. But if they try to use agent features (e.g., add a new agent), they'll find it fails silently — for example, unable to fetch the available model list, which is confusing.
- Furthermore, if users solve the auth problem by restarting ApiServer, they will discover that **agents data was not actually reset** (see #12837 — `agents.db` is not cleared during factory reset). The stale agents in the database also depend on provider and model configurations that have been reset, making these leftover agents **non-functional** — compounding the user confusion.
- The silent nature of the failure (no error message, no feedback) makes it particularly hard for users to diagnose.

**Fix:** Restarting ApiServer resolves the auth mismatch. Read operations then work correctly.

### Layer 2: Stale DB Connection → 500 (Write Failures) — Introduced by #12830

Even after restarting ApiServer (which fixes auth), **write operations** (`createAgent`, `createSession`, etc.) still fail with **500 errors**. This is because `DatabaseManager` is a static singleton that caches the SQLite connection from before the restore. The underlying `agents.db` file was deleted and replaced during restore, but the in-memory `libsql` client still points to the old (now invalid) file handle.

**This issue is introduced by #12830**, which moved `agents.db` into `Data/`. Before #12830, `agents.db` was outside `Data/` and not touched during restore, so this layer did not exist.

**Fix:** Only a full application restart resolves this, as it creates a fresh Node.js process with new singletons.

### Layer 1: Auth Config Not Reloaded (pre-existing)

```
Restore/Reset flow:
1. BackupManager.restore() overwrites {userData}/Data/ (or reset clears data)
2. Renderer reloads → picks up new auth credentials from restored/reset config
3. ApiServer still running with OLD auth config in memory
4. Renderer sends requests with NEW auth → ApiServer validates against OLD auth → 403
5. No error feedback shown to user → silent failure
```

Additional issue on main: after reset + ApiServer restart, users discover agents data was NOT reset (agents.db is outside the reset scope, see #12837). These leftover agents reference provider/model configs that have been reset, making them non-functional.

### Layer 2: DatabaseManager Singleton Never Resets (introduced by #12830)

`DatabaseManager` (`DatabaseManager.ts:52-71`) caches the instance statically:
```typescript
private static instance: DatabaseManager | null = null

public static async getInstance(): Promise<DatabaseManager> {
  if (DatabaseManager.instance) {
    return DatabaseManager.instance  // ← stale connection returned forever
  }
}
```

After #12830 moved `agents.db` into `Data/`, the restore flow now deletes and replaces this file. But `ApiServer.restart()` only restarts Express and reloads API config — it does NOT reinitialize `DatabaseManager`, `agentService`, or `sessionService` (all module-level singletons).

## Steps To Reproduce

1. Create some agents, configure API keys, create a backup
2. Restore from the backup (or perform a data reset)
3. **Observe Layer 1:** Agent-related API calls silently fail with 403. If trying to add a new agent, the available model list cannot be fetched. No error message is shown.
4. Restart ApiServer only
5. **(On main)** Discover that agents data was not reset — old agents still exist but are non-functional because their provider/model dependencies have been reset
6. **Observe Layer 2 (only after #12830):** Read operations now work. Try creating a new agent → 500 error.
7. Restart the full application → everything works

## Expected Behavior

After restoring a backup or resetting data, all services should be fully re-synchronized. Both auth config and database connections should reflect the new state without requiring manual restarts. At minimum, if services are out of sync, the user should receive a clear error message or a prompt to restart.

## Resolution Path

This should be resolvable by **improving application lifecycle management**:

- **Layer 1 (auth):** Ensure ApiServer reloads its auth config after restore/reset, or trigger a full ApiServer restart as part of the restore/reset flow
- **Layer 2 (DB connection):** Add a `DatabaseManager.reset()` method to close the connection and clear the singleton, then call it during restore. Alternatively, use `app.relaunch()` + `app.exit()` instead of `window.api.reload()` to force a full process restart.

## Priority & Status

**Severity: Low** — Both layers can be fully resolved by restarting the application. PR #12830 has been merged first to address the more critical data loss risk (agents.db not included in backup/restore). This lifecycle issue is deferred for later resolution.

## Related

- #12830 — PR that moved agents.db into Data/ (merged, introduces Layer 2)
- #12837 — Incomplete data reset during factory reset (agents.db, memories.db, etc. not cleared)

### LINKED ISSUE #12891: [Bug]: Error when restoring backup
> [!NOTE]
> This issue was translated by Claude.

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

1.7.18

### Bug Description

(Basic data settings - data directory - data settings - data backup and restore)
When restoring a backup from Windows computer A on Windows computer B, a data format error is reported. The js console error is as follows:
```
jsx-runtime-BYowWDHx.js:432 <error> [BackupService] restore: Error restoring backup file: Error: Error invoking remote method 'backup:restore': Error: EBUSY: resource busy or locked, unlink 'C:\Users\xxx\AppData\Roaming\CherryStudio\Data\agents.db'
```

### Steps To Reproduce

Restore a backup from Windows computer A on Windows computer B, prompts for data format error

### Expected Behavior

Successfully restore backup

### Relevant Log Output

```shell

```

### Additional Context

_No response_

---
<details>
<summary>Original Content</summary>

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

1.7.18

### Bug Description

（基础数据设置-数据目录-数据设置-数据备份与恢复）
从A windows电脑备份，在B windows电脑恢复备份，提示数据格式错误，js console报错如下：
```
jsx-runtime-BYowWDHx.js:432 <error> [BackupService] restore: Error restoring backup file: Error: Error invoking remote method 'backup:restore': Error: EBUSY: resource busy or locked, unlink 'C:\Users\xxx\AppData\Roaming\CherryStudio\Data\agents.db'
```

### Steps To Reproduce

从A windows电脑备份，在B windows电脑恢复备份，提示数据格式错误

### Expected Behavior

成功恢复备份

### Relevant Log Output

```shell

```

### Additional Context

_No response_

</details>

### PR DESCRIPTION
**Pull request by EurFelux**
### What this PR does

Before this PR:
- On Windows, restoring a backup fails with `EBUSY: resource busy or locked, unlink '...\Data\agents.db'` because the DatabaseManager holds an open libsql connection.
- After restore/reset, ApiServer keeps stale auth config in memory, causing silent 403 errors. DatabaseManager also holds a stale connection, causing 500 errors on write operations.
- **Factory reset (`Settings > Data > Reset Data`) only clears localStorage, IndexedDB, and `Data/Files/`, leaving `agents.db`, `memories.db`, `KnowledgeBase/`, and `Notes/` intact.**

After this PR:
- `DatabaseManager.close()` releases the file handle before deleting the Data directory, allowing restore to succeed on Windows.
- `window.api.relaunchApp()` replaces `window.api.reload()` after restore/reset, restarting the entire Electron process so all singletons (ApiServer, DatabaseManager, etc.) re-initialize with fresh config.
- **Factory reset now closes all DB connections (agents, memory, knowledge) and removes the entire `Data/` directory, ensuring a complete data wipe. On relaunch, all services auto-recreate empty databases.**
- **Backup restore also closes MemoryService and KnowledgeService connections (in addition to DatabaseManager), preventing EBUSY on Windows for `memories.db` and KnowledgeBase files.**

Fixes #12891, Fixes #12838, Fixes #12837

### Why we need it and why it was done in this way

The following tradeoffs were made:
- Using full app relaunch instead of renderer-only reload is slightly more disruptive to the user (brief window close/reopen), but it's the only reliable way to ensure all main process singletons refresh. A renderer-only reload cannot trigger `ApiServer.restart()` at the right time because `reduxService.select()` reads from in-memory Redux state which hasn't rehydrated yet.
- For factory reset, we delete the entire `Data/` directory instead of individual files. This is simpler and more thorough — any future data files added to `Data/` will automatically be covered.
- `KnowledgeService.closeAll()` accesses `LibSqlDb`'s private `client` field via `(db as any).client.close()` to release file handles. This breaks encapsulation but is necessary because `LibSqlDb` doesn't expose a `close()` method, and on Windows open handles prevent file deletion.

The following alternatives were considered:
- Calling `apiServer.restart()` from the renderer before reload — doesn't work because Redux in-memory state still has old config at that point.
- Listening for `ReduxStoreReady` after reload to trigger ApiServer restart — more complex, fragile, and only partially fixes the problem (other singletons would still be stale).
- Deleting individual DB files in factory reset — fragile and requires maintenance whenever new data files are added.

### Breaking changes

None. The user experience changes from a page refresh to a full app restart after restore/reset, which is a minor UX difference. Factory reset now actually clears all data as users expect.

### Special notes for your reviewer

- `DatabaseManager.close()` is a new public static method that closes the connection and resets the singleton. The next `getInstance()` call lazily re-initializes.
- `KnowledgeService.closeAll()` is a new method that closes all open knowledge base DB connections and clears cached RAG application instances.
- The `relaunchApp()` change affects 3 code paths in `BackupService.ts`: v1 restore, v2+ restore, and data reset.
- New `App_ResetData` IPC channel orchestrates the complete factory reset sequence from the main process.
- Backup/restore already copies/restores the entire `Data/` directory, so `agents.db`, `memories.db`, `KnowledgeBase/`, and `Notes/` are all properly backed up and restored.

### Checklist

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: Write code that humans can understand and Keep it simple
- [x] Refactor: You have left the code cleaner than you found it (Boy Scout Rule)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: Not required — internal behavior change, no user-facing documentation needed

### Release note

```release-note
Fixed factory reset not clearing agents.db, memories.db, KnowledgeBase, and Notes data. Fixed backup restore failure on Windows (EBUSY error) for memory and knowledge base files. Fixed auth/DB connection staleness after restore/reset.
```

### CODE REVIEW

**Comment by EurFelux** [comment]
> [!NOTE]
> This issue/comment/review was translated by Claude.

> **Note to reviewers:**
>
> **Verified on macOS:**
> - ✅ After restore, ApiServer auth works correctly (no silent 403)
> - ✅ After restore, agent CRUD operations work (no 500 from stale DB connection)
>
> **Needs Windows testing:**
> - ⬜ Backup restore completes without EBUSY error (`DatabaseManager.close()` releases the file handle before `fs.remove()`)
> - ⬜ After data reset, app relaunches and all services function normally

---
<details>
<summary>Original Content</summary>

> **Note to reviewers:**
>
> **Verified on macOS:**
> - ✅ After restore, ApiServer auth works correctly (no silent 403)
> - ✅ After restore, agent CRUD operations work (no 500 from stale DB connection)
>
> **Needs Windows testing:**
> - ⬜ Backup restore completes without EBUSY error (`DatabaseManager.close()` releases the file handle before `fs.remove()`)
> - ⬜ After data reset, app relaunches and all services function normally

</details>

File: src/main/ipc.ts [hunk 1]
```diff
@@ -487,6 +487,14 @@ export async function registerIpc(mainWindow: BrowserWindow, app: Electron.App)
     app.exit(0)
   })
 
+  // Reset all data (factory reset)
+  ipcMain.handle(IpcChannel.App_ResetData, async () => {
+    await DatabaseManager.close()
+    await memoryService.close()
+    await KnowledgeService.closeAll()
+    await fs.promises.rm(getDataPath(), { recursive: true, force: true })
+  })
```
Comment (EurFelux) [inline src/main/ipc.ts:500]: **Error handling concern**: If any of the `close()` calls throw (e.g., `memoryService.close()` fails), the subsequent calls and the `fs.promises.rm()` won't execute.

Consider wrapping each close call individually so that a failure in one doesn't prevent the others from running:

```ts
ipcMain.handle(IpcChannel.App_ResetData, async () => {
  await DatabaseManager.close()
  await memoryService.close().catch((e) => logger.warn('Failed to close memoryService', e))
  await KnowledgeService.closeAll().catch((e) => logger.warn('Failed to close KnowledgeService', e))
  await fs.promises.rm(getDataPath(), { recursive: true, force: true })
})
```

Alternatively, use `Promise.allSettled` for the three close operations.

`DatabaseManager.close()` and `KnowledgeService.closeAll()` already have internal try/catch around `client.close()`, but `memoryService.close()` calls `this.db.close()` without a try/catch guard — if that throws, the reset will silently fail to delete the Data directory.

File: src/main/services/KnowledgeService.ts [hunk 2]
```diff
@@ -682,6 +682,30 @@ class KnowledgeService {
...
+   * Used during factory reset and backup restore to release file handles.
+   */
+  public closeAll = async (): Promise<void> => {
+    for (const [id, db] of this.dbInstances) {
+      try {
+        // LibSqlDb's client is private, but we need to close the underlying connection
+        // to release file handles (critical on Windows to avoid EBUSY)
+        const client = (db as any).client
+        if (client && typeof client.close === 'function') {
+          client.close()
```
Comment (EurFelux) [inline src/main/services/KnowledgeService.ts:698]: **Encapsulation concern (as noted in PR description)**: Accessing `(db as any).client` breaks LibSqlDb's encapsulation. This is fragile — if the upstream library renames or restructures that field, this will silently fail (the `if` check will just skip closing).

A couple of suggestions:

1. **Short-term**: Add an inline comment referencing a tracking issue to add a proper `close()` method to LibSqlDb so this cast can be removed later.
2. **Defensive check**: Consider logging at `warn` level (not just `debug`) when `client` is falsy, since that would indicate the internal structure changed and connections are leaking:

```ts
if (!client || typeof client.close !== 'function') {
  logger.warn(`Cannot close database instance for id: ${id} — client not accessible`)
  continue
}
```

File: src/main/services/agents/database/DatabaseManager.ts [hunk 3]
```diff
@@ -208,4 +208,30 @@ export class DatabaseManager {
...
+      } catch (error) {
+        logger.warn('Failed to close database connection:', error as Error)
+      }
+    }
+
+    instance.client = null
+    instance.db = null
+    instance.state = InitState.INITIALIZING
+    DatabaseManager.instance = null
+  }
```
Comment (EurFelux) [inline src/main/services/agents/database/DatabaseManager.ts:235]: **Race condition risk**: There's a potential race between `close()` and a concurrent `getInstance()` call. Consider this sequence:

1. `close()` starts, sets `instance.client = null`
2. Concurrent code calls `getInstance()` — sees `DatabaseManager.instance` is still set (not null yet)
3. Returns stale instance with null client
4. `close()` finishes, sets `DatabaseManager.instance = null`

The window is small, but during backup restore this could cause a crash if any IPC handler fires between steps 1-4.

A simple mitigation would be to null out `DatabaseManager.instance` **first** (before clearing `client`/`db`), so that any concurrent `getInstance()` will create a fresh instance:

```ts
public static async close(): Promise<void> {
  const instance = DatabaseManager.instance
  if (!instance) return

  // Detach singleton first so concurrent getInstance() creates a new one
  DatabaseManager.instance = null

  if (instance.client) {
    try {
      instance.client.close()
      logger.info('Database connection closed')
    } catch (error) {
      logger.warn('Failed to close database connection:', error as Error)
    }
  }
}
```

This also simplifies the method since you no longer need to manually null `client`/`db`/`state` — the old instance is garbage collected.

File: src/main/services/BackupManager.ts [hunk 4]
```diff
@@ -409,6 +412,12 @@ class BackupManager {
         const totalSize = await this.getDirSize(sourcePath)
         let copiedSize = 0
 
+        // Close all database connections before removing Data directory.
+        // On Windows, open file handles prevent deletion (EBUSY).
+        await DatabaseManager.close()
+        await MemoryService.getInstance().close()
+        await KnowledgeService.closeAll()
```
Comment (EurFelux) [inline src/main/services/BackupManager.ts]: **Inconsistency with ipc.ts**: The close sequence here uses `MemoryService.getInstance().close()`, while the equivalent code in `ipc.ts:493` uses the module-level `memoryService.close()` (which is the same singleton obtained at module load time).

Both should work, but the inconsistency is worth noting. If `MemoryService.getInstance()` were ever to create a *new* instance (e.g., if someone adds a `close()` that nulls the singleton), calling `getInstance().close()` would initialize a fresh instance just to close it.

Consider importing and using the same `memoryService` instance for consistency, or ensure `MemoryService.close()` is static (like `DatabaseManager.close()`) to make the pattern uniform across all three services.

File: src/renderer/src/services/BackupService.ts [hunk 5]
```diff
@@ -123,8 +123,8 @@ export async function reset() {
         onOk: async () => {
           await localStorage.clear()
           await clearDatabase()
-          await window.api.file.clear()
-          window.api.reload()
+          await window.api.resetData()
+          window.api.relaunchApp()
```
Comment (EurFelux) [inline src/renderer/src/services/BackupService.ts]: **Error handling gap**: If `resetData()` throws (e.g., `fs.promises.rm` fails on a locked file), `relaunchApp()` will still be called on the next line because it's not inside the `await` chain's error handling.

However, more importantly — if `resetData()` succeeds but `relaunchApp()` fails or is slow, the user is left with a cleared data directory but no relaunch. Consider making this more robust:

```ts
await window.api.resetData()
await window.api.relaunchApp()
```

Also: is there intentional that `relaunchApp()` is not `await`-ed here? In contrast, the `handleData` paths (lines 848, 876) use `setTimeout(() => window.api.relaunchApp(), 1000)` to give the toast time to display. This path (factory reset) relaunches immediately — the user won't see any success feedback before the app restarts. Consider adding a brief delay or toast here too for consistency.

**Comment by GeorgeDong32** [comment]
> [!NOTE]
> This issue/comment/review was translated by Claude.

## PR #12892 Code Review Report

### Summary of Changes

This PR introduces **LAN file transfer functionality**, primarily adding two new methods for creating and cleaning up temporary backup files for LAN transfer:

1. `createLanTransferBackup` - Creates lightweight temporary backup (skips Data directory)
2. `deleteTempBackup` - Safely deletes temporary backup files

---

### Detailed Review Results

#### Strengths

1. **Well-designed security**
   - `deleteTempBackup` implements path traversal protection by using `path.normalize` and path prefix checking to ensure only files within the temp directory can be deleted
   - Uses `path.sep` to handle path separators across different operating systems

2. **Comprehensive code documentation**
   - Both new methods include detailed JSDoc comments explaining purpose, parameters, and return values

3. **Proper error handling**
   - Both new methods implement try-catch error handling and logging
   - Uses logger to record logs at different levels (info, warn, error)

4. **Architectural consistency**
   - Follows existing IPC communication patterns
   - Integrates well with existing backup system

---

#### Issues Requiring Attention

##### 1. Potential Issue with Path Security Check (Recommended Fix)

**Location**: `src/main/services/BackupManager.ts:818-820`

```typescript
// Current code
if (!resolvedPath.startsWith(tempBase + path.sep) && resolvedPath !== tempBase) {
```

**Problem**:
- `tempBase` may not end with a path separator, causing inaccurate `startsWith` checks
- For example: `/temp/cherry-studio/lan-transfer` + `/file.txt` might fail to match

**Suggested fix**:
```typescript
// Ensure tempBase ends with path separator
const normalizedTempBase = tempBase.endsWith(path.sep) ? tempBase : tempBase + path.sep

if (!resolvedPath.startsWith(normalizedTempBase) && resolvedPath !== tempBase) {
  logger.warn(`[BackupManager] Attempted to delete file outside temp directory: ${filePath}`)
  return false
}
```

---

##### 2. File Permission Issues (Low Risk)

**Location**: `src/main/services/BackupManager.ts:825-829`

```typescript
if (await fs.pathExists(resolvedPath)) {
  await fs.remove(resolvedPath)
```

**Problem**:
- If a file is locked by another process (e.g., during transfer), deletion will fail
- No special handling for read-only files

**Suggestions**:
- Consider adding a retry mechanism
- Or use `forceSetWritable`-like logic on Windows

---

##### 3. Temporary Directory May Not Be Cleaned Up (Medium Risk)

**Location**: `createLanTransferBackup` and `deleteTempBackup`

**Problem**:
- If LAN transfer is interrupted or fails, temporary files may not be cleaned up
- No mechanism to periodically clean up expired temporary files

**Suggestions**:
- Consider cleaning up expired temporary files on app startup (e.g., files older than 24 hours)
- Or clean up old temporary files in the same directory when calling `createLanTransferBackup`

---

##### 4. Missing Unit Tests (Recommended)

**Problem**:
- Neither new method has corresponding unit tests
- Particularly, the path security check in `deleteTempBackup` needs test coverage

**Recommended test cases**:
1. Normal deletion of files within temp directory
2. Attempting to delete files outside temp directory (should be rejected)
3. Attempting path traversal attacks (e.g., `../../../etc/passwd`)
4. Deleting non-existent files
5. Deleting locked files

---

### Overall Assessment

| Dimension | Score | Notes |
|-----------|-------|-------|
| Code Quality | 4/5 | Good overall, with clear comments and error handling |
| Security | 4/5 | Path security checks mostly in place, but has minor issues |
| Architectural Consistency | 5/5 | Consistent with existing code style |
| Test Coverage | 2/5 | Missing unit tests |

### Recommended Actions

1. **Must fix**: Potential issue with path security check (suggestion 1)
2. **Recommended fix**: Add mechanism to periodically clean up expired temporary files (suggestion 3)
3. **Future improvement**: Add unit tests (suggestion 4)

### Conclusion

This is a **good quality** PR that implements clear functionality with basic security considerations. Recommended to merge after fixing the minor path security check issue.

---

*Reviewer: Claude Code*
*Date: 2026-02-12*

---
<details>
<summary>Original Content</summary>

## PR #12892 代码审查报告

### 变更概要

这个PR引入了**LAN文件传输功能**，主要添加了两个新方法用于创建和清理局域网传输用的临时备份文件：

1. `createLanTransferBackup` - 创建轻量级临时备份（跳过Data目录）
2. `deleteTempBackup` - 安全删除临时备份文件

---

### 详细审查结果

#### 优点

1. **安全性设计良好**
   - `deleteTempBackup` 实现了路径遍历防护，通过 `path.normalize` 和路径前缀检查确保只能删除临时目录内的文件
   - 使用 `path.sep` 处理不同操作系统的路径分隔符

2. **代码文档完善**
   - 新增方法都包含详细的 JSDoc 注释，说明用途、参数和返回值

3. **错误处理到位**
   - 两个新方法都实现了 try-catch 错误处理和日志记录
   - 使用 logger 记录不同级别（info, warn, error）的日志

4. **架构一致性**
   - 遵循现有的 IPC 通信模式
   - 与现有备份系统良好集成

---

#### 需要关注的问题

##### 1. 路径安全检查的潜在问题 (建议修复)

**位置**: `src/main/services/BackupManager.ts:818-820`

```typescript
// 当前代码
if (!resolvedPath.startsWith(tempBase + path.sep) && resolvedPath !== tempBase) {
```

**问题**:
- `tempBase` 末尾可能没有路径分隔符，导致 `startsWith` 检查不准确
- 例如: `/temp/cherry-studio/lan-transfer` + `/file.txt` 可能匹配失败

**建议修复**:
```typescript
// 确保 tempBase 以路径分隔符结尾
const normalizedTempBase = tempBase.endsWith(path.sep) ? tempBase : tempBase + path.sep

if (!resolvedPath.startsWith(normalizedTempBase) && resolvedPath !== tempBase) {
  logger.warn(`[BackupManager] Attempted to delete file outside temp directory: ${filePath}`)
  return false
}
```

---

##### 2. 文件权限问题 (低风险)

**位置**: `src/main/services/BackupManager.ts:825-829`

```typescript
if (await fs.pathExists(resolvedPath)) {
  await fs.remove(resolvedPath)
```

**问题**:
- 如果文件被其他进程锁定（如正在传输中），删除会失败
- 没有处理只读文件的特殊逻辑

**建议**:
- 考虑添加重试机制
- 或者在 Windows 上使用 `forceSetWritable` 类似的逻辑

---

##### 3. 临时目录可能未清理 (中风险)

**位置**: `createLanTransferBackup` 和 `deleteTempBackup`

**问题**:
- 如果 LAN 传输过程中断或失败，临时文件可能不会被清理
- 没有定期清理过期临时文件的机制

**建议**:
- 考虑在应用启动时清理过期的临时文件（如超过24小时的文件）
- 或者在 `createLanTransferBackup` 时清理同目录下的旧临时文件

---

##### 4. 缺少单元测试 (建议)

**问题**:
- 两个新方法都没有对应的单元测试
- 特别是 `deleteTempBackup` 的路径安全检查需要测试覆盖

**建议测试用例**:
1. 正常删除临时目录内的文件
2. 尝试删除临时目录外的文件（应被拒绝）
3. 尝试使用路径遍历攻击（如 `../../../etc/passwd`）
4. 删除不存在的文件
5. 删除被锁定的文件

---

### 总体评估

| 维度 | 评分 | 说明 |
|------|------|------|
| 代码质量 | 4/5 | 整体良好，有清晰的注释和错误处理 |
| 安全性 | 4/5 | 路径安全检查基本到位，但有小问题 |
| 架构一致性 | 5/5 | 与现有代码风格一致 |
| 测试覆盖 | 2/5 | 缺少单元测试 |

### 建议操作

1. **必须修复**: 路径安全检查的潜在问题（建议1）
2. **建议修复**: 添加定期清理过期临时文件的机制（建议3）
3. **后续改进**: 添加单元测试（建议4）

### 结论

这是一个**质量良好**的PR，实现了清晰的功能，有基本的安全考虑。建议修复路径安全检查的小问题后即可合并。

---

*审查者: Claude Code*
*日期: 2026-02-12*

</details>

**Comment by EurFelux** [comment]
> [!NOTE]
> This issue/comment/review was translated by Claude.

> ## PR #12892 Code Review Report
> ### Summary of Changes
> This PR introduces **LAN file transfer functionality**, primarily adding two new methods for creating and cleaning up temporary backup files for LAN transfer:
>
> If this is a model hallucination, it's too serious.

---
<details>
<summary>Original Content</summary>

> ## PR #12892 Code Review Report\r\n> ### Summary of Changes\r\n> This PR introduces **LAN file transfer functionality**, primarily adding two new methods for creating and cleaning up temporary backup files for LAN transfer:\r\n\r\n这个如果是模型幻觉的话也太严重了

</details>

File: src/main/ipc.ts (hunk 1 above)
Comment (EurFelux) [reply src/main/ipc.ts:500]: Fixed in 107ac6e. Added `.catch()` guards on `memoryService.close()` and `KnowledgeService.closeAll()` so a failure in one won't block subsequent close calls or `fs.promises.rm()`. `DatabaseManager.close()` already has internal try/catch so it doesn't need an outer guard.

File: src/main/services/KnowledgeService.ts (hunk 2 above)
Comment (EurFelux) [reply src/main/services/KnowledgeService.ts:698]: Fixed in 107ac6e. Now logs at `warn` level when `client` is not accessible (with `continue` to skip the instance), so we'll catch upstream changes early. Also added a TODO comment referencing that LibSqlDb should expose `close()` natively.

File: src/main/services/agents/database/DatabaseManager.ts (hunk 3 above)
Comment (EurFelux) [reply src/main/services/agents/database/DatabaseManager.ts:235]: Good catch. Fixed in 107ac6e. Now nulls `DatabaseManager.instance` **first** before closing the client, so any concurrent `getInstance()` call will create a fresh connection instead of getting a stale instance with null client. The old instance is held by a local variable for safe cleanup and then GC'd.

**Comment by GeorgeDong32** [comment]
> [!NOTE]
> This issue/comment/review was translated by Claude.

> That's too serious if it's a model hallucination. That was indeed written by me 😅. I accidentally selected auto-allow when uploading the review.

---
<details>
<summary>Original Content</summary>

> 这个如果是模型幻觉的话也太严重了\r\n\r\n这就是火山 😅，Review上传不小心选成自动允许了

</details>

File: src/main/services/BackupManager.ts (hunk 4 above)
Comment (EurFelux) [reply src/main/services/BackupManager.ts]: Addressed in 107ac6e. The `MemoryService.getInstance().close()` pattern here is intentional — `BackupManager` is an independent class that doesn't hold a module-level reference to `memoryService`, so `getInstance()` is the correct way to access the singleton. In `ipc.ts`, the module-level `memoryService` constant is already the same singleton obtained at import time, so both access the same instance.

Added `.catch()` guards on both `MemoryService` and `KnowledgeService` close calls here as well, consistent with `ipc.ts`.

File: src/renderer/src/services/BackupService.ts (hunk 5 above)
Comment (EurFelux) [reply src/renderer/src/services/BackupService.ts]: Fixed in 107ac6e. Added `window.toast.success(i18n.t('message.reset.success'))` and `setTimeout(() => window.api.relaunchApp(), 1000)` to match the restore paths' UX pattern. Added `message.reset.success` i18n key across all locales.

Regarding the error handling gap: if `resetData()` throws, the promise rejection will propagate and `relaunchApp()` won't be called (they're sequential `await` + `setTimeout`). The user stays on the confirmation dialog with an unhandled promise — but this matches the existing restore behavior. Adding a try/catch with error toast would be a separate improvement.

**Comment by EurFelux** [comment]
## Follow-up: Address DeJeune's review + deduplicate close logic

### Commits: 810cf85 → b92bbe0

#### 1. Stop FileStorage watcher before fs.remove() (810cf85)
Addresses DeJeune's review point about chokidar. FileStorage uses chokidar to watch Data/Files/ and Data/Notes/. On Windows, ReadDirectoryChangesW holds directory handles that cause EBUSY. Now stopFileWatcher() is called before deleting the Data directory in both App_ResetData and BackupManager.restore().

#### 2. KnowledgeService.closeAll() throws on unclosable handles (810cf85)
Addresses DeJeune's review point about silent skipping. Instead of silently skipping when client is not accessible, closeAll() now collects failed IDs and throws Error. Callers already have .catch() guards so they log and proceed.

#### 3. Extract closeAllDataConnections() to src/main/utils/lifecycle.ts (df0572d)
The 4-step close sequence (DatabaseManager → MemoryService → KnowledgeService → FileWatcher) was duplicated in ipc.ts and BackupManager.ts. Extracted to a shared function using Promise.allSettled — all closes run in parallel, failures in one don't block others.

#### 4. Best-effort fs.rm() in factory reset (b92bbe0)
If fs.rm() fails (e.g., a handle wasn't released on Windows), the error is logged but not thrown. This ensures relaunchApp() always executes — process exit releases all remaining handles, and services auto-recreate on next start.

**Review by kangfenmao — APPROVED** [review]
