### PR TITLE
fix: limit builtin web search usage

### LINKED ISSUE #14465: [Bug]: Built-in web search can repeat excessively and consume huge tokens
## Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the FAQ.
- [x] I've looked at pinned issues and searched for existing open issues, closed issues, and discussions, no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

## Platform

macOS

## Version

v1.9.2

## Bug Description

When an assistant has built-in web search enabled, the `buildin_web_search` tool can be invoked repeatedly during a single assistant response. In the reported case, one response produced many separate search result/citation groups and consumed more than 120k tokens.

Observed symptoms:

- Multiple search result groups are shown in one response, such as 17, 20, 5, 6, 6, 3, and 20 search results.
- Multiple citation blocks are created for the same assistant response.
- Token usage can become extremely high, for example `Tokens: 122737`.

This makes web search unexpectedly expensive and can slow down or disrupt the conversation.

## Steps To Reproduce

1. Configure an assistant with a web search provider enabled.
2. Ask a question that triggers built-in web search.
3. Let the assistant stream the response.
4. Observe that `buildin_web_search` may be called repeatedly in the same response, producing many search/citation groups and very high token usage.

## Expected Behavior

Built-in web search should have a bounded per-response budget. A single assistant response should not repeatedly call `buildin_web_search` and append multiple large search result payloads unless explicitly allowed.

Expected behavior for the default path:

- Execute built-in web search at most once per assistant response.
- Reuse the first search result if the model attempts to call the tool again.
- Limit and deduplicate prepared search queries.
- Keep URLs compact in search results to reduce token overhead.

## Relevant Log Output

```shell
N/A
```

## Additional Context

The screenshots supplied with the report show repeated search result groups and a token counter above 122k tokens.

### PR DESCRIPTION
**Pull request by kangfenmao**
### What this PR does

Before this PR:

Built-in web search could be called repeatedly during a single assistant response, producing multiple large search/citation payloads and very high token usage.

After this PR:

Built-in web search is bounded for a single response: prepared queries are deduplicated and capped, repeated tool executions reuse cached results, later tool-loop steps cannot call the built-in web search tool again, and returned source URLs are shortened to their origin.

Fixes #14465

### Why we need it and why it was done in this way

The repeated built-in web search calls can cause excessive token consumption and slow or expensive responses. The fix keeps the hotfix scope narrow by changing only the built-in web search path and the orchestration hook that exposes it to AI SDK tool loops.

The following tradeoffs were made:

The default behavior now favors bounded search cost over repeated autonomous searches in one assistant response. If one search pass is insufficient, the assistant should answer with the available sources or ask the user for a follow-up.

The following alternatives were considered:

- Lowering the global max tool-call setting: rejected because it would affect all tools, not just built-in web search.
- Allowing multiple web searches with a larger budget: rejected for now because the reported issue is runaway token usage.

Links to places where the discussion took place: #14465

### Breaking changes

None.

### Special notes for your reviewer

This PR targets `main` as a minimal `hotfix/*` branch because the current behavior can consume a very large number of tokens in a single response.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. Check this only when the PR introduces or changes a user-facing feature or behavior.
- [x] Self-review: I have reviewed my own code (e.g., via [`/gh-pr-review`](/.claude/skills/gh-pr-review/SKILL.md), `gh pr diff`, or GitHub UI) before requesting review from others

### Release note

```release-note
Fixed built-in web search repeatedly running within a single assistant response and consuming excessive tokens.
```

### CODE REVIEW

File: src/renderer/src/aiCore/tools/WebSearchTool.ts [hunk 1]
```diff
@@ -66,7 +93,8 @@ You can use this tool as-is to search with the prepared queries, or provide addi
           links: extractedKeywords.links
         }
       }
-      searchResults = await WebSearchService.processWebsearch(webSearchProvider!, extractResults, requestId)
+      const searchResults = await WebSearchService.processWebsearch(webSearchProvider!, extractResults, requestId)
```
Comment (kangfenmao) [inline src/renderer/src/aiCore/tools/WebSearchTool.ts]: > [\!NOTE]
> This comment was translated by Claude.

The cache here is only assigned after `processWebsearch` resolves, which cannot block multiple `buildin_web_search` calls arriving concurrently within the same AI SDK step. After receiving a tool-call chunk, the AI SDK doesn't wait for the current tool execution to complete before processing the next tool-call. Instead, it launches `executeToolCall(...).then(...)` and continues processing the stream. Therefore, if the model emits two web search tool calls in one step, both `execute` calls will see `cachedSearchResults === undefined` and each call `processWebsearch`.

This means this hotfix may still result in multiple search requests and large payloads in a single response. I recommend caching an in-flight promise, such as using `let cachedSearchResultsPromise: Promise<WebSearchProviderResponse> | undefined`, assigning it before initiating the search, and having subsequent concurrent calls directly await the same promise. Additionally, please add a test that executes `searchTool.execute(...)` twice concurrently to verify `processWebsearch` is only called once.

---
<details>
<summary>Original Content</summary>

这里的缓存只有在 `processWebsearch` resolve 之后才会赋值，挡不住同一个 AI SDK step 内并行到达的多次 `buildin_web_search` 调用。AI SDK 在收到 tool-call chunk 后不会等待当前 tool 执行完成才处理下一个 tool-call，而是启动 `executeToolCall(...).then(...)` 并继续处理流；因此如果模型在同一步里一次性发出两个 web search tool calls，两次 `execute` 都会看到 `cachedSearchResults === undefined`，并各自调用 `processWebsearch`。

这会让本 hotfix 仍然可能在单次响应里打出多次搜索请求和大 payload。建议缓存 in-flight promise，例如用 `let cachedSearchResultsPromise: Promise<WebSearchProviderResponse> | undefined`，在发起搜索前先赋值，后续并发调用直接 await 同一个 promise；同时补一个并发执行两次 `searchTool.execute(...)` 的测试，验证 `processWebsearch` 只调用一次。

</details>

**Review by kangfenmao — COMMENTED** [review]
> [\!NOTE]
> This review was translated by Claude.

Found a blocking issue: the current cache is only populated after the search completes, which cannot prevent duplicate built-in web searches caused by parallel tool calls within the same AI SDK step. Please change to caching in-flight promises and add concurrent execute tests.

---
<details>
<summary>Original Content</summary>

发现一个阻塞问题：当前缓存只在搜索完成后赋值，不能阻止同一个 AI SDK step 内并行 tool calls 导致的重复 built-in web search。请改为缓存 in-flight promise，并补充并发 execute 测试。

</details>

**Comment by RuanJintao** [comment]
> This comment was translated automatically.

Could this modification be reconsidered? With this change, each round of conversation's search only uses the content from the first search. If the first search doesn't find suitable content, then this round of conversation won't find anything, wasting the large model API calls in vain. Of course, sometimes frequent search calls are indeed redundant and wasteful, even resulting in situations with 120,000 tokens in a single conversation. I hope a toggle switch can be provided for users to choose whether to limit or relax the call restrictions.

---
<details>
<summary>Original Content</summary>

这次修改是否可以再次考虑呢？这么一修改，搞得每轮对话的搜索只调用了第一次搜索的内容了。如果第一次没有搜到合适的内容，那么本轮对话就搜不到东西了，反倒白白浪费调用大模型的次数。当然，有时频繁调用搜索的确繁冗并且浪费，甚至干出一轮对话十二万token的情况。这希望可以提供一个切换的开关，供使用者自行选择是限制调用还是放松限制。
</details>
