### PR TITLE
fix: The edit button cannot be used after using MCP. 修复对话中使用 MCP 后编辑按钮消失的问题

### LINKED ISSUE #6594: [错误]: 调用MCP的对话无法编辑，按钮消失
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我的问题不是 [常见问题](https://github.com/CherryHQ/cherry-studio/issues/3881) 中的内容。
- [x] 我已经查看了 **置顶 Issue** 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。

### 平台

Windows

### 版本

1.3.12

### 错误描述

调用MCP后，回复的编辑按钮消失

### 重现步骤

Image

### 预期行为

1.3.10版本可以正常编辑，1.3.12无法编辑调用了MCP的回复，导致回复中的格式等错误无法修改或调整

### 相关日志输出

```shell

```

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by NageNalock**
### What this PR does

Before this PR:

https://github.com/CherryHQ/cherry-studio/issues/6594

After this PR:

使用 MCP 后编辑按钮可以出现了
image

Fixes #6594

### Why we need it and why it was done in this way

使用 MCP Server 后会有大于一段 MatinTextBlock, 导致 isEditable 逻辑被判断为了 false.

另外测试时发现多段 MainTextBlock 时编辑窗口的交互不太好, 这块可以考虑设计下.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### CODE REVIEW

File: src/renderer/src/pages/home/Messages/MessageMenubar.tsx [hunk 1]
```diff
@@ -154,7 +154,7 @@ const MessageMenubar: FC<Props> = (props) => {
   )
 
   const isEditable = useMemo(() => {
-    return findMainTextBlocks(message).length === 1
+    return findMainTextBlocks(message).length > 0 // 使用 MCP Server 后会有大于一段 MatinTextBlock
```
Comment (MyPrototypeWhat) [inline src/renderer/src/pages/home/Messages/MessageMenubar.tsx:157]: 可以加一个 `&& findMcpBlock.length`的逻辑 对mcp判断一下
`findMainTextBlocks(message).length > 0` 会对所有有`maintext`的都开放编辑

Comment (NageNalock) [reply src/renderer/src/pages/home/Messages/MessageMenubar.tsx:157]: 这块预期不对什么类型的 maintext 开放编辑?

Comment (NageNalock) [reply src/renderer/src/pages/home/Messages/MessageMenubar.tsx:157]: 我看
```
export const findMainTextBlocks = (message: Message): MainTextMessageBlock[] => {
  if (!message || !message.blocks || message.blocks.length === 0) {
    return []
  }
  const state = store.getState()
  const textBlocks: MainTextMessageBlock[] = []
  for (const blockId of message.blocks) {
    const block = messageBlocksSelectors.selectById(state, blockId)
    if (block && block.type === MessageBlockType.MAIN_TEXT) {
      textBlocks.push(block as MainTextMessageBlock)
    }
  }
  return textBlocks
}
```
已经把大多数的 TextBlock 过滤了🤔还有啥场景没用 MCP 会导致多 MainText 的场景, 且这个场景下就是不允许所有的 Maintext 被编辑么
