### PR TITLE
feat(streaming): replace fixed timeout with resettable idle timeout

### LINKED ISSUE #13489: [Bug]: 1.7.25 version request was aborted, signal timed out
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

1.7.25 

### Bug Description

1.7.25 version request was aborted, signal timed out, the 1.7.24 version work well and do not has those errors

Image

### Steps To Reproduce

using the llama.cpp provieder for models

### Expected Behavior

should got the all the content for questions for the model

### Relevant Log Output

```shell

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by EurFelux**
### What this PR does

Before this PR:

The streaming timeout used a fixed `AbortSignal.timeout()` that starts counting from the initial request. For long-running SSE streams (e.g., complex reasoning or tool-calling chains), the request could be aborted even while data was actively flowing.

After this PR:

Introduces an `IdleTimeoutController` that resets its countdown every time a stream chunk is received. The timeout now only fires when the stream is truly idle (no data received for the configured duration), not based on total elapsed time.

Fixes #13489

### Why we need it and why it was done in this way

The following tradeoffs were made:

- The idle timeout controller is a simple utility class with `reset()` and `cleanup()` methods, exposed via an `IdleTimeoutHandle` interface and threaded through `ModernAiProviderConfig` to `AiSdkToChunkAdapter`.
- The `reset()` callback is invoked on every `reader.read()` return in `readFullStream`, which is the natural place where SSE chunks are consumed.
- `cleanup()` is called in the `finally` block to prevent timer leaks when the stream ends normally or errors out.

The following alternatives were considered:

- Implementing idle timeout at the AI SDK level — not feasible as the AI SDK does not support idle timeout natively.
- Using a wrapper around `reader.read()` with `Promise.race` — more invasive and less clean than resetting a timer on each chunk.

### Breaking changes

None. The default timeout duration remains unchanged (30 minutes). The only behavioral change is that the timeout now resets on each chunk instead of being fixed from request start.

### Special notes for your reviewer

- The `IdleTimeoutController` is covered by 6 unit tests (fake timers).
- The new optional `idleTimeout` constructor parameter on `AiSdkToChunkAdapter` is backward-compatible — existing callers (e.g., `messageThunk.ts`) are unaffected.

### Checklist

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780096809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. Check this only when the PR introduces or changes a user-facing feature or behavior.
- [x] Self-review: I have reviewed my own code (e.g., via [`/gh-pr-review`](/.claude/skills/gh-pr-review/SKILL.md), `gh pr diff`, or GitHub UI) before requesting review from others

### Release note

```release-note
NONE
```

### CODE REVIEW

File: src/renderer/src/aiCore/chunk/AiSdkToChunkAdapter.ts [hunk 1]
```diff
@@ -41,14 +43,18 @@ export class AiSdkToChunkAdapter {
     enableWebSearch?: boolean,
     onSessionUpdate?: (sessionId: string) => void,
     getSessionWasCleared?: () => boolean,
-    providerId?: string
+    providerId?: string,
+    resetIdleTimeout?: () => void,
+    cleanupIdleTimeout?: () => void
```
Comment (EurFelux) [inline src/renderer/src/aiCore/chunk/AiSdkToChunkAdapter.ts]: **Suggestion: Consider using an options object to reduce positional parameter sprawl**

The constructor now has **9 positional parameters**, many of which are optional. This is becoming hard to read and maintain — callers need to pass `undefined` placeholders to reach later parameters (as seen in `index_new.ts` lines 336-337).

Consider refactoring to an options object pattern:

```ts
interface AiSdkToChunkAdapterOptions {
  mcpTools?: MCPTool[]
  accumulate?: boolean
  enableWebSearch?: boolean
  onSessionUpdate?: (sessionId: string) => void
  getSessionWasCleared?: () => boolean
  providerId?: string
  resetIdleTimeout?: () => void
  cleanupIdleTimeout?: () => void
}

constructor(
  onChunk: (chunk: Chunk) => void,
  options?: AiSdkToChunkAdapterOptions
)
```

This is not a blocker for this PR since it's a pre-existing issue you're extending, but worth considering as a follow-up to improve the DX.

File: src/renderer/src/aiCore/types/middlewareConfig.ts [hunk 2]
```diff
@@ -26,4 +26,6 @@ export interface AiSdkMiddlewareConfig {
   webSearchPluginConfig?: WebSearchPluginConfig
   knowledgeRecognition?: 'off' | 'on'
   mcpMode?: string
+  resetIdleTimeout?: () => void
+  cleanupIdleTimeout?: () => void
```
Comment (EurFelux) [inline src/renderer/src/aiCore/types/middlewareConfig.ts]: **Nit: These callbacks feel out of place in `AiSdkMiddlewareConfig`**

`resetIdleTimeout` and `cleanupIdleTimeout` are not middleware concerns — they're stream lifecycle callbacks. Threading them through the middleware config just to pass them to `AiSdkToChunkAdapter` creates coupling between unrelated layers.

An alternative would be to pass them directly when constructing the adapter (e.g., via a separate `streamLifecycle` option), keeping the middleware config focused on actual middleware behavior.

Low priority — the current approach works, just noting the layering concern.

**Review by EurFelux — COMMENTED** [review]
Re-reviewed after the refactor commit (`e8642d8b`). Both suggestions from the previous round have been addressed nicely:

1. **`IdleTimeoutHandle` interface** — cleanly aggregates `reset`/`cleanup` into a single handle object, reducing the constructor param count and improving readability
2. **Layering fix** — `AiSdkMiddlewareConfig` is now free of idle timeout concerns; `idleTimeout` lives only in `ModernAiProviderConfig` where it belongs

The code is clean and well-structured. No further comments — LGTM 🎉
