### PR TITLE
fix: silicon reasoning

### LINKED ISSUE #10596: [Bug]: GLM-4.6 not performing reasoning when reasoning is enabled
> [!NOTE]
> This issue was translated by Claude.

In SiliconFlow, GLM-4.6 in Cherry Studio version 1.6.3 still doesn't perform reasoning even when Chain of Thought is enabled.
image

---
<details>
<summary>Original Content</summary>

siliconflow 硅基流动里面的glm4.6在Cherry Studio 1.6.3版本中,开启了思维链,模型仍然不思考
image

</details>

_Originally posted by @eaeful in https://github.com/CherryHQ/cherry-studio/issues/10475#issuecomment-3384646104_

### PR DESCRIPTION
**Pull request by EurFelux**
### What this PR does

- Removed redundant Doubao reasoning control logic
- Specially add silicon reasoning control

Fixes #10596

### Why we need it and why it was done in this way

The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Breaking changes

If this PR introduces breaking changes, please describe the changes and the impact on users.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### Release note

```release-note

```

### CODE REVIEW

File: src/renderer/src/aiCore/utils/reasoning.ts [hunk 1]
```diff
@@ -112,9 +113,51 @@ export function getReasoningEffort(assistant: Assistant, model: Model): Reasonin
...
+        reasoning: {
+          effort: reasoningEffort === 'auto' ? 'medium' : reasoningEffort
+        }
+      }
+    }
+  }
+
+  const effortRatio = EFFORT_RATIO[reasoningEffort]
+  const budgetTokens = Math.floor(
+    (findTokenLimit(model.id)?.max! - findTokenLimit(model.id)?.min!) * effortRatio + findTokenLimit(model.id)?.min!
```
Comment (DeJeune) [inline src/renderer/src/aiCore/utils/reasoning.ts]: > [!NOTE]
> This comment was translated by Claude.

The budget tokens cannot be calculated for Zhipu models on SiliconCloud

---
<details>
<summary>Original Content</summary>

硅基流动的智谱模型算不出来budgettoken

</details>

Comment (EurFelux) [reply src/renderer/src/aiCore/utils/reasoning.ts]: Fixed

**Review by DeJeune — APPROVED** [review]

**Review by GeorgeDong32 — APPROVED** [review]

**Comment by kangfenmao** [comment]
https://linux.do/t/topic/1117192
