### PR TITLE
fix: filter hidden elements when exporting messages as images

### LINKED ISSUE #13024: [Bug]: Long code snippets are incomplete when exporting AI responses as images
> [!NOTE]
> This issue was translated by Claude.

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.7.19

### Bug Description

When the AI response contains long code, after exporting as an image (or copying as an image), some code cannot be displayed.

<details>
<summary>Example (long image warning):</summary>
Image
</details>

### Steps To Reproduce

1. Use AI to generate a response that involves long code
2. Click "Export as Image" / "Copy as Image"

I can successfully reproduce this. For example, asking AI to write a basic social media recommendation algorithm using Python, then exporting as an image, I found that some code snippets are missing.

<details>
<summary>Reproduction example (long image warning):</summary>
Image
</details>

### Expected Behavior

Display the complete AI response, including all code generated by AI

### Relevant Log Output

```shell

```

### Additional Context

_No response_

---
<details>
<summary>Original Content</summary>

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.7.19

### Bug Description

如果 AI 回答中出现长的代码，导出为图片（或者是复制为图片）后，部分代码无法显示
<details>
<summary>例子（长图预警）：</summary>
Image
</details>

### Steps To Reproduce

1. 使用 AI 生成回答，当中涉及长的代码
2. 点击「导出为图片」/ 「复制为图片」

我可以成功复现，例如要求 AI 使用 Python 撰写一个基础的社交媒体推荐算法，再导出为图片后发现，当中部分代码片段缺失
<details>
<summary>复现例子（长图预警）：</summary>
Image
</details>

### Expected Behavior

展示完整的 AI 回答，包括全部 AI 所生成的代码

### Relevant Log Output

```shell

```

### Additional Context

_No response_
</details>

### PR DESCRIPTION
**Pull request by kovsu**
Fix #13024 

The thinking block uses Ant Design's `Collapse` component, which contains some hidden elements. This component has issues with the `html-to-image` library, requiring us to manually filter out hidden elements.

### CODE REVIEW

File: src/renderer/src/pages/home/Messages/MessageMenubar.tsx [hunk 1]
```diff
@@ -343,7 +343,8 @@ const MessageMenubar: FC<Props> = (props) => {
               const imageData = await captureScrollableAsDataURL(messageContainerRef)
               const title = await getMessageTitle(message)
               if (title && imageData) {
-                window.api.file.saveImage(title, imageData)
+                await window.api.file.saveImage(title, imageData)
+                window.toast.success(t('chat.topics.export.image_saved'))
```
Comment (beyondkmp) [inline src/renderer/src/pages/home/Messages/MessageMenubar.tsx]: Potential false-positive success toast:  in main process resolves even when user cancels Save dialog ( is empty), so this toast can still show after cancellation. Consider returning a save result (e.g. boolean/filePath) from IPC and only show  when it actually succeeds.

Comment (beyondkmp) [reply src/renderer/src/pages/home/Messages/MessageMenubar.tsx]: 补充说明：这里可能会误报成功。主进程 FileStorage.saveImage 在用户取消保存对话框时也会正常返回（没有 filePath，但不会抛错），因此当前逻辑仍会触发 success toast。建议让 saveImage 返回保存结果（boolean 或 filePath），仅在实际写入成功后再提示 image_saved。

**Review by beyondkmp — COMMENTED** [review]
Added one actionable inline note about export-image success toast behavior when save is canceled.

File: src/renderer/src/pages/home/Messages/MessageMenubar.tsx (hunk 1 above)
Comment (kovsu) [reply src/renderer/src/pages/home/Messages/MessageMenubar.tsx]: Thanks for your comments, I have updated my code. Please review it again.

Comment (beyondkmp) [reply src/renderer/src/pages/home/Messages/MessageMenubar.tsx]: 已复核，修复生效：saveImage 现在返回 boolean，且仅在 success=true 时显示 image_saved toast。这个问题可以关闭。
