### PR TITLE
fix(reasoning): add qwen3-max to supported reasoning models

### LINKED ISSUE #12816: [Bug]: qwen3-max has not updated to reasoning model
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.7.17

### Bug Description

Image

> [!NOTE]
> This issue was translated by Claude.

As mentioned in the title, qwen3-max is now equivalent to qwen3-max-2026-01-23, which is a reasoning model, but Cherry Studio has not yet updated the handling logic.

---
<details>
<summary>Original Content</summary>

如题，qwen3-max现在已经等于qwen3-max-2026-01-23了，是个reasoning model，但cherry studio还未更新处理逻辑

</details>

### Steps To Reproduce

.

### Expected Behavior

.

### Relevant Log Output

```shell

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by GeorgeDong32**
### What this PR does

Before this PR:
- qwen3-max was not listed as a supported reasoning model.

After this PR:
- Add qwen3-max to the list of supported reasoning models.

Fixes #12816

### Why we need it and why it was done in this way

- Ensure qwen3-max is recognized and available for reasoning workflows.

### Breaking changes

- None

### Checklist

- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: Write code that humans can understand and keep it simple
- [ ] Refactor: Left the code cleaner than you found it (Boy Scout Rule)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A user-guide update was considered and is present or not required

Release note

```release-note
Add qwen3-max to supported reasoning models.
```

### CODE REVIEW

**Review by DeJeune — APPROVED** [review]

File: src/renderer/src/config/models/reasoning.ts [hunk 1]
```diff
@@ -775,6 +776,8 @@ const THINKING_TOKEN_MAP: Record<string, { min: number; max: number }> = {
   'qwen-plus.*$': { min: 0, max: 81_920 },
   'qwen-turbo.*$': { min: 0, max: 38_912 },
   'qwen-flash.*$': { min: 0, max: 81_920 },
+  // qwen3-max series (reasoning models, equivalent to qwen-plus for thinking budget)
+  'qwen3-max(-.*)?$': { min: 0, max: 81_920 },
```
Comment (EurFelux) [inline src/renderer/src/config/models/reasoning.ts:780]: Good catch on placing `qwen3-max(-.*)?$` **before** the `qwen3-(?!max).*$` pattern. Since `THINKING_TOKEN_MAP` iterates keys in insertion order (via `Object.keys`), this ensures `qwen3-max` hits the correct `{ min: 0, max: 81_920 }` entry instead of falling through to the generic `qwen3-*` pattern with `{ min: 1024, max: 38_912 }`.

nit: The comment says "equivalent to qwen-plus for thinking budget" — consider explicitly noting the `min: 0` difference from generic qwen3 models (`min: 1024`) since that's the key distinction this regex ordering achieves.

File: src/renderer/src/config/models/reasoning.ts [hunk 2]
```diff
@@ -469,6 +469,7 @@ export function isSupportedThinkingTokenQwenModel(model?: Model): boolean {
     'qwen-turbo-2025-07-15',
     'qwen-flash',
     'qwen-flash-2025-07-28',
+    'qwen3-max', // qwen3-max is now a reasoning model (equivalent to qwen3-max-2026-01-23)
```
Comment (EurFelux) [inline src/renderer/src/config/models/reasoning.ts:472]: suggestion (minor): Since `qwen3-max-2026-01-23` and `qwen3-max-preview` are already in the list, and the new `THINKING_TOKEN_MAP` regex `qwen3-max(-.*)?$` covers all `qwen3-max*` variants, have you considered using a regex/prefix match here too instead of an explicit allowlist? Something like checking `modelId.startsWith('qwen3-max')` would cover future dated versions automatically (e.g., `qwen3-max-2026-06-01`) without requiring code changes.

Not blocking — the current approach is consistent with the existing pattern in this function, and explicitness has its own value.

**Review by EurFelux — APPROVED** [review]
LGTM! Clean and well-scoped change.

**Summary:**
- Adds `qwen3-max` to the `isSupportedThinkingTokenQwenModel` allowlist, which cascades correctly through `isQwenReasoningModel`
- Adds `qwen3-max(-.*)?$` regex to `THINKING_TOKEN_MAP` with `{ min: 0, max: 81_920 }` — correctly placed **before** the generic `qwen3-(?!max).*$` pattern to ensure proper matching
- Test coverage is thorough — covers `isQwenReasoningModel`, `isSupportedThinkingTokenQwenModel`, `getThinkModelType`, `findTokenLimit`, and `getModelSupportedReasoningEffortOptions`

Left two minor non-blocking suggestions on the implementation file.
