### PR TITLE
fix: improve proxy configuration handling and logging in ProxyManager

### LINKED ISSUE #8329: [错误]: 无法连通OpenAI官方的api
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我的问题不是 [常见问题](https://github.com/CherryHQ/cherry-studio/issues/3881) 中的内容。
- [x] 我已经查看了 **置顶 Issue** 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。

### 平台

Windows

### 版本

1.5.1

### 错误描述

<video src="https://github.com/user-attachments/assets/83f22e0f-0c4c-4b13-a7fa-0cdc75b4deb5" controls></video>

如视频所示，一直转圈，无法输出答案，最后跳出以下报错：

我保证不是api的问题，也不是网络的问题，同样的url+api，同样的机场，同样的节点，同样的wifi，手机上都能连通
Image

### 重现步骤

1、选择openai官方渠道
2、选择一个模型提问

### 预期行为

模型正常回答

### 相关日志输出

```shell

```

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by beyondkmp**
### What this PR does

Before this PR:
获取系统代理有时候会失败，有时候可能是代理软件还没有开，后面再开的，就会导致获取不到，就不再monitor，会导致后面代理软件开了也打不开。

After this PR:

没有获取到系统代理的url，也需要一直monitor。

Fixes #8329 #8316

### Why we need it and why it was done in this way

The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Breaking changes

If this PR introduces breaking changes, please describe the changes and the impact on users.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### Release note

```release-note

```

### CODE REVIEW

File: src/renderer/src/pages/settings/GeneralSettings.tsx [hunk 1]
```diff
@@ -106,10 +105,8 @@ const GeneralSettings: FC = () => {
   const onProxyModeChange = (mode: 'system' | 'custom' | 'none') => {
     dispatch(setProxyMode(mode))
     if (mode === 'system') {
-      window.api.setProxy('system')
```
Comment (beyondkmp) [inline src/renderer/src/pages/settings/GeneralSettings.tsx:109]: 在src/renderer/src/hooks/useAppInit.ts里面已经有监听了，不删除的话，修改一下代理配置，会触发两次的api调用。
image

**Review by DeJeune — APPROVED** [review]
