### PR TITLE
fix: Groq verbosity setting

### LINKED ISSUE #11435: [Bug]: Using Groq models shows 'property verbosity is unsupported' request error, please check if request parameters are correct. If model settings were modified, please reset to default settings
> [!NOTE]
> This issue/comment/review was translated by Claude.

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.7.0-rc.2

### Bug Description

Error name: AI_APICallError
Error message: property 'verbosity' is unsupported
Stack information: AI_APICallError: property 'verbosity' is unsupported
    at file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/dist-C-kSq4IC.js:5132:11
    at async postToApi (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/dist-C-kSq4IC.js:5028:24)
    at async OpenAICompatibleChatLanguageModel.doStream (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/dist-Tharrv8p.js:348:48)
    at async fn (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-DFCJLw3w.js:58132:17)
    at async file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-DFCJLw3w.js:55510:19
    at async _retryWithExponentialBackoff (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-DFCJLw3w.js:55612:10)
    at async streamStep (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-DFCJLw3w.js:58100:108)
    at async fn (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-DFCJLw3w.js:58379:5)
    at async file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-DFCJLw3w.js:55510:19)
Error cause: "[undefined]"
Status code: 400
Request path: https://api.groq.com/openai/v1/chat/completions
Request body: {
  "model": "moonshotai/kimi-k2-instruct-0905",
  "user": "[undefined]",
  "max_tokens": 4096,
  "temperature": 0.7,
  "top_p": "[undefined]",
  "frequency_penalty": "[undefined]",
  "presence_penalty": "[undefined]",
  "response_format": "[undefined]",
  "stop": "[undefined]",
  "seed": "[undefined]",
  "serviceTier": "[undefined]",
  "reasoning_effort": "[undefined]",
  "verbosity": "medium",
  "messages": [
    {
      "role": "user",
      "content": "Who are you"
    }
  ],
  "tools": "[undefined]",
  "tool_choice": "[undefined]",
  "stream": true,
  "stream_options": {
    "include_usage": true
  }
}
Response headers: {
  "alt-svc": "h3=\":443\"; ma=86400",
  "cache-control": "private, max-age=0, no-store, no-cache, must-revalidate",
  "cf-cache-status": "DYNAMIC",
  "cf-ray": "9a3967ca78eb17d2-SJC",
  "content-length": "91",
  "content-type": "application/json",
  "date": "Mon, 24 Nov 2025 13:55:41 GMT",
  "document-policy": "include-js-call-stacks-in-crash-reports",
  "server": "cloudflare",
  "vary": "Origin",
  "via": "1.1 google",
  "x-groq-region": "dls",
  "x-request-id": "req_01kav2c6n5eb5b3csedratzbza"
}
Response content: {
  "error": {
    "message": "property 'verbosity' is unsupported",
    "type": "invalid_request_error"
  }
}
Data: {
  "error": {
    "message": "property 'verbosity' is unsupported",
    "type": "invalid_request_error"
  }
}

### Steps To Reproduce

Open chat window
Click new topic
Converse with default Groq model
Error occurs

### Expected Behavior

Normally should reply directly

### Relevant Log Output

```shell

```

### Additional Context

_No response_

---
<details>
<summary>Original Content</summary>

### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.7.0-rc.2

### Bug Description

错误名称: AI_APICallError
错误信息: property 'verbosity' is unsupported
堆栈信息: AI_APICallError: property 'verbosity' is unsupported
    at file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/dist-C-kSq4IC.js:5132:11
    at async postToApi (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/dist-C-kSq4IC.js:5028:24)
    at async OpenAICompatibleChatLanguageModel.doStream (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/dist-Tharrv8p.js:348:48)
    at async fn (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-DFCJLw3w.js:58132:17)
    at async file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-DFCJLw3w.js:55510:19
    at async _retryWithExponentialBackoff (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-DFCJLw3w.js:55612:10)
    at async streamStep (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-DFCJLw3w.js:58100:108)
    at async fn (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-DFCJLw3w.js:58379:5)
    at async file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-DFCJLw3w.js:55510:19)
错误原因: "[undefined]"
状态码: 400
请求路径: https://api.groq.com/openai/v1/chat/completions
请求体: {
  "model": "moonshotai/kimi-k2-instruct-0905",
  "user": "[undefined]",
  "max_tokens": 4096,
  "temperature": 0.7,
  "top_p": "[undefined]",
  "frequency_penalty": "[undefined]",
  "presence_penalty": "[undefined]",
  "response_format": "[undefined]",
  "stop": "[undefined]",
  "seed": "[undefined]",
  "serviceTier": "[undefined]",
  "reasoning_effort": "[undefined]",
  "verbosity": "medium",
  "messages": [
    {
      "role": "user",
      "content": "你是谁"
    }
  ],
  "tools": "[undefined]",
  "tool_choice": "[undefined]",
  "stream": true,
  "stream_options": {
    "include_usage": true
  }
}
响应首部: {
  "alt-svc": "h3=\":443\"; ma=86400",
  "cache-control": "private, max-age=0, no-store, no-cache, must-revalidate",
  "cf-cache-status": "DYNAMIC",
  "cf-ray": "9a3967ca78eb17d2-SJC",
  "content-length": "91",
  "content-type": "application/json",
  "date": "Mon, 24 Nov 2025 13:55:41 GMT",
  "document-policy": "include-js-call-stacks-in-crash-reports",
  "server": "cloudflare",
  "vary": "Origin",
  "via": "1.1 google",
  "x-groq-region": "dls",
  "x-request-id": "req_01kav2c6n5eb5b3csedratzbza"
}
响应内容: {
  "error": {
    "message": "property 'verbosity' is unsupported",
    "type": "invalid_request_error"
  }
}
数据: {
  "error": {
    "message": "property 'verbosity' is unsupported",
    "type": "invalid_request_error"
  }
}

### Steps To Reproduce

打开聊天窗口
点击新建话题
与默认groq的模型对话
报错

### Expected Behavior

正常来说应该是直接回复

### Relevant Log Output

```shell

```

### Additional Context

_No response_
</details>

### PR DESCRIPTION
**Pull request by EurFelux**
### What this PR does

Before this PR:
- Groq provider was using verbosity settings, but Groq API doesn't support the `verbosity` parameter
- This could cause API errors or unexpected behavior when using Groq models
- No provider-specific settings UI for Groq service tier configuration
- Missing test coverage for `isSupportVerbosityProvider` function
- Selector component only accepts `string | number` as value type, causing issues when `undefined` or `null` values need to be passed

After this PR:
- Added `verbosity` field to Provider type and API options
- Implemented provider capability check before applying verbosity parameter
- Disabled verbosity for Groq provider (set to `undefined`) via migration
- Added dedicated Groq settings group component with service tier configuration
- Added i18n support for Groq settings and verbosity options
- Added comprehensive test coverage for `isSupportVerbosityProvider` function
- Fixed Selector component value type issue by introducing `toOptionValue` and `toRealValue` utility functions

Fixes #11435

### Why we need it and why it was done in this way

**The Problem:**
The Groq API doesn't support the `verbosity` parameter that OpenAI API supports. Using this parameter with Groq could lead to API errors or the parameter being silently ignored.

**The Solution:**
1. **Added provider capability flags**: Introduced `isNotSupportVerbosity` flag in `ProviderApiOptions` to declare which providers don't support verbosity
2. **Capability-based parameter application**: Modified `modelParameters.ts` to check provider support before applying verbosity
3. **Migration for existing users**: Added version 178 migration to set Groq provider's verbosity to `undefined`
4. **Dedicated settings UI**: Created `GroqSettingsGroup` component for Groq-specific settings (service tier)
5. **Fixed Selector type constraints**: Created utility functions to handle `undefined` and `null` values:
   - `toOptionValue()`: Converts `undefined` → `'undefined'`, `null` → `'null'` (strings for Selector)
   - `toRealValue()`: Converts `'undefined'` → `undefined`, `'null'` → `null` (original values)
   - Applied to both `GroqSettingsGroup` and `OpenAISettingsGroup` for service tier selection
6. **Test coverage**: Added comprehensive test cases for `isSupportVerbosityProvider` covering:
   - Custom providers with explicit flags
   - Default behavior for providers without apiOptions
   - System providers (both supported and blacklisted)
   - Blacklist enforcement (cannot be overridden by apiOptions)
   - Edge cases with apiOptions overrides

**Tradeoffs:**
- Added complexity with provider capability checks, but improves API compatibility and prevents errors
- Requires migration for existing users, but ensures consistent behavior going forward
- Blacklist is enforced and cannot be overridden (by design for API compatibility)
- Added conversion layer for Selector values, but provides type safety and cleaner API

**Alternatives considered:**
- Could silently filter out unsupported parameters, but explicit capability flags provide better clarity and maintainability
- Could hardcode provider checks in multiple places, but centralized capability system is more scalable
- Could modify Selector to accept `undefined`/`null`, but string conversion approach is more backward-compatible

### Breaking changes

None. This is a fix that improves API compatibility. The migration automatically updates existing Groq provider configurations.

### Special notes for your reviewer

- The `GroqSettingsGroup` component reuses OpenAI service tier translations and logic, as Groq uses similar service tier concepts
- Migration version 178 specifically targets Groq provider to disable verbosity
- Type definitions now include `OpenAIVerbosity` and related service tier types for better type safety
- Test cases validate that the blacklist is enforced (using `&&` logic instead of `||`)
- All 15 test cases in `provider.test.ts` pass ✅
- The `toOptionValue`/`toRealValue` pattern is now used in both `OpenAISettingsGroup` and `GroqSettingsGroup` for consistent handling of special values
- Utility functions have full TypeScript overload signatures for type safety

### Checklist

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed (migration v178)
- [x] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required
- [x] Tests: Added comprehensive test coverage for the new functionality

### Release note

\`\`\`release-note
fix: Improve Groq API compatibility by disabling unsupported verbosity parameter and adding Groq-specific service tier settings. Fixed Selector component to properly handle undefined and null values.
\`\`\`

### CODE REVIEW

File: src/renderer/src/pages/settings/ProviderSettings/ApiOptionsSettings/ApiOptionsSettings.tsx [hunk 1]
```diff
@@ -76,6 +76,17 @@ const ApiOptionsSettings = ({ providerId }: Props) => {
...
         checked: !provider.apiOptions?.isNotSupportEnableThinking
+      },
+      {
+        key: 'openai_verbosity',
+        label: t('settings.provider.api.options.verbosity.label'),
+        tip: t('settings.provider.api.options.verbosity.help'),
+        onChange: (checked: boolean) => {
+          updateProviderTransition({
+            apiOptions: { ...provider.apiOptions, isNotSupportVerbosity: !checked }
+          })
```
Comment (0xfullex) [inline src/renderer/src/pages/settings/ProviderSettings/ApiOptionsSettings/ApiOptionsSettings.tsx:87]: **🐛 BUG: Copy-paste error - wrong property referenced**

The `checked` property incorrectly references `isNotSupportEnableThinking` instead of `isNotSupportVerbosity`.

```diff
- checked: !provider.apiOptions?.isNotSupportEnableThinking
+ checked: !provider.apiOptions?.isNotSupportVerbosity
```

**Impact:** The verbosity toggle will display incorrect state, mirroring the "enable thinking" toggle instead of the actual verbosity setting. The `onChange` handler correctly updates `isNotSupportVerbosity`, but the displayed state reads from the wrong property.

File: src/renderer/src/store/migrate.ts [hunk 2]
```diff
@@ -2871,6 +2871,19 @@ const migrateConfig = {
       logger.error('migrate 177 error', error as Error)
       return state
     }
+  },
+  '178': (state: RootState) => {
+    try {
+      const groq = state.llm.providers.find((p) => p.id === SystemProviderIds.groq)
+      if (groq) {
+        groq.verbosity = undefined
+      }
```
Comment (0xfullex) [inline src/renderer/src/store/migrate.ts:2880]: **⚠️ Potential Issue: Setting non-existent property on Provider**

The migration sets `groq.verbosity = undefined`, but the `Provider` type does not appear to have a `verbosity` field. Looking at the PR changes to `types/provider.ts`, only `isNotSupportVerbosity` was added to `ProviderApiOptions`, not a direct `verbosity` field on Provider.

**Questions:**
1. Is there a `verbosity` field on Provider that exists elsewhere in the base type?
2. Should this migration instead be setting `groq.apiOptions = { ...groq.apiOptions, isNotSupportVerbosity: true }` to disable verbosity for Groq?

If this is intentional and `verbosity` exists elsewhere, please clarify. Otherwise, the migration may need to be updated.

File: src/renderer/src/pages/home/Tabs/components/GroqSettingsGroup.tsx [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+    ] as const satisfies ServiceTierOptions[]
+    return options.filter((option) => {
+      if (option.value === 'flex') {
+        return isSupportFlexServiceTier
+      }
+      return true
+    })
+  }, [isSupportFlexServiceTier, t])
+
+  useEffect(() => {
```
Comment (0xfullex) [inline src/renderer/src/pages/home/Tabs/components/GroqSettingsGroup.tsx]: **💡 Suggestion: Add logging for silent state correction**

This `useEffect` silently corrects invalid `serviceTierMode` values without any logging. Per CLAUDE.md guidelines, logging should go through `loggerService`.

Consider adding logging to help with debugging:

```typescript
useEffect(() => {
  if (serviceTierMode && !serviceTierOptions.some((option) => option.value === serviceTierMode)) {
    logger.warn('Invalid serviceTierMode detected for Groq provider, resetting to on_demand', {
      invalidValue: serviceTierMode,
      validOptions: serviceTierOptions.map(o => o.value)
    })
    setServiceTierMode(GroqServiceTiers.on_demand)
  }
}, [provider.id, serviceTierMode, serviceTierOptions, setServiceTierMode])
```

This helps diagnose issues when users report that their settings "randomly" changed.

File: src/renderer/src/pages/home/Tabs/components/GroqSettingsGroup.tsx [hunk 4]
```diff
@@ -0,0 +1,99 @@
...
+  SettingGroup: FC<{ children: React.ReactNode }>
+  SettingRowTitleSmall: FC<{ children: React.ReactNode }>
+}
+
+const GroqSettingsGroup: FC<Props> = ({ model, SettingGroup, SettingRowTitleSmall }) => {
+  const { t } = useTranslation()
+  const { provider, updateProvider } = useProvider(SystemProviderIds.groq)
+  const serviceTierMode = provider.serviceTier
+
+  // I'm not sure if this function applies to Groq, but it should be fine to use
```
Comment (0xfullex) [inline src/renderer/src/pages/home/Tabs/components/GroqSettingsGroup.tsx]: **💬 Suggestion: Clarify or remove uncertain comment**

This comment indicates uncertainty about whether the function applies to Groq. Before merging, it would be helpful to:

1. Verify whether `isSupportFlexServiceTierModel` actually applies to Groq models
2. If verified, update the comment to be more definitive
3. If not applicable, remove the call or adjust the logic

Comments expressing uncertainty can become misleading over time ("comment rot").

File: src/renderer/src/types/provider.ts [hunk 5]
```diff
@@ -20,28 +20,30 @@ export const ProviderTypeSchema = z.enum([
...
   isSupportServiceTier?: boolean
-  /** 是否不支持 enable_thinking 参数 */
+  /** Whether the enable_thinking parameter is not supported */
   isNotSupportEnableThinking?: boolean
-  /** 是否不支持 APIVersion */
+  /** Whether APIVersion is not supported */
   isNotSupportAPIVersion?: boolean
+  /** Whether verbosity is not supported. For OpenAI API (completions & responses). */
+  isNotSupportVerbosity?: boolean
 }
```
Comment (0xfullex) [inline src/renderer/src/types/provider.ts:48]: **💡 Suggestion: Consider positive boolean naming**

The new `isNotSupportVerbosity` field uses the negative form (`isNotSupport*`), but the codebase is migrating toward positive forms:

- `isNotSupportDeveloperRole` → `@deprecated`, replaced by `isSupportDeveloperRole`
- `isNotSupportServiceTier` → `@deprecated`, replaced by `isSupportServiceTier`

For consistency with the migration direction, consider using `isSupportVerbosity?: boolean` instead. This avoids double negation in usage code:

```typescript
// Current (double negative):
if (provider.apiOptions?.isNotSupportVerbosity !== true) { ... }

// With positive form (clearer):
if (provider.apiOptions?.isSupportVerbosity !== false) { ... }
```

This is a minor suggestion - the current implementation is functional and follows the existing pattern for other fields.
