### PR TITLE
fix: create assistant causing blank screen

### LINKED ISSUE #10840: [Bug]: Blank screen when creating assistant
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.7.0-beta.2

### Bug Description

Click create assistant from assistant tab will trigger blank screen.

https://github.com/user-attachments/assets/12773443-82bc-4ce7-bb96-c88c08afa658

error logs:

Image

### Steps To Reproduce

Unable to reproduce the issue on a freshly installed v1.7.0. Will verify on the upgraded version.

### Expected Behavior

Create assistant successfully

### Relevant Log Output

```shell

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by defi-failure**
### What this PR does
1. Adds a fallback and logging to `useAssistantPresets` to prevent crashes.
2. Adds a migration to clean up invalid data.

Before this PR:
Assistants can now be created successfully

After this PR:
Create assistant successfully

Fixes #10840 

### Why we need it and why it was done in this way

The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Breaking changes

If this PR introduces breaking changes, please describe the changes and the impact on users.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### Release note

```release-note

```

### CODE REVIEW

File: src/renderer/src/hooks/useAssistantPresets.ts [hunk 1]
```diff
@@ -21,15 +36,24 @@ export function useAssistantPresets() {
...
-    preset,
+    preset: preset as AssistantPreset | undefined,
     updateAssistantPreset: (preset: AssistantPreset) => dispatch(updateAssistantPreset(preset)),
     updateAssistantPresetSettings: (settings: Partial<AssistantSettings>) => {
-      dispatch(updateAssistantPresetSettings({ assistantId: preset.id, settings }))
+      if (!preset) {
+        logger.warn('Failed to update assistant preset settings because preset is missing.', { id })
+        return
+      }
+      dispatch(updateAssistantPresetSettings({ assistantId: id, settings }))
```
[the remark this answers is not in the document]
Comment (defi-failure) [reply src/renderer/src/hooks/useAssistantPresets.ts]: check again, it's `preset` not `presets` and is returned from array find

File: src/renderer/src/hooks/useAssistantPresets.ts [hunk 2]
```diff
@@ -21,15 +36,24 @@ export function useAssistantPresets() {
...
+  const preset = presets.find((a) => a.id === id)
   const dispatch = useAppDispatch()
 
+  if (!preset) {
+    logger.warn('Assistant preset not found in state.', { id })
+  }
+
   return {
-    preset,
+    preset: preset as AssistantPreset | undefined,
```
[the remark this answers is not in the document]
Comment (EurFelux) [reply src/renderer/src/hooks/useAssistantPresets.ts]:
```suggestion
    preset,
```

File: src/renderer/src/hooks/useAssistantPresets.ts [hunk 3]
```diff
@@ -8,8 +9,22 @@ import {
...
+function ensurePresetsArray(storedPresets: unknown): AssistantPreset[] {
+  if (Array.isArray(storedPresets)) {
+    return storedPresets
+  }
+  logger.warn('Unexpected data type from state.assistants.presets, falling back to empty list.', {
+    type: typeof storedPresets,
+    value: storedPresets
+  })
+  return []
+}
```
Comment (EurFelux) [inline src/renderer/src/hooks/useAssistantPresets.ts:23]: The presets should be recognized as an array type, as that's how the Redux state is defined. There's no need for additional runtime checks here; the real issue stems from the fact that `preset`, which could originally be `undefined`, is being cast to `AssistantPreset`, resulting in a runtime access of `undefined`.

File: src/renderer/src/hooks/useAssistantPresets.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (EurFelux) [reply src/renderer/src/hooks/useAssistantPresets.ts]: We may use `preset.id` instead of `id` to clarify it

File: src/renderer/src/store/migrate.ts [hunk 4]
```diff
@@ -2677,12 +2676,27 @@ const migrateConfig = {
...
       return state
     } catch (error) {
       logger.error('migrate 163 error', error as Error)
       return state
     }
+  },
+  '164': (state: RootState) => {
+    try {
+      if (!state.assistants) {
+        return state
```
Comment (EurFelux) [inline src/renderer/src/store/migrate.ts]: This is definitely a highly unusual situation. Either we shouldn't assume such an anomaly will occur, or we should handle this situation properly.

File: src/renderer/src/hooks/useAssistantPresets.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (defi-failure) [reply src/renderer/src/hooks/useAssistantPresets.ts]: fixed

File: src/renderer/src/hooks/useAssistantPresets.ts (hunk 3 above)
Comment (defi-failure) [reply src/renderer/src/hooks/useAssistantPresets.ts:23]: I’ve already provided the user with a version that includes logging, confirming that `presets` in the Redux state is `undefined`. This might have been introduced during the `agent → assistant.presets` migration, which involved extensive changes.
image

File: src/renderer/src/store/migrate.ts (hunk 4 above)
Comment (defi-failure) [reply src/renderer/src/store/migrate.ts]: I agree, it’s definitely an unusual situation. But since it has already happened to a user, I think we should address the known invalid data.

Comment (EurFelux) [reply src/renderer/src/store/migrate.ts]: What I mean is, it's quite unusual for the "assistants" field to be undefined, and directly returning the state without any handling shouldn't be allowed. Either we assume that "assistants" should exist, or we initialize it.

File: src/renderer/src/hooks/useAssistantPresets.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (defi-failure) [reply src/renderer/src/hooks/useAssistantPresets.ts]: > We may use `preset.id` instead of `id` to clarify it

fixed

File: src/renderer/src/store/migrate.ts (hunk 4 above)
Comment (defi-failure) [reply src/renderer/src/store/migrate.ts]: Got it now, removed this check.

File: src/renderer/src/hooks/useAssistantPresets.ts (hunk 3 above)
Comment (EurFelux) [reply src/renderer/src/hooks/useAssistantPresets.ts:23]: I understand. In this case, since the predecessor of presets has already been removed from the definition, we only need to reset this field to an empty array during migration.

Comment (EurFelux) [reply src/renderer/src/hooks/useAssistantPresets.ts:23]: I don't agree with distrusting the type system, so I still believe this function shouldn't exist. If we start considering that every state might not conform to its type definition at runtime, we'll never reach a conclusion.

Comment (defi-failure) [reply src/renderer/src/hooks/useAssistantPresets.ts:23]: Got it. As I mentioned earlier, that part of the migration changed quite a lot, so I couldn’t identify exactly why this field ended up being set to `undefined`. 
I think it’s still worth keeping the logging for now, so if it happens again, we can recover some data from it.

Comment (EurFelux) [reply src/renderer/src/hooks/useAssistantPresets.ts:23]: That works too. This part will soon be refactored out in v2, so it doesn't really matter.

**Review by GeorgeDong32 — APPROVED** [review]
