### PR TITLE
fix: restrict using gemini native tools and mcp tools simultaneously

### LINKED ISSUE #9358: [错误]: openrouter 提供的 gemini 模型不支持网页上下文，但还是有网页上下文功能按钮展示
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我的问题不是 [常见问题](https://github.com/CherryHQ/cherry-studio/issues/3881) 中的内容。
- [x] 我已经查看了 **置顶 Issue** 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。
- [x] 我确认我正在使用最新版本的 Cherry Studio。

### 平台

Windows

### 版本

v1.5.6

### 错误描述

Image

### 重现步骤

NA

### 预期行为

NA

### 相关日志输出

```shell

```

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by EurFelux**
### What this PR does

Gemini 不支持原生工具和函数调用同时使用。

image

现在在ui部分和api部分限制gemini的原生工具和mcp工具同时使用。提示词模式不受影响。

Fixes #9358

### Why we need it and why it was done in this way

The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Breaking changes

If this PR introduces breaking changes, please describe the changes and the impact on users.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### Release note

```release-note

```

### CODE REVIEW

**Comment by DeJeune** [comment]
可以顺便在请求组装那里加一下，urlcontext和原生tool是互斥的

File: src/renderer/src/pages/home/Inputbar/MCPToolsButton.tsx [hunk 1]
```diff
@@ -135,13 +139,33 @@ const MCPToolsButton: FC<Props> = ({ ref, setInputValue, resizeTextArea, Toolbar
...
       if (assistantMcpServers.some((s) => s.id === server.id)) {
-        updateAssistant({ ...assistant, mcpServers: mcpServers?.filter((s) => s.id !== server.id) })
+        update.mcpServers = mcpServers.filter((s) => s.id !== server.id)
       } else {
-        updateAssistant({ ...assistant, mcpServers: [...mcpServers, server] })
+        update.mcpServers = [...mcpServers, server]
       }
+
+      // only for gemini
+      if (update.mcpServers.length > 0 && isGeminiModel(model) && assistant.settings?.toolUseMode === 'function') {
```
Comment (DeJeune) [inline src/renderer/src/pages/home/Inputbar/MCPToolsButton.tsx]: `assistant.settings?.toolUseMode === 'function'`这个顺便封装一下不

Comment (EurFelux) [reply src/renderer/src/pages/home/Inputbar/MCPToolsButton.tsx]: 封装了一下

File: src/renderer/src/pages/home/Inputbar/InputbarTools.tsx [hunk 2]
```diff
@@ -346,7 +348,7 @@ const InputbarTools = ({
         key: 'url_context',
         label: t('chat.input.url_context'),
         component: <UrlContextButton ref={urlContextButtonRef} assistant={assistant} ToolbarButton={ToolbarButton} />,
-        condition: model.id.toLowerCase().includes('gemini')
+        condition: model.id.toLowerCase().includes('gemini') && isSupportUrlContextProvider(getProviderByModel(model))
```
Comment (DeJeune) [inline src/renderer/src/pages/home/Inputbar/InputbarTools.tsx]:
```suggestion
        isGeminiModel(model) && isSupportUrlContextProvider(getProviderByModel(model))
```

File: src/renderer/src/pages/home/Inputbar/InputbarTools.tsx [hunk 3]
```diff
@@ -1,6 +1,8 @@
 import { DragDropContext, Draggable, Droppable, DropResult } from '@hello-pangea/dnd'
 import { QuickPanelListItem } from '@renderer/components/QuickPanel'
 import { isGenerateImageModel } from '@renderer/config/models'
```
Comment (DeJeune) [inline src/renderer/src/pages/home/Inputbar/InputbarTools.tsx]:
```suggestion
import { isGeminiModel, isGenerateImageModel } from '@renderer/config/models'
```

**Review by GeorgeDong32 — APPROVED** [review]
