### PR TITLE
fix(ImageViewer): prevent double menu, improve icons

### LINKED ISSUE #9489: [错误]: 右键选项重叠
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我的问题不是 [常见问题](https://github.com/CherryHQ/cherry-studio/issues/3881) 中的内容。
- [x] 我已经查看了 **置顶 Issue** 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。
- [x] 我确认我正在使用最新版本的 Cherry Studio。

### 平台

macOS

### 版本

v1.5.7

### 错误描述

如视频所示，
选中文字并右键——正常
直接在图片上右键——正常
选中文字后在图片上右键——不正常
具体来说，会导致文字右键和图片右键的选项同时出现

https://github.com/user-attachments/assets/1e3e88e9-4708-4042-84ee-71ebcbf58c46

### 重现步骤

1、找一条消息，包含文字与图片
2、选中文字，在图片上右键

### 预期行为

既然我在图片上右键了，我应该想要只弹出图片的右键选项，不管我是否选中了文字

### 相关日志输出

```shell

```

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by alephpiece**
### What this PR does

修复重叠 menu

| BEFORE| AFTER|
|---|---|
|image|image|

Fixes #9489 

### Why we need it and why it was done in this way

The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Breaking changes

If this PR introduces breaking changes, please describe the changes and the impact on users.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### Release note

```release-note

```

### CODE REVIEW

File: src/renderer/src/components/ImageViewer.tsx [hunk 1]
```diff
@@ -72,7 +74,7 @@ const ImageViewer: React.FC<ImageViewerProps> = ({ src, style, ...props }) => {
       {
         key: 'copy-url',
         label: t('common.copy'),
-        icon: <CopyOutlined />,
+        icon: <CopyIcon size={14} />,
```
Comment (EurFelux) [inline src/renderer/src/components/ImageViewer.tsx]: size可以做成默认参数

Comment (alephpiece) [reply src/renderer/src/components/ImageViewer.tsx]: 这个吗？

https://github.com/CherryHQ/cherry-studio/blob/649a2a645cdd610d3060e233134b9e180f871c57/src/renderer/src/components/Icons/CopyIcon.tsx#L3

Comment (EurFelux) [reply src/renderer/src/components/ImageViewer.tsx]: `getContextMenuItems`

Comment (alephpiece) [reply src/renderer/src/components/ImageViewer.tsx]: 可以提个 pr 统一规范一下图标大小

Comment (EurFelux) [reply src/renderer/src/components/ImageViewer.tsx]:
```ts
const getContextMenuItems = (src: string, size: number = 14) => {
```

局部改一下够了，不同地方要的大小不一定一样

Comment (alephpiece) [reply src/renderer/src/components/ImageViewer.tsx]: 行

**Review by EurFelux — APPROVED** [review]
