### PR TITLE
fix: Replace actioningPlugin with useLoading hook

### LINKED ISSUE #13092: [Bug]: Cannot install multiple plugins simultaneously - loading state lost on component unmount
Thank you for taking the time to fill out this bug report!
Before submitting this issue, please make sure that you have understood the [FAQ](https://docs.cherry-ai.com/question-contact/questions) and [Knowledge Science](https://docs.cherry-ai.com/question-contact/knowledge)

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform
macOS

### Version
latest

### Bug Description

In the plugin browser page (PluginBrowser.tsx), the plugin installation state management has several issues related to asynchronous operations and React component lifecycle.

**Root Cause**: The `actioningPlugin` state uses a single `string | null` type, which cannot properly track:
1. Multiple concurrent installation operations
2. Installation state after component unmount

Related code location: `src/renderer/src/pages/settings/AgentSettings/components/PluginsSettings/components/PluginBrowser.tsx:54`

```typescript
const [actioningPlugin, setActioningPlugin] = useState<string | null>(null)
```

#### Issue 1 - Concurrent Installations (UI Only)
When a user quickly clicks install buttons for multiple plugins in succession, only the last-clicked plugin shows a loading state. However, the earlier installation continues to run in the background (not cancelled).

#### Issue 2 - Component Unmount - Most Critical
When the user navigates away while an installation is in progress:

1. **Scenario A** (Works correctly):
   - User starts installation → installation completes in background → user returns → sees "Installed" ✓

2. **Scenario B** (Problematic):
   - User starts installation → user navigates away (component unmounts) → installation still in progress → user returns
   - Sees **Install button** (not loading state!)
   - User thinks installation was cancelled → clicks Install again
   - **Result: Two installation tasks running simultaneously!** ← This causes the most user confusion

This is a serious UX issue because:
- User sees "Install button" and assumes the operation was cancelled
- User triggers another installation, causing duplicate operations
- May lead to race conditions, duplicate files, or unexpected behavior

### Steps To Reproduce

**For Issue 2 (Component Unmount - Critical)**:
1. Open the plugin browser in settings
2. Click the install button of a plugin
3. Immediately navigate to a different page (causing PluginBrowser to unmount)
4. Wait a few seconds (but not long enough for installation to complete)
5. Navigate back to the plugin browser
6. Observe: You see the "Install" button, not a loading state
7. Click the Install button again
8. Now you have two concurrent installation operations!

### Expected Behavior

1. When user returns to the plugin browser after navigating away:
   - If installation completed: Show "Installed" state
   - If installation is still in progress: Show loading state (NOT install button!)
   - If installation failed: Show error state

2. When installing multiple plugins:
   - Each plugin should show its own loading state
   - User should be able to see all ongoing operations

### Additional Context

Recommended solutions:
1. Change `actioningPlugin` from `string | null` to `Set<string>` to track multiple concurrent operations
2. Persist installation state (e.g., in Redux store) so it survives component unmount
3. When component mounts, check for any in-progress installations and restore the loading state
4. Optionally: Use AbortController to cancel in-flight operations when component unmounts

### PR DESCRIPTION
**Pull request by EurFelux**
### What this PR does

Before this PR:
- Used local component state (`useState<string | null>`) to track loading status in `PluginBrowser.tsx`
- This caused a bug where loading state is lost when component unmounts (user navigates away)
- When user returns, they see "Install" button instead of loading state, and may click again causing duplicate operations
- Used session-specific waiting state (`sessionWaiting`) in Redux store

After this PR:
- Introduces a reusable `useLoading` hook that manages loading state in Redux store (persists across component lifecycle)
- Replaces `setSessionWaitingAction` with more generic `setLoadingAction` that uses a `loadingMap` for multiple loading states
- `PluginBrowser.tsx` now uses the centralized `useLoading` hook that survives component remount

Fixes #13092

### Why we need it and why it was done in this way

This PR fixes a bug where loading state is lost when the PluginBrowser component unmounts. When the user navigates away and returns, they see "Install" button instead of loading state, leading them to click again and cause duplicate operations.

The following tradeoffs were made:
- Centralized loading state allows multiple components to track loading status for the same operation (e.g., both the button and the modal can check if installation is in progress)
- Using a key-based map (`loadingMap`) instead of single session-specific state provides flexibility for future use cases

The following alternatives were considered:
- Keep local state in each component: rejected as it doesn't allow sharing loading state across components
- Use existing sessionWaiting directly: rejected as it's session-specific and not reusable for plugins

Links to places where the discussion took place: 

### Breaking changes

If this PR introduces breaking changes, please describe the changes and the impact on users.

### Special notes for your reviewer

- This fix ensures loading state persists when user navigates away and returns to the plugin browser
- The `useLoading` hook supports both global loading map and individual id-based usage
- Also prevents duplicate clicks while loading

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. Check this only when the PR introduces or changes a user-facing feature or behavior.
- [ ] Self-review: I have reviewed my own code (e.g., via [`/gh-pr-review`](/.claude/skills/gh-pr-review/SKILL.md), `gh pr diff`, or GitHub UI) before requesting review from others

### Release note

```release-note
fix: Persist plugin loading state in Redux to survive component unmount (prevents duplicate installs when user navigates away and returns)
```

### CODE REVIEW

File: src/renderer/src/store/runtime.ts [hunk 1]
```diff
@@ -205,9 +205,9 @@ const runtimeSlice = createSlice({
       }
       state.websearch.activeSearches[requestId] = status
     },
-    setSessionWaitingAction: (state, action: PayloadAction<{ id: string; value: boolean }>) => {
+    setLoadingAction: (state, action: PayloadAction<{ id: string; value: boolean }>) => {
```
Comment (DeJeune) [inline src/renderer/src/store/runtime.ts]: **Bug:** `loadingMap` entries are never cleaned up. When `value` is `false`, the key remains in the map with a `false` value. Over time this leaks memory as stale keys accumulate (every plugin install/uninstall, every session delete leaves a residual entry).

Suggestion — delete the key when `value` is `false`:
```ts
setLoadingAction: (state, action: PayloadAction<{ id: string; value: boolean }>) => {
  const { id, value } = action.payload
  if (value) {
    state.loadingMap[id] = true
  } else {
    delete state.loadingMap[id]
  }
},
```

File: src/renderer/src/hooks/useLoading.ts [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+
+import { useRuntime } from './useRuntime'
+
+export function useLoading(): {
+  loadingMap: Record<string, boolean>
+  setLoading: (params: { id: string; value: boolean }) => void
+}
+export function useLoading(id: string): { isLoading: boolean; setLoading: (value: boolean) => void }
+export function useLoading(id?: string) {
+  const { loadingMap } = useRuntime()
```
Comment (DeJeune) [inline src/renderer/src/hooks/useLoading.ts]: **Perf:** The no-arg overload destructures `loadingMap` from `useRuntime()`, which subscribes this component to the *entire* `RuntimeState`. Any unrelated state change (e.g. `generating`, `detectedRegion`, `websearch`) will trigger a re-render of `PluginBrowser` and all its children (a virtual list with potentially hundreds of items).

Consider using a targeted selector instead:
```ts
const loadingMap = useAppSelector((state) => state.runtime.loadingMap)
```
This way the component only re-renders when `loadingMap` itself changes, not on every runtime state update.

File: src/renderer/src/pages/home/Tabs/components/Sessions.tsx [hunk 3]
```diff
@@ -45,7 +41,7 @@ const Sessions: React.FC<SessionsProps> = ({ agentId }) => {
         window.toast.error(t('agent.session.delete.error.last'))
         return
       }
-      dispatch(setSessionWaitingAction({ id, value: true }))
+      dispatch(setLoadingAction({ id, value: true }))
```
Comment (DeJeune) [inline src/renderer/src/pages/home/Tabs/components/Sessions.tsx]: **Significant:** Session IDs are dispatched as bare keys (e.g. `dispatch(setLoadingAction({ id, value: true }))`) while plugin keys are namespaced with `plugin:` prefix. Since both now share the same global `loadingMap`, a collision is theoretically possible if a session UUID happens to match a plugin key.

For consistency and safety, consider namespacing session keys too:
```ts
dispatch(setLoadingAction({ id: `session:${id}`, value: true }))
```

Also, the PR adds duplicate-click guards in `PluginBrowser` (`if (loadingMap[loadingKey]) return`) but not here. If the motivation is preventing duplicate operations, the same pattern should be applied to session deletion.

File: src/renderer/src/pages/settings/AgentSettings/components/PluginsSettings/components/PluginBrowser.tsx [hunk 4]
```diff
@@ -51,11 +54,12 @@ export const PluginBrowser: FC<PluginBrowserProps> = ({ installedPlugins, onInst
...
-  const [actioningPlugin, setActioningPlugin] = useState<string | null>(null)
   const [selectedPlugin, setSelectedPlugin] = useState<PluginMetadata | null>(null)
   const [isModalOpen, setIsModalOpen] = useState(false)
   const [sortDropdownOpen, setSortDropdownOpen] = useState(false)
 
+  const { loadingMap, setLoading } = useLoading()
+
   // Debounce search query
   const handleSearchChange = useCallback(
     (value: string) => {
```
Comment (DeJeune) [inline src/renderer/src/pages/settings/AgentSettings/components/PluginsSettings/components/PluginBrowser.tsx:65]: **Nit:** Good that you added duplicate-click guards in `handleInstall`/`handleUninstall`. However, using the no-arg `useLoading()` overload here means the entire component re-renders on *any* loading state change (even from unrelated features like session deletion). 

Since `PluginBrowser` renders a virtual list with many items, this could be noticeable. An alternative approach: keep `actioningPlugin` as local state for the UI rendering, but *also* set the Redux loading key for cross-component persistence. Or refactor to use the single-id overload per action.

File: src/renderer/src/store/runtime.ts (hunk 1 above)
Comment (EurFelux) [reply src/renderer/src/store/runtime.ts]: > [!NOTE]
> This comment was translated by Claude.

I have extracted a more semantically clear API to solve this issue.

---
<details>
<summary>Original Content</summary>

我拆解出了语义更明确的api以解决此问题。

</details>

File: src/renderer/src/pages/home/Tabs/components/Sessions.tsx (hunk 3 above)
Comment (EurFelux) [reply src/renderer/src/pages/home/Tabs/components/Sessions.tsx]: > [!NOTE]
> This issue/comment/review was translated by Claude.

After inspection, the session's loading state is no longer being used, so I will remove it.

---
<details>
<summary>Original Content</summary>

经过检查，session的loading状态已经不再使用，因此我会将其移除
</details>

File: src/renderer/src/pages/home/Tabs/components/Sessions.tsx [hunk 5]
```diff
@@ -45,7 +43,7 @@ const Sessions: React.FC<SessionsProps> = ({ agentId }) => {
         window.toast.error(t('agent.session.delete.error.last'))
```
Comment (DeJeune) [inline src/renderer/src/pages/home/Tabs/components/Sessions.tsx:88]: **Nit (non-blocking):** Session IDs are still dispatched as bare keys here (`startLoading(id)`). Plugin keys are namespaced with `plugin:` prefix via `createPluginLoadingKey`. For defensive consistency in the shared `loadingMap`, consider namespacing session keys too (e.g. `startLoading(`session:${id}`)`). Low risk since UUIDs won't realistically collide with `plugin:...` strings.

File: src/renderer/src/hooks/useLoading.ts [hunk 6]
```diff
@@ -0,0 +1,69 @@
...
+ *
+ * @param id - Optional unique identifier. When provided, returns specific loading state;
+ *             when undefined, returns full loading map and generic control functions.
+ * @returns Loading state object based on whether id is provided
+ *
+ * @internal
+ */
+export function useLoading(id?: string) {
+  const loadingMap = useAppSelector((state) => state.runtime.loadingMap)
+  const dispatch = useAppDispatch()
```
Comment (DeJeune) [inline src/renderer/src/hooks/useLoading.ts]: **Nit (non-blocking):** The JSDoc on the implementation overload (`@internal`) is unnecessary — TypeScript won't expose it to consumers and it duplicates what the two public overload signatures already document. Consider trimming this block to keep the hook concise.

**Review by DeJeune — APPROVED** [review]
## Follow-up Review

The latest commit addresses both critical issues from the previous review:

1. **Memory leak fixed** — `finishLoadingAction` now uses `delete state.loadingMap[id]` instead of setting `false`. Clean.
2. **Re-render issue fixed** — `useLoading` now uses `useAppSelector((state) => state.runtime.loadingMap)` instead of `useRuntime()`. Only re-renders when `loadingMap` changes.
3. **Improved API** — Splitting `setLoading(value)` into `startLoading()`/`finishLoading()` is more expressive and prevents misuse (no way to accidentally pass the wrong boolean).

Two non-blocking nits remain (session key namespacing, verbose JSDoc on internal overload) — can be addressed in a follow-up if desired.

LGTM, approving.

File: src/renderer/src/pages/settings/AgentSettings/components/PluginsSettings/components/PluginBrowser.tsx (hunk 4 above)
Comment (EurFelux) [reply src/renderer/src/pages/settings/AgentSettings/components/PluginsSettings/components/PluginBrowser.tsx:65]: > [!NOTE]
> This issue/comment/review was translated by Claude.

Currently, to prevent memory leaks, each call to `finishLoading` causes the `loadingMap` reference to change, thereby triggering a re-render.

A better solution would be to not use `delete` and instead perform periodic GC operations during the application lifecycle. However, since there is currently no lifecycle management architecture, this solution is not being adopted for now.

---
<details>
<summary>Original Content</summary>

目前为了防止内存泄漏，每次调用`finishLoading`都会导致`loadingMap`引用发生变化，从而触发重渲染。

更好的解决方案是不使用`delete`，同时在应用生命周期内定时执行GC操作。然而，由于目前尚缺少生命周期管理架构，暂不采用此方案。

</details>
