### PR TITLE
fix(ollama): improve reasoningEffort handling in providerOptions

### LINKED ISSUE #12081: [Bug]: invalid ollama provider options for local installed ollama model happened just for gpt-oss:20b or gpt-oss
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Windows

### Version

v1.7.6

### Bug Description

Encounter the following error when calling the local installed ollama model : gpt-oss:20b or gpt-oss
Prior version of v1.7.5 and before is working fine there
Other local installed Ollama model calling is fine there and can responded with user prompt

### Steps To Reproduce

1. Go to Assistant
2. Launch a new Topic  under any Assistant
3. Select local installed ollama model : gpt-oss:20b or gpt-oss
4. Key in the prompt - "Who are you"
5. Error message return : invalid ollama provider options

### Expected Behavior

The local installed ollama model gpt-oss:20b or gpt-oss should provide response to user prompt

### Relevant Log Output

```shell
AI_InvalidArgumentError: invalid ollama provider options
    at parseProviderOptions (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/dist-K3A05YNJ.js:404:44)
    at async OllamaRequestBuilder.parseProviderOptions (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/dist-CF87piMw.js:729:18)
    at async OllamaRequestBuilder.buildRequest (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/dist-CF87piMw.js:675:25)
    at async OllamaResponsesLanguageModel.prepareRequest (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/dist-CF87piMw.js:1102:10)
    at async OllamaResponsesLanguageModel.doStream (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/dist-CF87piMw.js:1078:36)
    at async fn (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-e4Pmzkul.js:37120:17)
    at async file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-e4Pmzkul.js:34498:19
    at async _retryWithExponentialBackoff (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-e4Pmzkul.js:34600:10)
    at async streamStep (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-e4Pmzkul.js:37088:108)
    at async fn (file:///C:/Program%20Files/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-e4Pmzkul.js:37367:5)
```

### Additional Context

Image

### PR DESCRIPTION
**Pull request by DeJeune**
### What this PR does

**Before this PR:**
- When using gpt-oss models (e.g., gpt-oss:20b) with Ollama provider, users encountered "invalid ollama provider options" error
- gpt-oss models were incorrectly classified as 'o' type (same as o1/o3 models), inheriting reasoning_effort options including 'default'
- Ollama's provider schema only accepts `boolean | 'low' | 'medium' | 'high'` for the `think` parameter
- When users selected 'default' or other unsupported values, they were passed directly to Ollama, causing schema validation failures

**After this PR:**
- Created dedicated 'gpt_oss' model type with proper reasoning_effort options: `['default', 'none', 'low', 'medium', 'high']`
- Updated `_getThinkModelType()` to classify gpt-oss models as 'gpt_oss' type instead of 'o' type
- Added value mapping logic in `buildOllamaProviderOptions` for defensive handling:
  - Supported values ('low', 'medium', 'high') are passed through as-is
  - 'none' and undefined are mapped to `false` (disable thinking)
  - Unsupported values ('default', etc.) are mapped to 'medium' as a sensible default
- Updated tests to reflect the new model type classification
- gpt-oss models now work correctly with Ollama and show the correct reasoning options in UI

Fixes #12081

### Why we need it and why it was done in this way

**Root cause:**
The issue stemmed from incorrect model type classification:
1. `isOpenAIOpenWeightModel(model)` returns true for gpt-oss models ✓
2. `isSupportedReasoningEffortOpenAIModel(model)` also returns true (line 105 in openai.ts) ✓
3. In `_getThinkModelType()`, the check for `isSupportedReasoningEffortOpenAIModel` came before checking for gpt-oss
4. This caused gpt-oss to be classified as 'o' type (line 132-133 in reasoning.ts)
5. 'o' type models get `['default', 'low', 'medium', 'high']` options
6. But Ollama's schema (defined in the patch) only accepts `boolean | 'low' | 'medium' | 'high'`
7. When users selected 'default', it failed Ollama's schema validation

**Why this approach:**
- **Upstream fix (model type classification)**: Creates a dedicated 'gpt_oss' type that accurately represents these models' capabilities
- **Downstream fix (provider options)**: Adds defensive value mapping in case edge cases occur
- **Two-layer protection**: Ensures robustness at both the type system level and runtime level

**The following tradeoffs were made:**
- Added a new model type 'gpt_oss' instead of reusing 'o' type - this is more accurate and prevents future confusion
- Kept the defensive value mapping in `buildOllamaProviderOptions` even though 'default' shouldn't reach it anymore - provides safety against edge cases
- Updated test expectations to match the new behavior - tests now validate the correct classification

**The following alternatives were considered:**
1. Only fix downstream (map 'default' in buildOllamaProviderOptions)
   - Pros: Simpler, fewer files changed
   - Cons: Doesn't fix the root cause, UI would still show wrong options
2. Current approach: Fix both upstream (type classification) and downstream (value mapping)
   - Pros: Comprehensive fix, correct UI options, defensive against edge cases
   - Cons: More files changed, requires test updates

### Breaking changes

None. This is a bug fix that:
- Makes previously failing configurations work correctly
- Improves UI accuracy by showing the correct reasoning options for gpt-oss models
- Does not change behavior for other model types

### Special notes for your reviewer

- The Ollama provider schema patch (`.yarn/patches/ollama-ai-provider-v2-npm-1.5.5-8bef249af9.patch`) already extends the `think` parameter to accept `'low' | 'medium' | 'high'` strings in addition to boolean
- gpt-oss models are now properly classified as a separate type with their own configuration
- The fix ensures all reasoning_effort values are properly mapped to valid Ollama schema values
- Test coverage updated: 309/309 tests passing (added 4 new tests for gpt-oss type classification)
- Files changed:
  - `src/renderer/src/types/index.ts`: Added 'gpt_oss' to ThinkModelTypes
  - `src/renderer/src/config/models/reasoning.ts`: Added gpt_oss configuration and type detection
  - `src/renderer/src/aiCore/utils/options.ts`: Updated comments for defensive handling
  - `src/renderer/src/config/models/__tests__/reasoning.test.ts`: Added tests for gpt_oss type

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Documentation: A [user-guide update](https://docs.cherry-ai.com) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature.

### Release note

```release-note
fix(ollama): Fix "invalid ollama provider options" error for gpt-oss models by introducing dedicated 'gpt_oss' model type with proper reasoning_effort options and value mapping
```

### CODE REVIEW

File: src/renderer/src/aiCore/utils/options.ts [hunk 1]
```diff
@@ -580,8 +580,10 @@ function buildOllamaProviderOptions(
   const reasoningEffort = assistant.settings?.reasoning_effort
   if (enableReasoning) {
     if (isOpenAIOpenWeightModel(model)) {
-      // @ts-ignore upstream type error
-      providerOptions.think = reasoningEffort as any
+      // For gpt-oss models, Ollama accepts: boolean | 'low' | 'medium' | 'high'
+      if (reasoningEffort === 'low' || reasoningEffort === 'medium' || reasoningEffort === 'high') {
```
Comment (EurFelux) [inline src/renderer/src/aiCore/utils/options.ts:584]: So boolean is supported? But `none` is not in the options. May allow `none` to be mapped to false?

Comment (DeJeune) [reply src/renderer/src/aiCore/utils/options.ts:584]: comment error

**Review by EurFelux — APPROVED** [review]
