### PR TITLE
fix(models): enhance model type checks for function calling and web s…

### LINKED ISSUE #9575: [错误]: gemini-2.5-flash-image-preview适配
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我的问题不是 [常见问题](https://github.com/CherryHQ/cherry-studio/issues/3881) 中的内容。
- [x] 我已经查看了 **置顶 Issue** 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。
- [x] 我确认我正在使用最新版本的 Cherry Studio。

### 平台

Windows

### 版本

1.5.7

### 错误描述

调用谷歌新模型gemini-2.5-flash-image-preview时，报错如图所示，思考设置为“关闭”“默认”“沉思”均显示同一报错，我已经使用付费层级key，确保不是因为没有免费配额导致的报错，没有配额是另一个报错

Image

### 重现步骤

调用谷歌新模型gemini-2.5-flash-image-preview

### 预期行为

正确处理请求

### 相关日志输出

```shell

```

### 附加信息

_No response_

### PR DESCRIPTION
**Pull request by DeJeune**
…earch models

### What this PR does

Before this PR:

After this PR:

Fixes #9575

### CODE REVIEW

File: src/renderer/src/config/models.ts [hunk 1]
```diff
@@ -2957,7 +2964,7 @@ export function isNotSupportTemperatureAndTopP(model: Model): boolean {
 }
 
 export function isWebSearchModel(model: Model): boolean {
-  if (!model || isEmbeddingModel(model) || isRerankModel(model)) {
+  if (!model || isEmbeddingModel(model) || isRerankModel(model) || isTextToImageModel(model)) {
```
Comment (EurFelux) [inline src/renderer/src/config/models.ts:2967]: 可以抽象一个 `isTextToTextModel`出来了

Comment (DeJeune) [reply src/renderer/src/config/models.ts:2967]: 没有一个很好的语义，先这样吧

**Review by EurFelux — APPROVED** [review]
