### PR TITLE
fix: update Dashscope Anthropic API host and migrate old configs

### LINKED ISSUE #10970: Regarding the issue of Claude code being incompatible with the Qwen AI system.
### Issue Checklist

- [x] I understand that issues are meant for feedback and problem-solving, not for venting, and I will provide as much detail as possible to help resolve the issue.
- [x] I have checked the pinned issues and searched through the existing [open issues](https://github.com/CherryHQ/cherry-studio/issues), [closed issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [discussions](https://github.com/CherryHQ/cherry-studio/discussions) and did not find a similar suggestion.
- [x] I confirm that I am here to ask questions and discuss issues, not to report bugs or request features.

### Platform

Windows

### Version

v1.6.5

### Your Question

Image

I have successfully installed the Claude Code module from Cherry Studio without encountering any issues during the setup process. However, upon accessing Claude Code and attempting to send a simple greeting like "Hello," the system returns a 403 error. Interestingly, this problem appears to be specific to all Qwen AI models, while other AI systems including DeepSeek and GLM function normally without such errors. Initially suspecting potential issues with Claude Code itself, I completely removed all related files and performed a fresh installation, yet the problem persists. Could you kindly assist me in resolving this matter? Your support would be greatly appreciated.

### Context

_No response_

### Additional Information

```shell

```

### Priority

High (Blocking progress)

### PR DESCRIPTION
**Pull request by GeorgeDong32**
### What this PR does

Before this PR:
- Dashscope Anthropic integrations used the old API host and older saved config format.

After this PR:
- Update Anthropic API host used by Dashscope.
- Migrate existing/old Dashscope Anthropic configurations to the new host/format.

Fixes #10970

### CODE REVIEW

File: src/renderer/src/store/migrate.ts [hunk 1]
```diff
@@ -2715,6 +2715,14 @@ const migrateConfig = {
           preset.settings.toolUseMode = DEFAULT_ASSISTANT_SETTINGS.toolUseMode
         }
       })
+      state.llm.providers.forEach((provider) => {
+        if (
+          provider.id === 'dashscope' &&
+          provider.anthropicApiHost === 'https://dashscope.aliyuncs.com/api/v2/apps/claude-code-proxy'
```
Comment (EurFelux) [inline src/renderer/src/store/migrate.ts]: [!NOTE]
> This comment was translated by Claude.

Should we just overwrite it directly?

---
<details>
<summary>Original Content</summary>

直接覆盖掉就ok了吧？

</details>

Comment (GeorgeDong32) [reply src/renderer/src/store/migrate.ts]: [!NOTE]
> This comment was translated by Claude.

OK, I'll make the change.

---
<details>
<summary>Original Content</summary>

OK，我改一下

</details>

File: src/renderer/src/store/migrate.ts [hunk 2]
```diff
@@ -2715,14 +2715,6 @@ const migrateConfig = {
           preset.settings.toolUseMode = DEFAULT_ASSISTANT_SETTINGS.toolUseMode
         }
       })
-      state.llm.providers.forEach((provider) => {
-        if (
-          provider.id === 'dashscope' &&
-          provider.anthropicApiHost === 'https://dashscope.aliyuncs.com/api/v2/apps/claude-code-proxy'
```
Comment (EurFelux) [inline src/renderer/src/store/migrate.ts]: I mean the condition check is unnecessary

Comment (GeorgeDong32) [reply src/renderer/src/store/migrate.ts]: > [!NOTE]
> This comment was translated by Claude.

My bad, I had an issue with reading comprehension 🙃

---
<details>
<summary>Original Content</summary>

我的，阅读理解出问题了 🙃

</details>

**Review by EurFelux — APPROVED** [review]

**Review by beyondkmp — APPROVED** [review]

**Review by 0xfullex — APPROVED** [review]
